import com.pis.storage.*;import java.nio.file.*;import java.io.*;import java.security.*;import java.util.*;
class StorageProviderProbe {static void check(boolean x){if(!x)throw new AssertionError();}public static void main(String[]x)throws Exception{if(x.length==3&&x[0].equals("--crash")){var crashed=new LocalStorageProvider(Path.of(x[1]));Files.write(Path.of(x[1]).resolve(UUID.fromString(x[2])+".blob"),new byte[]{7},StandardOpenOption.CREATE_NEW);check(crashed.state().equals("CONFIGURED_LOCAL"));Runtime.getRuntime().halt(0);}Path root=Files.createTempDirectory("pis-t28-probe-").resolve("owned");byte[] b=new byte[2097152];for(int i=0;i<b.length;i++)b[i]=(byte)(i%251);byte[] m="PIS-SYNTHETIC-STORAGE-V1\n".getBytes();System.arraycopy(m,0,b,0,m.length);String hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));UUID id=UUID.randomUUID(),crashId=UUID.randomUUID(),rid;
try(var p=new LocalStorageProvider(root)){rid=p.rootId();
Path external=root.getParent().resolve("synthetic-outside");Files.write(external,new byte[]{9});UUID link=UUID.randomUUID();Files.createSymbolicLink(root.resolve(link+".part"),external);try{p.stage(link,new ByteArrayInputStream(b),b.length,hash);throw new AssertionError();}catch(IOException expected){}check(Files.readAllBytes(external)[0]==9);
try(var duplicate=new LocalStorageProvider(root)){throw new AssertionError();}catch(IOException expected){}
p.stage(id,new ByteArrayInputStream(b),b.length,hash);p.publish(id,b.length,hash);check(Arrays.equals(p.read(id,b.length,hash,"bytes=1048576-2097151").bytes(),Arrays.copyOfRange(b,1048576,b.length)));check(p.capacity().volumeTotal()>0);UUID bad=UUID.randomUUID();try{p.stage(bad,new ByteArrayInputStream(new byte[25]),25,"0".repeat(64));throw new AssertionError();}catch(IOException expected){}try{p.publish(bad,25,"0".repeat(64));throw new AssertionError();}catch(IOException expected){}UUID partial=UUID.randomUUID();p.stage(partial,new ByteArrayInputStream(b),b.length,hash);Files.write(root.resolve(partial+".blob"),new byte[]{7});try{p.publish(partial,b.length,hash);throw new AssertionError();}catch(IOException expected){}check(Files.size(root.resolve(partial+".blob"))==1);p.stage(crashId,new ByteArrayInputStream(b),b.length,hash);}
StorageConcurrencyContract.simultaneous(root.getParent().resolve("barrier-race"),2097152);StorageConcurrencyContract.saturatedAdmissionAndRecovery(root.getParent().resolve("admission"));StorageConcurrencyContract.nonBusyErrorsAreNeverRetried();
var child=new ProcessBuilder(System.getProperty("java.home")+"/bin/java","--class-path",System.getProperty("java.class.path"),"backend/src/test/probes/StorageProviderProbe.java","--crash",root.toString(),crashId.toString()).inheritIO().start();check(child.waitFor(15,java.util.concurrent.TimeUnit.SECONDS));check(child.exitValue()==0);
try(var p=new LocalStorageProvider(root)){check(p.rootId().equals(rid));try{p.publish(crashId,b.length,hash);throw new AssertionError();}catch(IOException expected){}check(Files.size(root.resolve(crashId+".blob"))==1);p.publish(id,b.length,hash);check(p.read(id,b.length,hash,"bytes=0-127").bytes().length==128);}System.out.println("PASS actual provider: 2MiB streaming, SHA, Range, capacity, restart/replay, corrupt/partial fail closed, symlink protection, exclusive root, concurrent publish, child JVM abrupt halt and lock recovery");}}
