import { test, expect, type Page } from '@playwright/test';
const rid = '44444444-4444-4444-8444-444444444444', vid = '55555555-5555-4555-8555-555555555555';
const view = { requestId: rid, caseId: 'case-syn', patientId: 'patient-syn', page: 1, jobs: [{ id: 'scan-qc', requestId: rid, caseId: 'case-syn', patientId: 'patient-syn', claimedCaseId: 'case-syn', claimedPatientId: 'patient-syn', slideId: 'slide-a', objectId: 'object-a', objectHash: 'a'.repeat(64), objectSize: 256, ordinal: 0, previousId: null, sourceBasis: 'b'.repeat(64), barcode: 'SYN-A', sourceCode: 'SYN-LOCAL', scannerCode: 'SYN-DEV', reason: 'Synthetic', state: 'PENDING_DIGITAL_QC', errorCode: 'DIGITAL_QC_REQUIRED', version: 2, attempts: 1, leaseId: 'lease', leaseActor: 'actor', leaseUntil: null, retryAt: null, width: 32, height: 32, invalidReason: '' }], slides: [{ id: 'slide-a', barcode: 'SYN-A', version: 0, status: 'PASS' }, { id: 'slide-b', barcode: 'SYN-B', version: 0, status: 'PASS' }], capabilities: { SYNTHETIC_HEADER_V1: 'CONTRACT_ONLY', TIFF_CONTAINER: 'NOT_CONFIGURED', SVS: 'NOT_CONFIGURED', NDPI: 'NOT_CONFIGURED', MRXS: 'NOT_CONFIGURED', ARCHIVE: 'UNSUPPORTED' }, publication: 'NOT_PUBLISHED_BY_IMPORT' };
const scope = '11111111-1111-4111-8111-111111111111';
const encounter = { id: '22222222-2222-4222-8222-222222222222', patientId: '33333333-3333-4333-8333-333333333333', patientLabel: '合成患者', encounterNumber: 'SYN-001' };
async function start(page: Page) {
  await page.route('**/api/auth/me', route => route.fulfill({ json: { id: 'synthetic-user', username: 'synthetic', displayName: '合成用户' } }));
  await page.route('**/api/auth/csrf', route => route.fulfill({ json: { headerName: 'X-CSRF-TOKEN', token: 'synthetic-only' } }));
  await page.route('**/api/hello', route => route.fulfill({ json: { application: 'PIS', message: 'Hello World' } }));
  await page.route('**/api/requests/scopes', route => route.fulfill({ json: [{ id: scope, name: '合成院区 / 科室' }] }));
  await page.route('**/api/requests?*', route => route.fulfill({ json: { items: [], total: 0, page: 1, pageSize: 20 } }));
  await page.route('**/api/requests/encounters?*', route => route.fulfill({ json: [encounter] }));
  await page.goto('/');
  await page.getByRole('button', { name: '申请登记工作区' }).click();
  await page.getByRole('combobox', { name: '授权工作范围' }).click();
  await page.getByText('合成院区 / 科室', { exact: true }).last().click();
}
async function openScan(page: Page) {
 await start(page); const d = { id: rid, scopeId: scope, version: 2, state: 'RECEIVED', requestNumber: 'DEV-AP-STORAGE', patientId: encounter.patientId, patientLabel: encounter.patientLabel, encounterId: encounter.id, encounterNumber: encounter.encounterNumber, department: '合成科室', requestedAt: '2026-01-01T08:00:00Z', clinicalHistory: '合成资料', sampledAt: '2026-01-01T08:00:00Z', containers: [{ id: vid, site: 'Synthetic', laterality: 'UNKNOWN', materialQuantity: 1, fixative: 'Synthetic', fixedAt: '2026-01-01T08:10:00Z' }] };
 await page.route('**/api/requests?*', r => r.fulfill({ json: { items: [d], total: 1, page: 1, pageSize: 20 } })); await page.route('**/api/requests/' + rid, r => r.fulfill({ json: d })); await page.getByRole('button', { name: '刷新', exact: true }).click(); await page.getByRole('button', { name: '查看 DEV-AP-STORAGE', exact: true }).click(); await page.getByRole('button', { name: '处理此申请扫描导入', exact: true }).click();
}


const qc = { requestId: rid, scanId: 'scan-qc', caseId: 'case-syn', slideId: 'slide-a', objectId: 'object-a', objectHash: 'a'.repeat(64), scanVersion: 2, ordinal: 0, currentScan: true, version: -1, state: 'UNASSESSED', effectiveState: 'ISOLATED', invalidReason: 'UNASSESSED', assessment: null, events: [], capability: 'SYNTHETIC_CONTRACT_ONLY_NO_VIEWER' };
async function openQc(page: Page) { await page.route('**/scans?*', r => r.fulfill({ json: view })); await openScan(page); await page.getByRole('button', { name: '数字QC 0', exact: true }).click(); }
async function fillQc(page: Page) { for (const label of ['覆盖评价', '焦点评价', '缺失区域评价']) { await page.getByLabel(label, { exact: true }).click(); const list = await page.getByLabel(label, { exact: true }).getAttribute('aria-controls'); expect(list).toBeTruthy(); await page.locator(`[id="${list}"]`).getByRole('option', { name: '合成评价通过 / PASS', exact: true }).click(); } await page.getByLabel('覆盖百分比', { exact: true }).fill('100'); await page.getByLabel('缺失瓦片数', { exact: true }).fill('0'); await page.getByLabel('QC人工备注或原因', { exact: true }).fill('Synthetic manual evaluation'); }
test('digital QC unknown fields never default to pass and empty quantities never become zero', async ({ page }) => { await page.route('**/digital-qc', r => r.fulfill({ json: qc })); await openQc(page); await expect(page.getByRole('button', { name: '发布合成契约版本' })).toBeDisabled(); await page.getByLabel('QC人工备注或原因', { exact: true }).fill('Synthetic unknown'); await page.getByRole('button', { name: '追加人工评价' }).click(); await expect(page.getByText('请填写有界覆盖百分比和缺失瓦片数量，不将空值当零。', { exact: true })).toBeVisible(); await expect(page.getByLabel('焦点评价', { exact: true })).toHaveAttribute('aria-expanded', 'false'); });
test('digital QC uncertain duplicate preserves original exact binding and key', async ({ page }) => { const writes: { body: string | null; key: string | undefined }[] = []; await page.route('**/digital-qc', async r => { if (r.request().method() === 'GET') { await r.fulfill({ json: qc }); return; } writes.push({ body: r.request().postData(), key: r.request().headers()['idempotency-key'] }); if (writes.length === 1) await r.abort(); else await r.fulfill({ json: { receipt: { resourceType: 'DIGITAL_QC', resourceId: 'scan-qc', status: 200, version: 0 }, replayed: true } }); }); await openQc(page); await fillQc(page); await page.getByRole('button', { name: '追加人工评价' }).dblclick(); await expect(page.getByRole('button', { name: '原键确认QC操作' })).toBeEnabled(); expect(writes).toHaveLength(1); await page.getByRole('button', { name: '原键确认QC操作' }).click(); await expect(page.getByLabel('QC人工备注或原因', { exact: true })).toHaveValue(''); expect(writes[1]).toEqual(writes[0]); expect(JSON.parse(writes[0].body ?? '{}')).toMatchObject({ expectedVersion: -1, scanVersion: 2, objectId: 'object-a', objectHash: 'a'.repeat(64), checklist: 'SYN-DIGITAL-QC-1' }); });
test('digital QC conflict retains dirty input, local cancellation is explicit and navigation clears it', async ({ page }) => { await page.route('**/digital-qc', r => r.request().method() === 'GET' ? r.fulfill({ json: qc }) : r.fulfill({ status: 409, json: { code: 'VERSION_CONFLICT' } })); await openQc(page); await fillQc(page); await page.getByRole('button', { name: '追加人工评价' }).click(); await expect(page.getByRole('button', { name: '原键确认QC操作' })).toBeEnabled(); await expect(page.getByLabel('QC人工备注或原因', { exact: true })).toHaveValue('Synthetic manual evaluation'); await page.getByRole('button', { name: '取消本地QC输入' }).click(); await page.getByRole('button', { name: '继续核对', exact: true }).click(); await expect(page.getByLabel('覆盖百分比', { exact: true })).toHaveValue('100'); await page.getByRole('button', { name: '取消本地QC输入' }).click(); await page.getByRole('button', { name: '清除并停止本地跟踪' }).click(); await expect(page.getByLabel('覆盖百分比', { exact: true })).toHaveValue(''); await page.getByRole('button', { name: '申请单查询', exact: true }).click(); await expect(page.getByLabel('数字扫描QC', { exact: true })).toHaveCount(0); });
test('digital QC cancelled late response cannot restore old object after leaving', async ({ page }) => { let release: (() => void) | undefined; await page.route('**/digital-qc', async r => { await new Promise<void>(resolve => { release = resolve; }); await r.fulfill({ json: qc }).catch(() => {}); }); await openQc(page); await expect.poll(() => !!release).toBe(true); await page.getByRole('button', { name: '停止等待QC' }).click(); await page.getByRole('button', { name: '申请单查询', exact: true }).click(); release?.(); await expect(page.getByLabel('数字扫描QC', { exact: true })).toHaveCount(0); await page.route('**/digital-qc', r => r.fulfill({ status: 404, json: { code: 'DIGITAL_QC_NOT_FOUND' } })); await page.getByRole('button', { name: '查看 DEV-AP-STORAGE', exact: true }).click(); await page.getByRole('button', { name: '处理此申请扫描导入' }).click(); await page.getByRole('button', { name: '数字QC 0', exact: true }).click(); await expect(page.getByText('数字QC专业资格或资源不可用。', { exact: true })).toBeVisible(); await expect(page.getByText('物理玻片 slide-a', { exact: true })).toHaveCount(0); });

test('digital QC history rejects a foreign object and dirty evaluation cannot silently publish', async ({ page }) => {
 const assessment = { version: 0, scanVersion: 2, objectId: 'object-a', slideId: 'slide-a', objectHash: 'a'.repeat(64), sourceBasis: 'b'.repeat(64), checklist: 'SYN-DIGITAL-QC-1', coverage: 'PASS', focus: 'PASS', missing: 'PASS', coveragePercent: 100, missingTiles: 0, regions: [], note: 'Synthetic prior assessment', passed: true, actorId: 'reviewer', occurredAt: '2026-10-03T00:00:00Z' };
 await page.route('**/digital-qc', r => r.fulfill({ json: { ...qc, version: 0, state: 'EVALUATED', effectiveState: 'EVALUATED_NOT_PUBLISHED', invalidReason: '', assessment } })); await page.route('**/digital-qc/history', r => r.fulfill({ json: [{ ...assessment, objectId: 'foreign-object' }] })); await openQc(page);
 await expect(page.getByRole('button', { name: '发布合成契约版本' })).toBeEnabled(); await page.getByLabel('覆盖百分比', { exact: true }).fill('99'); await expect(page.getByRole('button', { name: '发布合成契约版本' })).toBeDisabled(); await expect(page.getByRole('button', { name: '刷新QC与授权' })).toBeDisabled(); await page.getByRole('button', { name: '读取不可变评价历史' }).click(); await expect(page.getByText('历史评价与当前扫描绑定不匹配', { exact: true })).toBeVisible(); await expect(page.getByRole('cell', { name: 'foreign-object', exact: true })).toHaveCount(0); await expect(page.getByLabel('覆盖百分比', { exact: true })).toHaveValue('99');
});
