import { test, expect, type Page } from '@playwright/test';
const rid = '44444444-4444-4444-8444-444444444444', vid = '55555555-5555-4555-8555-555555555555';
const view = { requestId: rid, caseId: 'case-syn', patientId: 'patient-syn', page: 1, jobs: [], slides: [{ id: 'slide-a', barcode: 'SYN-A', version: 0, status: 'PASS' }, { id: 'slide-b', barcode: 'SYN-B', version: 0, status: 'PASS' }], capabilities: { SYNTHETIC_HEADER_V1: 'CONTRACT_ONLY', TIFF_CONTAINER: 'NOT_CONFIGURED', SVS: 'NOT_CONFIGURED', NDPI: 'NOT_CONFIGURED', MRXS: 'NOT_CONFIGURED', ARCHIVE: 'UNSUPPORTED' }, publication: 'NOT_PUBLISHED_BY_IMPORT' };
const scope = '11111111-1111-4111-8111-111111111111';
const encounter = { id: '22222222-2222-4222-8222-222222222222', patientId: '33333333-3333-4333-8333-333333333333', patientLabel: '合成患者', encounterNumber: 'SYN-001' };
async function start(page: Page) {
  await page.route('**/api/auth/me', route => route.fulfill({ json: { id: 'synthetic-user', username: 'synthetic', displayName: '合成用户' } }));
  await page.route('**/api/auth/csrf', route => route.fulfill({ json: { headerName: 'X-CSRF-TOKEN', token: 'synthetic-only' } }));
  await page.route('**/api/hello', route => route.fulfill({ json: { application: 'PIS', message: 'Hello World' } }));
  await page.route('**/api/requests/work-context', route => route.fulfill({ json: { defaultScopeId: scope, writableScopes: [scope], name: '合成院区 / 科室', scopes: [{ id: scope, name: '合成院区 / 科室' }], administration: false, menus: ['operations', 'adapters', 'requests', 'registration', 'manual', 'reception', 'labels', 'grossing', 'technical', 'materials', 'quality', 'worklist', 'diagnosis', 'report', 'review', 'output', 'amendments', 'delivery', 'frozen', 'cytology', 'staining', 'consultation', 'archive', 'statistics', 'storage', 'scan', 'digitalqc', 'viewer', 'ai', 'aitasks'] } }));
  await page.route('**/api/requests?*', route => route.fulfill({ json: { items: [], total: 0, page: 1, pageSize: 20 } }));
  await page.route('**/api/requests/encounters?*', route => route.fulfill({ json: [encounter] }));
  await page.goto('/');
  await page.getByRole('button', { name: '申请登记工作区' }).click();
  await expect(page.getByText('当前工作范围：合成院区 / 科室', { exact: true })).toBeVisible();
}
async function openScan(page: Page) {
 await start(page); const d = { id: rid, scopeId: scope, version: 2, state: 'RECEIVED', requestNumber: 'DEV-AP-STORAGE', patientId: encounter.patientId, patientLabel: encounter.patientLabel, encounterId: encounter.id, encounterNumber: encounter.encounterNumber, department: '合成科室', requestedAt: '2026-01-01T08:00:00Z', clinicalHistory: '合成资料', sampledAt: '2026-01-01T08:00:00Z', containers: [{ id: vid, site: 'Synthetic', laterality: 'UNKNOWN', materialQuantity: 1, fixative: 'Synthetic', fixedAt: '2026-01-01T08:10:00Z' }] };
 await page.route('**/api/requests?*', r => r.fulfill({ json: { items: [d], total: 1, page: 1, pageSize: 20 } })); await page.route('**/api/requests/' + rid, r => r.fulfill({ json: d })); await page.getByRole('button', { name: '刷新', exact: true }).click(); await page.getByRole('button', { name: '查看 DEV-AP-STORAGE', exact: true }).click(); await page.getByRole('button', { name: '处理此申请扫描导入', exact: true }).click();
}


async function fill(page: Page, second = false) { await page.getByLabel('物理玻片', { exact: true }).click(); await page.getByRole('option', { name: second ? 'slide-b / SYN-B / PASS' : 'slide-a / SYN-A / PASS', exact: true }).click(); for (const [label, value] of [['核对病例UUID', 'case-syn'], ['核对患者UUID', 'patient-syn'], ['人工扫描条码', second ? 'SYN-B' : 'SYN-A'], ['原件版本UUID', second ? 'object-b' : 'object-a'], ['合成来源编号', 'SYN-LOCAL'], ['合成扫描仪编号', 'SYN-DEV'], ['人工操作原因', 'Synthetic import']]) await page.getByLabel(label, { exact: true }).fill(value); }
test('scan duplicate click and uncertain response preserve the complete original batch key', async ({ page }) => { await page.route('**/scans?*', r => r.fulfill({ json: view })); const writes: { body: string | null; key: string | undefined }[] = []; await page.route('**/scans', async r => { writes.push({ body: r.request().postData(), key: r.request().headers()['idempotency-key'] }); if (writes.length === 1) await r.abort(); else await r.fulfill({ json: [{ objectId: 'object-a', status: 201, scanId: 'scan-a', code: 'RECORDED_NOT_PUBLISHED' }, { objectId: 'object-b', status: 409, scanId: null, code: 'VERSION_CONFLICT' }] }); }); await openScan(page); await fill(page); await page.getByRole('button', { name: '加入已核对批次' }).click(); await fill(page, true); await page.getByRole('button', { name: '加入已核对批次' }).click(); await page.getByRole('button', { name: '登记逐项导入' }).dblclick(); await expect(page.getByRole('button', { name: '原键确认导入操作' })).toBeEnabled(); expect(writes).toHaveLength(1); await page.getByRole('button', { name: '原键确认导入操作' }).click(); await expect(page.getByRole('cell', { name: '201', exact: true })).toBeVisible(); await expect(page.getByRole('cell', { name: '409', exact: true })).toBeVisible(); expect(writes[1]).toEqual(writes[0]); });
test('scan changing mapping confirms dirty fields and clears obsolete object identity', async ({ page }) => { await page.route('**/scans?*', r => r.fulfill({ json: view })); await openScan(page); await fill(page); await page.getByLabel('物理玻片', { exact: true }).click(); await page.getByRole('option', { name: 'slide-b / SYN-B / PASS', exact: true }).click(); await page.getByRole('button', { name: '继续核对', exact: true }).click(); await expect(page.getByLabel('人工扫描条码', { exact: true })).toHaveValue('SYN-A'); await page.getByLabel('物理玻片', { exact: true }).click(); await page.getByRole('option', { name: 'slide-b / SYN-B / PASS', exact: true }).click(); await page.getByRole('button', { name: '清除并切换' }).click(); await expect(page.getByLabel('原件版本UUID', { exact: true })).toHaveValue(''); await expect(page.getByLabel('核对病例UUID', { exact: true })).toHaveValue(''); });
test('scan cancelled late query cannot restore an old case or fake successful import', async ({ page }) => { let release: (() => void) | undefined; await page.route('**/scans?*', async r => { await new Promise<void>(resolve => { release = resolve; }); await r.fulfill({ json: view }).catch(() => {}); }); await openScan(page); await expect.poll(() => !!release).toBe(true); await page.getByRole('button', { name: '停止等待导入' }).click(); await page.getByRole('button', { name: '申请单查询', exact: true }).click(); release?.(); await expect(page.getByLabel('合成扫描导入')).toHaveCount(0); await page.route('**/scans?*', r => r.fulfill({ status: 404, json: { code: 'SCAN_NOT_FOUND' } })); await page.getByRole('button', { name: '查看 DEV-AP-STORAGE', exact: true }).click(); await page.getByRole('button', { name: '处理此申请扫描导入' }).click(); await expect(page.getByText('导入病例、对象或扫描资格不可用。')).toBeVisible(); await expect(page.getByText('patient-syn', { exact: true })).toHaveCount(0); });

test('scan uncertain cancellation preserves lease and key; confirmed cancel never leaves a parse action enabled', async ({ page }) => {
 const job = { id: 'scan-syn', requestId: rid, caseId: view.caseId, patientId: view.patientId, claimedCaseId: view.caseId, claimedPatientId: view.patientId, slideId: 'slide-a', objectId: 'object-a', objectHash: 'a'.repeat(64), objectSize: 256, ordinal: 0, previousId: null, sourceBasis: 'b'.repeat(64), barcode: 'SYN-A', sourceCode: 'SYN-LOCAL', scannerCode: 'SYN-DEV', reason: 'Synthetic', state: 'RUNNING', errorCode: '', version: 1, attempts: 1, leaseId: 'lease-syn', leaseActor: 'actor-syn', leaseUntil: '2026-10-03T00:00:00Z', retryAt: null, width: null, height: null, invalidReason: '' }; const writes: { key: string | undefined; body: string | null }[] = [];
 await page.route('**/scans?*', r => r.fulfill({ json: { ...view, jobs: [job] } })); await page.route('**/scans/scan-syn/CANCEL', async r => { writes.push({ key: r.request().headers()['idempotency-key'], body: r.request().postData() }); if (writes.length === 1) await r.abort(); else { job.state = 'CANCELLED'; job.version = 2; await r.fulfill({ json: { receipt: { status: 200, resourceType: 'SCAN_IMPORT', resourceId: job.id, version: 2 }, replayed: false } }); } }); await openScan(page); await page.getByLabel('人工操作原因', { exact: true }).fill('Synthetic cancel'); await page.getByRole('button', { name: '取消任务', exact: true }).dblclick(); await expect(page.getByRole('button', { name: '原键确认导入操作' })).toBeEnabled(); expect(writes).toHaveLength(1); await page.getByRole('button', { name: '原键确认导入操作' }).click(); await expect(page.getByRole('cell', { name: 'CANCELLED', exact: true })).toBeVisible(); expect(writes[1]).toEqual(writes[0]); await expect(page.getByRole('button', { name: '本地解析合成头' })).toBeDisabled();
});
