import {test,expect,type Page} from '@playwright/test';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',result='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',scope='11111111-1111-4111-8111-111111111111';
const fields={gross:'',microscopy:'',diagnosis:'Synthetic untouched manual',notes:''};
const revision={id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',caseId:id,version:0,templateCode:'SYN-REPORT',templateVersion:1,fields,assignmentVersion:0,authorId:'synthetic-user',reason:'Synthetic',createdAt:'2026-01-01T00:00:00Z'};
function view(){return {caseId:id,resultId:result,version:-1,assignmentVersion:0,page:1,executionAllowed:false,ready:true,invalidReason:null,target:revision,source:{id:result,artifactHash:'a'.repeat(64),binding:{resultId:result,input:{caseId:id,preprocessing:'SYN-PRE-1',configDigest:'b'.repeat(64),decision:{executionAllowed:false,modelDigest:'c'.repeat(64)}}}},history:[]};}
async function setup(page:Page){
 await page.route('**/api/auth/me',r=>r.fulfill({json:{id:'synthetic-user',username:'synthetic',displayName:'合成用户'}}));await page.route('**/api/auth/csrf',r=>r.fulfill({json:{headerName:'X-CSRF-TOKEN',token:'synthetic-only'}}));await page.route('**/api/hello',r=>r.fulfill({json:{application:'PIS',message:'Hello'}}));await page.route('**/api/requests/work-context', route => route.fulfill({ json: { defaultScopeId: scope, writableScopes: [scope], name: '合成范围', scopes: [{ id: scope, name: '合成范围' }], administration: false, menus: ['operations', 'adapters', 'requests', 'registration', 'manual', 'reception', 'labels', 'grossing', 'technical', 'materials', 'quality', 'worklist', 'diagnosis', 'report', 'review', 'output', 'amendments', 'delivery', 'frozen', 'cytology', 'staining', 'consultation', 'archive', 'statistics', 'storage', 'scan', 'digitalqc', 'viewer', 'ai', 'aitasks'] } }));await page.route('**/api/requests?*',r=>r.fulfill({json:{items:[],total:0,page:1,pageSize:20}}));
 const item={caseId:id,requestId:'synthetic-request',patientId:'synthetic-patient',number:'SYN-REFERENCE',state:'ACTIVE',version:0,ownerId:'synthetic-user',ready:true};
 await page.route('**/api/requests/diagnosis/{scopes,output-scopes}/*',r=>r.fulfill({json:{total:1,page:1,pageSize:10,items:[item]}}));await page.route('**/api/requests/reports/cases/'+id,r=>r.fulfill({json:{context:{...item,assignmentVersion:0},current:revision,templates:[{code:'SYN-REPORT',version:1,title:'合成模板',schemaCode:'SYN-TEXT-1'}]}}));await page.route('**/api/requests/reports/cases/'+id+'/history?*',r=>r.fulfill({json:{caseId:id,page:1,revisions:[revision]}}));await page.route('**/synthetic-decisions?*',r=>r.fulfill({json:view()}));
 await page.goto('/');await page.getByRole('button',{name:'申请登记工作区'}).click();await expect(page.getByText('当前工作范围：合成范围', { exact: true })).toBeVisible();await page.getByRole('button',{name:'报告草稿',exact:true}).click();await page.getByRole('button',{name:'编辑报告草稿 '+id}).click();await page.getByRole('button',{name:'医生人工处理合成结果',exact:true}).click();await page.getByLabel('人工处理结果ID',{exact:true}).fill(result);await page.getByRole('button',{name:'核验人工处理依据'}).click();await expect(page.getByText(/决定版本 -1/)).toBeVisible();
}
test('explicit confirmation cancel, dirty return and immutable synthetic snapshot screenshot',async({page},info)=>{await setup(page);let writes=0;await page.route('**/synthetic-decisions',r=>{writes++;return r.fulfill({json:{receipt:{status:200,resourceType:'SYNTHETIC_REPORT_DECISION',resourceId:'event',version:0},replayed:false}});});await page.getByLabel('人工处理动作').click();await page.getByRole('option',{name:'采纳非诊断引用',exact:true}).click();await page.getByLabel('人工处理原因').fill('Synthetic explicit reference only');await page.getByRole('button',{name:'确认人工处理版本'}).click();await page.getByRole('button',{name:'保留并返回'}).click();expect(writes).toBe(0);await expect(page.getByLabel('人工处理原因')).toHaveValue('Synthetic explicit reference only');await page.getByRole('button',{name:'返回报告草稿'}).click();await page.getByRole('button',{name:'保留表单'}).click();await page.getByText('精确输入、模型及配置快照').click();await page.screenshot({path:info.outputPath('synthetic-human-reference.png'),fullPage:true});await page.getByRole('button',{name:'确认人工处理版本'}).click();await page.getByRole('button',{name:'明确提交人工处理'}).click();await expect.poll(()=>writes).toBe(1);await expect(page.getByLabel('人工处理原因')).toHaveValue('');});
test('uncertain retry keeps exact key body, double click and controlled late response cannot overwrite form',async({page})=>{await setup(page);const requests:{key:string;body:unknown}[]=[];let release=()=>{};const gate=new Promise<void>(r=>{release=r;});await page.route('**/synthetic-decisions',async r=>{requests.push({key:r.request().headers()['idempotency-key'],body:r.request().postDataJSON() as unknown});if(requests.length===1)await r.abort('failed');else{await gate;await r.fulfill({json:{receipt:{status:200,resourceType:'SYNTHETIC_REPORT_DECISION',resourceId:'event',version:0},replayed:true}});}});await page.getByLabel('人工处理原因').fill('Synthetic defer');await page.getByRole('button',{name:'确认人工处理版本'}).click();await page.getByRole('button',{name:'明确提交人工处理'}).click();await page.getByRole('button',{name:'原键确认人工处理'}).click();await expect.poll(()=>requests.length).toBe(2);await expect(page.getByRole('button',{name:'返回报告草稿'})).toBeDisabled();await expect(page.getByLabel('人工处理原因')).toBeDisabled();expect(requests[1]).toEqual(requests[0]);release();await expect(page.getByLabel('人工处理原因')).toHaveValue('');await expect(page.getByRole('button',{name:'原键确认人工处理'})).toHaveCount(0);expect(requests).toHaveLength(2);});
test('revoked source remains visible as history but blocks all new decisions',async({page})=>{await setup(page);await page.route('**/synthetic-decisions?*',r=>r.fulfill({json:{...view(),ready:false,invalidReason:'RESULT_DEPENDENCY_CHANGED'}}));await page.getByRole('button',{name:'核验人工处理依据'}).click();await expect(page.getByText('禁止新处理：RESULT_DEPENDENCY_CHANGED')).toBeVisible();await page.getByLabel('人工处理原因').fill('Synthetic');await expect(page.getByRole('button',{name:'确认人工处理版本'})).toBeDisabled();});
test('cancelled delayed source cannot replace newly selected exact result',async({page})=>{await setup(page);const other='dddddddd-dddd-4ddd-8ddd-dddddddddddd';let captured=()=>{},release=()=>{},finished=()=>{};const seen=new Promise<void>(r=>{captured=r;}),gate=new Promise<void>(r=>{release=r;}),done=new Promise<void>(r=>{finished=r;});await page.route('**/synthetic-decisions?*',async r=>{if(new URL(r.request().url()).searchParams.get('resultId')===result){captured();await gate;await r.fulfill({json:view()});finished();}else{const v=view();await r.fulfill({json:{...v,resultId:other,source:{...v.source,id:other,binding:{...v.source.binding,resultId:other}}}});}});await page.getByRole('button',{name:'核验人工处理依据'}).click();await seen;await page.getByRole('button',{name:'取消等待人工处理'}).click();await page.getByLabel('人工处理结果ID',{exact:true}).fill(other);await page.getByRole('button',{name:'核验人工处理依据'}).click();await expect(page.getByText(/决定版本 -1/)).toContainText(other);release();await done;await expect(page.getByText(/决定版本 -1/)).toContainText(other);await expect(page.getByText(/决定版本 -1/)).not.toContainText(result);});

test('action-only changes require explicit discard before refreshing',async({page})=>{await setup(page);await page.getByLabel('人工处理动作').click();await page.getByRole('option',{name:'拒绝',exact:true}).click();await page.getByRole('button',{name:'核验人工处理依据'}).click();await expect(page.getByRole('dialog')).toContainText('清除人工处理表单');await page.getByRole('button',{name:'清除并核验'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByLabel('人工处理动作').click();await expect(page.getByRole('option',{name:'暂缓',exact:true})).toHaveAttribute('aria-selected','true');});
