import {test,expect,type Page} from '@playwright/test';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',result='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',scope='11111111-1111-4111-8111-111111111111';
const fields={gross:'',microscopy:'',diagnosis:'Synthetic untouched manual',notes:''};
const revision={id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',caseId:id,version:0,templateCode:'SYN-REPORT',templateVersion:1,fields,assignmentVersion:0,authorId:'synthetic-user',reason:'Synthetic',createdAt:'2026-01-01T00:00:00Z'};
function view(){return {caseId:id,resultId:result,version:-1,assignmentVersion:0,page:1,executionAllowed:false,ready:true,invalidReason:null,target:revision,source:{id:result,artifactHash:'a'.repeat(64),binding:{resultId:result,input:{caseId:id,preprocessing:'SYN-PRE-1',configDigest:'b'.repeat(64),decision:{executionAllowed:false,modelDigest:'c'.repeat(64)}}}},history:[]};}
async function base(page:Page){
 await page.route('**/api/auth/me',r=>r.fulfill({json:{id:'synthetic-user',username:'synthetic',displayName:'合成用户'}}));await page.route('**/api/auth/csrf',r=>r.fulfill({json:{headerName:'X-CSRF-TOKEN',token:'synthetic-only'}}));await page.route('**/api/hello',r=>r.fulfill({json:{application:'PIS',message:'Hello'}}));await page.route('**/api/requests/scopes',r=>r.fulfill({json:[{id:scope,name:'合成范围'}]}));await page.route('**/api/requests?*',r=>r.fulfill({json:{items:[],total:0,page:1,pageSize:20}}));
 const item={caseId:id,requestId:'synthetic-request',patientId:'synthetic-patient',number:'SYN-REFERENCE',state:'ACTIVE',version:0,ownerId:'synthetic-user',ready:true};
 await page.route('**/api/requests/diagnosis/scopes/*',r=>r.fulfill({json:{total:1,page:1,pageSize:10,items:[item]}}));await page.route('**/api/requests/reports/cases/'+id,r=>r.fulfill({json:{context:{...item,assignmentVersion:0},current:revision,templates:[{code:'SYN-REPORT',version:1,title:'合成模板',schemaCode:'SYN-TEXT-1'}]}}));await page.route('**/api/requests/reports/cases/'+id+'/history?*',r=>r.fulfill({json:{caseId:id,page:1,revisions:[revision]}}));await page.route('**/synthetic-decisions?*',r=>r.fulfill({json:view()}));
 await page.goto('/');await page.getByRole('button',{name:'申请登记工作区'}).click();await page.getByRole('combobox',{name:'授权工作范围'}).click();await page.getByText('合成范围',{exact:true}).last().click();await page.getByRole('button',{name:'报告草稿',exact:true}).click();await page.getByRole('button',{name:'编辑报告草稿 '+id}).click();await page.getByRole('button',{name:'医生人工处理合成结果',exact:true}).click();await page.getByLabel('人工处理结果ID',{exact:true}).fill(result);await page.getByRole('button',{name:'核验人工处理依据'}).click();await expect(page.getByText(/决定版本 -1/)).toBeVisible();
}

const decision='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
const entry={id:decision,caseId:id,resultId:result,version:0,targetRevisionId:revision.id,targetVersion:0,action:'ACCEPT_REFERENCE',reason:'Synthetic prior choice',actorId:'synthetic-user',recordedAt:'2026-01-01T00:00:00Z',adoptedRevisionId:revision.id,artifactHash:'a'.repeat(64),binding:{}};
function impact(){return {caseId:id,decision:entry,snapshot:{decisionId:decision,resultId:result,epoch:'a'.repeat(64),currentRevisionId:revision.id,assignmentVersion:0,reportFrozen:true,reportReady:true,validity:{epoch:'b'.repeat(64),reasons:['MODEL_DISABLED_OR_RETIRED'],dependencies:{modelStateVersion:2,modelState:'DISABLED',qcVersion:1,scanHead:0}}},version:-1,sourceValid:false,consumable:false,pendingReview:true,history:[],executionAllowed:false};}
async function setup(page:Page){await base(page);await page.route('**/synthetic-decisions?*',r=>r.fulfill({json:{...view(),history:[entry]}}));await page.route('**/impact',r=>r.fulfill({json:impact()}));await page.getByRole('button',{name:'核验人工处理依据'}).click();await page.getByRole('button',{name:`查看失效影响 ${decision}`}).click();await expect(page.getByText('待人工复核',{exact:true})).toBeVisible();}
test('explicit impact acknowledgement preserves historical report and screenshot',async({page},info)=>{await setup(page);let writes=0;await page.route('**/impact-reviews',r=>{writes++;return r.fulfill({json:{receipt:{status:200,resourceType:'SYNTHETIC_IMPACT_REVIEW',resourceId:'review',version:0},replayed:false}});});await page.getByLabel('影响复核动作').click();await page.getByRole('option',{name:'已知悉失效并保留历史',exact:true}).click();await page.getByLabel('影响复核理由').fill('Synthetic invalidation reviewed; keep original report');await page.getByRole('button',{name:'确认影响快照'}).click();await page.getByRole('button',{name:'保留并返回',exact:true}).click();expect(writes).toBe(0);await page.getByText('精确失效依赖与原目标版本').click();await page.screenshot({path:info.outputPath('synthetic-impact-history.png'),fullPage:true});await page.getByRole('button',{name:'确认影响快照'}).click();await page.getByRole('button',{name:'提交此快照复核'}).click();await expect.poll(()=>writes).toBe(1);await expect(page.getByLabel('影响复核理由')).toHaveValue('');await expect(page.getByText('仅授权历史；不可作为当前有效引用消费',{exact:true})).toBeVisible();});
test('dirty refresh and back require explicit clearing; conflict preserves input',async({page})=>{await setup(page);await page.getByLabel('影响复核理由').fill('Synthetic unsaved reason');await page.getByRole('button',{name:'返回人工决定'}).click();await page.getByRole('button',{name:'保留复核表单'}).click();await expect(page.getByLabel('影响复核理由')).toHaveValue('Synthetic unsaved reason');await page.route('**/impact-reviews',r=>r.fulfill({status:409,json:{code:'AI_IMPACT_CHANGED',detail:'Synthetic snapshot changed'}}));await page.getByRole('button',{name:'确认影响快照'}).click();await page.getByRole('button',{name:'提交此快照复核'}).click();await expect(page.getByText('失效影响快照已变化，请保留理由并重新核验。',{exact:true})).toBeVisible();await expect(page.getByLabel('影响复核理由')).toHaveValue('Synthetic unsaved reason');await page.getByRole('button',{name:'重新核验失效影响'}).click();await page.getByRole('button',{name:'清除并继续'}).click();await expect(page.getByLabel('影响复核理由')).toHaveValue('');});
test('uncertain review uses identical key and body with controlled delayed replay',async({page})=>{await setup(page);const calls:{key:string;body:unknown}[]=[];let release=()=>{};const gate=new Promise<void>(r=>{release=r;});await page.route('**/impact-reviews',async r=>{calls.push({key:r.request().headers()['idempotency-key'],body:r.request().postDataJSON() as unknown});if(calls.length===1)await r.abort('failed');else{await gate;await r.fulfill({json:{receipt:{status:200,resourceType:'SYNTHETIC_IMPACT_REVIEW',resourceId:'review',version:0},replayed:true}});}});await page.getByLabel('影响复核理由').fill('Synthetic defer');await page.getByRole('button',{name:'确认影响快照'}).click();await page.getByRole('button',{name:'提交此快照复核'}).click();await page.getByRole('button',{name:'原键确认影响复核'}).click();await expect.poll(()=>calls.length).toBe(2);expect(calls[1]).toEqual(calls[0]);await expect(page.getByRole('button',{name:'返回人工决定'})).toBeDisabled();release();await expect(page.getByLabel('影响复核理由')).toHaveValue('');expect(calls).toHaveLength(2);});
test('cancelled delayed impact cannot reopen old history after return',async({page})=>{await setup(page);let captured=()=>{},release=()=>{},finished=()=>{};const seen=new Promise<void>(r=>{captured=r;}),gate=new Promise<void>(r=>{release=r;}),done=new Promise<void>(r=>{finished=r;});await page.route('**/impact',async r=>{captured();await gate;await r.fulfill({json:impact()});finished();});await page.getByRole('button',{name:'重新核验失效影响'}).click();await seen;await page.getByRole('button',{name:'取消等待影响'}).click();await page.getByRole('button',{name:'返回人工决定'}).click();await expect(page.getByLabel('人工处理结果ID',{exact:true})).toBeVisible();release();await done;await expect(page.getByLabel('合成引用失效复核',{exact:true})).toHaveCount(0);await expect(page.getByLabel('人工处理结果ID',{exact:true})).toBeVisible();});
test('cancelled write wait preserves exact intent and late response cannot clear new retry',async({page})=>{await setup(page);const calls:{key:string;body:unknown}[]=[];let release=()=>{},captured=()=>{},done=()=>{};const gate=new Promise<void>(r=>{release=r;}),seen=new Promise<void>(r=>{captured=r;}),finished=new Promise<void>(r=>{done=r;});await page.route('**/impact-reviews',async r=>{calls.push({key:r.request().headers()['idempotency-key'],body:r.request().postDataJSON() as unknown});if(calls.length===1){captured();await gate;}await r.fulfill({json:{receipt:{status:200,resourceType:'SYNTHETIC_IMPACT_REVIEW',resourceId:'same-review',version:0},replayed:calls.length>1}});if(calls.length===1)done();});await page.getByLabel('影响复核理由').fill('Synthetic cancel wait');await page.getByRole('button',{name:'确认影响快照'}).click();await page.getByRole('button',{name:'提交此快照复核'}).click();await seen;await page.getByRole('button',{name:'取消等待影响'}).click();await expect(page.getByRole('button',{name:'原键确认影响复核'})).toBeVisible();release();await finished;await expect(page.getByLabel('影响复核理由')).toHaveValue('Synthetic cancel wait');await page.getByRole('button',{name:'原键确认影响复核'}).click();await expect.poll(()=>calls.length).toBe(2);expect(calls[1]).toEqual(calls[0]);await expect(page.getByLabel('影响复核理由')).toHaveValue('');});
