import {test,expect,type Page} from '@playwright/test';
import {render} from './viewer-fixture';
const rid='44444444-4444-4444-8444-444444444444';
const job={id:'task-a',requestId:rid,scanId:'scan-qc',assessmentId:'assessment-a',state:'QUEUED',version:0,generation:0,progress:null,leaseId:null,artifactId:null,bindingHash:'a'.repeat(64),binding:{decision:{executionAllowed:false,requestId:rid,scanId:'scan-qc',modelDigest:'b'.repeat(64),objectHash:'c'.repeat(64)},preprocessing:'SYN-PRE',configDigest:'d'.repeat(64)}};
const detail={job,effectiveState:'QUEUED',invalidReason:null,clinicalExecutionAllowed:false,history:[]};
async function start(page:Page){await page.route('**/synthetic-tasks?*',r=>r.fulfill({json:{requestId:rid,scanId:'scan-qc',page:1,jobs:[job,{...job,id:'task-b'}],capability:'SYNTHETIC_CONTRACT_ONLY_NO_CLINICAL_EXECUTION'}}));await page.route('**/synthetic-tasks/task-*',r=>r.fulfill({json:{...detail,job:{...job,id:r.request().url().endsWith('task-b')?'task-b':'task-a'}}}));await render(page);await page.getByRole('button',{name:'此扫描合成任务队列',exact:true}).click();await page.getByRole('button',{name:'刷新合成任务',exact:true}).click();await page.getByRole('button',{name:'核验任务 task-a',exact:true}).click();await expect(page.getByRole('region',{name:'合成契约任务'}).getByRole('status')).toContainText('未知');}
test('synthetic queue has unknown progress, explicit dirty cancellation and independent task identity',async({page},info)=>{await start(page);await page.getByLabel('合成任务操作原因',{exact:true}).fill('Unsaved synthetic reason');await page.getByRole('button',{name:'核验任务 task-b',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'保留任务表单',exact:true}).click();await expect(page.getByLabel('合成任务操作原因',{exact:true})).toHaveValue('Unsaved synthetic reason');await page.getByRole('button',{name:'核验任务 task-b',exact:true}).click();await page.getByRole('button',{name:'清除并重新核对',exact:true}).click();await expect(page.getByLabel('任务精确版本',{exact:true})).toContainText('task-b');await expect(page.getByLabel('合成任务操作原因',{exact:true})).toHaveValue('');await expect(page.getByRole('dialog')).toBeHidden();await page.screenshot({path:info.outputPath('synthetic-task-queue.png'),fullPage:true});});
test('delayed cancelled wait cannot write into another task; unresolved command retains exact retry key',async({page})=>{await start(page);let release:()=>void=()=>{};const gate=new Promise<void>(r=>{release=r;});const received: {body:unknown;key:string|undefined}[]=[];await page.route('**/synthetic-tasks/task-a/actions/CLAIM',async r=>{received.push({body:r.request().postDataJSON() as unknown,key:r.request().headers()['idempotency-key']});if(received.length===1)await gate;await r.fulfill({json:{receipt:{status:200,resourceType:'SYNTHETIC_AI_TASK',resourceId:'task-a',version:1},replayed:received.length>1}});});await page.getByLabel('合成任务操作原因',{exact:true}).fill('Synthetic claim');await page.getByRole('button',{name:'领取合成任务',exact:true}).click();await expect.poll(()=>received.length).toBe(1);await expect(page.getByRole('button',{name:'核验任务 task-b',exact:true})).toBeDisabled();await page.getByRole('button',{name:'停止等待任务请求',exact:true}).click();release();await page.route('**/synthetic-tasks/task-a',r=>r.fulfill({json:{...detail,job:{...job,state:'RUNNING',version:1,generation:1,leaseId:'lease'},effectiveState:'RUNNING'}}));await page.getByRole('button',{name:'原键确认任务操作',exact:true}).click();await expect(page.getByRole('button',{name:'原键确认任务操作',exact:true})).toBeDisabled();expect(received).toHaveLength(2);expect(received[1]).toEqual(received[0]);await expect(page.getByRole('region',{name:'合成契约任务'}).getByRole('status')).toContainText('RUNNING');});
test('revoked task and failed requests are errors, never empty success or zero progress',async({page})=>{await start(page);await page.route('**/synthetic-tasks/task-b',r=>r.fulfill({status:404,json:{code:'AI_TASK_NOT_FOUND'}}));await page.getByRole('button',{name:'核验任务 task-b',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'合成任务或当前资格不可用'})).toBeVisible();await expect(page.getByLabel('任务精确版本',{exact:true})).toHaveCount(0);});
test('technical artifact is explicitly fetched and revoked reads clear previously shown content',async({page})=>{await start(page);await page.route('**/synthetic-tasks/task-b',r=>r.fulfill({json:{...detail,job:{...job,id:'task-b',state:'SYNTHETIC_SUCCEEDED',version:2,generation:1,progress:100,leaseId:'lease',artifactId:'artifact'},effectiveState:'SYNTHETIC_SUCCEEDED'}}));await page.getByRole('button',{name:'核验任务 task-b',exact:true}).click();await page.route('**/synthetic-tasks/task-b/artifact',r=>r.fulfill({contentType:'application/octet-stream',body:'PIS-SYNTHETIC-STORAGE-V1\nNON_DIAGNOSTIC_SYNTHETIC_CONTRACT_ONLY\nSYN-CONTRACT-WORKER-1\n'}));await expect(page.getByLabel('合成技术产物',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'读取非诊断技术产物',exact:true}).click();await expect(page.getByLabel('合成技术产物',{exact:true})).toContainText('NON_DIAGNOSTIC');await page.route('**/synthetic-tasks/task-b/artifact',r=>r.fulfill({status:409,json:{code:'AI_CONFLICT'}}));await page.getByRole('button',{name:'读取非诊断技术产物',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'AI依据版本已变化'})).toBeVisible();await expect(page.getByLabel('合成技术产物',{exact:true})).toHaveCount(0);});
