import type { Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import type { Tile } from '../src/features/viewer/api';
const rid = '44444444-4444-4444-8444-444444444444', vid = '55555555-5555-4555-8555-555555555555';
const view = { requestId: rid, caseId: 'case-syn', patientId: 'patient-syn', page: 1, jobs: [{ id: 'scan-qc', requestId: rid, caseId: 'case-syn', patientId: 'patient-syn', claimedCaseId: 'case-syn', claimedPatientId: 'patient-syn', slideId: 'slide-a', objectId: 'object-a', objectHash: 'a'.repeat(64), objectSize: 256, ordinal: 0, previousId: null, sourceBasis: 'b'.repeat(64), barcode: 'SYN-A', sourceCode: 'SYN-LOCAL', scannerCode: 'SYN-DEV', reason: 'Synthetic', state: 'PENDING_DIGITAL_QC', errorCode: 'DIGITAL_QC_REQUIRED', version: 2, attempts: 1, leaseId: 'lease', leaseActor: 'actor', leaseUntil: null, retryAt: null, width: 32, height: 32, invalidReason: '' }], slides: [{ id: 'slide-a', barcode: 'SYN-A', version: 0, status: 'PASS' }, { id: 'slide-b', barcode: 'SYN-B', version: 0, status: 'PASS' }], capabilities: { SYNTHETIC_HEADER_V1: 'CONTRACT_ONLY', TIFF_CONTAINER: 'NOT_CONFIGURED', SVS: 'NOT_CONFIGURED', NDPI: 'NOT_CONFIGURED', MRXS: 'NOT_CONFIGURED', ARCHIVE: 'UNSUPPORTED' }, publication: 'NOT_PUBLISHED_BY_IMPORT' };
const scope = '11111111-1111-4111-8111-111111111111';
const encounter = { id: '22222222-2222-4222-8222-222222222222', patientId: '33333333-3333-4333-8333-333333333333', patientLabel: '合成患者', encounterNumber: 'SYN-001' };
async function start(page: Page) {
  await page.route('**/api/auth/me', route => route.fulfill({ json: { id: 'synthetic-user', username: 'synthetic', displayName: '合成用户' } }));
  await page.route('**/api/auth/csrf', route => route.fulfill({ json: { headerName: 'X-CSRF-TOKEN', token: 'synthetic-only' } }));
  await page.route('**/api/hello', route => route.fulfill({ json: { application: 'PIS', message: 'Hello World' } }));
  await page.route('**/api/requests/scopes', route => route.fulfill({ json: [{ id: scope, name: '合成院区 / 科室' }] }));
  await page.route('**/api/requests?*', route => route.fulfill({ json: { items: [], total: 0, page: 1, pageSize: 20 } }));
  await page.route('**/api/requests/encounters?*', route => route.fulfill({ json: [encounter] }));
  await page.goto('/');
  await page.getByRole('button', { name: '申请登记工作区' }).click();
  await page.getByRole('combobox', { name: '授权工作范围' }).click();
  await page.getByText('合成院区 / 科室', { exact: true }).last().click();
}
async function openScan(page: Page) {
 await start(page); const d = { id: rid, scopeId: scope, version: 2, state: 'RECEIVED', requestNumber: 'DEV-AP-STORAGE', patientId: encounter.patientId, patientLabel: encounter.patientLabel, encounterId: encounter.id, encounterNumber: encounter.encounterNumber, department: '合成科室', requestedAt: '2026-01-01T08:00:00Z', clinicalHistory: '合成资料', sampledAt: '2026-01-01T08:00:00Z', containers: [{ id: vid, site: 'Synthetic', laterality: 'UNKNOWN', materialQuantity: 1, fixative: 'Synthetic', fixedAt: '2026-01-01T08:10:00Z' }] };
 await page.route('**/api/requests?*', r => r.fulfill({ json: { items: [d], total: 1, page: 1, pageSize: 20 } })); await page.route('**/api/requests/' + rid, r => r.fulfill({ json: d })); await page.getByRole('button', { name: '刷新', exact: true }).click(); await page.getByRole('button', { name: '查看 DEV-AP-STORAGE', exact: true }).click(); await page.getByRole('button', { name: '处理此申请扫描导入', exact: true }).click();
}


const qc = { requestId: rid, scanId: 'scan-qc', caseId: 'case-syn', slideId: 'slide-a', objectId: 'object-a', objectHash: 'a'.repeat(64), scanVersion: 2, ordinal: 0, currentScan: true, version: -1, state: 'UNASSESSED', effectiveState: 'ISOLATED', invalidReason: 'UNASSESSED', assessment: null, events: [], capability: 'SYNTHETIC_CONTRACT_ONLY_NO_VIEWER' };
async function openQc(page: Page) { await page.route('**/scans?*', r => r.fulfill({ json: view })); await openScan(page); await page.getByRole('button', { name: '数字QC 0', exact: true }).click(); }
const tileSets = { a: JSON.parse(readFileSync(new URL('./fixtures/viewer/a/tiles.json', import.meta.url), 'utf8')) as Tile[], b: JSON.parse(readFileSync(new URL('./fixtures/viewer/b/tiles.json', import.meta.url), 'utf8')) as Tile[] };
const assessment = { version: 0, scanVersion: 2, objectId: 'object-a', slideId: 'slide-a', objectHash: 'a'.repeat(64), sourceBasis: 'b'.repeat(64), checklist: 'SYN-DIGITAL-QC-1', coverage: 'PASS', focus: 'PASS', missing: 'PASS', coveragePercent: 100, missingTiles: 0, regions: [], note: 'Synthetic', passed: true, actorId: 'actor', occurredAt: '2026-10-03T00:00:00Z' };
const published = { ...qc, version: 1, state: 'PUBLISHED', effectiveState: 'PUBLISHED_SYNTHETIC_CONTRACT', invalidReason: '', assessment };
export function manifest(scan: string) { const b = scan === 'scan-b'; return { publicationVersion: 1, capability: 'SYNTHETIC_RGB_ONLY', calibration: 'UNAVAILABLE_NO_PHYSICAL_SCALE', content: { hospitalId: 'hospital-syn', requestId: rid, scanId: scan, slideId: b ? 'slide-b' : 'slide-a', objectId: b ? 'object-b' : 'object-a', objectHash: (b ? 'b' : 'a').repeat(64), scanVersion: 2, provider: 'SYN-RGB-PYRAMID-1', width: 512, height: 384, tileSize: 128, maxLevel: 9, manifestHash: (b ? 'd' : 'c').repeat(64), tiles: tileSets[b ? 'b' : 'a'] } }; }
export async function render(page: Page, state: { revoked?: boolean; broken?: boolean; delayA?: Promise<void>; prepare?: { keys: string[]; pending: Promise<void>; ready: boolean } } = {}) {
 await page.route('**/digital-qc', r => r.fulfill({ json: { ...published, scanId: r.request().url().includes('/scan-b/') ? 'scan-b' : 'scan-qc' } }));
 await page.route(/\/api\/requests\/[^/]+\/scans\/[^/]+\/viewer(?:\/|\?|$)/, async r => { const url = new URL(r.request().url()), b = url.pathname.includes('/scan-b/'), scan = b ? 'scan-b' : 'scan-qc'; if (state.revoked) { await r.fulfill({ status: 409, json: { code: 'DIGITAL_QC_NOT_READY' } }); return; } if (url.pathname.endsWith('/viewer')) { if (state.prepare) { if (r.request().method() === 'POST') { state.prepare.keys.push(r.request().headers()['idempotency-key']); if (state.prepare.keys.length === 1) await state.prepare.pending; else state.prepare.ready = true; await r.fulfill({ json: { receipt: { resourceId: scan, resourceType: 'VIEWER_MANIFEST', version: 0, status: 200 }, replayed: false } }).catch(() => {}); return; } if (!state.prepare.ready) { await r.fulfill({ status: 409, json: { code: 'VIEWER_NOT_PREPARED' } }); return; } } if (!b && state.delayA) await state.delayA; await r.fulfill({ json: manifest(scan) }).catch(() => {}); return; } const part = url.pathname.match(/tiles\/(\d+)\/(\d+)\/(\d+)$/); if (!part || state.broken) { await r.fulfill({ status: 404, json: { code: 'VIEWER_TILE_MISSING' } }); return; } const t = tileSets[b ? 'b' : 'a'].find(t => t.level === Number(part[1]) && t.x === Number(part[2]) && t.y === Number(part[3])); if (!t) { await r.fulfill({ status: 404 }); return; } const body = readFileSync(new URL(`./fixtures/viewer/${b ? 'b' : 'a'}/${part[1]}-${part[2]}-${part[3]}.png`, import.meta.url)); await r.fulfill({ body, contentType: 'image/png', headers: { 'Content-Length': String(body.length), 'X-Content-SHA256': t.sha256, 'Cache-Control': 'private, no-store' } }); });
 await openQc(page); await page.route('**/scans?*', r => r.fulfill({ json: { ...view, jobs: [...view.jobs, { ...view.jobs[0], id: 'scan-b', slideId: 'slide-b', objectId: 'object-b' }] } })); await page.getByRole('button', { name: '打开合成瓦片阅片器' }).click();
}
export async function pixels(page: Page) { return page.getByLabel('合成瓦片画布', { exact: true }).locator('canvas').first().evaluate(canvas => { const c = canvas as HTMLCanvasElement, ctx = c.getContext('2d'); if (!ctx) return { pink: 0, green: 0 }; const d = ctx.getImageData(0, 0, c.width, c.height).data; let pink = 0, green = 0; for (let i = 0; i < d.length; i += 16) { if (d[i] > 140 && d[i + 2] > 120 && d[i] > d[i + 1] + 15) pink++; if (d[i + 1] > d[i + 2] + 20 && d[i] > 120) green++; } return { pink, green }; }); }
