package com.pis.integration;
import static com.pis.integration.HospitalAdapterContracts.*;
import com.pis.accession.*;import com.pis.api.ApiException;import com.pis.audit.*;import com.pis.idempotency.*;import com.pis.material.MaterialService;import com.pis.report.DeliveryPolicy;
import java.util.*;import java.time.*;import jakarta.validation.*;import org.springframework.stereotype.Service;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.http.HttpStatus;import org.springframework.transaction.annotation.Transactional;import org.springframework.transaction.support.TransactionSynchronizationManager;import tools.jackson.databind.json.JsonMapper;
@Service
public class HospitalAdapterService {
 private final JdbcTemplate jdbc;private final WorkflowAccess access;private final RequestService requests;private final MaterialService materials;private final IdempotentCommands commands;private final AuditRecorder audit;private final Validator validator;private final JsonMapper json;
 public HospitalAdapterService(JdbcTemplate jdbc,WorkflowAccess access,RequestService requests,MaterialService materials,IdempotentCommands commands,AuditRecorder audit,Validator validator,JsonMapper json){this.jdbc=jdbc;this.access=access;this.requests=requests;this.materials=materials;this.commands=commands;this.audit=audit;this.validator=validator;this.json=json;}
 private static ApiException error(String code){return new ApiException(HttpStatus.CONFLICT,code,"Local synthetic adapter requires exact identity, sequence and receipt evidence");}
 private static ApiException missing(){return new ApiException(HttpStatus.NOT_FOUND,"ADAPTER_NOT_FOUND","Synthetic adapter resource unavailable");}
 private void validate(Object input){var errors=validator.validate(input);if(!errors.isEmpty())throw new ConstraintViolationException(errors);}
 private RequestService.CaseIdentity context(UUID request,boolean write){try{var c=requests.caseIdentity(request);if(TransactionSynchronizationManager.isActualTransactionActive()){jdbc.queryForList("SELECT id FROM pathology_request WHERE id=? FOR UPDATE",request);jdbc.queryForList("SELECT user_id FROM adapter_grant WHERE scope_id=? AND user_id=? FOR SHARE",c.scopeId(),access.actor().id());}c=requests.caseIdentity(request);access.require(c.scopeId(),write);if(jdbc.queryForObject("SELECT count(*) FROM adapter_grant WHERE scope_id=? AND user_id=? AND qualification='SYN-ADAPTER-1' AND revoked_at IS NULL AND valid_until>statement_timestamp()",Long.class,c.scopeId(),access.actor().id())!=1)throw missing();return c;}catch(org.springframework.security.access.AccessDeniedException e){throw missing();}}
 private static Instant time(java.sql.ResultSet r,String name)throws java.sql.SQLException{var t=r.getObject(name,OffsetDateTime.class);return t==null?null:t.toInstant();}
 private static final String SELECT="SELECT m.*,o.version,o.state,o.attempts,o.attempt_id,o.lease_until,o.next_at,o.error_code,EXISTS(SELECT 1 FROM adapter_local_record r WHERE r.message_id=m.id) recorded FROM adapter_message m JOIN adapter_outbox o ON o.message_id=m.id WHERE m.request_id=?";
 private Item map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new Item(r.getObject("id",UUID.class),r.getObject("request_id",UUID.class),r.getObject("case_id",UUID.class),r.getObject("source_id",UUID.class),Adapter.valueOf(r.getString("adapter")),r.getString("external_id"),r.getInt("sequence"),r.getString("payload_hash"),r.getLong("version"),r.getString("state"),r.getInt("attempts"),r.getObject("attempt_id",UUID.class),time(r,"lease_until"),time(r,"next_at"),r.getString("error_code"),r.getBoolean("recorded"));}
 private Item item(UUID request,UUID id){var rows=jdbc.query(SELECT+" AND m.id=?",this::map,request,id);if(rows.isEmpty())throw missing();return rows.getFirst();}
 @Transactional(timeout=10) public View view(UUID request,int page){var c=context(request,false);if(page<1||page>50)throw error("ADAPTER_PAGE");audit.append(c.hospitalId(),"ADAPTER_QUERY_V1","PATHOLOGY_CASE",c.caseId(),null,0);return new View(request,c.caseId(),c.patientId(),c.sourceId(),page,jdbc.query(SELECT+" ORDER BY m.created_at DESC,m.id LIMIT 20 OFFSET ?",this::map,request,(page-1)*20),Map.of("HIS","SYN_HOSPITAL_1_LOCAL_ONLY","BILLING","SYNTHETIC_RECORD_NOT_PAYMENT","DEVICE","SYNTHETIC_RECORD_NOT_DEVICE_ACTION","EMR","T21_LOCAL_SIM_ONLY","VENDOR_HIS_EMR_BILLING_DEVICE","NOT_CONFIGURED","HL7_FHIR","NOT_CONFIGURED"));}
 @Transactional(timeout=10) public List<Event> history(UUID request,UUID id){var c=context(request,false);item(request,id);audit.append(c.hospitalId(),"ADAPTER_HISTORY_V1","SYNTHETIC_MESSAGE",id,null,0);return jdbc.query("SELECT * FROM adapter_event WHERE message_id=? ORDER BY version DESC LIMIT 100",(r,i)->new Event(r.getLong("version"),r.getString("action"),r.getString("state"),r.getString("error_code"),r.getObject("actor_id",UUID.class),r.getString("reason"),time(r,"created_at")),id);}
 private void binding(RequestService.CaseIdentity c,Submit input){if(!c.caseId().equals(input.confirmedCaseId())||!c.patientId().equals(input.patientId())||!c.sourceId().equals(input.sourceId()))throw error("ADAPTER_IDENTITY");if((input.adapter()==Adapter.BILLING)!=(input.amountMinor()!=null)||(input.adapter()==Adapter.DEVICE)!=(input.materialId()!=null))throw error("ADAPTER_SCHEMA");if(input.materialId()!=null&&materials.archiveSources(c.requestId()).stream().noneMatch(m->m.id().equals(input.materialId())))throw missing();}
 public IdempotentCommands.Result submit(UUID request,Submit input,String key){validate(input);var c=context(request,true);byte[] payload=json.writeValueAsBytes(input);if(payload.length>4096)throw error("ADAPTER_SIZE");String hash=com.pis.scan.ScanFormat.sha(payload);
  return commands.execute(c.hospitalId(),"ADAPTER_QUEUE_V1",key,Map.of("request",request,"input",input),new IdempotentCommands.Work(){public void authorize(CurrentActor.Actor a){binding(context(request,true),input);}public void authorizeReplay(CurrentActor.Actor a,CommandReceipt r){authorize(a);item(request,r.resourceId());}public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){var now=context(request,true);binding(now,input);var old=jdbc.queryForList("SELECT id FROM adapter_message WHERE scope_id=? AND source_id=? AND adapter=? AND external_id=?",UUID.class,now.scopeId(),input.sourceId(),input.adapter().name(),input.externalId());if(!old.isEmpty()){var saved=item(request,old.getFirst());if(!saved.payloadHash().equals(hash))throw error("ADAPTER_DUPLICATE_CONFLICT");return receipt(saved,null);}if(jdbc.queryForObject("SELECT count(*) FROM adapter_message WHERE request_id=?",Long.class,request)>=1000)throw error("ADAPTER_LIMIT");UUID id=UUID.randomUUID();jdbc.update("INSERT INTO adapter_message(id,request_id,case_id,patient_id,hospital_id,scope_id,source_id,adapter,external_id,sequence,schema_code,payload,payload_hash,actor_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?::jsonb,?,?)",id,request,now.caseId(),now.patientId(),now.hospitalId(),now.scopeId(),now.sourceId(),input.adapter().name(),input.externalId(),input.sequence(),input.schema(),new String(payload,java.nio.charset.StandardCharsets.UTF_8),hash,a.id());jdbc.update("INSERT INTO adapter_outbox(message_id) VALUES(?)",id);event(item(request,id),"QUEUE",input.note());return receipt(item(request,id),null);}});
 }
 private void exact(RequestService.CaseIdentity c,Item old,Command input){if(!c.caseId().equals(input.confirmedCaseId())||!old.caseId().equals(c.caseId())||!c.sourceId().equals(input.sourceId())||!old.sourceId().equals(input.sourceId())||!old.payloadHash().equals(input.payloadHash()))throw error("ADAPTER_IDENTITY");}
 private boolean received(Item old){return jdbc.queryForObject("SELECT count(*) FROM adapter_inbox i JOIN adapter_local_record r ON r.message_id=i.message_id WHERE i.message_id=? AND i.payload_hash=?",Long.class,old.id(),old.payloadHash())==1;}
 private int receiver(Item old){jdbc.update("INSERT INTO adapter_receiver(request_id,adapter) VALUES(?,?) ON CONFLICT DO NOTHING",old.requestId(),old.adapter().name());return jdbc.queryForObject("SELECT sequence FROM adapter_receiver WHERE request_id=? AND adapter=? FOR UPDATE",Integer.class,old.requestId(),old.adapter().name());}
 public IdempotentCommands.Result step(UUID request,UUID id,Action action,Command input,String key){validate(input);var c=context(request,true);return commands.execute(c.hospitalId(),"ADAPTER_"+action+"_V1",key,Map.of("request",request,"id",id,"input",input),new IdempotentCommands.Work(){public void authorize(CurrentActor.Actor a){var scope=context(request,true);exact(scope,item(request,id),input);}public void authorizeReplay(CurrentActor.Actor a,CommandReceipt r){authorize(a);}public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){var scope=context(request,true);var old=item(request,id);exact(scope,old,input);if(old.version()!=input.expectedVersion())throw error("ADAPTER_VERSION");String state=old.state(),code="";int attempts=old.attempts();UUID attempt=old.attemptId();Instant now=jdbc.queryForObject("SELECT statement_timestamp()",OffsetDateTime.class).toInstant(),lease=null,next=old.nextAt();
  switch(action){
   case CLAIM -> {if(!DeliveryPolicy.canClaim(state,attempts,next,now)||input.attemptId()!=null)throw error("ADAPTER_NOT_READY");state="ATTEMPTING";attempts++;attempt=UUID.randomUUID();lease=now.plusSeconds(30);}
   case RECEIVE,ACK -> {if(!DeliveryPolicy.active(state,attempt,input.attemptId(),old.leaseUntil(),now))throw error("ADAPTER_STALE_ATTEMPT");lease=old.leaseUntil();if(action==Action.ACK){if(!received(old))throw error("ADAPTER_ACK_MISMATCH");state="ACKED";lease=null;}else if(!received(old)){if(receiver(old)!=old.sequence()-1){state="REJECTED";code="NACK_OUT_OF_ORDER";lease=null;}else{jdbc.update("INSERT INTO adapter_inbox(message_id,payload_hash) VALUES(?,?)",id,old.payloadHash());jdbc.update("INSERT INTO adapter_local_record(message_id,meaning) VALUES(?,'SYNTHETIC_RECORD_NOT_CLINICAL_DELIVERY_OR_PAYMENT')",id);if(jdbc.update("UPDATE adapter_receiver SET sequence=? WHERE request_id=? AND adapter=? AND sequence=?",old.sequence(),request,old.adapter().name(),old.sequence()-1)!=1)throw error("ADAPTER_VERSION");}}}
   case FAIL,TIMEOUT,POISON -> {if(!state.equals("ATTEMPTING")||!Objects.equals(attempt,input.attemptId())||action==Action.TIMEOUT&&now.isBefore(old.leaseUntil()))throw error("ADAPTER_STALE_ATTEMPT");state=DeliveryPolicy.failureState(attempts,action==Action.POISON);code=action==Action.TIMEOUT?"ACK_UNKNOWN_TIMEOUT":action==Action.POISON?"POISON_MESSAGE":"LOCAL_ATTEMPT_FAILED";next=now.plusSeconds(DeliveryPolicy.backoffSeconds(attempts));}
   case RECONCILE -> {if(!state.equals("ACKED")||!Objects.equals(attempt,input.attemptId()))throw error("ADAPTER_NOT_READY");if(!received(old))throw error("ADAPTER_ACK_MISMATCH");state="RECONCILED";}
   case CANCEL -> {if(!Set.of("QUEUED","RETRY_WAIT","ATTEMPTING","REJECTED","DEAD").contains(state)||!Objects.equals(attempt,input.attemptId()))throw error("ADAPTER_NOT_READY");state="CANCELLED";code=received(old)?"CANCELLED_WITH_LOCAL_RECORD":"CANCELLED_NO_ACK";}
   case REPAIR -> {if(!state.equals("REJECTED")||attempts>=3||!Objects.equals(attempt,input.attemptId())||receiver(old)!=old.sequence()-1)throw error("ADAPTER_NOT_READY");state="RETRY_WAIT";code="MANUALLY_REVIEWED_ORDER";next=now.plusSeconds(DeliveryPolicy.backoffSeconds(attempts));}
  }
  if(jdbc.update("UPDATE adapter_outbox SET version=version+1,state=?,attempts=?,attempt_id=?,lease_until=?,next_at=?,error_code=? WHERE message_id=? AND version=? AND version<99",state,attempts,attempt,lease==null?null:OffsetDateTime.ofInstant(lease,ZoneOffset.UTC),OffsetDateTime.ofInstant(next,ZoneOffset.UTC),code,id,old.version())!=1)throw error("ADAPTER_VERSION");var current=item(request,id);event(current,action.name(),input.reason());return receipt(current,old.version());}});}
 private void event(Item i,String action,String reason){jdbc.update("INSERT INTO adapter_event(message_id,version,action,state,error_code,attempt_id,actor_id,reason) VALUES(?,?,?,?,?,?,?,?)",i.id(),i.version(),action,i.state(),i.errorCode(),i.attemptId(),access.actor().id(),reason);}
 private static IdempotentCommands.Mutation receipt(Item i,Long previous){return new IdempotentCommands.Mutation(new CommandReceipt(200,"SYNTHETIC_ADAPTER_MESSAGE",i.id(),i.version()),previous);}
}
