package com.pis.scan;
import static com.pis.scan.ScanContracts.*;
import com.pis.accession.WorkflowAccess;import com.pis.api.ApiException;import com.pis.audit.*;import com.pis.idempotency.*;import com.pis.storage.StorageService;import com.pis.material.MaterialService;import com.pis.quality.*;
import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;import jakarta.validation.Validator;import org.springframework.stereotype.Service;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.http.HttpStatus;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.*;
@Service
public class ScanService {
 private final JdbcTemplate jdbc;private final WorkflowAccess access;private final StorageService storage;private final MaterialService materials;private final QualitySubjects subjects;private final QualityGate quality;private final IdempotentCommands commands;private final AuditRecorder audit;private final Validator validator;private final TransactionTemplate tx;private final Clock clock;
 public ScanService(JdbcTemplate jdbc,WorkflowAccess access,StorageService storage,MaterialService materials,QualitySubjects subjects,QualityGate quality,IdempotentCommands commands,AuditRecorder audit,Validator validator,PlatformTransactionManager manager,@org.springframework.beans.factory.annotation.Qualifier("worklistClock") Clock clock){this.clock=clock;this.jdbc=jdbc;this.access=access;this.storage=storage;this.materials=materials;this.subjects=subjects;this.quality=quality;this.commands=commands;this.audit=audit;this.validator=validator;tx=new TransactionTemplate(manager);tx.setTimeout(10);}
 private record Context(UUID request,UUID caseId,UUID hospital,UUID scope,UUID actor){}
 private Context context(UUID rid){try{var actor=access.actor();if(TransactionSynchronizationManager.isActualTransactionActive())jdbc.queryForList("SELECT id FROM pathology_request WHERE id=? FOR UPDATE",rid);var view=storage.list(rid,1);var rows=jdbc.query("SELECT c.hospital_id,w.scope_id FROM pathology_case c JOIN request_workflow w ON w.request_id=c.request_id WHERE c.id=?",(r,i)->new Context(rid,view.caseId(),r.getObject(1,UUID.class),r.getObject(2,UUID.class),actor.id()),view.caseId());if(rows.isEmpty())throw missing();var c=rows.getFirst();if(TransactionSynchronizationManager.isActualTransactionActive())jdbc.queryForList("SELECT user_id FROM scan_grant WHERE user_id=? AND scope_id=? FOR SHARE",actor.id(),c.scope());if(jdbc.queryForObject("SELECT count(*) FROM scan_grant WHERE user_id=? AND scope_id=? AND qualification='SYN-SCAN-1' AND valid_until>statement_timestamp() AND revoked_at IS NULL",Long.class,actor.id(),c.scope())!=1)throw missing();return c;}catch(org.springframework.security.access.AccessDeniedException e){throw missing();}}
 private String basis(UUID rid){return ScanFormat.sha(quality.reportSnapshot(rid).getBytes(StandardCharsets.UTF_8));}
 private void valid(Object v){var errors=validator.validate(v);if(!errors.isEmpty())throw new jakarta.validation.ConstraintViolationException(errors);}
 private Instant now(){return clock.instant();}
 private static Instant instant(java.sql.ResultSet r,String key)throws java.sql.SQLException{var t=r.getObject(key,OffsetDateTime.class);return t==null?null:t.toInstant();}
 private static org.springframework.jdbc.core.RowMapper<Job> mapper(UUID rid,String currentBasis){return (r,i)->new Job(r.getObject("id",UUID.class),rid,r.getObject("case_id",UUID.class),r.getObject("patient_id",UUID.class),r.getObject("claimed_case_id",UUID.class),r.getObject("claimed_patient_id",UUID.class),r.getObject("slide_id",UUID.class),r.getObject("object_id",UUID.class),r.getString("object_hash"),r.getLong("object_size"),r.getLong("ordinal"),r.getObject("previous_id",UUID.class),r.getString("source_basis"),r.getString("barcode"),r.getString("source_code"),r.getString("scanner_code"),r.getString("reason"),r.getString("state"),r.getString("error_code"),r.getLong("version"),r.getInt("attempts"),r.getObject("lease_id",UUID.class),r.getObject("lease_actor",UUID.class),instant(r,"lease_until"),instant(r,"retry_at"),r.getObject("width",Integer.class),r.getObject("height",Integer.class),currentBasis!=null&&!currentBasis.equals(r.getString("source_basis"))?"SOURCE_CHANGED":"");}
 private Job row(UUID rid,UUID id,String currentBasis){var list=jdbc.query("SELECT * FROM scan_import WHERE id=? AND request_id=?",mapper(rid,currentBasis),id,rid);if(list.isEmpty())throw missing();return list.getFirst();}
 private void event(Context c,UUID id,long version,String action,String reason){jdbc.update("INSERT INTO scan_event(scan_id,version,action,actor_id,reason,snapshot) SELECT id,?,?,?, ?,to_jsonb(s) FROM scan_import s WHERE id=?",version,action,c.actor(),reason,id);}
 public View view(UUID rid,int page){return tx.execute(s->{var c=context(rid);if(page<1||page>50)throw problem(HttpStatus.BAD_REQUEST,"SCAN_PAGE");String digest=basis(rid);var jobs=jdbc.query("SELECT * FROM scan_import WHERE request_id=? ORDER BY created_at DESC,id LIMIT 20 OFFSET ?",mapper(rid,digest),rid,(page-1)*20);var slides=materials.archiveSources(rid).stream().filter(m->m.kind().equals("SLIDE")).map(m->new Source(m.id(),m.barcode(),m.version(),m.status())).toList();audit.append(c.hospital(),"SCAN_READ_V1","PATHOLOGY_REQUEST",rid,null,0);return new View(rid,c.caseId(),jdbc.queryForObject("SELECT patient_id FROM pathology_request WHERE id=?",UUID.class,rid),page,jobs,slides,Map.of("SYNTHETIC_HEADER_V1","CONTRACT_ONLY","TIFF_CONTAINER","NOT_CONFIGURED","SVS","NOT_CONFIGURED","NDPI","NOT_CONFIGURED","MRXS","NOT_CONFIGURED","ARCHIVE","UNSUPPORTED"),"NOT_PUBLISHED_T30_REQUIRED");});}
 public Job detail(UUID rid,UUID id){return tx.execute(s->{var c=context(rid);var j=row(rid,id,basis(rid));audit.append(c.hospital(),"SCAN_DETAIL_V1","SCAN_IMPORT",id,null,j.version());return j;});}
 public List<Event> events(UUID rid,UUID id){return tx.execute(s->{var c=context(rid);var job=row(rid,id,null);var events=jdbc.query("SELECT scan_id,version,action,snapshot->>'state' AS state,snapshot->>'error_code' AS error_code,(snapshot->>'lease_id')::uuid AS lease_id,(snapshot->>'attempts')::integer AS attempts,reason,occurred_at FROM scan_event WHERE scan_id=? ORDER BY version DESC LIMIT 50",(r,i)->new Event(r.getObject("scan_id",UUID.class),r.getLong("version"),r.getString("action"),r.getString("state"),r.getString("error_code"),r.getObject("lease_id",UUID.class),r.getInt("attempts"),r.getString("reason"),instant(r,"occurred_at")),id);audit.append(c.hospital(),"SCAN_HISTORY_V1","SCAN_IMPORT",id,null,job.version());return events;});}
 public List<Item> batch(UUID rid,Batch input,String key){valid(input);context(rid);if(key==null||!key.matches("[A-Za-z0-9._:-]{1,100}"))throw problem(HttpStatus.BAD_REQUEST,"SCAN_KEY");var results=new ArrayList<Item>();for(int i=0;i<input.items().size();i++){var item=input.items().get(i);try{var r=create(rid,item,key+":"+i);results.add(new Item(item.objectId(),r.receipt().status(),r.receipt().resourceId(),"RECORDED_NOT_PUBLISHED"));}catch(ApiException e){results.add(new Item(item.objectId(),e.status().value(),null,e.code()));}}return List.copyOf(results);}
 public IdempotentCommands.Result create(UUID rid,Create input,String key){valid(input);var first=context(rid);return commands.execute(first.hospital(),"SCAN_CREATE_V1",key,Map.of("request",rid,"input",input),new IdempotentCommands.Work(){
  public void authorize(CurrentActor.Actor a){context(rid);}public void authorizeReplay(CurrentActor.Actor a,CommandReceipt receipt){context(rid);row(rid,receipt.resourceId(),null);storage.detail(rid,input.objectId());}
  public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){var c=context(rid);var source=materials.archiveSources(rid).stream().filter(m->m.id().equals(input.slideId())&&m.kind().equals("SLIDE")).findFirst().orElseThrow(ScanService::missing);var subject=subjects.subject(source.id());var object=storage.detail(rid,input.objectId());if(!object.state().equals("READY"))throw conflict("SCAN_OBJECT_NOT_READY");
   if(jdbc.queryForObject("SELECT count(*) FROM scan_import WHERE object_id=?",Long.class,object.id())>0)throw conflict("SCAN_DUPLICATE");if(jdbc.queryForObject("SELECT count(*) FROM scan_import WHERE request_id=?",Long.class,rid)>=1000)throw conflict("SCAN_LIMIT");
   if(input.previousId()!=null){var prev=row(rid,input.previousId(),null);if(!prev.slideId().equals(source.id())||prev.objectId().equals(object.id())||prev.ordinal()!=input.expectedHead())throw conflict("SCAN_RESCAN_BINDING");}else if(input.expectedHead()!=-1)throw conflict("SCAN_RESCAN_BINDING");
   jdbc.update("INSERT INTO scan_series(slide_id) VALUES(?) ON CONFLICT DO NOTHING",source.id());if(jdbc.update("UPDATE scan_series SET head=head+1 WHERE slide_id=? AND head=?",source.id(),input.expectedHead())!=1)throw conflict("VERSION_CONFLICT");
   boolean identity=c.caseId().equals(input.confirmedCaseId())&&subject.patientId().equals(input.patientId())&&source.barcode().equals(input.barcode())&&com.pis.label.LabelBarcode.valid(input.barcode());String reason=!identity?"MANUAL_IDENTITY_MISMATCH":!source.status().equals("PASS")?"SOURCE_QC_BLOCKED":"";UUID id=UUID.randomUUID();
   jdbc.update("INSERT INTO scan_import(id,hospital_id,request_id,case_id,patient_id,scope_id,slide_id,object_id,object_hash,object_size,ordinal,previous_id,source_basis,barcode,source_code,scanner_code,reason,state,error_code,claimed_patient_id,claimed_case_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,c.hospital(),rid,c.caseId(),subject.patientId(),c.scope(),source.id(),object.id(),object.sha256(),object.byteSize(),input.expectedHead()+1,input.previousId(),basis(rid),input.barcode(),input.sourceCode(),input.scannerCode(),input.reason(),reason.isEmpty()?"QUEUED":"QUARANTINED",reason,input.patientId(),input.confirmedCaseId());event(c,id,0,"CREATE",input.reason());return new IdempotentCommands.Mutation(new CommandReceipt(201,"SCAN_IMPORT",id,0),null);
  }
 });}
 private void lease(Job j,Command input,Context c){if(!j.state().equals("RUNNING")||j.version()!=input.expectedVersion()||!Objects.equals(j.leaseId(),input.leaseId())||!Objects.equals(j.leaseActor(),c.actor())||j.leaseUntil()==null||ScanLeasePolicy.expired(j.leaseUntil(),now()))throw conflict("SCAN_LEASE_STALE");}
 public IdempotentCommands.Result command(UUID rid,UUID id,String action,Command input,String key){valid(input);if(!Set.of("CLAIM","CANCEL","RECOVER","RETRY").contains(action))throw problem(HttpStatus.BAD_REQUEST,"SCAN_ACTION");return change(rid,id,action,input,key,null);}
 public IdempotentCommands.Result process(UUID rid,UUID id,Command input,String key){valid(input);var before=tx.execute(s->{var c=context(rid);var j=row(rid,id,null);storage.detail(rid,j.objectId());if(j.state().equals("RUNNING"))lease(j,input,c);else if(!Objects.equals(j.leaseId(),input.leaseId())||!Objects.equals(j.leaseActor(),c.actor()))throw conflict("SCAN_LEASE_STALE");return j;});ScanFormat.Result result=null;
  if(before.state().equals("RUNNING")){try{var bytes=storage.bytes(rid,before.objectId(),"bytes=0-"+(Math.min(512,before.objectSize())-1),"PREVIEW");result=ScanFormat.inspect(bytes.bytes());}catch(ApiException e){if(!Set.of("STORAGE_BUSY","STORAGE_IO","STORAGE_TIMEOUT","STORAGE_RATE","STORAGE_INTEGRITY").contains(e.code()))throw e;result=new ScanFormat.Result(e.code().equals("STORAGE_INTEGRITY")?"CORRUPT_OBJECT":"STORAGE_TEMPORARY",null,null,null,"",0,0);}}
  return change(rid,id,"COMPLETE",input,key,result);
 }
 private IdempotentCommands.Result change(UUID rid,UUID id,String action,Command input,String key,ScanFormat.Result parsed){var first=context(rid);return commands.execute(first.hospital(),"SCAN_"+action+"_V1",key,Map.of("request",rid,"id",id,"input",input),new IdempotentCommands.Work(){
  public void authorize(CurrentActor.Actor a){context(rid);row(rid,id,null);}public void authorizeReplay(CurrentActor.Actor a,CommandReceipt receipt){authorize(a);}
  public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){var c=context(rid);var j=row(rid,id,basis(rid));if(j.version()!=input.expectedVersion())throw conflict("VERSION_CONFLICT");String state=j.state(),error=j.errorCode();int attempts=j.attempts();UUID leaseId=j.leaseId(),owner=j.leaseActor();Instant until=j.leaseUntil(),retry=j.retryAt();Integer width=j.width(),height=j.height();
   switch(action){
    case "CLAIM" -> {if(!state.equals("QUEUED")||attempts>=3)throw conflict("SCAN_STATE");if(!j.invalidReason().isEmpty())throw conflict("SCAN_SOURCE_CHANGED");storage.detail(rid,j.objectId());state="RUNNING";attempts++;leaseId=UUID.randomUUID();owner=c.actor();until=ScanLeasePolicy.deadline(now());retry=null;error="";}
    case "CANCEL" -> {if(state.equals("CANCELLED"))throw conflict("SCAN_STATE");state="CANCELLED";error="MANUALLY_CANCELLED";}
    case "RECOVER" -> {if(!state.equals("RUNNING")||until==null||until.isAfter(now()))throw conflict("SCAN_LEASE_STALE");state=attempts>=3?"FAILED":"RETRY_WAIT";error=attempts>=3?"ATTEMPTS_EXHAUSTED":"LEASE_EXPIRED";retry=ScanLeasePolicy.retryAt(now(),attempts);}
    case "RETRY" -> {if(!state.equals("RETRY_WAIT")||attempts>=3||retry==null||retry.isAfter(now())||!j.invalidReason().isEmpty())throw conflict("SCAN_RETRY_BLOCKED");state="QUEUED";error="";}
    case "COMPLETE" -> {lease(j,input,c);if(parsed==null)throw conflict("SCAN_LEASE_STALE");storage.detail(rid,j.objectId());error=parsed.code();
     if(!j.invalidReason().isEmpty()){state="QUARANTINED";error="SOURCE_CHANGED";}
     else if(error.equals("STORAGE_TEMPORARY")){state=attempts>=3?"FAILED":"RETRY_WAIT";retry=ScanLeasePolicy.retryAt(now(),attempts);}
     else if(!error.equals("SYNTHETIC_HEADER_ONLY"))state="FAILED";
     else if(!j.caseId().equals(parsed.caseId())||!j.patientId().equals(parsed.patientId())||!j.slideId().equals(parsed.slideId())||!j.barcode().equals(parsed.barcode())){state="QUARANTINED";error="FILE_IDENTITY_MISMATCH";}
     else{state="PENDING_DIGITAL_QC";error="T30_NOT_IMPLEMENTED";width=parsed.width();height=parsed.height();}
    }
    default -> throw problem(HttpStatus.BAD_REQUEST,"SCAN_ACTION");
   }
   if(jdbc.update("UPDATE scan_import SET state=?,error_code=?,attempts=?,lease_id=?,lease_actor=?,lease_until=?,retry_at=?,width=?,height=?,version=version+1 WHERE id=? AND version=?",state,error,attempts,leaseId,owner,until==null?null:OffsetDateTime.ofInstant(until,ZoneOffset.UTC),retry==null?null:OffsetDateTime.ofInstant(retry,ZoneOffset.UTC),width,height,id,j.version())!=1)throw conflict("VERSION_CONFLICT");event(c,id,j.version()+1,action,input.reason());return new IdempotentCommands.Mutation(new CommandReceipt(200,"SCAN_IMPORT",id,j.version()+1),j.version());
  }
 });}
 private static ApiException missing(){return problem(HttpStatus.NOT_FOUND,"SCAN_NOT_FOUND");}private static ApiException conflict(String code){return problem(HttpStatus.CONFLICT,code);}private static ApiException problem(HttpStatus status,String code){return new ApiException(status,code,"Synthetic scan import unavailable; verify authorized identity and attempt");}
}
