import { useEffect, useRef, useState } from 'react';
import { Alert, Button, Input, Modal, Select, Space, Table } from 'antd';
import { ApiError } from '../../api';
import * as api from './api';
type Intent={path:string;body:unknown;key:string;model?:api.Model;scan?:api.Scan};
export function AiRegistry({scopeId,requestId,scanId,onDirty,onClean,onPending,onExpired}:{scopeId:string;requestId?:string;scanId?:string;onDirty:()=>void;onClean:()=>void;onPending:(v:boolean)=>void;onExpired:()=>void}){
 const [view,setView]=useState<api.Catalog>(),[scan,setScan]=useState<api.Scan>(),[selected,setSelected]=useState(''),[page,setPage]=useState(1),[code,setCode]=useState(''),[metadata,setMetadata]=useState(''),[profile,setProfile]=useState(''),[reason,setReason]=useState(''),[state,setState]=useState('DISABLED'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[decision,setDecision]=useState<api.Decision>(),[decisionPath,setDecisionPath]=useState(''),[abandon,setAbandon]=useState(false),[history,setHistory]=useState<unknown>(),[next,setNext]=useState<(()=>void)>();
 const active=useRef<AbortController|undefined>(undefined),locked=useRef(false),dirty=useRef(false),intent=useRef<Intent|undefined>(undefined);const model=view?.models.find(m=>m.id===selected);
 useEffect(()=>{const c=new AbortController();active.current=c;setBusy(true);locked.current=true;void api.catalog(scopeId,page,c.signal).then(v=>{if(!c.signal.aborted)setView(v);}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'读取失败');}).finally(()=>{if(!c.signal.aborted){setBusy(false);locked.current=false;}});return()=>{c.abort();active.current?.abort();};},[scopeId,page]);
 useEffect(()=>{if(!decisionPath||!scan||!model)return;const c=new AbortController();let checking=false;const timer=setInterval(()=>{if(checking)return;checking=true;void api.get(decisionPath,AbortSignal.any([c.signal,AbortSignal.timeout(10000)])).then(v=>{if(!c.signal.aborted)setDecision(api.parseDecision(v,scan,model));}).catch(e=>{if(!c.signal.aborted){setDecision(undefined);setDecisionPath('');if(e instanceof ApiError&&[401,403,404].includes(e.status)){setScan(undefined);setView(undefined);setHistory(undefined);}setError('判定已失效或无法核验，请刷新当前权限和版本');}}).finally(()=>{checking=false;});},5000);return()=>{c.abort();clearInterval(timer);};},[decisionPath,scan,model]);
 function changed(){setDecisionPath('');dirty.current=true;onDirty();setDecision(undefined);}
 function reset(){setState('DISABLED');setDecisionPath('');setCode('');setMetadata('');setProfile('');setReason('');setDecision(undefined);setHistory(undefined);dirty.current=false;onClean();}
 function change(work:()=>void){if(pending||locked.current)return;if(dirty.current)setNext(()=>work);else work();}
 async function run(work:(signal:AbortSignal)=>Promise<unknown>){if(locked.current)return;const c=new AbortController();active.current=c;locked.current=true;setBusy(true);setError('');try{await work(c.signal);}catch(e){if(!c.signal.aborted){setError(e instanceof Error?e.message:'AI契约操作失败');setDecision(undefined);if(e instanceof ApiError&&[401,403,404].includes(e.status)){setView(undefined);setScan(undefined);setHistory(undefined);}if(e instanceof ApiError&&e.status===401)onExpired();}}finally{if(active.current===c){locked.current=false;setBusy(false);}}}
 async function refresh(s:AbortSignal){setDecisionPath('');setDecision(undefined);setHistory(undefined);const v=await api.catalog(scopeId,page,s);if(!s.aborted)setView(v);let current:api.Scan|undefined;if(requestId&&scanId&&scan){current=await api.scan(scopeId,requestId,scanId,s);if(!s.aborted)setScan(current);}return {catalog:v,scan:current};}
 async function send(s:AbortSignal){const i=intent.current;if(!i)return;const result=await api.post(i.path,i.body,i.key,s);if(s.aborted)return;
  const body=i.body as Record<string,unknown>;const expected=i.path.endsWith('/state')?'AI_MODEL_STATE':i.path.endsWith('/profile')?'AI_SCAN_PROFILE':i.path.endsWith('/assess')?'AI_ASSESSMENT':'AI_MODEL_VERSION';if(result.type!==expected || result.version!==(expected==='AI_MODEL_VERSION'?Number(body.expectedHead)+1:expected==='AI_ASSESSMENT'?0:Number(body.expectedVersion)+1) || (expected==='AI_SCAN_PROFILE'&&result.id!==scanId) || (expected==='AI_MODEL_STATE'&&result.id!==selected))throw Error('AI操作回执身份或版本不匹配');
  let d:api.Decision|undefined;if(i.model&&i.scan){if(result.type!=='AI_ASSESSMENT')throw Error('判定回执不匹配');d=api.parseDecision(await api.get(`${api.scanPath(i.scan.requestId,i.scan.scanId)}/assess/${result.id}`,s),i.scan,i.model);}
  if(s.aborted)return;intent.current=undefined;setPending(false);onPending(false);reset();const latest=await refresh(s);if(!s.aborted&&d&&i.model&&latest.scan){const m=latest.catalog.models.find(m=>m.id===i.model?.id);if(!m)throw Error('模型版本已变化，重新核对');setDecision(api.parseDecision(d,latest.scan,m));setDecisionPath(`${api.scanPath(latest.scan.requestId,latest.scan.scanId)}/assess/${result.id}`);}
 }
 function submit(kind:string){if(locked.current||pending||!view)return;if(!reason.trim()){setError('必须填写人工原因');return;}
  try{let path=api.catalogPath(scopeId),body:unknown;let assessment=false;
   if(kind==='register'){const meta:unknown=JSON.parse(metadata);body={modelId:model?.modelId??crypto.randomUUID(),expectedHead:model?.head??-1,code,metadata:meta,reason};}
   else if(kind==='state'){if(!model)return;path+=`/${model.id}/state`;body={expectedVersion:model.stateVersion,state,reason};}
   else {if(!scan)throw Error('先核对当前已发布扫描');path=api.scanPath(scan.requestId,scan.scanId);
    if(kind==='profile'){const p:unknown=JSON.parse(profile);path+='/profile';body={publicationVersion:scan.publicationVersion,manifestHash:scan.manifestHash,expectedVersion:scan.profile?.version??-1,profile:p,reason};}
    else {if(!model||!scan.profile)throw Error('选择模型并登记当前适用资料');path+='/assess';body={modelVersionId:model.id,stateVersion:model.stateVersion,profileVersion:scan.profile.version,publicationVersion:scan.publicationVersion,manifestHash:scan.manifestHash,calibrationVersion:scan.calibrationVersion,reason};assessment=true;}}
   intent.current={path,body,key:crypto.randomUUID(),model:assessment?model:undefined,scan:assessment?scan:undefined};setPending(true);onPending(true);changed();void run(send);
  }catch(e){setError(e instanceof Error?e.message:'输入错误');}
 }
 return <section aria-label="AI模型契约管理"><Alert type="warning" title="仅合成契约夹具 · 注册不是安装或执行 · 无临床批准、监管许可或诊断性能证明" />{error&&<Alert role="alert" type="error" title={error}/>}<p>范围 {scopeId}；临床批准权限：无；推理执行：禁止。验证证据仅人工声明，不代表验证通过。</p>
 <Space wrap><Button disabled={busy||pending} onClick={()=>change(()=>{reset();void run(refresh);})}>刷新AI契约与权限</Button><Button disabled={!busy} onClick={()=>{active.current?.abort();locked.current=false;setBusy(false);setDecision(undefined);}}>停止等待AI请求</Button><Button disabled={busy||!pending} onClick={()=>void run(send)}>原键确认AI操作</Button><Button disabled={busy||!pending} onClick={()=>setAbandon(true)}>放弃重试并重新核对</Button><Button disabled={busy||pending} onClick={()=>change(()=>{reset();setSelected('');})}>新模型系列</Button></Space>
 <Table rowKey="id" dataSource={view?.models??[]} pagination={false} scroll={{x:900}} columns={[{title:'模型／版本',render:(_,m:api.Model)=>`${m.code} / v${m.ordinal} ${m.ordinal===m.head?'当前':'历史'}`},{title:'状态',dataIndex:'state'},{title:'证据',render:(_,m:api.Model)=>`${m.metadata.evidence} / 临床证据缺失`},{title:'选择',render:(_,m:api.Model)=><Button disabled={busy||pending} onClick={()=>change(()=>{reset();setSelected(m.id);})}>选择模型 {m.id}</Button>}]}/>
 <Space><Button disabled={busy||pending||page===1} onClick={()=>change(()=>{reset();setSelected('');setView(undefined);setPage(p=>p-1);})}>上一页AI版本</Button><span>第{page}页</span><Button disabled={busy||pending||page>=50||view?.models.length!==20} onClick={()=>change(()=>{reset();setSelected('');setView(undefined);setPage(p=>p+1);})}>下一页AI版本</Button></Space>
 {model&&<><pre aria-label="模型确切版本">{JSON.stringify(model,null,2)}</pre><Button disabled={busy||pending} onClick={()=>change(()=>{reset();setCode(model.code);setMetadata(JSON.stringify(model.metadata,null,2));changed();})}>复制为新版本元数据</Button><Button disabled={busy||pending} onClick={()=>void run(async s=>{const h=await api.get(`${api.catalogPath(scopeId)}/${model.id}/history`,s);if(!s.aborted)setHistory(h);})}>读取模型追加历史</Button></>}{history!==undefined&&<pre>{JSON.stringify(history,null,2)}</pre>}
 <Button disabled={busy||pending} onClick={()=>change(()=>{reset();setSelected('');setCode('SYN-CONTRACT-FIXTURE');setMetadata(JSON.stringify({digest:'0'.repeat(64),preprocessing:'SYN-PRE-1',configSchema:'SYN-AI-CONFIG-1',maxTiles:16,inputContract:'SYN-RGB-PYRAMID-1',pathology:'SYN-UNSPECIFIED',stain:'SYN-UNSPECIFIED',scannerCode:'SYN-UNSPECIFIED',scannerVersion:'SYN-UNSPECIFIED',quality:'ALL_DIGITAL_QC_PASS',calibration:'SYNTHETIC_XY_MPP_REQUIRED',approvalScope:'SYNTHETIC_CONTRACT_ONLY',evidence:'MISSING',evidenceRef:'',limitations:'仅合成契约示例，无模型文件、临床证据或执行许可。'},null,2));changed();})}>填入合成契约示例（不保存）</Button><label>模型代码<Input aria-label="模型代码" value={code} disabled={busy||pending} onChange={e=>{setCode(e.target.value);changed();}} maxLength={64}/></label><label>不可变模型元数据JSON<Input.TextArea aria-label="不可变模型元数据JSON" value={metadata} maxLength={12000} rows={5} disabled={busy||pending} onChange={e=>{setMetadata(e.target.value);changed();}}/></label><p>schema=SYN-AI-CONFIG-1；inputContract=SYN-RGB-PYRAMID-1；digest为声明摘要，不下载文件。病理/染色/扫描仪版本必须显式SYN-标识。</p>
 <label>AI操作原因<Input aria-label="AI操作原因" value={reason} disabled={busy||pending} maxLength={500} onChange={e=>{setReason(e.target.value);changed();}}/></label><Button disabled={busy||pending||!view?.permissions.register} onClick={()=>submit('register')}>保存不可变模型版本</Button>
 <Select aria-label="AI验证状态" value={state} disabled={busy||pending} options={['VALIDATION_ONLY','DISABLED','RETIRED'].map(value=>({value,label:value}))} onChange={v=>{setState(v);changed();}}/><Button disabled={busy||pending||!model||!view?.permissions.validate} onClick={()=>submit('state')}>登记模型状态</Button>
 <Button disabled={busy||pending||!requestId||!scanId||!view?.permissions.assess} onClick={()=>change(()=>{reset();setScan(undefined);void run(async s=>{if(!requestId||!scanId)return;const v=await api.scan(scopeId,requestId,scanId,s);if(!s.aborted)setScan(v);});})}>核对当前扫描适用资料</Button>
 {scan&&<><pre aria-label="AI扫描依据">{JSON.stringify(scan,null,2)}</pre><label>人工合成适用资料JSON<Input.TextArea aria-label="人工合成适用资料JSON" value={profile} disabled={busy||pending} maxLength={1000} placeholder='{"pathology":"UNKNOWN","stain":"UNKNOWN","scannerVersion":"UNKNOWN"}' onChange={e=>{setProfile(e.target.value);changed();}}/></label><Button disabled={busy||pending} onClick={()=>submit('profile')}>保存扫描适用资料版本</Button><Button disabled={busy||pending||!model||!scan.profile} onClick={()=>submit('assess')}>判定合成适用性（不执行）</Button></>}
 {decision&&<Alert role="status" type="info" title={`${decision.outcome} · 不允许推理执行`} description={<pre>{JSON.stringify(decision,null,2)}</pre>}/>}
 <Modal open={abandon} title="放弃此请求的后续重试？" okText="放弃重试并核对" cancelText="保留原键" onCancel={()=>setAbandon(false)} onOk={()=>{setAbandon(false);intent.current=undefined;setPending(false);onPending(false);reset();void run(refresh);}}><p>不会撤销服务端已保存的数据。必须重新核对版本后才能发起新操作。</p></Modal><Modal open={!!next} title="丢弃未保存AI契约输入？" okText="丢弃并切换" cancelText="继续编辑" onCancel={()=>setNext(undefined)} onOk={()=>{const work=next;setNext(undefined);work?.();}}><p>不会撤销已经提交的请求；未确认请求必须原键确认。</p></Modal></section>;
}
