import { fetchCsrf, readJson, request } from '../../api';
export interface Metadata { digest: string; preprocessing: string; configSchema: string; maxTiles: number; inputContract: string; pathology: string; stain: string; scannerCode: string; scannerVersion: string; quality: string; calibration: string; approvalScope: string; evidence: string; evidenceRef: string; limitations: string }
export interface Model { id: string; modelId: string; scopeId: string; code: string; ordinal: number; head: number; stateVersion: number; state: string; metadata: Metadata }
export interface Catalog { scopeId: string; page: number; models: Model[]; permissions: { register: boolean; validate: boolean; assess: boolean; clinicalApproval: false; execution: false }; capability: string }
export interface Scan { requestId: string; scanId: string; scopeId: string; publicationVersion: number; manifestHash: string; scannerCode: string; profile: { version: number; publicationVersion: number; manifestHash: string; profile: { pathology: string; stain: string; scannerVersion: string } } | null; calibrationVersion: number | null; calibration: string }
export interface Decision { requestId: string; scanId: string; scopeId: string; modelVersionId: string; manifestHash: string; outcome: string; reasons: string[]; executionAllowed: false; clinicalEvidence: string; objectHash: string; modelDigest: string; profileVersion: number; stateVersion: number }
const hash = (v: unknown) => typeof v === 'string' && /^[a-f0-9]{64}$/.test(v);
const version = (v: unknown) => Number.isSafeInteger(v) && Number(v) >= 0;
const syn = (v: unknown) => typeof v === 'string' && /^SYN-[A-Za-z0-9_-]{1,60}$/.test(v);
const object = (v: unknown): Record<string, unknown> => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw Error('AI响应格式错误'); return v as Record<string, unknown>; };
export const catalogPath = (scope: string) => `/api/requests/ai/scopes/${encodeURIComponent(scope)}/models`;
export const scanPath = (requestId: string, scan: string) => `/api/requests/${encodeURIComponent(requestId)}/scans/${encodeURIComponent(scan)}/ai`;
export function parseCatalog(value: unknown, scope: string, page: number): Catalog {
 const v = object(value), p = object(v.permissions);
 if (v.scopeId !== scope || v.page !== page || v.capability !== 'CONTRACT_ONLY_NO_EXECUTION' || p.clinicalApproval !== false || p.execution !== false || !['register','validate','assess'].every(k => typeof p[k] === 'boolean') || !Array.isArray(v.models) || v.models.length > 20) throw Error('AI范围或能力不匹配');
 for (const item of v.models) { const m = object(item), meta = object(m.metadata); if (m.scopeId !== scope || typeof m.id !== 'string' || typeof m.modelId !== 'string' || !['DRAFT','VALIDATION_ONLY','DISABLED','RETIRED'].includes(String(m.state)) || ![m.ordinal,m.head,m.stateVersion].every(n=>version(n)&&Number(n)<=99) || Number(m.ordinal)>Number(m.head) || !hash(meta.digest) || ![meta.preprocessing,meta.pathology,meta.stain,meta.scannerCode,meta.scannerVersion,m.code].every(syn) || meta.configSchema!=='SYN-AI-CONFIG-1' || meta.inputContract!=='SYN-RGB-PYRAMID-1' || !Number.isInteger(meta.maxTiles) || Number(meta.maxTiles)<1 || Number(meta.maxTiles)>16 || meta.quality!=='ALL_DIGITAL_QC_PASS' || !['PIXEL_ONLY','SYNTHETIC_XY_MPP_REQUIRED'].includes(String(meta.calibration)) || !['MISSING','DECLARED_SYNTHETIC'].includes(String(meta.evidence)) || typeof meta.evidenceRef!=='string' || typeof meta.limitations!=='string' || meta.approvalScope !== 'SYNTHETIC_CONTRACT_ONLY') throw Error('模型版本契约错误'); }
 return v as unknown as Catalog;
}
export function parseScan(value: unknown, scope: string, rid: string, id: string): Scan {
 const v = object(value); if (v.scopeId!==scope||v.requestId!==rid||v.scanId!==id||!version(v.publicationVersion)||!hash(v.manifestHash)||typeof v.scannerCode!=='string'||!['UNKNOWN','SYNTHETIC_TEST_ONLY'].includes(String(v.calibration))||(v.calibrationVersion===null?v.calibration!=='UNKNOWN':!version(v.calibrationVersion)||v.calibration!=='SYNTHETIC_TEST_ONLY')) throw Error('AI扫描版本不匹配');
 if(v.profile!==null){const p=object(v.profile),fields=object(p.profile);if(!version(p.version)||!version(p.publicationVersion)||p.manifestHash!==v.manifestHash||![fields.pathology,fields.stain,fields.scannerVersion].every(x=>x==='UNKNOWN'||syn(x)))throw Error('AI适用资料格式错误');}return v as unknown as Scan;
}
export function parseDecision(value: unknown, scan: Scan, model: Model): Decision {
 const v=object(value);if(v.requestId!==scan.requestId||v.scanId!==scan.scanId||v.scopeId!==scan.scopeId||v.modelVersionId!==model.id||v.modelDigest!==model.metadata.digest||v.modelOrdinal!==model.ordinal||v.modelHead!==model.head||v.manifestHash!==scan.manifestHash||v.publicationVersion!==scan.publicationVersion||v.calibrationVersion!==scan.calibrationVersion||v.profileVersion!==scan.profile?.version||v.stateVersion!==model.stateVersion||!hash(v.objectHash)||typeof v.objectId!=='string'||!version(v.scanVersion)||v.executionAllowed!==false||v.clinicalEvidence!=='MISSING_NO_CLINICAL_OR_REGULATORY_APPROVAL'||!['VALIDATION_ONLY_APPLICABLE','NEEDS_REVIEW','NOT_APPLICABLE'].includes(String(v.outcome))||!Array.isArray(v.reasons)||!v.reasons.every(r=>typeof r==='string'))throw Error('AI判定依据不匹配或非法执行许可');return v as unknown as Decision;
}
export async function catalog(scope: string,page: number,signal: AbortSignal){return parseCatalog(await readJson(await request(`${catalogPath(scope)}?page=${page}`,{signal})),scope,page);}
export async function scan(scope:string,rid:string,id:string,signal:AbortSignal){const qc=object(await readJson(await request(`/api/requests/${rid}/scans/${id}/digital-qc`,{signal})));if(qc.requestId!==rid||qc.scanId!==id||qc.effectiveState!=='PUBLISHED_SYNTHETIC_CONTRACT'||qc.currentScan!==true||qc.invalidReason!=='')throw Error('当前扫描QC未就绪');return parseScan(await readJson(await request(`${scanPath(rid,id)}?publicationVersion=${qc.version}`,{signal})),scope,rid,id);}
export async function get(path:string,signal:AbortSignal){return readJson(await request(path,{signal}));}
export async function post(path:string,body:unknown,key:string,signal:AbortSignal){const csrf=await fetchCsrf(signal);const v=object(await readJson(await request(path,{method:'POST',signal,headers:{'Content-Type':'application/json',[csrf.headerName]:csrf.token,'Idempotency-Key':key},body:JSON.stringify(body)})));const r=object(v.receipt);if(r.status!==200||typeof r.resourceId!=='string'||!version(r.version)||!['AI_MODEL_VERSION','AI_MODEL_STATE','AI_SCAN_PROFILE','AI_ASSESSMENT'].includes(String(r.resourceType)))throw Error('AI回执不匹配');return {id:r.resourceId,type:String(r.resourceType),version:Number(r.version)};}
