import { describe,it,expect } from 'vitest';
import { parseCatalog,parseScan,parseDecision } from './api';
export const metadata={digest:'a'.repeat(64),preprocessing:'SYN-PRE',configSchema:'SYN-AI-CONFIG-1',maxTiles:16,inputContract:'SYN-RGB-PYRAMID-1',pathology:'SYN-PATH',stain:'SYN-STAIN',scannerCode:'SYN-DEV',scannerVersion:'SYN-V1',quality:'ALL_DIGITAL_QC_PASS',calibration:'PIXEL_ONLY',approvalScope:'SYNTHETIC_CONTRACT_ONLY',evidence:'MISSING',evidenceRef:'',limitations:'Synthetic only; no performance evidence'};
const model={id:'model',modelId:'series',scopeId:'scope',code:'SYN-MODEL',ordinal:0,head:0,stateVersion:0,state:'DRAFT',metadata};
const catalog={scopeId:'scope',page:1,models:[model],permissions:{register:true,validate:false,assess:true,clinicalApproval:false,execution:false},capability:'CONTRACT_ONLY_NO_EXECUTION'};
const scan={scopeId:'scope',requestId:'request',scanId:'scan',publicationVersion:1,manifestHash:'c'.repeat(64),scannerCode:'SYN-DEV',profile:{version:0,publicationVersion:1,manifestHash:'c'.repeat(64),profile:{pathology:'UNKNOWN',stain:'UNKNOWN',scannerVersion:'UNKNOWN'}},calibrationVersion:null,calibration:'UNKNOWN'};
const decision={...scan,modelVersionId:'model',modelDigest:metadata.digest,modelOrdinal:0,modelHead:0,stateVersion:0,profileVersion:0,objectId:'object',objectHash:'a'.repeat(64),scanVersion:2,outcome:'NEEDS_REVIEW',reasons:['STAIN_UNKNOWN'],executionAllowed:false,clinicalEvidence:'MISSING_NO_CLINICAL_OR_REGULATORY_APPROVAL'};
describe('AI contract response boundaries',()=>{
 it('separates qualification capabilities and rejects clinical approval',()=>{expect(parseCatalog(catalog,'scope',1).permissions.validate).toBe(false);expect(()=>parseCatalog({...catalog,permissions:{...catalog.permissions,clinicalApproval:true}},'scope',1)).toThrow();expect(()=>parseCatalog(catalog,'other',1)).toThrow();});
 it('rejects unknown state/schema and synthetic metadata mismatch',()=>{for(const m of [{...model,state:'APPROVED'},{...model,metadata:{...metadata,inputContract:'REMOTE_URL'}},{...model,metadata:{...metadata,maxTiles:0}}])expect(()=>parseCatalog({...catalog,models:[m]},'scope',1)).toThrow();});
 it('requires exact scan and explicit unknown calibration',()=>{expect(parseScan(scan,'scope','request','scan').calibrationVersion).toBeNull();expect(()=>parseScan(scan,'scope','request','other')).toThrow();expect(()=>parseScan({...scan,calibrationVersion:NaN},'scope','request','scan')).toThrow();expect(()=>parseScan({...scan,profile:{...scan.profile,profile:{stain:undefined}}},'scope','request','scan')).toThrow();});
 it('binds every returned judgment to exact input and never execution',()=>{const s=parseScan(scan,'scope','request','scan'),m=parseCatalog(catalog,'scope',1).models[0];expect(parseDecision(decision,s,m).outcome).toBe('NEEDS_REVIEW');for(const patch of [{modelDigest:'b'.repeat(64)},{modelHead:1},{profileVersion:1},{stateVersion:1},{calibrationVersion:0},{publicationVersion:2},{executionAllowed:true},{scanId:'other'}])expect(()=>parseDecision({...decision,...patch},s,m)).toThrow();});
});
