import {useEffect,useRef,useState} from 'react';
import {Alert,Button,Input,Modal,Space,Table} from 'antd';
import {ApiError} from '../../api';
import * as api from './task-api';
type Intent={url:string;body:unknown;key:string;id?:string};
export function SyntheticTasks({requestId,scanId,assessmentId,onDirty,onClean,onPending,onExpired}:{requestId:string;scanId:string;assessmentId?:string;onDirty:()=>void;onClean:()=>void;onPending:(p:boolean)=>void;onExpired:()=>void}){
 const [jobs,setJobs]=useState<api.Job[]>([]),[view,setView]=useState<api.View>(),[reason,setReason]=useState(''),[error,setError]=useState(''),[artifact,setArtifact]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[confirm,setConfirm]=useState<(()=>void)>();
 const active=useRef<AbortController|undefined>(undefined),lock=useRef(false),dirty=useRef(false),intent=useRef<Intent|undefined>(undefined);
 useEffect(()=>()=>{active.current?.abort();},[requestId,scanId]);
 function reset(){setArtifact('');setReason('');dirty.current=false;onClean();}
 async function run(work:(s:AbortSignal)=>Promise<void>){if(lock.current)return;const c=new AbortController();active.current=c;lock.current=true;setBusy(true);setError('');try{await work(c.signal);}catch(e){if(!c.signal.aborted){setError(e instanceof Error?e.message:'合成任务请求失败');if(e instanceof ApiError&&[401,403,404].includes(e.status)){setView(undefined);setArtifact('');setJobs([]);}if(e instanceof ApiError&&e.status===401)onExpired();}}finally{if(active.current===c){lock.current=false;setBusy(false);}}}
 function change(work:()=>void){if(lock.current||pending)return;if(dirty.current)setConfirm(()=>work);else work();}
 async function send(s:AbortSignal){const i=intent.current;if(!i)return;const r=await api.post(i.url,i.body,i.key,s);if(s.aborted)return;if(i.id&&r.id!==i.id)throw Error('任务回执串号');const v=await api.get(requestId,r.id,s);if(s.aborted)return;if(v.job.version<r.version)throw Error('任务版本尚未确认');const items=await api.list(requestId,scanId,s);if(s.aborted)return;setView(v);setJobs(items);intent.current=undefined;setPending(false);onPending(false);reset();}
 function submit(action:string){if(lock.current||pending)return;if(!reason.trim()){setError('请填写合成人工操作原因');return;}const j=view?.job;let url:string,body:unknown;if(action==='SUBMIT'){if(!assessmentId){setError('先取得当前扫描的确切适用判定');return;}url=`/api/requests/${encodeURIComponent(requestId)}/scans/${encodeURIComponent(scanId)}/synthetic-tasks`;body={assessmentId,workerSchema:'SYN-CONTRACT-WORKER-1',reason};}else{if(!j)return;url=`${api.path(requestId)}/${j.id}/${action==='RUN'?'run':`actions/${action}`}`;body={expectedVersion:j.version,generation:j.generation,leaseId:j.leaseId,reason};}intent.current={url,body,key:crypto.randomUUID(),id:action==='SUBMIT'?undefined:j?.id};setPending(true);onPending(true);onDirty();void run(send);}
 return <section aria-label="合成契约任务"><Alert type="warning" title="仅 synthetic contract worker · 非诊断产物 · 临床执行始终禁止 · 默认关闭"/><p>申请 {requestId}；扫描 {scanId}；判定 {assessmentId??'未选择'}。租约30秒、最多3次尝试仅为合成开发策略；进度未知不等于零或阴性。</p>{error&&<Alert role="alert" type="error" title={error}/>}
 <Space wrap><Button disabled={busy||pending} onClick={()=>change(()=>{reset();setView(undefined);void run(async s=>{const v=await api.list(requestId,scanId,s);if(!s.aborted)setJobs(v);});})}>刷新合成任务</Button><Button disabled={!busy} onClick={()=>{active.current?.abort();lock.current=false;setBusy(false);}}>停止等待任务请求</Button><Button disabled={busy||!pending} onClick={()=>void run(send)}>原键确认任务操作</Button><Button disabled={busy||!pending} onClick={()=>setConfirm(()=>()=>{intent.current=undefined;setPending(false);onPending(false);reset();setView(undefined);setArtifact('');setJobs([]);})}>放弃任务重试并重新核对</Button></Space>
 <p>显示当前扫描最近20项；停止等待不等于服务器取消。</p><Table rowKey="id" pagination={false} dataSource={jobs} columns={[{title:'任务',dataIndex:'id'},{title:'已存状态（需选中核验）',dataIndex:'state'},{title:'选择',render:(_,j:api.Job)=><Button disabled={busy||pending} onClick={()=>change(()=>{reset();setView(undefined);void run(async s=>{const v=await api.get(requestId,j.id,s);if(!s.aborted)setView(v);});})}>核验任务 {j.id}</Button>}]}/>
 {view&&<><p role="status">上次核验：{view.effectiveState}；实际进度 {view.job.progress===null?'未知':`${view.job.progress}%`}；代次 {view.job.generation}/3；{view.invalidReason}</p><pre aria-label="任务精确版本">{JSON.stringify(view,null,2)}</pre></>}
 {view?.effectiveState==='SYNTHETIC_SUCCEEDED'&&<Button disabled={busy||pending} onClick={()=>{setArtifact('');void run(async s=>{const text=await api.artifact(requestId,view.job.id,s);if(!s.aborted)setArtifact(text);});}}>读取非诊断技术产物</Button>}{artifact&&<pre aria-label="合成技术产物">{artifact}</pre>}
 <Input aria-label="合成任务操作原因" value={reason} maxLength={500} disabled={busy||pending} onChange={e=>{setReason(e.target.value);dirty.current=true;onDirty();}}/>
 <Space wrap><Button disabled={busy||pending||!assessmentId} onClick={()=>submit('SUBMIT')}>创建合成契约任务</Button>{[['CLAIM','领取合成任务'],['HEARTBEAT','续约合成任务'],['RUN','运行有界非诊断夹具'],['CANCEL','取消合成任务'],['RETRY','重试合成任务'],['RECONCILE','核对超时或失效']].map(([a,label])=><Button key={a} disabled={busy||pending||!view} onClick={()=>submit(a)}>{label}</Button>)}</Space>
 <Modal open={!!confirm} title="清除未保存内容或放弃未确认请求？" okText="清除并重新核对" cancelText="保留任务表单" onCancel={()=>setConfirm(undefined)} onOk={()=>{const work=confirm;setConfirm(undefined);reset();work?.();}}><p>放弃重试不会取消服务器任务。必须刷新并核验结果，不能视为未执行。</p></Modal></section>;
}
