import { fetchCsrf, readJson, request } from '../../api';
export const states=['QUEUED','RUNNING','SYNTHETIC_SUCCEEDED','FAILED','CANCELLED','TIMEOUT','UNSUPPORTED','INVALIDATED'];
export interface Job {id:string;requestId:string;scanId:string;assessmentId:string;state:string;version:number;generation:number;progress:number|null;leaseId:string|null;artifactId:string|null;bindingHash:string;binding:{decision:{executionAllowed:false;scanId:string;requestId:string;modelDigest:string;objectHash:string};preprocessing:string;configDigest:string}}
export interface View {job:Job;effectiveState:string;invalidReason:string|null;clinicalExecutionAllowed:false;history:unknown[]}
const object=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('任务响应格式错误');return v as Record<string,unknown>;};
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
export function parseJob(value:unknown,rid:string):Job {const j=object(value),b=object(j.binding),d=object(b.decision);if(j.requestId!==rid||typeof j.id!=='string'||typeof j.scanId!=='string'||typeof j.assessmentId!=='string'||!states.includes(String(j.state))||!Number.isSafeInteger(j.version)||Number(j.version)<0||!Number.isInteger(j.generation)||Number(j.generation)<0||Number(j.generation)>3||!(j.progress===null||Number.isInteger(j.progress)&&Number(j.progress)>=0&&Number(j.progress)<=100)||!(j.leaseId===null||typeof j.leaseId==='string')||!(j.artifactId===null||typeof j.artifactId==='string')||!hash(j.bindingHash)||d.executionAllowed!==false||d.requestId!==rid||d.scanId!==j.scanId||!hash(d.modelDigest)||!hash(d.objectHash)||!hash(b.configDigest)||typeof b.preprocessing!=='string')throw Error('任务身份、绑定或非临床契约不匹配');return j as unknown as Job;}
export function parseView(value:unknown,rid:string,id:string):View {const v=object(value),j=parseJob(v.job,rid);if(j.id!==id||v.clinicalExecutionAllowed!==false||!states.includes(String(v.effectiveState))||!(v.invalidReason===null||typeof v.invalidReason==='string')||!Array.isArray(v.history)||v.history.length>100)throw Error('任务详情不匹配');return {...v,job:j} as unknown as View;}
export const path=(rid:string)=>`/api/requests/${encodeURIComponent(rid)}/synthetic-tasks`;
export async function get(rid:string,id:string,s:AbortSignal){return parseView(await readJson(await request(`${path(rid)}/${encodeURIComponent(id)}`,{signal:s})),rid,id);}
export async function list(rid:string,scan:string,s:AbortSignal){const v=object(await readJson(await request(`${path(rid)}?page=1&scanId=${encodeURIComponent(scan)}`,{signal:s})));if(v.requestId!==rid||v.scanId!==scan||v.page!==1||v.capability!=='SYNTHETIC_CONTRACT_ONLY_NO_CLINICAL_EXECUTION'||!Array.isArray(v.jobs)||v.jobs.length>20)throw Error('任务列表范围不匹配');return v.jobs.map(j=>{const value=parseJob(j,rid);if(value.scanId!==scan)throw Error('任务列表扫描不匹配');return value;});}
export async function post(url:string,body:unknown,key:string,s:AbortSignal){const csrf=await fetchCsrf(s);const v=object(await readJson(await request(url,{method:'POST',signal:s,headers:{'Content-Type':'application/json',[csrf.headerName]:csrf.token,'Idempotency-Key':key},body:JSON.stringify(body)})));const r=object(v.receipt);if(r.status!==200||r.resourceType!=='SYNTHETIC_AI_TASK'||typeof r.resourceId!=='string'||!Number.isSafeInteger(r.version)||typeof v.replayed!=='boolean')throw Error('任务回执不匹配');return {id:r.resourceId,version:Number(r.version)};}
export async function artifact(rid:string,id:string,s:AbortSignal){const csrf=await fetchCsrf(s);const response=await request(`${path(rid)}/${encodeURIComponent(id)}/artifact`,{method:'POST',signal:s,headers:{[csrf.headerName]:csrf.token}});const bytes=await response.arrayBuffer();if(bytes.byteLength>4096)throw Error('技术产物超过上限');const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(!text.startsWith('PIS-SYNTHETIC-STORAGE-V1\nNON_DIAGNOSTIC_SYNTHETIC_CONTRACT_ONLY\n'))throw Error('非诊断产物标识不匹配');return text;}
