package com.pis.roi;
import com.pis.api.ApiException;
import com.pis.audit.*;
import com.pis.idempotency.*;
import com.pis.viewer.ViewerService;
import jakarta.validation.*;
import jakarta.validation.constraints.*;
import java.util.*;
import java.time.OffsetDateTime;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;
@Service
public class RoiService {
 public record Save(@NotNull @Min(0) Long publicationVersion,@NotBlank @Pattern(regexp="[a-f0-9]{64}") String manifestHash,@NotNull @Min(-1) Long expectedVersion,@NotNull UUID roiId,@NotNull @Min(-1) Long expectedRevision,@NotBlank String kind,@NotNull @Size(min=1,max=32) List<RoiGeometry.Point> points,boolean deleted,@NotBlank @Size(max=200) String reason,Long calibrationVersion){}
 public record CalibrationInput(@NotNull @Min(0) Long publicationVersion,@NotBlank @Pattern(regexp="[a-f0-9]{64}") String manifestHash,@NotNull @Min(-1) Long expectedVersion,@NotNull Double mppX,@NotNull Double mppY,@NotBlank String basis,@NotBlank @Size(max=200) String reason){}
 public record Calibration(long version,double mppX,double mppY,String basis,String reason,UUID actorId){}
 public record Revision(UUID roiId,long revision,long collectionVersion,UUID authorId,UUID actorId,String kind,List<RoiGeometry.Point> points,boolean deleted,String reason,Long calibrationVersion,RoiGeometry.Measure measurement,OffsetDateTime createdAt){}
 public record View(UUID requestId,UUID scanId,String manifestHash,long version,UUID actorId,Calibration calibration,List<Revision> items,boolean historyOnly){}
 private final JdbcTemplate jdbc;private final ViewerService viewer;private final CurrentActor actors;private final IdempotentCommands commands;private final AuditRecorder audit;private final Validator validator;private final TransactionTemplate tx;private final JsonMapper json=JsonMapper.builder().build();
 public RoiService(JdbcTemplate jdbc,ViewerService viewer,CurrentActor actors,IdempotentCommands commands,AuditRecorder audit,Validator validator,PlatformTransactionManager manager){this.jdbc=jdbc;this.viewer=viewer;this.actors=actors;this.commands=commands;this.audit=audit;this.validator=validator;tx=new TransactionTemplate(manager);tx.setTimeout(10);}
 private void valid(Object input){var errors=validator.validate(input);if(!errors.isEmpty())throw new ConstraintViolationException(errors);}
 private ViewerService.Content context(UUID request,UUID scan,long pub,String hash){var c=viewer.manifest(request,scan,pub).content();if(hash!=null&&!c.manifestHash().equals(hash))throw problem(HttpStatus.CONFLICT,"ROI_BINDING");return c;}
 private long version(UUID scan){var r=jdbc.queryForList("SELECT version FROM roi_head WHERE scan_id=?",Long.class,scan);return r.isEmpty()?-1:r.getFirst();}
 private Calibration calibration(UUID scan,Long version){if(version==null)return null;var rows=jdbc.query("SELECT * FROM roi_calibration WHERE scan_id=? AND version=?",(r,i)->new Calibration(r.getLong("version"),r.getDouble("mpp_x"),r.getDouble("mpp_y"),r.getString("basis"),r.getString("reason"),r.getObject("actor_id",UUID.class)),scan,version);if(rows.isEmpty())throw problem(HttpStatus.CONFLICT,"ROI_CALIBRATION");return rows.getFirst();}
 private Calibration latest(UUID scan){var v=jdbc.queryForObject("SELECT max(version) FROM roi_calibration WHERE scan_id=?",Long.class,scan);return calibration(scan,v);}
 public Calibration calibrationHistory(UUID request,UUID scan){return tx.execute(t->{viewer.annotationHistory(request,scan);return latest(scan);});}
 private org.springframework.jdbc.core.RowMapper<Revision> mapper(){return (r,i)->new Revision(r.getObject("roi_id",UUID.class),r.getLong("revision"),r.getLong("collection_version"),r.getObject("author_id",UUID.class),r.getObject("actor_id",UUID.class),r.getString("kind"),List.of(json.readValue(r.getString("points"),RoiGeometry.Point[].class)),r.getBoolean("deleted"),r.getString("reason"),r.getObject("calibration_version",Long.class),json.readValue(r.getString("measurement"),RoiGeometry.Measure.class),r.getObject("created_at",OffsetDateTime.class));}
 private List<Revision> current(UUID scan){return jdbc.query("SELECT DISTINCT ON(roi_id) * FROM roi_revision WHERE scan_id=? ORDER BY roi_id,revision DESC LIMIT 50",mapper(),scan);}
 public View view(UUID request,UUID scan,long pub){return tx.execute(s->{var c=context(request,scan,pub,null);audit.append(c.hospitalId(),"ROI_READ_V1","SCAN_IMPORT",scan,null,Math.max(0,version(scan)));return new View(request,scan,c.manifestHash(),version(scan),actors.require().id(),latest(scan),current(scan),false);});}
 public View history(UUID request,UUID scan,UUID roi){return tx.execute(s->{var c=viewer.annotationHistory(request,scan);var rows=jdbc.query("SELECT * FROM roi_revision WHERE scan_id=? AND roi_id=? ORDER BY revision DESC LIMIT 100",mapper(),scan,roi);if(rows.isEmpty())throw problem(HttpStatus.NOT_FOUND,"ROI_NOT_FOUND");return new View(request,scan,c.manifestHash(),version(scan),actors.require().id(),latest(scan),rows,true);});}
 private long advance(UUID scan,String hash,long expected){jdbc.update("INSERT INTO roi_head(scan_id,manifest_hash) VALUES(?,?) ON CONFLICT DO NOTHING",scan,hash);if(jdbc.update("UPDATE roi_head SET version=version+1 WHERE scan_id=? AND manifest_hash=? AND version=?",scan,hash,expected)!=1)throw problem(HttpStatus.CONFLICT,"ROI_CONFLICT");return expected+1;}
 public IdempotentCommands.Result save(UUID request,UUID scan,Save input,String key){valid(input);var c=context(request,scan,input.publicationVersion(),input.manifestHash());return commands.execute(c.hospitalId(),"ROI_SAVE_V1",key,Map.of("request",request,"scan",scan,"input",input),new IdempotentCommands.Work(){
  public void authorize(CurrentActor.Actor a){context(request,scan,input.publicationVersion(),input.manifestHash());}
  public void authorizeReplay(CurrentActor.Actor a,CommandReceipt receipt){authorize(a);var owner=jdbc.queryForObject("SELECT author_id FROM roi_revision WHERE scan_id=? AND roi_id=? AND revision=0",UUID.class,scan,input.roiId());if(!a.id().equals(owner))throw problem(HttpStatus.NOT_FOUND,"ROI_NOT_FOUND");}
  public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){var now=context(request,scan,input.publicationVersion(),input.manifestHash());long next=advance(scan,input.manifestHash(),input.expectedVersion());var old=current(scan);var previous=old.stream().filter(x->x.roiId().equals(input.roiId())).findFirst().orElse(null);
   if(previous==null&&(input.expectedRevision()!=-1||input.deleted()))throw problem(HttpStatus.CONFLICT,"ROI_CONFLICT");if(previous!=null&&(!previous.authorId().equals(a.id())))throw problem(HttpStatus.NOT_FOUND,"ROI_NOT_FOUND");
   if(previous!=null&&(previous.revision()!=input.expectedRevision()||previous.deleted()))throw problem(HttpStatus.CONFLICT,"ROI_CONFLICT");if(previous==null&&old.size()>=50||previous!=null&&previous.revision()>=99)throw problem(HttpStatus.CONFLICT,"ROI_LIMIT");
   try{RoiGeometry.validate(input.kind(),input.points(),now.width(),now.height());}catch(IllegalArgumentException e){throw problem(HttpStatus.BAD_REQUEST,"ROI_GEOMETRY");}
   var cal=input.deleted()?calibration(scan,input.calibrationVersion()):latest(scan);if(!Objects.equals(input.calibrationVersion(),cal==null?null:cal.version()))throw problem(HttpStatus.CONFLICT,"ROI_CALIBRATION");
   if(input.deleted()&&(!previous.kind().equals(input.kind())||!previous.points().equals(input.points())||!Objects.equals(previous.calibrationVersion(),input.calibrationVersion())))throw problem(HttpStatus.CONFLICT,"ROI_BINDING");
   long revision=previous==null?0:previous.revision()+1;var measure=RoiGeometry.measure(input.kind(),input.points(),cal==null?null:cal.mppX(),cal==null?null:cal.mppY(),cal==null?null:cal.version());
   jdbc.update("INSERT INTO roi_revision(scan_id,roi_id,revision,collection_version,author_id,actor_id,kind,points,deleted,reason,calibration_version,measurement) VALUES(?,?,?,?,?,?,?,?::jsonb,?,?,?,?::jsonb)",scan,input.roiId(),revision,next,a.id(),a.id(),input.kind(),json.writeValueAsString(input.points()),input.deleted(),input.reason(),input.calibrationVersion(),json.writeValueAsString(measure));return new IdempotentCommands.Mutation(new CommandReceipt(200,"ROI",input.roiId(),revision),null);
  }});}
 public IdempotentCommands.Result calibrate(UUID request,UUID scan,CalibrationInput input,String key){valid(input);if(!input.basis().equals("SYNTHETIC_TEST")||!Double.isFinite(input.mppX())||!Double.isFinite(input.mppY())||input.mppX()<=0||input.mppY()<=0||input.mppX()>100||input.mppY()>100)throw problem(HttpStatus.BAD_REQUEST,"ROI_CALIBRATION");var c=context(request,scan,input.publicationVersion(),input.manifestHash());return commands.execute(c.hospitalId(),"ROI_CALIBRATE_V1",key,Map.of("request",request,"scan",scan,"input",input),new IdempotentCommands.Work(){public void authorize(CurrentActor.Actor a){context(request,scan,input.publicationVersion(),input.manifestHash());}public void authorizeReplay(CurrentActor.Actor a,CommandReceipt r){authorize(a);}public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){context(request,scan,input.publicationVersion(),input.manifestHash());if(jdbc.queryForObject("SELECT count(*) FROM roi_calibration WHERE scan_id=?",Long.class,scan)>=20)throw problem(HttpStatus.CONFLICT,"ROI_LIMIT");long next=advance(scan,input.manifestHash(),input.expectedVersion());jdbc.update("INSERT INTO roi_calibration(scan_id,version,mpp_x,mpp_y,basis,reason,actor_id) VALUES(?,?,?,?,'SYNTHETIC_TEST',?,?)",scan,next,input.mppX(),input.mppY(),input.reason(),a.id());return new IdempotentCommands.Mutation(new CommandReceipt(200,"ROI_CALIBRATION",scan,next),null);}});}
 private static ApiException problem(HttpStatus status,String code){return new ApiException(status,code,"Synthetic ROI unavailable; verify authorized exact image and revision");}
}
