package com.pis.ai;
import com.pis.accession.*;import com.pis.api.ApiException;import com.pis.audit.*;import com.pis.idempotency.*;import com.pis.storage.*;import com.pis.viewer.ViewerService;import com.pis.scan.ScanFormat;
import jakarta.validation.*;import jakarta.validation.constraints.*;import java.util.*;import java.io.ByteArrayInputStream;import java.nio.charset.StandardCharsets;
import org.springframework.stereotype.Service;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.TransactionTemplate;import tools.jackson.databind.json.JsonMapper;
@Service
public class AiResultService {
 public record Create(@NotNull UUID taskId,@NotNull @Min(0)Long expectedTaskVersion,@NotBlank @Size(max=500)String reason){}
 public record Result(UUID id,UUID taskId,UUID requestId,UUID scanId,long taskVersion,long version,String state,SyntheticResultPackage.Binding binding,String artifactHash,long artifactSize,UUID artifactId){}
 public record Metadata(Result result,String schema,String tileHash,int tileWidth,int tileHeight,int tileCount,List<Integer> intensities,List<SyntheticResultPackage.Region> regions,String meaning,boolean executionAllowed,String epoch){}
 public record Tile(byte[] bytes,String hash,String epoch){}
 private final AiTaskService tasks;private final RequestService requests;private final StorageService storage;private final ViewerService viewer;private final JdbcTemplate jdbc;private final WorkflowAccess access;private final IdempotentCommands commands;private final AuditRecorder audit;private final Validator validator;private final TransactionTemplate tx;private final JsonMapper json=JsonMapper.builder().enable(tools.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES,tools.jackson.databind.DeserializationFeature.FAIL_ON_TRAILING_TOKENS,tools.jackson.databind.DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES).enable(tools.jackson.core.StreamReadFeature.STRICT_DUPLICATE_DETECTION).disable(tools.jackson.databind.MapperFeature.ALLOW_COERCION_OF_SCALARS).disable(tools.jackson.databind.DeserializationFeature.ACCEPT_FLOAT_AS_INT).withCoercionConfig(tools.jackson.databind.type.LogicalType.Textual,c->c.setCoercion(tools.jackson.databind.cfg.CoercionInputShape.Integer,tools.jackson.databind.cfg.CoercionAction.Fail).setCoercion(tools.jackson.databind.cfg.CoercionInputShape.Float,tools.jackson.databind.cfg.CoercionAction.Fail).setCoercion(tools.jackson.databind.cfg.CoercionInputShape.Boolean,tools.jackson.databind.cfg.CoercionAction.Fail)).build();
 public AiResultService(AiTaskService tasks,RequestService requests,StorageService storage,ViewerService viewer,JdbcTemplate jdbc,WorkflowAccess access,IdempotentCommands commands,AuditRecorder audit,Validator validator,PlatformTransactionManager manager){this.tasks=tasks;this.requests=requests;this.storage=storage;this.viewer=viewer;this.jdbc=jdbc;this.access=access;this.commands=commands;this.audit=audit;this.validator=validator;tx=new TransactionTemplate(manager);tx.setTimeout(10);}
 private static ApiException problem(String code){return new ApiException(HttpStatus.CONFLICT,code,"Synthetic non-diagnostic result unavailable; recheck exact versions and authorization");}
 private static ApiException missing(){return new ApiException(HttpStatus.NOT_FOUND,"AI_RESULT_NOT_FOUND","Synthetic result unavailable");}
 private Result row(UUID request,UUID id){requests.authorizedScope(request);var rows=jdbc.query("SELECT * FROM ai_result WHERE request_id=? AND id=?",(r,i)->new Result(r.getObject("id",UUID.class),r.getObject("task_id",UUID.class),r.getObject("request_id",UUID.class),r.getObject("scan_id",UUID.class),r.getLong("task_version"),r.getLong("version"),r.getString("state"),json.readValue(r.getString("binding"),SyntheticResultPackage.Binding.class),r.getString("artifact_hash"),r.getLong("artifact_size"),r.getObject("artifact_id",UUID.class)),request,id);if(rows.isEmpty())throw missing();return rows.getFirst();}
 private record Source(AiTaskContracts.Job job,String hash){}
 private Source source(UUID request,UUID task,long expected){var view=tasks.detail(request,task);var j=view.job();if(!view.effectiveState().equals("SYNTHETIC_SUCCEEDED")||j.version()!=expected||view.clinicalExecutionAllowed())throw problem("AI_RESULT_INVALIDATED");var bytes=tasks.artifact(request,task).bytes();return new Source(j,ScanFormat.sha(bytes));}
 private Source current(Result r){var s=source(r.requestId(),r.taskId(),r.taskVersion());if(!s.hash().equals(r.binding().inputArtifactHash())||!s.job().bindingHash().equals(r.binding().taskBindingHash())||!s.job().binding().equals(r.binding().input()))throw problem("AI_RESULT_INVALIDATED");return s;}
 private byte[] encode(SyntheticResultPackage.Binding b){byte[] body=json.writeValueAsBytes(SyntheticResultPackage.generate(b));byte[] bytes=new byte[SyntheticResultPackage.PREFIX.length+body.length];System.arraycopy(SyntheticResultPackage.PREFIX,0,bytes,0,SyntheticResultPackage.PREFIX.length);System.arraycopy(body,0,bytes,SyntheticResultPackage.PREFIX.length,body.length);if(bytes.length>65536)throw problem("AI_RESULT_LIMIT");return bytes;}
 public IdempotentCommands.Result prepare(UUID request,Create input,String key){var errors=validator.validate(input);if(!errors.isEmpty())throw new ConstraintViolationException(errors);var initial=tx.execute(t->source(request,input.taskId(),input.expectedTaskVersion()));return commands.execute(initial.job().hospitalId(),"AI_RESULT_PREPARE_V1",key,Map.of("request",request,"input",input),new IdempotentCommands.Work(){
  public void authorize(CurrentActor.Actor a){source(request,input.taskId(),input.expectedTaskVersion());}
  public void authorizeReplay(CurrentActor.Actor a,CommandReceipt r){current(row(request,r.resourceId()));}
  public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){var s=source(request,input.taskId(),input.expectedTaskVersion());var j=s.job();var old=jdbc.queryForList("SELECT id FROM ai_result WHERE task_id=? AND generator=?",UUID.class,input.taskId(),SyntheticResultPackage.GENERATOR);if(!old.isEmpty())throw problem("AI_RESULT_EXISTS");var m=viewer.manifest(request,j.scanId(),j.binding().decision().publicationVersion()).content();UUID id=UUID.randomUUID();var b=new SyntheticResultPackage.Binding(id,j.id(),j.version(),j.generation(),j.hospitalId(),m.slideId(),j.ownerAuthVersion(),j.artifactId(),s.hash(),j.bindingHash(),j.binding(),m.width(),m.height(),SyntheticResultPackage.GENERATOR,Runtime.version().toString());var bytes=encode(b);jdbc.update("INSERT INTO ai_result(id,task_id,request_id,scope_id,hospital_id,scan_id,owner_id,task_version,source_hash,binding,generator,artifact_hash,artifact_size) VALUES(?,?,?,?,?,?,?,?,?,?::jsonb,?,?,?)",id,j.id(),request,j.scopeId(),j.hospitalId(),j.scanId(),a.id(),j.version(),s.hash(),json.writeValueAsString(b),b.generator(),ScanFormat.sha(bytes),bytes.length);return new IdempotentCommands.Mutation(new CommandReceipt(200,"SYNTHETIC_AI_RESULT",id,0),null);}
 });}
 public IdempotentCommands.Result create(UUID request,Create input,String key){var reserved=prepare(request,input,key);finish(request,reserved.receipt().resourceId());return reserved;}
 public Result finish(UUID request,UUID id){var r=tx.execute(t->{var v=row(request,id);current(v);return v;});if(r.state().equals("READY")){metadata(request,id);return r;}if(!SyntheticResultPackage.GENERATOR.equals(r.binding().generator())||!Runtime.version().toString().equals(r.binding().runtime()))throw problem("AI_RESULT_GENERATOR_CHANGED");var bytes=encode(r.binding());if(bytes.length!=r.artifactSize()||!ScanFormat.sha(bytes).equals(r.artifactHash()))throw problem("AI_RESULT_GENERATOR_CHANGED");String key="result:"+id;
  var reserved=storage.reserveResultArtifact(request,new StorageContracts.Reserve(null,-1L,r.binding().input().caseId(),(long)bytes.length,r.artifactHash(),"SYNTHETIC_RESULT_ARTIFACT","application/octet-stream"),key);UUID object=reserved.receipt().resourceId();var v=storage.detail(request,object);
  if(v.state().equals("RESERVED")){tx.execute(t->{current(r);return null;});v=storage.upload(request,object,v.version(),bytes.length,new ByteArrayInputStream(bytes));}
  if(Set.of("UPLOADING","FINALIZING").contains(v.state()))v=storage.reconcile(request,object);
  if(v.state().equals("STAGED")){tx.execute(t->{current(r);return null;});v=storage.finish(request,object,new StorageContracts.Command(r.binding().input().caseId(),v.version()),key+":finish");}
  if(!v.state().equals("READY"))throw problem("AI_RESULT_NOT_READY");
  tx.executeWithoutResult(t->{var now=row(request,id);var s=current(now);jdbc.queryForList("SELECT id FROM ai_result WHERE id=? FOR UPDATE",id);now=row(request,id);if(now.state().equals("READY")){if(!object.equals(now.artifactId()))throw problem("AI_RESULT_BINDING");return;}var stored=storage.resultArtifactBytes(request,object).bytes();decode(now,stored);if(jdbc.update("UPDATE ai_result SET state='READY',version=1,artifact_id=? WHERE id=? AND state='BUILDING' AND version=0",object,id)!=1)throw problem("AI_RESULT_CONFLICT");audit.append(s.job().hospitalId(),"AI_RESULT_READY_V1","SYNTHETIC_AI_RESULT",id,0L,1);});return tx.execute(t->{var result=row(request,id);current(result);return result;});
 }
 private SyntheticResultPackage.Package decode(Result r,byte[] bytes){if(bytes.length!=r.artifactSize()||bytes.length>65536||!ScanFormat.sha(bytes).equals(r.artifactHash())||!Arrays.equals(Arrays.copyOf(bytes,SyntheticResultPackage.PREFIX.length),SyntheticResultPackage.PREFIX))throw problem("AI_RESULT_CORRUPT");try{var p=json.readValue(new String(bytes,SyntheticResultPackage.PREFIX.length,bytes.length-SyntheticResultPackage.PREFIX.length,StandardCharsets.UTF_8),SyntheticResultPackage.Package.class);SyntheticResultPackage.validate(p,r.binding());return p;}catch(IllegalArgumentException|tools.jackson.core.JacksonException e){throw problem("AI_RESULT_CORRUPT");}}
 private String epoch(Result r){return ScanFormat.sha((r.id()+":"+r.artifactHash()+":"+access.actor().authVersion()+":"+r.binding().taskBindingHash()).getBytes(StandardCharsets.UTF_8));}
 public Metadata metadata(UUID request,UUID id){return tx.execute(t->{var r=row(request,id);var s=current(r);if(!r.state().equals("READY"))throw problem("AI_RESULT_NOT_READY");var p=decode(r,storage.resultArtifactBytes(request,r.artifactId()).bytes());audit.append(s.job().hospitalId(),"AI_RESULT_READ_V1","SYNTHETIC_AI_RESULT",id,null,r.version());return new Metadata(r,p.schema(),p.pngHash(),p.heatmapWidth(),p.heatmapHeight(),p.tileCount(),p.intensities(),p.regions(),p.meaning(),false,epoch(r));});}
 /** Authorized metadata history, not pixel consumption; revoked current dependencies remain explicit. */
 public record Reference(Result result,String invalidReason){}
 public Reference reference(UUID request,UUID id){return tx.execute(t->{var r=row(request,id);var v=tasks.detail(request,r.taskId());
  boolean current=v.effectiveState().equals("SYNTHETIC_SUCCEEDED")&&v.job().version()==r.taskVersion()&&v.job().bindingHash().equals(r.binding().taskBindingHash())&&v.job().binding().equals(r.binding().input())&&r.state().equals("READY");
  audit.append(r.binding().hospitalId(),"AI_RESULT_REFERENCE_READ_V1","SYNTHETIC_AI_RESULT",id,null,r.version());return new Reference(r,current?null:"RESULT_DEPENDENCY_CHANGED");});}
 public Tile tile(UUID request,UUID id,int tile,String expectedEpoch){if(tile!=0)throw problem("AI_RESULT_TILE");return tx.execute(t->{var r=row(request,id);var s=current(r);if(!r.state().equals("READY")||!epoch(r).equals(expectedEpoch))throw problem("AI_RESULT_INVALIDATED");var p=decode(r,storage.resultArtifactBytes(request,r.artifactId()).bytes());var png=SyntheticResultPackage.validate(p,r.binding());current(r);audit.append(s.job().hospitalId(),"AI_RESULT_TILE_V1","SYNTHETIC_AI_RESULT",id,null,r.version());return new Tile(png,p.pngHash(),epoch(r));});}
}
