package com.pis.storage;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.io.*;import java.security.*;import java.util.*;import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
class LocalStorageProviderTest {
 @TempDir Path temp;
 static byte[] data(int size){byte[] bytes=new byte[size];for(int i=0;i<size;i++)bytes[i]=(byte)(i%251);System.arraycopy(StoragePolicy.MARKER,0,bytes,0,StoragePolicy.MARKER.length);return bytes;}
 static String hash(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}
 @Test void boundedOriginalSurvivesRestartAndKeepsExactRangeAndHash()throws Exception{var id=UUID.randomUUID();var bytes=data(2*1024*1024);String hash=hash(bytes);Path root=temp.resolve("owned");UUID providerId;
  try(var p=new LocalStorageProvider(root)){providerId=p.rootId();p.stage(id,new ByteArrayInputStream(bytes),bytes.length,hash);p.publish(id,bytes.length,hash);var slice=p.read(id,bytes.length,hash,"bytes=1048576-2097151");assertThat(slice.bytes()).isEqualTo(Arrays.copyOfRange(bytes,1048576,2097152));assertThatThrownBy(()->p.read(id,bytes.length,hash,null)).isInstanceOf(StorageProvider.Failure.class);assertThat(p.capacity().volumeTotal()).isPositive();}
  try(var p=new LocalStorageProvider(root)){assertThat(p.rootId()).isEqualTo(providerId);p.publish(id,bytes.length,hash);assertThat(p.read(id,bytes.length,hash,"bytes=0-127").bytes()).isEqualTo(Arrays.copyOf(bytes,128));}
 }
 @Test void shortLongWrongHashAndUnmarkedUploadsNeverPublish()throws Exception{var bytes=data(128);try(var p=new LocalStorageProvider(temp.resolve("owned"))){
  for(var sample:List.of(Arrays.copyOf(bytes,127),Arrays.copyOf(bytes,129),new byte[128])){UUID id=UUID.randomUUID();assertThatThrownBy(()->p.stage(id,new ByteArrayInputStream(sample),128,hash(bytes))).isInstanceOf(IOException.class);assertThatThrownBy(()->p.publish(id,128,hash(bytes))).isInstanceOf(IOException.class);assertThat(Files.exists(temp.resolve("owned").resolve(id+".blob"))).isFalse();}
  assertThatThrownBy(()->p.stage(UUID.randomUUID(),new ByteArrayInputStream(bytes),128,"0".repeat(64))).isInstanceOf(IOException.class);
 }}
 @Test void partialOriginalIsNeverOverwrittenAfterCrash()throws Exception{var bytes=data(128);var id=UUID.randomUUID();var root=temp.resolve("owned");try(var p=new LocalStorageProvider(root)){p.stage(id,new ByteArrayInputStream(bytes),128,hash(bytes));Files.write(root.resolve(id+".blob"),new byte[]{7},StandardOpenOption.CREATE_NEW);assertThatThrownBy(()->p.publish(id,128,hash(bytes))).isInstanceOf(IOException.class);assertThat(Files.readAllBytes(root.resolve(id+".blob"))).containsExactly((byte)7);}}
 @Test void symlinkRootsAndObjectsCannotEscape()throws Exception{var outside=temp.resolve("outside");Files.createDirectory(outside);Files.createSymbolicLink(temp.resolve("link"),outside);assertThatThrownBy(()->new LocalStorageProvider(temp.resolve("link"))).isInstanceOf(IOException.class);var bytes=data(128);var id=UUID.randomUUID();var external=outside.resolve("secret");Files.write(external,bytes);var root=temp.resolve("owned");try(var p=new LocalStorageProvider(root)){Files.createSymbolicLink(root.resolve(id+".part"),external);assertThatThrownBy(()->p.stage(id,new ByteArrayInputStream(bytes),128,hash(bytes))).isInstanceOf(IOException.class);assertThatThrownBy(()->p.publish(id,128,hash(bytes))).isInstanceOf(IOException.class);Files.createSymbolicLink(root.resolve(id+".blob"),external);assertThatThrownBy(()->p.read(id,128,hash(bytes),null)).isInstanceOf(IOException.class);assertThat(Files.readAllBytes(external)).isEqualTo(bytes);}}
 @Test void rejectsPreexistingUserDirectoryAndConcurrentOwner()throws Exception{var user=temp.resolve("user");Files.createDirectory(user,java.nio.file.attribute.PosixFilePermissions.asFileAttribute(java.nio.file.attribute.PosixFilePermissions.fromString("rwx------")));Files.writeString(user.resolve("keep"),"synthetic user file");assertThatThrownBy(()->new LocalStorageProvider(user)).isInstanceOf(IOException.class);assertThat(Files.readString(user.resolve("keep"))).isEqualTo("synthetic user file");try(var p=new LocalStorageProvider(temp.resolve("owned"))){assertThatThrownBy(()->new LocalStorageProvider(temp.resolve("owned"))).isInstanceOf(IOException.class);assertThat(p.state()).isEqualTo("CONFIGURED_LOCAL");}}
 @Test void simultaneousPublishNeverChangesOriginalAndReplayIsExact()throws Exception{var id=UUID.randomUUID();var bytes=data(65536);String hash=hash(bytes);try(var p=new LocalStorageProvider(temp.resolve("owned"));var pool=Executors.newVirtualThreadPerTaskExecutor()){p.stage(id,new ByteArrayInputStream(bytes),bytes.length,hash);Callable<Boolean> work=()->{try{p.publish(id,bytes.length,hash);return true;}catch(IOException e){return false;}};var a=pool.submit(work);var b=pool.submit(work);assertThat(List.of(a.get(5,TimeUnit.SECONDS),b.get(5,TimeUnit.SECONDS))).contains(true);p.publish(id,bytes.length,hash);assertThat(p.read(id,bytes.length,hash,null).bytes()).isEqualTo(bytes);}}
 @Test void rangesAndS3RemainExplicitlyUnsupportedWhereNecessary()throws Exception{for(String range:List.of("bytes=-10","bytes=0-1,4-5","bytes=5-4","bytes=0-128","https://example.invalid"))assertThatThrownBy(()->StoragePolicy.range(range,128)).isInstanceOf(StorageProvider.Failure.class);var s3=new S3StorageContract();assertThat(s3.state()).isEqualTo("NOT_CONFIGURED");assertThat(s3.capacity().volumeTotal()).isNull();assertThatThrownBy(()->s3.read(UUID.randomUUID(),128,"0".repeat(64),null)).isInstanceOf(StorageProvider.Failure.class);}
}
