import {useEffect,useState} from 'react';
import {Alert,Button,Card,Descriptions,Table} from 'antd';
import {ApiError} from '../../api';
import {load,type Snapshot} from './api';
export function Operations({requestId,onExpired}:{requestId:string;onExpired:()=>void}) {
 const [turn,setTurn]=useState(0),[data,setData]=useState<Snapshot>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[controller,setController]=useState<AbortController>();
 useEffect(()=>{let live=true,timedOut=false;const c=new AbortController();const timer=setTimeout(()=>{timedOut=true;c.abort();},15000);setController(c);setData(undefined);setError('');setBusy(true);void load(requestId,c.signal).then(d=>{if(live&&!c.signal.aborted)setData(d);}).catch(e=>{if(!live)return;if(e instanceof ApiError&&e.status===401)onExpired();setError(c.signal.aborted?(timedOut?'运维查询超时，请重试。':'运维等待已取消，请重新读取。'):e instanceof Error?e.message:'运维读取失败');}).finally(()=>{clearTimeout(timer);if(live)setBusy(false);});return()=>{live=false;clearTimeout(timer);c.abort();};},[requestId,turn,onExpired]);
 return <Card title="合成运维只读快照"><Alert type="warning" title="仅本病例授权范围 · 非医院运维认证" description="未知不是正常。队列为本病例实际保存状态；容量是配置根所在文件系统可测量值，非医院容量或SLA。备份演练仅运行专用脚本，不操作当前实例。"/><Button disabled={busy} onClick={()=>setTurn(v=>v+1)}>刷新运维快照</Button><Button disabled={!busy} onClick={()=>controller?.abort()}>取消运维等待</Button>{busy&&<p role="status">正在核验运维资格</p>}{error&&<Alert role="alert" type="error" title={error}/>}{data&&data.requestId===requestId&&<><p>快照时间 {data.observedAt}</p><Descriptions column={1} items={[{key:'p',label:'待处理本地接口',children:data.pending},{key:'f',label:'失败或死信',children:data.failed},{key:'o',label:'就绪不可变对象',children:data.readyObjects},{key:'c',label:'私有根容量状态',children:data.capacityState},{key:'b',label:'可用字节',children:data.volumeUsable===null?'未知 / 不可用':data.volumeUsable},{key:'r',label:'当前实例恢复验证',children:data.recovery},{key:'e',label:'加密与异地备份',children:'NOT_CONFIGURED'}]}/>{data.failed>0&&<Alert type="error" role="alert" title="本病例存在失败或死信，请在原接口流程人工核对"/>}<Table rowKey="id" dataSource={data.events} pagination={false} scroll={{x:800}} columns={[{title:'时间',dataIndex:'at'},{title:'审计操作',dataIndex:'operation'},{title:'资源类型',dataIndex:'resourceType'},{title:'版本',dataIndex:'version'},{title:'关联ID',dataIndex:'traceId'}]}/><p>仅最近20项直接引用本申请的审计元数据；不包含报告正文、人员账号或全院审计。</p></>}</Card>;
}
