CREATE TABLE digital_qc_grant(user_id uuid NOT NULL REFERENCES app_user(id),scope_id uuid NOT NULL REFERENCES workflow_scope(id),qualification text NOT NULL CHECK(qualification='SYN-DIGITAL-QC-1'),valid_until timestamptz NOT NULL,revoked_at timestamptz,PRIMARY KEY(user_id,scope_id));
CREATE TABLE digital_qc_head(scan_id uuid PRIMARY KEY REFERENCES scan_import(id),version bigint NOT NULL DEFAULT -1 CHECK(version BETWEEN -1 AND 99),assessment_version bigint,state text NOT NULL DEFAULT 'UNASSESSED' CHECK(state IN('UNASSESSED','EVALUATED','PUBLISHED','REVOKED')),CHECK((version=-1 AND assessment_version IS NULL AND state='UNASSESSED') OR (version>=0 AND assessment_version IS NOT NULL AND assessment_version BETWEEN 0 AND version AND state<>'UNASSESSED')));
CREATE TABLE digital_qc_assessment(scan_id uuid NOT NULL REFERENCES scan_import(id),version bigint NOT NULL CHECK(version>=0),scan_version bigint NOT NULL,object_id uuid NOT NULL REFERENCES storage_version(id),object_hash text NOT NULL CHECK(object_hash~'^[a-f0-9]{64}$'),slide_id uuid NOT NULL REFERENCES material_entity(id),source_basis text NOT NULL,checklist text NOT NULL CHECK(checklist='SYN-DIGITAL-QC-1'),coverage text NOT NULL CHECK(coverage IN('PASS','FAIL','UNKNOWN')),focus text NOT NULL CHECK(focus IN('PASS','FAIL','UNKNOWN')),missing text NOT NULL CHECK(missing IN('PASS','FAIL','UNKNOWN')),coverage_percent integer NOT NULL CHECK(coverage_percent BETWEEN 0 AND 100),missing_tiles integer NOT NULL CHECK(missing_tiles BETWEEN 0 AND 1000000),regions jsonb NOT NULL CHECK(jsonb_typeof(regions)='array' AND jsonb_array_length(regions)<=20),note text NOT NULL CHECK(length(btrim(note)) BETWEEN 1 AND 1000),passed boolean NOT NULL,actor_id uuid NOT NULL REFERENCES app_user(id),occurred_at timestamptz NOT NULL DEFAULT statement_timestamp(),PRIMARY KEY(scan_id,version),CHECK(passed=(coverage='PASS' AND focus='PASS' AND missing='PASS' AND coverage_percent=100 AND missing_tiles=0 AND jsonb_array_length(regions)=0)));
ALTER TABLE digital_qc_head ADD FOREIGN KEY(scan_id,assessment_version) REFERENCES digital_qc_assessment(scan_id,version);
CREATE TABLE digital_qc_event(scan_id uuid NOT NULL REFERENCES scan_import(id),version bigint NOT NULL,action text NOT NULL CHECK(action IN('EVALUATE','PUBLISH','REVOKE')),assessment_version bigint NOT NULL,actor_id uuid NOT NULL REFERENCES app_user(id),reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 1000),occurred_at timestamptz NOT NULL DEFAULT statement_timestamp(),PRIMARY KEY(scan_id,version),FOREIGN KEY(scan_id,assessment_version) REFERENCES digital_qc_assessment(scan_id,version));
CREATE FUNCTION digital_qc_binding() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM scan_import s WHERE s.id=NEW.scan_id AND s.version=NEW.scan_version AND s.object_id=NEW.object_id AND s.object_hash=NEW.object_hash AND s.slide_id=NEW.slide_id AND s.source_basis=NEW.source_basis AND s.state='PENDING_DIGITAL_QC') THEN RAISE EXCEPTION 'Digital QC binding mismatch' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_digital_qc_binding BEFORE INSERT ON digital_qc_assessment FOR EACH ROW EXECUTE FUNCTION digital_qc_binding();
CREATE TRIGGER trg_digital_qc_assessment_immutable BEFORE UPDATE OR DELETE ON digital_qc_assessment FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE TRIGGER trg_digital_qc_event_immutable BEFORE UPDATE OR DELETE ON digital_qc_event FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE FUNCTION protect_digital_qc_head() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' OR NEW.scan_id<>OLD.scan_id OR NEW.version<>OLD.version+1 OR NOT((NEW.state='EVALUATED' AND NEW.assessment_version=NEW.version) OR(NEW.state='PUBLISHED' AND OLD.state='EVALUATED' AND NEW.assessment_version=OLD.assessment_version) OR(NEW.state='REVOKED' AND OLD.state IN('EVALUATED','PUBLISHED') AND NEW.assessment_version=OLD.assessment_version)) THEN RAISE EXCEPTION 'Digital QC CAS transition required' USING ERRCODE='23514';END IF;
 IF NEW.state='PUBLISHED' AND NOT EXISTS(SELECT 1 FROM digital_qc_assessment a JOIN scan_import s ON s.id=a.scan_id JOIN scan_series ss ON ss.slide_id=s.slide_id WHERE a.scan_id=NEW.scan_id AND a.version=NEW.assessment_version AND a.passed AND a.scan_version=s.version AND s.state='PENDING_DIGITAL_QC' AND ss.head=s.ordinal) THEN RAISE EXCEPTION 'Exact current passed assessment required' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_digital_qc_head BEFORE UPDATE OR DELETE ON digital_qc_head FOR EACH ROW EXECUTE FUNCTION protect_digital_qc_head();
