-- No identities, clinical grants or models are seeded. Development worker only.
ALTER TABLE storage_version DROP CONSTRAINT storage_version_purpose_check;
ALTER TABLE storage_version ADD CONSTRAINT storage_version_purpose_check CHECK(purpose IN('SYNTHETIC_ORIGINAL','SYNTHETIC_WORKER_ARTIFACT'));
CREATE TABLE ai_task_grant(user_id uuid NOT NULL REFERENCES app_user(id),scope_id uuid NOT NULL REFERENCES workflow_scope(id),qualification text NOT NULL CHECK(qualification='SYN-CONTRACT-WORKER-1'),can_submit boolean NOT NULL DEFAULT false,can_work boolean NOT NULL DEFAULT false,valid_until timestamptz NOT NULL,revoked_at timestamptz,PRIMARY KEY(user_id,scope_id));
CREATE TABLE ai_task(id uuid PRIMARY KEY,request_id uuid NOT NULL,scope_id uuid NOT NULL,hospital_id uuid NOT NULL REFERENCES hospital(id),scan_id uuid NOT NULL REFERENCES scan_import(id),assessment_id uuid NOT NULL REFERENCES ai_assessment(id),owner_id uuid NOT NULL REFERENCES app_user(id),owner_auth_version bigint NOT NULL,binding jsonb NOT NULL CHECK(jsonb_typeof(binding)='object'),binding_hash text NOT NULL CHECK(binding_hash~'^[a-f0-9]{64}$'),worker_schema text NOT NULL,reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 500),state text NOT NULL CHECK(state IN('QUEUED','RUNNING','SYNTHETIC_SUCCEEDED','FAILED','CANCELLED','TIMEOUT','UNSUPPORTED','INVALIDATED')),version bigint NOT NULL DEFAULT 0 CHECK(version>=0),generation integer NOT NULL DEFAULT 0 CHECK(generation BETWEEN 0 AND 3),progress integer CHECK(progress BETWEEN 0 AND 100),lease_id uuid,lease_actor uuid REFERENCES app_user(id),lease_until timestamptz,deadline timestamptz,retry_at timestamptz,error_code text NOT NULL DEFAULT '',artifact_id uuid REFERENCES storage_version(id),created_at timestamptz NOT NULL DEFAULT statement_timestamp(),FOREIGN KEY(request_id,scope_id) REFERENCES request_workflow(request_id,scope_id),CHECK(state<>'RUNNING' OR (lease_id IS NOT NULL AND lease_actor IS NOT NULL AND lease_until IS NOT NULL AND deadline IS NOT NULL)),CHECK(state<>'SYNTHETIC_SUCCEEDED' OR artifact_id IS NOT NULL));
CREATE INDEX idx_ai_task_request ON ai_task(request_id,created_at DESC,id);
CREATE INDEX idx_ai_task_leases ON ai_task(state,lease_until);
CREATE TABLE ai_task_outbox(task_id uuid PRIMARY KEY REFERENCES ai_task(id),generation integer NOT NULL DEFAULT 0,state text NOT NULL CHECK(state IN('PENDING','LEASED','DONE')),updated_at timestamptz NOT NULL DEFAULT statement_timestamp());
CREATE TABLE ai_task_attempt(task_id uuid NOT NULL REFERENCES ai_task(id),generation integer NOT NULL CHECK(generation BETWEEN 1 AND 3),lease_id uuid NOT NULL UNIQUE,actor_id uuid NOT NULL REFERENCES app_user(id),artifact_id uuid REFERENCES storage_version(id),created_at timestamptz NOT NULL DEFAULT statement_timestamp(),PRIMARY KEY(task_id,generation));
CREATE TABLE ai_task_callback(task_id uuid NOT NULL REFERENCES ai_task(id),generation integer NOT NULL,callback_id uuid NOT NULL UNIQUE,payload_hash text NOT NULL CHECK(payload_hash~'^[a-f0-9]{64}$'),result_version bigint NOT NULL,PRIMARY KEY(task_id,generation),FOREIGN KEY(task_id,generation) REFERENCES ai_task_attempt(task_id,generation));
CREATE TABLE ai_task_event(task_id uuid NOT NULL REFERENCES ai_task(id),version bigint NOT NULL,generation integer NOT NULL,state text NOT NULL,action text NOT NULL,error_code text NOT NULL,actor_id uuid NOT NULL REFERENCES app_user(id),reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 500),occurred_at timestamptz NOT NULL DEFAULT statement_timestamp(),PRIMARY KEY(task_id,version));
CREATE TRIGGER trg_ai_task_event_immutable BEFORE UPDATE OR DELETE ON ai_task_event FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE TRIGGER trg_ai_task_callback_immutable BEFORE UPDATE OR DELETE ON ai_task_callback FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE FUNCTION guard_ai_task() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Task history is retained' USING ERRCODE='23514';END IF;
 IF TG_OP='INSERT' THEN
  IF NOT EXISTS(SELECT 1 FROM ai_assessment a JOIN scan_import s ON s.id=a.scan_id WHERE a.id=NEW.assessment_id AND a.scope_id=NEW.scope_id AND a.scan_id=NEW.scan_id AND s.request_id=NEW.request_id AND s.hospital_id=NEW.hospital_id) THEN RAISE EXCEPTION 'Task source mismatch' USING ERRCODE='23514';END IF;
 ELSE
  IF ROW(NEW.id,NEW.request_id,NEW.scope_id,NEW.hospital_id,NEW.scan_id,NEW.assessment_id,NEW.owner_id,NEW.owner_auth_version,NEW.binding,NEW.binding_hash,NEW.worker_schema,NEW.reason,NEW.created_at) IS DISTINCT FROM ROW(OLD.id,OLD.request_id,OLD.scope_id,OLD.hospital_id,OLD.scan_id,OLD.assessment_id,OLD.owner_id,OLD.owner_auth_version,OLD.binding,OLD.binding_hash,OLD.worker_schema,OLD.reason,OLD.created_at) OR NEW.version<>OLD.version+1 OR NEW.generation<OLD.generation OR NEW.generation>OLD.generation+1 THEN RAISE EXCEPTION 'Task immutable binding/CAS' USING ERRCODE='23514';END IF;
  IF NOT ((OLD.state='QUEUED' AND NEW.state IN('RUNNING','CANCELLED','INVALIDATED')) OR (OLD.state='RUNNING' AND NEW.state IN('RUNNING','SYNTHETIC_SUCCEEDED','FAILED','TIMEOUT','CANCELLED','INVALIDATED','UNSUPPORTED')) OR (OLD.state IN('FAILED','TIMEOUT') AND NEW.state IN('QUEUED','CANCELLED','INVALIDATED')) OR (OLD.state='SYNTHETIC_SUCCEEDED' AND NEW.state='INVALIDATED')) THEN RAISE EXCEPTION 'Task transition rejected' USING ERRCODE='23514';END IF;
 END IF;
 IF NEW.artifact_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM storage_version v WHERE v.id=NEW.artifact_id AND v.request_id=NEW.request_id AND v.hospital_id=NEW.hospital_id AND v.purpose='SYNTHETIC_WORKER_ARTIFACT' AND v.state='READY' AND v.byte_size<=4096) THEN RAISE EXCEPTION 'Task artifact mismatch' USING ERRCODE='23514';END IF;
 RETURN NEW;END $$;
CREATE TRIGGER trg_ai_task BEFORE INSERT OR UPDATE OR DELETE ON ai_task FOR EACH ROW EXECUTE FUNCTION guard_ai_task();
CREATE FUNCTION guard_ai_attempt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='INSERT' THEN
  IF NOT EXISTS(SELECT 1 FROM ai_task t WHERE t.id=NEW.task_id AND t.owner_id=NEW.actor_id AND t.state='QUEUED' AND NEW.generation=t.generation+1) THEN RAISE EXCEPTION 'Attempt owner/generation mismatch' USING ERRCODE='23514';END IF;RETURN NEW;
 END IF;
 IF NEW.artifact_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM ai_task t JOIN storage_version v ON v.request_id=t.request_id AND v.hospital_id=t.hospital_id WHERE t.id=NEW.task_id AND v.id=NEW.artifact_id AND v.purpose='SYNTHETIC_WORKER_ARTIFACT' AND v.byte_size<=4096) THEN RAISE EXCEPTION 'Attempt artifact scope mismatch' USING ERRCODE='23514';END IF;
 IF TG_OP='DELETE' OR ROW(NEW.task_id,NEW.generation,NEW.lease_id,NEW.actor_id,NEW.created_at) IS DISTINCT FROM ROW(OLD.task_id,OLD.generation,OLD.lease_id,OLD.actor_id,OLD.created_at) OR OLD.artifact_id IS NOT NULL OR NEW.artifact_id IS NULL THEN RAISE EXCEPTION 'Attempt binding is immutable' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_ai_attempt BEFORE INSERT OR UPDATE OR DELETE ON ai_task_attempt FOR EACH ROW EXECUTE FUNCTION guard_ai_attempt();
