CREATE TABLE report_result_head(case_id uuid NOT NULL REFERENCES pathology_case(id),result_id uuid NOT NULL REFERENCES ai_result(id),version bigint NOT NULL DEFAULT -1 CHECK(version BETWEEN -1 AND 99),PRIMARY KEY(case_id,result_id));
CREATE TABLE report_result_decision(id uuid PRIMARY KEY,case_id uuid NOT NULL REFERENCES pathology_case(id),result_id uuid NOT NULL REFERENCES ai_result(id),version bigint NOT NULL CHECK(version BETWEEN 0 AND 99),target_revision_id uuid NOT NULL REFERENCES report_revision(id),target_version bigint NOT NULL,assignment_version bigint NOT NULL,action text NOT NULL CHECK(action IN('ACCEPT_REFERENCE','REJECT','DEFER')),reason text NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 500),actor_id uuid NOT NULL REFERENCES app_user(id),recorded_at timestamptz NOT NULL DEFAULT statement_timestamp(),binding jsonb NOT NULL CHECK(jsonb_typeof(binding)='object'),artifact_hash text NOT NULL CHECK(artifact_hash~'^[a-f0-9]{64}$'),adopted_revision_id uuid REFERENCES report_revision(id),UNIQUE(case_id,result_id,version),FOREIGN KEY(case_id,result_id) REFERENCES report_result_head(case_id,result_id),CHECK((action='ACCEPT_REFERENCE')=(adopted_revision_id IS NOT NULL)));
CREATE FUNCTION guard_report_result_decision() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM ai_result r JOIN pathology_case c ON c.request_id=r.request_id JOIN report_revision v ON v.case_id=c.id WHERE c.id=NEW.case_id AND r.id=NEW.result_id AND r.state='READY' AND r.binding=NEW.binding AND r.artifact_hash=NEW.artifact_hash AND v.id=NEW.target_revision_id AND v.version=NEW.target_version) THEN RAISE EXCEPTION 'Synthetic decision source mismatch' USING ERRCODE='23514';END IF;
 IF NEW.adopted_revision_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM report_revision v JOIN report_revision previous ON previous.id=NEW.target_revision_id WHERE v.id=NEW.adopted_revision_id AND v.case_id=NEW.case_id AND v.version=previous.version+1 AND v.fields=previous.fields AND v.template_code=previous.template_code AND v.template_version=previous.template_version AND v.assignment_version=NEW.assignment_version) THEN RAISE EXCEPTION 'Synthetic reference must preserve manual fields' USING ERRCODE='23514';END IF;
 IF NOT EXISTS(SELECT 1 FROM report_result_head h WHERE h.case_id=NEW.case_id AND h.result_id=NEW.result_id AND h.version=NEW.version) THEN RAISE EXCEPTION 'Synthetic decision version mismatch' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_report_result_binding BEFORE INSERT ON report_result_decision FOR EACH ROW EXECUTE FUNCTION guard_report_result_decision();
CREATE TRIGGER trg_report_result_immutable BEFORE UPDATE OR DELETE ON report_result_decision FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE FUNCTION guard_report_result_head() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' OR ROW(NEW.case_id,NEW.result_id) IS DISTINCT FROM ROW(OLD.case_id,OLD.result_id) OR NEW.version<>OLD.version+1 THEN RAISE EXCEPTION 'Synthetic decision CAS required' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_report_result_head BEFORE UPDATE OR DELETE ON report_result_head FOR EACH ROW EXECUTE FUNCTION guard_report_result_head();
