CREATE TABLE report_impact_head(decision_id uuid PRIMARY KEY REFERENCES report_result_decision(id),version bigint NOT NULL DEFAULT -1 CHECK(version BETWEEN -1 AND 99));
CREATE TABLE report_impact_review(id uuid PRIMARY KEY,decision_id uuid NOT NULL REFERENCES report_impact_head(decision_id),case_id uuid NOT NULL REFERENCES pathology_case(id),result_id uuid NOT NULL REFERENCES ai_result(id),version bigint NOT NULL CHECK(version BETWEEN 0 AND 99),snapshot_hash text NOT NULL CHECK(snapshot_hash~'^[a-f0-9]{64}$'),snapshot jsonb NOT NULL CHECK(jsonb_typeof(snapshot)='object'),action text NOT NULL CHECK(action IN('ACKNOWLEDGE','DEFER')),reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 500),actor_id uuid NOT NULL REFERENCES app_user(id),recorded_at timestamptz NOT NULL DEFAULT statement_timestamp(),UNIQUE(decision_id,version));
CREATE FUNCTION guard_report_impact_review() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM report_result_decision d JOIN report_impact_head h ON h.decision_id=d.id WHERE d.id=NEW.decision_id AND d.case_id=NEW.case_id AND d.result_id=NEW.result_id AND h.version=NEW.version) OR NEW.snapshot->>'decisionId' IS DISTINCT FROM NEW.decision_id::text OR NEW.snapshot->>'resultId' IS DISTINCT FROM NEW.result_id::text OR NEW.snapshot->>'epoch' IS DISTINCT FROM NEW.snapshot_hash THEN RAISE EXCEPTION 'Impact review binding mismatch' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_report_impact_binding BEFORE INSERT ON report_impact_review FOR EACH ROW EXECUTE FUNCTION guard_report_impact_review();
CREATE TRIGGER trg_report_impact_immutable BEFORE UPDATE OR DELETE ON report_impact_review FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE FUNCTION guard_report_impact_head() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' OR NEW.decision_id<>OLD.decision_id OR NEW.version<>OLD.version+1 THEN RAISE EXCEPTION 'Impact review CAS required' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_report_impact_head BEFORE UPDATE OR DELETE ON report_impact_head FOR EACH ROW EXECUTE FUNCTION guard_report_impact_head();
