CREATE TABLE adapter_grant(user_id uuid NOT NULL REFERENCES app_user(id),scope_id uuid NOT NULL REFERENCES workflow_scope(id),qualification text NOT NULL CHECK(qualification='SYN-ADAPTER-1'),valid_until timestamptz NOT NULL,revoked_at timestamptz,PRIMARY KEY(user_id,scope_id));
CREATE TABLE adapter_message(id uuid PRIMARY KEY,request_id uuid NOT NULL REFERENCES pathology_request(id),case_id uuid NOT NULL REFERENCES pathology_case(id),patient_id uuid NOT NULL REFERENCES patient(id),hospital_id uuid NOT NULL REFERENCES hospital(id),scope_id uuid NOT NULL REFERENCES workflow_scope(id),source_id uuid NOT NULL REFERENCES source_system(id),adapter text NOT NULL CHECK(adapter IN('HIS','BILLING','DEVICE')),external_id text NOT NULL CHECK(external_id~'^SYN-[A-Za-z0-9_-]{1,60}$'),sequence integer NOT NULL CHECK(sequence BETWEEN 1 AND 1000),schema_code text NOT NULL CHECK(schema_code='SYN-HOSPITAL-1'),payload jsonb NOT NULL CHECK(jsonb_typeof(payload)='object' AND octet_length(payload::text)<=4096),payload_hash text NOT NULL CHECK(payload_hash~'^[a-f0-9]{64}$'),actor_id uuid NOT NULL REFERENCES app_user(id),created_at timestamptz NOT NULL DEFAULT statement_timestamp(),UNIQUE(scope_id,source_id,adapter,external_id),UNIQUE(id,request_id));
CREATE FUNCTION guard_adapter_identity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pathology_case c JOIN pathology_request r ON r.id=c.request_id JOIN request_workflow w ON w.request_id=r.id JOIN workflow_scope s ON s.id=w.scope_id WHERE c.id=NEW.case_id AND r.id=NEW.request_id AND r.patient_id=NEW.patient_id AND r.hospital_id=NEW.hospital_id AND s.id=NEW.scope_id AND s.source_system_id=NEW.source_id) THEN RAISE EXCEPTION 'Synthetic adapter identity mismatch' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_adapter_identity BEFORE INSERT ON adapter_message FOR EACH ROW EXECUTE FUNCTION guard_adapter_identity();
CREATE TRIGGER trg_adapter_message_immutable BEFORE UPDATE OR DELETE ON adapter_message FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE TABLE adapter_outbox(message_id uuid PRIMARY KEY REFERENCES adapter_message(id),version bigint NOT NULL DEFAULT 0 CHECK(version BETWEEN 0 AND 99),state text NOT NULL DEFAULT 'QUEUED' CHECK(state IN('QUEUED','ATTEMPTING','RETRY_WAIT','REJECTED','DEAD','CANCELLED','ACKED','RECONCILED')),attempts integer NOT NULL DEFAULT 0 CHECK(attempts BETWEEN 0 AND 3),attempt_id uuid,lease_until timestamptz,next_at timestamptz NOT NULL DEFAULT statement_timestamp(),error_code text NOT NULL DEFAULT '',CHECK((state='ATTEMPTING')=(lease_until IS NOT NULL)),CHECK((attempts=0)=(attempt_id IS NULL)));
CREATE TABLE adapter_receiver(request_id uuid NOT NULL REFERENCES pathology_request(id),adapter text NOT NULL CHECK(adapter IN('HIS','BILLING','DEVICE')),sequence integer NOT NULL DEFAULT 0 CHECK(sequence BETWEEN 0 AND 1000),PRIMARY KEY(request_id,adapter));
CREATE TABLE adapter_inbox(message_id uuid PRIMARY KEY REFERENCES adapter_message(id),payload_hash text NOT NULL,recorded_at timestamptz NOT NULL DEFAULT statement_timestamp());
CREATE TABLE adapter_local_record(message_id uuid PRIMARY KEY REFERENCES adapter_inbox(message_id),meaning text NOT NULL CHECK(meaning='SYNTHETIC_RECORD_NOT_CLINICAL_DELIVERY_OR_PAYMENT'),recorded_at timestamptz NOT NULL DEFAULT statement_timestamp());
CREATE FUNCTION guard_adapter_inbox() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM adapter_message m WHERE m.id=NEW.message_id AND m.payload_hash=NEW.payload_hash) THEN RAISE EXCEPTION 'Synthetic receipt digest mismatch' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER trg_adapter_inbox_binding BEFORE INSERT ON adapter_inbox FOR EACH ROW EXECUTE FUNCTION guard_adapter_inbox();
CREATE TRIGGER trg_adapter_inbox_immutable BEFORE UPDATE OR DELETE ON adapter_inbox FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE TRIGGER trg_adapter_record_immutable BEFORE UPDATE OR DELETE ON adapter_local_record FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();
CREATE TABLE adapter_event(message_id uuid NOT NULL REFERENCES adapter_message(id),version bigint NOT NULL,action text NOT NULL,state text NOT NULL,error_code text NOT NULL,attempt_id uuid,actor_id uuid NOT NULL REFERENCES app_user(id),reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 1 AND 500),created_at timestamptz NOT NULL DEFAULT statement_timestamp(),PRIMARY KEY(message_id,version));
CREATE TRIGGER trg_adapter_event_immutable BEFORE UPDATE OR DELETE ON adapter_event FOR EACH ROW EXECUTE FUNCTION protect_gross_append_only();

CREATE INDEX adapter_message_request_order ON adapter_message(request_id,created_at DESC,id);
