import { describe, expect, it } from 'vitest';
import { parseAssessment, parseView } from './api';
const a = { version: 0, scanVersion: 2, objectId: 'object', slideId: 'slide', objectHash: 'a'.repeat(64), sourceBasis: 'b'.repeat(64), checklist: 'SYN-DIGITAL-QC-1', coverage: 'PASS', focus: 'PASS', missing: 'PASS', coveragePercent: 100, missingTiles: 0, regions: [], note: 'Synthetic only', passed: true, actorId: 'reviewer', occurredAt: '2026-10-03T00:00:00Z' };
const v = { requestId: 'request', scanId: 'scan', caseId: 'case', slideId: 'slide', objectId: 'object', objectHash: a.objectHash, scanVersion: 2, ordinal: 0, currentScan: true, version: 1, state: 'PUBLISHED', effectiveState: 'PUBLISHED_SYNTHETIC_CONTRACT', invalidReason: '', assessment: a, events: [], capability: 'SYNTHETIC_CONTRACT_ONLY_NO_VIEWER' };
describe('digital QC exact version contract', () => {
 it('preserves the explicit synthetic publication without claiming a viewer', () => { expect(parseView(v, 'request', 'scan')).toEqual(v); });
 it('rejects unknown, missing and failed criteria disguised as PASS', () => { for (const patch of [{ focus: 'UNKNOWN' }, { missing: null }, { coverage: 'FAIL' }, { coveragePercent: 99 }, { missingTiles: 1 }, { regions: [{ x: 0, y: 0, width: 1, height: 1, note: 'Synthetic defect' }] }]) expect(() => parseAssessment({ ...a, ...patch })).toThrow(); });
 it('keeps an explicitly unknown evaluation isolated', () => { expect(parseView({ ...v, state: 'EVALUATED', effectiveState: 'ISOLATED', invalidReason: 'QC_NOT_PASSED', assessment: { ...a, focus: 'UNKNOWN', passed: false } }, 'request', 'scan').assessment?.passed).toBe(false); });
 it('rejects wrong case request, scan, object or hash', () => { expect(() => parseView(v, 'other', 'scan')).toThrow(); expect(() => parseView(v, 'request', 'other')).toThrow(); for (const patch of [{ objectId: 'other' }, { slideId: 'other' }, { objectHash: 'c'.repeat(64) }]) expect(() => parseView({ ...v, assessment: { ...a, ...patch } }, 'request', 'scan')).toThrow(); });
 it('rejects stale publication or fabricated image capability', () => { for (const patch of [{ currentScan: false }, { invalidReason: 'RESCANNED' }, { state: 'REVOKED' }, { scanVersion: 3 }, { capability: 'VIEWER_READY' }]) expect(() => parseView({ ...v, ...patch }, 'request', 'scan')).toThrow(); });
 it('rejects unsupported checklists and excessive or invalid regions', () => { expect(() => parseAssessment({ ...a, checklist: 'new-unverified' })).toThrow(); expect(() => parseAssessment({ ...a, regions: Array(21).fill({}) })).toThrow(); expect(() => parseAssessment({ ...a, regions: [{ x: -1, y: 0, width: 1, height: 1, note: 'bad' }] })).toThrow(); });
});
