import { request, readJson, fetchCsrf } from '../../api';
export type Result = 'PASS' | 'FAIL' | 'UNKNOWN';
export interface Region { x: number; y: number; width: number; height: number; note: string }
export interface Evaluation { expectedVersion: number; scanVersion: number; objectId: string; slideId: string; objectHash: string; checklist: 'SYN-DIGITAL-QC-1'; coverage: Result; focus: Result; missing: Result; coveragePercent: number; missingTiles: number; regions: Region[]; note: string }
export interface Assessment extends Omit<Evaluation, 'expectedVersion'> { version: number; sourceBasis: string; passed: boolean; actorId: string; occurredAt: string }
export interface Event { version: number; action: string; assessmentVersion: number; actorId: string; reason: string; occurredAt: string }
export interface View { requestId: string; scanId: string; caseId: string; slideId: string; objectId: string; objectHash: string; scanVersion: number; ordinal: number; currentScan: boolean; version: number; state: string; effectiveState: string; invalidReason: string; assessment: Assessment | null; events: Event[]; capability: string }
export interface Command { expectedVersion: number; assessmentVersion: number; reason: string }
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) throw Error('数字QC响应格式错误'); return v as Record<string, unknown>; }
function str(v: unknown): string { if (typeof v !== 'string') throw Error('数字QC文本缺失'); return v; }
function num(v: unknown, min = 0, max = Number.MAX_SAFE_INTEGER): number { if (typeof v !== 'number' || !Number.isSafeInteger(v) || v < min || v > max) throw Error('数字QC数值无效'); return v; }
function bool(v: unknown): boolean { if (typeof v !== 'boolean') throw Error('数字QC布尔状态缺失'); return v; }
function hash(v: unknown) { const s = str(v); if (!/^[a-f0-9]{64}$/.test(s)) throw Error('数字QC摘要无效'); return s; }
function result(v: unknown): Result { if (v !== 'PASS' && v !== 'FAIL' && v !== 'UNKNOWN') throw Error('未识别的检查结果'); return v; }
export function parseAssessment(value: unknown): Assessment { const v = obj(value); if (v.checklist !== 'SYN-DIGITAL-QC-1' || !Array.isArray(v.regions) || v.regions.length > 20) throw Error('检查单或区域越界'); const a: Assessment = { version: num(v.version), scanVersion: num(v.scanVersion), objectId: str(v.objectId), slideId: str(v.slideId), objectHash: hash(v.objectHash), sourceBasis: hash(v.sourceBasis), checklist: 'SYN-DIGITAL-QC-1', coverage: result(v.coverage), focus: result(v.focus), missing: result(v.missing), coveragePercent: num(v.coveragePercent, 0, 100), missingTiles: num(v.missingTiles, 0, 1000000), regions: v.regions.map(x => { const r = obj(x); return { x: num(r.x), y: num(r.y), width: num(r.width, 1), height: num(r.height, 1), note: str(r.note) }; }), note: str(v.note), passed: bool(v.passed), actorId: str(v.actorId), occurredAt: str(v.occurredAt) }; if (a.passed !== (a.coverage === 'PASS' && a.focus === 'PASS' && a.missing === 'PASS' && a.coveragePercent === 100 && a.missingTiles === 0 && a.regions.length === 0)) throw Error('不能将未知或缺陷默认为通过'); return a; }
export function parseView(value: unknown, rid: string, scan: string): View { const v = obj(value); if (v.requestId !== rid || v.scanId !== scan || v.capability !== 'SYNTHETIC_CONTRACT_ONLY_NO_VIEWER' || !['UNASSESSED', 'EVALUATED', 'PUBLISHED', 'REVOKED'].includes(str(v.state)) || !['ISOLATED', 'PUBLISHED_SYNTHETIC_CONTRACT', 'EVALUATED_NOT_PUBLISHED'].includes(str(v.effectiveState)) || !Array.isArray(v.events) || v.events.length > 100) throw Error('数字QC对象或状态不匹配'); const assessment = v.assessment === null ? null : parseAssessment(v.assessment); if (assessment && (assessment.objectId !== v.objectId || assessment.slideId !== v.slideId || assessment.objectHash !== v.objectHash)) throw Error('评价绑定错误'); if (v.effectiveState === 'PUBLISHED_SYNTHETIC_CONTRACT' && (!assessment?.passed || v.state !== 'PUBLISHED' || v.currentScan !== true || v.invalidReason !== '' || assessment.scanVersion !== v.scanVersion)) throw Error('无有效精确版本发布'); return { requestId: rid, scanId: scan, caseId: str(v.caseId), slideId: str(v.slideId), objectId: str(v.objectId), objectHash: hash(v.objectHash), scanVersion: num(v.scanVersion), ordinal: num(v.ordinal), currentScan: bool(v.currentScan), version: num(v.version, -1, 99), state: str(v.state), effectiveState: str(v.effectiveState), invalidReason: str(v.invalidReason), assessment, events: v.events.map(x => { const e = obj(x); if (!['EVALUATE', 'PUBLISH', 'REVOKE'].includes(str(e.action))) throw Error('QC历史动作无效'); return { version: num(e.version), action: str(e.action), assessmentVersion: num(e.assessmentVersion), actorId: str(e.actorId), reason: str(e.reason), occurredAt: str(e.occurredAt) }; }), capability: str(v.capability) }; }
const path = (rid: string, scan: string) => `/api/requests/${encodeURIComponent(rid)}/scans/${encodeURIComponent(scan)}/digital-qc`;
export async function load(rid: string, scan: string, signal: AbortSignal) { return parseView(await readJson(await request(path(rid, scan), { signal })), rid, scan); }
export async function history(rid: string, scan: string, signal: AbortSignal) { const v = await readJson(await request(`${path(rid, scan)}/history`, { signal })); if (!Array.isArray(v) || v.length > 100) throw Error('QC历史越界'); return v.map(parseAssessment); }
export async function post(rid: string, scan: string, action: string, body: Evaluation | Command, key: string, signal: AbortSignal) { const csrf = await fetchCsrf(signal); const value = await readJson(await request(path(rid, scan) + action, { method: 'POST', signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify(body) })); const r = obj(obj(value).receipt); if (r.resourceType !== 'DIGITAL_QC' || r.resourceId !== scan || r.status !== 200 || r.version !== body.expectedVersion + 1) throw Error('QC回执不属于原请求'); }
