import { useEffect, useRef, useState } from 'react';
import { Alert, Button, Input, Modal, Select, Space, Table, Typography } from 'antd';
import { ApiError } from '../../api';
import * as api from './api';
type Intent = { key: string; action: string; body: api.Evaluation | api.Command };
export function DigitalQc({ requestId, scanId, onDirty, onClean, onPending, onExpired, onViewer }: { onViewer: () => void; requestId: string; scanId: string; onDirty: () => void; onClean: () => void; onPending: (v: boolean) => void; onExpired: () => void }) {
 const [view, setView] = useState<api.View>(); const [history, setHistory] = useState<api.Assessment[]>([]); const [coverage, setCoverage] = useState<api.Result>('UNKNOWN'); const [focus, setFocus] = useState<api.Result>('UNKNOWN'); const [missing, setMissing] = useState<api.Result>('UNKNOWN'); const [percent, setPercent] = useState(''); const [tiles, setTiles] = useState(''); const [regions, setRegions] = useState(''); const [note, setNote] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [pending, setPending] = useState(false); const [discard, setDiscard] = useState(false);
 const locked = useRef(false); const active = useRef<AbortController | undefined>(undefined); const intent = useRef<Intent | undefined>(undefined); const expired = useRef(onExpired); expired.current = onExpired;
 useEffect(() => { const c = new AbortController(); active.current = c; locked.current = true; setBusy(true); void api.load(requestId, scanId, c.signal).then(v => { if (!c.signal.aborted) setView(v); }).catch(e => { if (!c.signal.aborted) { setError(e instanceof Error ? e.message : 'QC读取失败'); if (e instanceof ApiError && e.status === 401) expired.current(); } }).finally(() => { if (!c.signal.aborted) { locked.current = false; setBusy(false); } }); return () => { c.abort(); active.current?.abort(); }; }, [requestId, scanId]);
 function reset() { setCoverage('UNKNOWN'); setFocus('UNKNOWN'); setMissing('UNKNOWN'); setPercent(''); setTiles(''); setRegions(''); setNote(''); onClean(); }
 async function refresh(s: AbortSignal) { setView(undefined); setHistory([]); const v = await api.load(requestId, scanId, s); if (!s.aborted) setView(v); }
 async function run(work: (s: AbortSignal) => Promise<void>) { if (locked.current) return; locked.current = true; setBusy(true); setError(''); const c = new AbortController(); active.current = c; try { await work(c.signal); } catch (e) { if (!c.signal.aborted) { setError(e instanceof Error ? e.message : 'QC操作失败'); if (e instanceof ApiError && [401, 403, 404].includes(e.status)) { setView(undefined); setHistory([]); reset(); } if (e instanceof ApiError && e.status === 401) onExpired(); } } finally { if (active.current === c) { locked.current = false; setBusy(false); } } }
 async function send(s: AbortSignal) { const i = intent.current; if (!i) return; await api.post(requestId, scanId, i.action, i.body, i.key, s); if (s.aborted) return; intent.current = undefined; setPending(false); onPending(false); reset(); setNotice('服务器已记录；以重新读取的当前版本为准。没有生成图像或临床结论。'); await refresh(s); }
 function submit(action: '' | '/PUBLISH' | '/REVOKE') { if (!view || locked.current || pending) return; if (!note.trim()) { setError('必须填写人工备注或撤销原因。'); return; } let body: api.Evaluation | api.Command;
  if (!action) { let parsed: api.Region[] = []; try { if (regions.trim()) parsed = regions.split('\n').map(line => { const [x, y, width, height, ...rest] = line.split(','); const values = [x, y, width, height].map(Number); if ([x, y, width, height].some(v => !v?.trim()) || values.some(v => !Number.isSafeInteger(v)) || !rest.join(',').trim()) throw Error('区域格式：x,y,宽,高,人工备注，每行一区域'); return { x: values[0], y: values[1], width: values[2], height: values[3], note: rest.join(',') }; }); if (parsed.length > 20 || !percent.trim() || !tiles.trim() || !Number.isInteger(Number(percent)) || !Number.isInteger(Number(tiles)) || Number(percent) < 0 || Number(percent) > 100 || Number(tiles) < 0 || Number(tiles) > 1000000) throw Error('请填写有界覆盖百分比和缺失瓦片数量，不将空值当零。'); } catch (e) { setError(e instanceof Error ? e.message : '区域无效'); return; }
   body = { expectedVersion: view.version, scanVersion: view.scanVersion, objectId: view.objectId, slideId: view.slideId, objectHash: view.objectHash, checklist: 'SYN-DIGITAL-QC-1', coverage, focus, missing, coveragePercent: Number(percent), missingTiles: Number(tiles), regions: parsed, note };
  } else { if (!view.assessment) return; body = { expectedVersion: view.version, assessmentVersion: view.assessment.version, reason: note }; }
  intent.current = { key: crypto.randomUUID(), action, body }; setPending(true); onPending(true); onDirty(); void run(send);
 }
 const formChanged = coverage !== 'UNKNOWN' || focus !== 'UNKNOWN' || missing !== 'UNKNOWN' || !!percent || !!tiles || !!regions || !!note;
 const evaluationChanged = coverage !== 'UNKNOWN' || focus !== 'UNKNOWN' || missing !== 'UNKNOWN' || !!percent || !!tiles || !!regions;
 const choices = [{ value: 'UNKNOWN', label: '未评估 / UNKNOWN' }, { value: 'FAIL', label: '不通过 / FAIL' }, { value: 'PASS', label: '合成评价通过 / PASS' }];
 return <section aria-label="数字扫描QC"><Typography.Title level={2}>数字扫描质量检查</Typography.Title><Alert type="warning" title="仅人工合成测试评价；没有真实图像，仅显式合成RGB夹具支持阅片，真实WSI未支持。发布不证明真实WSI可用。" />
  {error && <Alert type="error" role="alert" title={error} />}{notice && <Alert type="info" role="status" title={notice} />}
  <p>申请 {requestId} / 扫描 {scanId}</p>{view && <><p>{view.currentScan ? '当前扫描' : '历史扫描：不可继续发布'} / 序列 {view.ordinal} / 扫描修订 {view.scanVersion} / QC版本 {view.version}</p><p>物理玻片 {view.slideId} / 原件 {view.objectId} / SHA-256 {view.objectHash}</p><Alert title={`${view.effectiveState} / ${view.invalidReason || '当前依赖有效'}`} type={view.effectiveState === 'ISOLATED' ? 'warning' : 'info'} /></>}
  <Space wrap><Button disabled={busy || pending || formChanged || view?.effectiveState !== 'PUBLISHED_SYNTHETIC_CONTRACT'} onClick={onViewer}>打开合成瓦片阅片器</Button><Button disabled={busy || formChanged || pending} onClick={() => void run(refresh)}>刷新QC与授权</Button><Button disabled={!busy} onClick={() => { active.current?.abort(); locked.current = false; setBusy(false); setNotice('仅停止等待；服务器可能已记录，请原键确认。'); }}>停止等待QC</Button><Button disabled={busy || !pending} onClick={() => void run(send)}>原键确认QC操作</Button><Button disabled={busy} onClick={() => setDiscard(true)}>取消本地QC输入</Button></Space>
  <fieldset disabled={busy || pending || !view}><legend>SYN-DIGITAL-QC-1 人工检查单</legend>
   <label>覆盖评价<Select virtual={false} aria-label="覆盖评价" disabled={busy || pending || !view} value={coverage} options={choices} onChange={v => { setCoverage(v); onDirty(); }} /></label><label>焦点评价<Select virtual={false} aria-label="焦点评价" disabled={busy || pending || !view} value={focus} options={choices} onChange={v => { setFocus(v); onDirty(); }} /></label><label>缺失区域评价<Select virtual={false} aria-label="缺失区域评价" disabled={busy || pending || !view} value={missing} options={choices} onChange={v => { setMissing(v); onDirty(); }} /></label>
   <label>覆盖百分比<Input aria-label="覆盖百分比" value={percent} maxLength={3} onChange={e => { setPercent(e.target.value); onDirty(); }} /></label><label>缺失瓦片数<Input aria-label="缺失瓦片数" value={tiles} maxLength={7} onChange={e => { setTiles(e.target.value); onDirty(); }} /></label>
   <label>合成缺陷区域<Input.TextArea aria-label="合成缺陷区域" placeholder="x,y,宽,高,备注；每行一区域，最多20个。合成头坐标，不是物理测量。" maxLength={5000} value={regions} onChange={e => { setRegions(e.target.value); onDirty(); }} /></label><label>QC人工备注或原因<Input.TextArea aria-label="QC人工备注或原因" maxLength={1000} value={note} onChange={e => { setNote(e.target.value); onDirty(); }} /></label>
   <Space><Button disabled={busy || pending || !view?.currentScan} onClick={() => submit('')}>追加人工评价</Button><Button disabled={busy || pending || evaluationChanged || view?.state !== 'EVALUATED' || !view.assessment?.passed || !!view.invalidReason} onClick={() => submit('/PUBLISH')}>发布合成契约版本</Button><Button disabled={busy || pending || evaluationChanged || !view || !['PUBLISHED', 'EVALUATED'].includes(view.state)} onClick={() => submit('/REVOKE')}>撤销QC并隔离</Button></Space>
  </fieldset>
  {view?.assessment && <p>当前评价 #{view.assessment.version}：覆盖 {view.assessment.coverage} / 焦点 {view.assessment.focus} / 缺失 {view.assessment.missing}；{view.assessment.note}；区域数 {view.assessment.regions.length}。未将历史输入自动填入新表单。</p>}
  <Button disabled={busy || !view} onClick={() => void run(async s => { setHistory([]); const rows = await api.history(requestId, scanId, s); if (!s.aborted) { if (rows.some(a => a.objectId !== view?.objectId || a.objectHash !== view?.objectHash || a.slideId !== view?.slideId)) throw Error('历史评价与当前扫描绑定不匹配'); setHistory(rows); } })}>读取不可变评价历史</Button>
  <Table<api.Assessment> rowKey="version" dataSource={history} pagination={{ pageSize: 10 }} columns={[{ title: '评价版本', dataIndex: 'version' }, { title: '确切原件', dataIndex: 'objectId' }, { title: '焦点', dataIndex: 'focus' }, { title: '人工备注', dataIndex: 'note' }, { title: '缺陷区域', render: (_, a) => a.regions.map(r => `${r.x},${r.y},${r.width},${r.height}: ${r.note}`).join('；') }]} />
  <Table<api.Event> rowKey="version" dataSource={view?.events ?? []} pagination={{ pageSize: 10 }} columns={[{ title: '动作版本', dataIndex: 'version' }, { title: '动作', dataIndex: 'action' }, { title: '评价依据版本', dataIndex: 'assessmentVersion' }, { title: '原因', dataIndex: 'reason' }, { title: '记录时间', dataIndex: 'occurredAt' }]} />
  <Modal title="清除本地QC输入？" open={discard} okText="清除并停止本地跟踪" cancelText="继续核对" onCancel={() => setDiscard(false)} onOk={() => { intent.current = undefined; setPending(false); onPending(false); reset(); setDiscard(false); setNotice('只清除本地输入；未撤销服务器操作，请刷新当前状态。'); }}><p>未确认操作可能已被服务器记录；清除不会撤销发布。</p></Modal>
 </section>;
}
