import { fetchCsrf, readJson, request } from '../../api';
export const names = { RECEIVE: '登记冰冻接收', PREPARE: '登记冰冻制备', CORRECT_TIME: '追加时间更正', QC_PASS: '人工合成QC通过', QC_FAIL: '人工合成QC失败', IDENTITY_MISMATCH: '登记身份隔离', DRAFT: '保存人工结果新修订', REVIEW: '独立人员合成复核', TRANSFER: '转交冰冻负责人', CLAIM: '领取转交冰冻', COMMUNICATE: '记录本地合成沟通', READBACK: '接收者记录合成回读', CONFIRM: '接收者记录合成确认', LINK_ROUTINE: '关联确切常规冻结版' };
export type Action = keyof typeof names;
export interface Head { id: string; materialId: string; containerId: string; site: string; version: number; ownerId: string; ownerActive: boolean; receivedId: string; preparedId: string | null; revisionId: string | null; reviewId: string | null; qcId: string | null; qcState: string; stage: string }
export interface Event { id: string; version: number; action: Action; actorId: string; targetUserId: string | null; resultId: string | null; relatedId: string | null; occurredAt: string; recordedAt: string; zoneId: string; offsetSeconds: number; reason: string; content: string; dependency: string | null; routineSignatureId: string | null; routineRevisionId: string | null; routineTemplateCode: string | null; routineTemplateVersion: number | null; comparison: string | null; communicationMethod: string | null }
export interface Detail { reviewToken: string | null; caseId: string; number: string; actorId: string; head: Head | null; gateReady: boolean; reviewValid: boolean; receivedAt: string | null; preparedAt: string | null; elapsedSeconds: number | null; sources: { id: string; site: string }[]; candidates: { id: string; name: string; record: boolean; review: boolean; qc: boolean }[]; page: number; events: Event[] }
export interface Command { caseId: string; action: Action; body: { reviewToken: string | null; confirmedCaseId: string; expectedVersion: number; occurredAt: string; zoneId: string; reason: string; containerId: string | null; site: string | null; resultId: string | null; relatedId: string | null; targetUserId: string | null; content: string; routineSignatureId: string | null; comparison: string | null } }
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('Invalid frozen response'); return v as Record<string, unknown>; }
function str(v: unknown, empty = false): string { if (typeof v !== 'string' || !empty && !v) throw new Error('Invalid frozen text'); return v; }
function nullable(v: unknown): string | null { return v === null ? null : str(v); }
function num(v: unknown, min = 0): number { if (typeof v !== 'number' || !Number.isSafeInteger(v) || v < min) throw new Error('Invalid frozen version'); return v; }
function bool(v: unknown): boolean { if (typeof v !== 'boolean') throw new Error('Invalid frozen flag'); return v; }
function list(v: unknown, max: number): unknown[] { if (!Array.isArray(v) || v.length > max) throw new Error('Invalid frozen list'); return v; }
function date(v: unknown): string { const s = str(v); if (!Number.isFinite(Date.parse(s)) || !/(Z|[+-]\d\d:\d\d)$/.test(s)) throw new Error('Invalid frozen instant'); return s; }
export function parseDetail(v: unknown, id: string, page: number): Detail {
 const d = obj(v); if (d.caseId !== id || d.page !== page) throw new Error('Mismatched frozen identity');
 let head: Head | null = null;
 if (d.head !== null) { const h = obj(d.head); if (!['RECEIVED', 'PREPARED', 'DRAFT', 'REVIEWED'].includes(str(h.stage))) throw new Error('Invalid frozen stage'); if (!['NOT_ASSESSED', 'PASS', 'FAIL', 'IDENTITY_MISMATCH'].includes(str(h.qcState))) throw new Error('Invalid frozen QC'); head = { id: str(h.id), materialId: str(h.materialId), containerId: str(h.containerId), site: str(h.site), version: num(h.version), ownerId: str(h.ownerId), ownerActive: bool(h.ownerActive), receivedId: str(h.receivedId), preparedId: nullable(h.preparedId), revisionId: nullable(h.revisionId), reviewId: nullable(h.reviewId), qcId: nullable(h.qcId), qcState: str(h.qcState), stage: str(h.stage) }; }
 const events = list(d.events, 20).map(v => { const e = obj(v), action = str(e.action); if (!Object.hasOwn(names, action)) throw new Error('Unknown frozen action'); if (['COMMUNICATE', 'READBACK', 'CONFIRM'].includes(action) ? e.communicationMethod !== 'LOCAL_SIMULATION' : e.communicationMethod !== null) throw new Error('Invalid frozen communication method'); const occurredAt = date(e.occurredAt), recordedAt = date(e.recordedAt); if (Date.parse(occurredAt) > Date.parse(recordedAt)) throw new Error('Future frozen event'); return { id: str(e.id), version: num(e.version), action: action as Action, actorId: str(e.actorId), targetUserId: nullable(e.targetUserId), resultId: nullable(e.resultId), relatedId: nullable(e.relatedId), occurredAt, recordedAt, zoneId: str(e.zoneId), offsetSeconds: num(e.offsetSeconds, -64800), reason: str(e.reason), content: str(e.content, true), dependency: nullable(e.dependency), routineSignatureId: nullable(e.routineSignatureId), routineRevisionId: nullable(e.routineRevisionId), routineTemplateCode: nullable(e.routineTemplateCode), routineTemplateVersion: e.routineTemplateVersion === null ? null : num(e.routineTemplateVersion, 1), comparison: nullable(e.comparison), communicationMethod: nullable(e.communicationMethod) }; });
 if (new Set(events.map(e => e.id)).size !== events.length || events.some((e, i) => !head || e.version > head.version || i > 0 && e.version >= events[i - 1].version)) throw new Error('Invalid frozen history');
 if (bool(d.reviewValid) && (!head?.reviewId || !head.revisionId || !head.ownerActive || head.qcState !== 'PASS' || !bool(d.gateReady))) throw new Error('Invalid frozen readiness');
 return { reviewToken: nullable(d.reviewToken), caseId: id, number: str(d.number), actorId: str(d.actorId), head, gateReady: bool(d.gateReady), reviewValid: bool(d.reviewValid), receivedAt: d.receivedAt === null ? null : date(d.receivedAt), preparedAt: d.preparedAt === null ? null : date(d.preparedAt), elapsedSeconds: d.elapsedSeconds === null ? null : num(d.elapsedSeconds), page, events, sources: list(d.sources, 100).map(v => { const s = obj(v); return { id: str(s.id), site: str(s.site) }; }), candidates: list(d.candidates, 100).map(v => { const c = obj(v); return { id: str(c.id), name: str(c.name), record: bool(c.record), review: bool(c.review), qc: bool(c.qc) }; }) };
}
const base = '/api/requests/frozen/cases/';
export async function load(id: string, page: number, signal: AbortSignal) { return parseDetail(await readJson(await request(base + id + '?page=' + page, { signal })), id, page); }
export async function cases(requestId: string, signal: AbortSignal) { return list(await readJson(await request('/api/requests/' + requestId + '/frozen-cases', { signal })), 100).map(v => { const c = obj(v); return { id: str(c.id), number: str(c.number) }; }); }
export async function send(c: Command, key: string) {
 const abort = new AbortController(), timer = setTimeout(() => abort.abort(), 15000);
 try { const csrf = await fetchCsrf(abort.signal); const result = obj(await readJson(await request(base + c.caseId + '/' + c.action, { method: 'POST', signal: abort.signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify(c.body) }))), r = obj(result.receipt); if (r.resourceType !== 'FROZEN_CASE' || r.resourceId !== c.caseId || r.status !== 200 || r.version !== c.body.expectedVersion + 1) throw new Error('Mismatched frozen receipt'); return true; } finally { clearTimeout(timer); }
}
