import { describe, expect, it } from 'vitest';
import { parseDetail } from './api';
const empty = { reviewToken: null, caseId: 'case-a', number: 'SYN-FROZEN', actorId: 'synthetic-user', head: null, gateReady: true, reviewValid: false, receivedAt: null, preparedAt: null, elapsedSeconds: null, page: 1, sources: [], candidates: [], events: [] };
const head = { id: 'frozen', materialId: 'material', containerId: 'source', site: 'Synthetic', version: 3, ownerId: 'owner', ownerActive: true, receivedId: 'receive', preparedId: 'prepare', revisionId: 'draft', reviewId: null, qcId: 'qc', qcState: 'PASS', stage: 'DRAFT' };
const event = { id: 'e1', version: 3, action: 'DRAFT', actorId: 'synthetic-user', targetUserId: null, resultId: 'e1', relatedId: null, occurredAt: '2026-01-01T08:00:00Z', recordedAt: '2026-01-01T09:00:00Z', zoneId: 'UTC', offsetSeconds: 0, reason: 'Synthetic late entry', content: 'Synthetic manually entered text', dependency: null, routineSignatureId: null, routineRevisionId: null, routineTemplateCode: null, routineTemplateVersion: null, comparison: null, communicationMethod: null };
describe('frozen strict response boundaries', () => {
 it('permits an explicit unregistered independent workflow', () => { expect(parseDetail(empty, 'case-a', 1).head).toBeNull(); });
 it('rejects another case or historical page', () => { expect(() => parseDetail(empty, 'case-b', 1)).toThrow(); expect(() => parseDetail(empty, 'case-a', 2)).toThrow(); });
 it('retains occurrence, recording time and original manual text', () => { const d = parseDetail({ ...empty, head, events: [event], elapsedSeconds: 60 }, 'case-a', 1); expect(d.events[0].occurredAt).not.toBe(d.events[0].recordedAt); expect(d.events[0].content).toBe(event.content); expect(d.elapsedSeconds).toBe(60); });
 it('rejects invented stages, future occurrence and unbounded history', () => { for (const events of [[{ ...event, action: 'DELIVERED' }], [{ ...event, action: 'toString' }], [{ ...event, occurredAt: '2026-01-02T00:00:00Z' }], Array.from({ length: 21 }, () => event)]) expect(() => parseDetail({ ...empty, head, events }, 'case-a', 1)).toThrow(); });
 it('rejects unordered, duplicate or future revisions', () => { for (const events of [[event, event], [{ ...event, version: 4 }], [{ ...event, version: 1 }, { ...event, id: 'second', version: 2 }]]) expect(() => parseDetail({ ...empty, head, events }, 'case-a', 1)).toThrow(); });
 it('never infers review readiness or conflates separate communication steps', () => { expect(() => parseDetail({ ...empty, head, reviewValid: true }, 'case-a', 1)).toThrow(); const d = parseDetail({ ...empty, head, events: [{ ...event, action: 'READBACK', communicationMethod: 'LOCAL_SIMULATION', relatedId: 'communication' }] }, 'case-a', 1); expect(d.events[0].action).toBe('READBACK'); expect(d.events.some(e => e.action === 'CONFIRM')).toBe(false); });
});
