package com.pis.storage;
import com.pis.accession.WorkflowAccess;import com.pis.audit.*;import com.pis.api.ApiException;import com.pis.idempotency.*;
import java.io.*;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.http.HttpStatus;import org.springframework.transaction.support.TransactionTemplate;import org.springframework.transaction.PlatformTransactionManager;import jakarta.validation.Validator;
import static com.pis.storage.StorageContracts.*;
@Service
public class StorageService {
 private final JdbcTemplate jdbc;private final WorkflowAccess access;private final IdempotentCommands commands;private final AuditRecorder audit;private final StorageProvider provider;private final Validator validator;private final TransactionTemplate tx;
 public StorageService(JdbcTemplate jdbc,WorkflowAccess access,IdempotentCommands commands,AuditRecorder audit,StorageProvider provider,Validator validator,PlatformTransactionManager manager){this.jdbc=jdbc;this.access=access;this.commands=commands;this.audit=audit;this.provider=provider;this.validator=validator;tx=new TransactionTemplate(manager);tx.setTimeout(10);}
 private record Context(UUID request,UUID caseId,UUID hospital,UUID scope,UUID actor){}
 private Context context(UUID request,boolean write,boolean capacity){
  try{var actor=access.actor();var rows=jdbc.query("SELECT c.id,c.hospital_id,w.scope_id,w.state FROM pathology_case c JOIN request_workflow w ON w.request_id=c.request_id WHERE c.request_id=?",(r,i)->new Context(request,r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class),actor.id()),request);if(rows.isEmpty())throw missing();var c=rows.getFirst();access.require(c.scope(),WorkflowAccess.Permission.READ);
   if(org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive()){jdbc.queryForList("SELECT id FROM pathology_request WHERE id=? FOR SHARE",request);jdbc.queryForList("SELECT user_id FROM storage_grant WHERE user_id=? AND scope_id=? FOR SHARE",c.actor(),c.scope());jdbc.queryForList("SELECT user_id FROM storage_case_grant WHERE user_id=? AND case_id=? FOR SHARE",c.actor(),c.caseId());}
   if(jdbc.queryForObject("SELECT count(*) FROM storage_grant g WHERE user_id=? AND scope_id=? AND revoked_at IS NULL AND valid_until>statement_timestamp() AND (NOT ? OR can_write) AND (NOT ? OR can_capacity) AND (all_cases OR EXISTS(SELECT 1 FROM storage_case_grant cg JOIN pathology_case c ON c.id=cg.case_id JOIN request_workflow w ON w.request_id=c.request_id WHERE cg.user_id=g.user_id AND cg.scope_id=g.scope_id AND w.scope_id=g.scope_id AND cg.case_id=? AND cg.revoked_at IS NULL AND cg.valid_until>statement_timestamp()))",Long.class,c.actor(),c.scope(),write,capacity,c.caseId())!=1)throw missing();
   if(!"RECEIVED".equals(jdbc.queryForObject("SELECT state FROM request_workflow WHERE request_id=?",String.class,request))||jdbc.queryForObject("SELECT count(*) FROM quality_head WHERE request_id=? AND state='IDENTITY_MISMATCH'",Long.class,request)>0||jdbc.queryForObject("SELECT count(*) FROM cytology_specimen WHERE request_id=? AND qc_state='IDENTITY_MISMATCH'",Long.class,request)>0||jdbc.queryForObject("SELECT count(*) FROM frozen_case WHERE request_id=? AND qc_state='IDENTITY_MISMATCH'",Long.class,request)>0)throw conflict("STORAGE_ISOLATED");return c;
  }catch(org.springframework.security.access.AccessDeniedException e){throw missing();}
 }
 private void validate(Object value){var errors=validator.validate(value);if(!errors.isEmpty())throw new jakarta.validation.ConstraintViolationException(errors);}
 private void configured(){if(!provider.state().equals("CONFIGURED_LOCAL"))throw problem(HttpStatus.SERVICE_UNAVAILABLE,"STORAGE_NOT_CONFIGURED");}
 private static final org.springframework.jdbc.core.RowMapper<Version> MAPPER=(r,i)->new Version(r.getObject("id",UUID.class),r.getObject("asset_id",UUID.class),r.getObject("case_id",UUID.class),r.getObject("root_id",UUID.class),r.getLong("ordinal"),r.getLong("version"),r.getString("state"),r.getLong("byte_size"),r.getString("sha256"),r.getString("purpose"),r.getObject("created_at",OffsetDateTime.class).toInstant());
 private Version version(UUID request,UUID id){var rows=jdbc.query("SELECT * FROM storage_version WHERE id=? AND request_id=? AND root_id=?",MAPPER,id,request,provider.rootId());if(rows.isEmpty())throw missing();return rows.getFirst();}
 private void event(Context c,UUID id,long v,String action){jdbc.update("INSERT INTO storage_event(version_id,version,action,actor_id) VALUES(?,?,?,?)",id,v,action,c.actor());}
 private void transition(Context c,Version v,String state){if(jdbc.update("UPDATE storage_version SET state=?,version=version+1 WHERE id=? AND version=? AND state=?",state,v.id(),v.version(),v.state())!=1)throw conflict("VERSION_CONFLICT");event(c,v.id(),v.version()+1,state);audit.append(c.hospital(),"STORAGE_"+state+"_V1","STORAGE_VERSION",v.id(),v.version(),v.version()+1);}
 public View list(UUID request,int page){return tx.execute(s->{var c=context(request,false,false);if(page<1||page>50)throw problem(HttpStatus.BAD_REQUEST,"STORAGE_PAGE");var items=jdbc.query("SELECT * FROM storage_version WHERE request_id=? AND purpose='SYNTHETIC_ORIGINAL' ORDER BY created_at DESC,id LIMIT 20 OFFSET ?",MAPPER,request,(page-1)*20);audit.append(c.hospital(),"STORAGE_LIST_V1","PATHOLOGY_REQUEST",request,null,0);return new View(request,c.caseId(),provider.state(),provider.rootId(),new S3StorageContract().state(),page,items);});}
 public IdempotentCommands.Result reserve(UUID request,Reserve input,String key){if(!"SYNTHETIC_ORIGINAL".equals(input.purpose()))throw problem(HttpStatus.BAD_REQUEST,"STORAGE_PURPOSE");return reserveChecked(request,input,key);}
 public IdempotentCommands.Result reserveWorkerArtifact(UUID request,Reserve input,String key){validate(input);if(!"SYNTHETIC_WORKER_ARTIFACT".equals(input.purpose())||input.byteSize()>4096)throw problem(HttpStatus.BAD_REQUEST,"STORAGE_PURPOSE");return reserveChecked(request,input,key);}
 private IdempotentCommands.Result reserveChecked(UUID request,Reserve input,String key){validate(input);configured();var initial=context(request,true,false);if(!initial.caseId().equals(input.confirmedCaseId()))throw conflict("STORAGE_IDENTITY");return commands.execute(initial.hospital(),"STORAGE_RESERVE_V1",key,Map.of("request",request,"input",input),new IdempotentCommands.Work(){
  public void authorize(CurrentActor.Actor a){context(request,true,false);}public void authorizeReplay(CurrentActor.Actor a,CommandReceipt r){authorize(a);version(request,r.resourceId());}
  public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){var c=context(request,true,false);jdbc.update("INSERT INTO storage_quota(hospital_id) VALUES(?) ON CONFLICT DO NOTHING",c.hospital());if(jdbc.update("UPDATE storage_quota SET reserved_bytes=reserved_bytes+? WHERE hospital_id=? AND reserved_bytes+?<=?",input.byteSize()*2,c.hospital(),input.byteSize()*2,StoragePolicy.QUOTA)!=1)throw conflict("STORAGE_QUOTA");
   if(jdbc.queryForObject("SELECT count(*) FROM storage_version WHERE request_id=?",Long.class,request)>=1000)throw conflict("STORAGE_QUOTA");UUID asset=input.assetId();if(asset==null){if(input.expectedHead()!=-1)throw conflict("VERSION_CONFLICT");asset=UUID.randomUUID();jdbc.update("INSERT INTO storage_asset(id,hospital_id,request_id,case_id,scope_id) VALUES(?,?,?,?,?)",asset,c.hospital(),request,c.caseId(),c.scope());}else if(jdbc.queryForObject("SELECT count(*) FROM storage_asset WHERE id=? AND request_id=?",Long.class,asset,request)!=1)throw missing();
   if(jdbc.update("UPDATE storage_asset SET head=head+1 WHERE id=? AND request_id=? AND head=?",asset,request,input.expectedHead())!=1)throw conflict("VERSION_CONFLICT");UUID id=UUID.randomUUID();jdbc.update("INSERT INTO storage_version(id,asset_id,hospital_id,request_id,case_id,scope_id,ordinal,root_id,purpose,media_type,byte_size,sha256,actor_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",id,asset,c.hospital(),request,c.caseId(),c.scope(),input.expectedHead()+1,provider.rootId(),input.purpose(),input.mediaType(),input.byteSize(),input.sha256(),c.actor());event(c,id,0,"RESERVED");return new IdempotentCommands.Mutation(new CommandReceipt(201,"STORAGE_VERSION",id,0),null);}
 });}
 public Version upload(UUID request,UUID id,long expected,long length,InputStream input){configured();Version v=tx.execute(s->{var c=context(request,true,false);var old=version(request,id);if(old.version()!=expected||!old.state().equals("RESERVED"))throw conflict("VERSION_CONFLICT");if(old.byteSize()!=length)throw problem(HttpStatus.BAD_REQUEST,"STORAGE_SIZE");transition(c,old,"UPLOADING");return version(request,id);});
  try{provider.stage(id,input,v.byteSize(),v.sha256());}catch(IOException e){tx.executeWithoutResult(s->{var c=context(request,true,false);var old=version(request,id);if(old.state().equals("UPLOADING"))transition(c,old,"FAILED");});throw failure(e);}
  return tx.execute(s->{var c=context(request,true,false);var old=version(request,id);if(!old.state().equals("UPLOADING")||old.version()!=v.version())throw conflict("VERSION_CONFLICT");transition(c,old,"STAGED");return version(request,id);});
 }
 public Version finish(UUID request,UUID id,Command input,String key){validate(input);configured();var initial=context(request,true,false);if(!initial.caseId().equals(input.confirmedCaseId()))throw conflict("STORAGE_IDENTITY");commands.execute(initial.hospital(),"STORAGE_FINALIZE_V1",key,Map.of("request",request,"id",id,"input",input),new IdempotentCommands.Work(){
  public void authorize(CurrentActor.Actor a){context(request,true,false);version(request,id);}public void authorizeReplay(CurrentActor.Actor a,CommandReceipt r){authorize(a);}
  public IdempotentCommands.Mutation mutate(CurrentActor.Actor a){var c=context(request,true,false);var old=version(request,id);if(old.version()!=input.expectedVersion()||!old.state().equals("STAGED"))throw conflict("VERSION_CONFLICT");transition(c,old,"FINALIZING");jdbc.update("INSERT INTO storage_finalize(version_id,state) VALUES(?,'PENDING')",id);return new IdempotentCommands.Mutation(new CommandReceipt(200,"STORAGE_VERSION",id,old.version()+1),old.version());}
 });return recoverFinal(request,id);}
 private Version recoverFinal(UUID request,UUID id){var before=tx.execute(s->{context(request,true,false);return version(request,id);});if(!List.of("FINALIZING","READY").contains(before.state()))throw conflict("STORAGE_STATE");try{provider.publish(id,before.byteSize(),before.sha256());}catch(IOException e){throw failure(e);}
  return tx.execute(s->{var c=context(request,true,false);var old=version(request,id);if(old.state().equals("FINALIZING")){transition(c,old,"READY");if(jdbc.update("UPDATE storage_finalize SET state='DONE' WHERE version_id=? AND state='PENDING'",id)!=1)throw conflict("STORAGE_STATE");}else if(!old.state().equals("READY"))throw conflict("STORAGE_STATE");else audit.append(c.hospital(),"STORAGE_FINALIZE_REPLAY_V1","STORAGE_VERSION",id,null,old.version());return version(request,id);});
 }
 public Version reconcile(UUID request,UUID id){configured();var old=tx.execute(s->{context(request,true,false);return version(request,id);});if(List.of("READY","FINALIZING").contains(old.state()))return recoverFinal(request,id);if(!old.state().equals("UPLOADING"))throw conflict("STORAGE_STATE");boolean valid;try{provider.verifyStage(id,old.byteSize(),old.sha256());valid=true;}catch(IOException e){valid=false;}final boolean good=valid;return tx.execute(s->{var c=context(request,true,false);var current=version(request,id);if(current.version()!=old.version()||!current.state().equals("UPLOADING"))throw conflict("VERSION_CONFLICT");transition(c,current,good?"STAGED":"FAILED");return version(request,id);});}
 public StorageProvider.Slice bytes(UUID request,UUID id,String range,String purpose){return readBytes(request,id,range,purpose,false);}
 public StorageProvider.Slice workerArtifactBytes(UUID request,UUID id){return readBytes(request,id,null,"DOWNLOAD",true);}
 private StorageProvider.Slice readBytes(UUID request,UUID id,String range,String purpose,boolean worker){configured();if(!List.of("PREVIEW","DOWNLOAD").contains(purpose))throw problem(HttpStatus.BAD_REQUEST,"STORAGE_PURPOSE");var before=tx.execute(s->{var c=context(request,false,false);var v=version(request,id);if(worker!=v.purpose().equals("SYNTHETIC_WORKER_ARTIFACT"))throw problem(HttpStatus.NOT_FOUND,"STORAGE_NOT_FOUND");if(!v.state().equals("READY"))throw conflict("STORAGE_STATE");try{budget(c,StoragePolicy.range(range,v.byteSize()).length(),id,v.version());}catch(IOException e){throw failure(e);}return v;});StorageProvider.Slice data;try{data=provider.read(id,before.byteSize(),before.sha256(),range);}catch(IOException e){throw failure(e);}
  tx.executeWithoutResult(s->{var c=context(request,false,false);var v=version(request,id);if(!v.state().equals("READY")||v.version()!=before.version())throw conflict("VERSION_CONFLICT");audit.append(c.hospital(),"STORAGE_"+purpose+"_V1","STORAGE_VERSION",id,null,v.version());});return data;
 }
 public Version detail(UUID request,UUID id){return tx.execute(s->{var c=context(request,false,false);var v=version(request,id);audit.append(c.hospital(),"STORAGE_DETAIL_V1","STORAGE_VERSION",id,null,v.version());return v;});}
 private void budget(Context c,int length,UUID id,long version){var minute=OffsetDateTime.now(ZoneOffset.UTC).truncatedTo(java.time.temporal.ChronoUnit.MINUTES);jdbc.update("INSERT INTO storage_read_budget(user_id,minute,requests,bytes) VALUES(?,?,0,0) ON CONFLICT DO NOTHING",c.actor(),minute);if(jdbc.update("UPDATE storage_read_budget SET requests=requests+1,bytes=bytes+? WHERE user_id=? AND minute=? AND requests<60 AND bytes+?<=33554432",length,c.actor(),minute,length)!=1)throw problem(HttpStatus.TOO_MANY_REQUESTS,"STORAGE_RATE");audit.append(c.hospital(),"STORAGE_READ_ATTEMPT_V1","STORAGE_VERSION",id,null,version);}
 public Capacity capacity(UUID request){return tx.execute(s->{var c=context(request,false,true);try{var v=provider.capacity();var total=jdbc.queryForList("SELECT reserved_bytes FROM storage_quota WHERE hospital_id=?",Long.class,c.hospital());audit.append(c.hospital(),"STORAGE_CAPACITY_V1","PATHOLOGY_REQUEST",request,null,0);return new Capacity(v.state(),v.volumeTotal(),v.volumeUsable(),total.isEmpty()?0:total.getFirst(),StoragePolicy.QUOTA,v.rootId()==null?null:Instant.now());}catch(IOException e){throw failure(e);}});}
 public Cleanup cleanup(UUID request){return tx.execute(s->{var c=context(request,true,true);var candidates=new ArrayList<UUID>();for(var id:jdbc.queryForList("SELECT id FROM storage_version WHERE request_id=? AND actor_id=? AND root_id=? AND state='FAILED' ORDER BY id LIMIT 100",UUID.class,request,c.actor(),provider.rootId())){try{if(provider.hasStage(id))candidates.add(id);}catch(IOException e){throw failure(e);}}audit.append(c.hospital(),"STORAGE_CLEANUP_DRY_RUN_V1","PATHOLOGY_REQUEST",request,null,0);return new Cleanup(request,List.copyOf(candidates),true,"NO_FILES_DELETED");});}
 private static ApiException failure(IOException e){String code=e instanceof StorageProvider.Failure f?f.code:"STORAGE_IO";return problem(code.equals("STORAGE_RANGE")?HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE:code.equals("STORAGE_BUSY")?HttpStatus.TOO_MANY_REQUESTS:HttpStatus.CONFLICT,code);}
 private static ApiException missing(){return problem(HttpStatus.NOT_FOUND,"STORAGE_NOT_FOUND");}private static ApiException conflict(String code){return problem(HttpStatus.CONFLICT,code);}private static ApiException problem(HttpStatus status,String code){return new ApiException(status,code,"Synthetic storage operation unavailable; verify the authorized version");}
}
