import { useEffect,useRef,useState,useSyncExternalStore } from 'react';
import { Alert,Button,Card,Form,Input,InputNumber,Modal,Table } from 'antd';
import { ApiError } from '../../api';
import { ReadController } from '../../shared/workflow';
import { ReadPanel } from '../../shared/WorkflowElements';
import { CommandIntent } from '../../shared/command';
import { actions,command,history,load,send,type Action,type Adapter,type Intent,type Item,type View } from './api';
type Props={requestId:string;onDirty:()=>void;onClean:()=>void;onPending:(v:boolean)=>void;onExpired:()=>void};
export function Adapters(props:Props){const [page,setPage]=useState(1),[selected,setSelected]=useState<Item>(),[generation,setGeneration]=useState(0),[dirty,setDirty]=useState(false),[pending,setPending]=useState(false),[leaving,setLeaving]=useState(false);const next=useRef<(()=>void)|undefined>(undefined);
 const [reader]=useState(()=>new ReadController(async(p:number,signal:AbortSignal)=>{try{return {status:'ready' as const,data:await load(props.requestId,p,signal)};}catch(e){if(e instanceof ApiError&&e.status===401)props.onExpired();throw e;}}));const state=useSyncExternalStore(reader.subscribe,reader.getSnapshot);useEffect(()=>{void reader.run(page);return reader.stop;},[reader,page]);
 function change(f:()=>void){if(pending)return;if(dirty){next.current=f;setLeaving(true);}else f();}
 function refresh(){setSelected(undefined);setGeneration(v=>v+1);setDirty(false);props.onClean();void reader.run(page);}
 return <><Alert type="warning" title="本地合成接口 · 非医院联通" description="SYN-HOSPITAL-1 自定义契约；HIS仅观察身份关联，收费仅登记模拟请求，不代表支付。设备仅记录观察，不触发临床动作。EMR使用原本地投递与回执页面。厂商、HL7、FHIR均未配置。"/><Button disabled={pending} onClick={()=>change(refresh)}>刷新接口队列</Button><ReadPanel state={state}>{d=><><p>来源 {d.sourceId} · 病例 {d.caseId}</p><Table rowKey="id" dataSource={d.items} pagination={false} scroll={{x:1000}} columns={[{title:'来源关联ID',dataIndex:'externalId'},{title:'适配器',dataIndex:'adapter'},{title:'序号',dataIndex:'sequence'},{title:'状态',dataIndex:'state'},{title:'次数',dataIndex:'attempts'},{title:'失败原因',dataIndex:'errorCode'},{title:'退避截止',dataIndex:'nextAt'},{title:'本地记录',render:(_,i)=>i.locallyRecorded?'已记录（非送达/支付）':'尚无记录'},{title:'操作',render:(_,i)=><Button disabled={pending} onClick={()=>change(()=>{setSelected(i);setGeneration(v=>v+1);})}>处理消息 {i.id}</Button>}]} />
 <Button disabled={pending||page===1} onClick={()=>change(()=>{setSelected(undefined);setPage(p=>p-1);})}>上一页接口</Button><Button disabled={pending||page>=50||d.items.length<20} onClick={()=>change(()=>{setSelected(undefined);setPage(p=>p+1);})}>下一页接口</Button><Button disabled={pending} onClick={()=>change(()=>{setSelected(undefined);setGeneration(v=>v+1);})}>新建合成接口消息</Button>
 <AdapterForm key={generation+':'+(selected?.id??'new')} {...props} view={d} item={selected} onDirty={()=>{setDirty(true);props.onDirty();}} onPending={v=>{setPending(v);props.onPending(v);}} onSaved={refresh}/>{selected&&<AdapterHistory key={selected.id} requestId={props.requestId} id={selected.id}/>}</>}</ReadPanel>
 <Modal open={leaving} title="清除未保存的接口输入？" okText="清除并切换接口" cancelText="继续编辑接口" onCancel={()=>{next.current=undefined;setLeaving(false);}} onOk={()=>{const f=next.current;next.current=undefined;setLeaving(false);setDirty(false);props.onClean();f?.();}}><p>不会撤销已持久化的本地记录。</p></Modal></>;
}
function AdapterForm({view,item,onSaved,...props}:Props&{view:View;item?:Item;onSaved:()=>void}){const [adapter,setAdapter]=useState<Adapter>('HIS'),[action,setAction]=useState<Action>('CLAIM'),[confirmation,setConfirmation]=useState<Intent>(),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[message,setMessage]=useState('');const [form]=Form.useForm();const active=useRef(false),alive=useRef(true),sequence=useRef(0),abort=useRef<AbortController|undefined>(undefined),original=useRef<Intent|undefined>(undefined);const [intent]=useState(()=>new CommandIntent<Intent>());useEffect(()=>{alive.current=true;return()=>{alive.current=false;abort.current?.abort();};},[]);
 async function execute(c:Intent){if(active.current)return;const turn=++sequence.current;active.current=true;original.current=c;setBusy(true);props.onPending(true);setMessage('');const controller=new AbortController();abort.current=controller;const timeout=setTimeout(()=>controller.abort(),15000);try{const result=await intent.run(c,(v,k)=>send(v,k,controller.signal));if(!alive.current||turn!==sequence.current)return;if(result){setUncertain(false);props.onPending(false);props.onClean();onSaved();}}catch(e){if(!alive.current||turn!==sequence.current)return;if(e instanceof ApiError&&e.status===401)props.onExpired();const definite=e instanceof ApiError&&([400,403,404,413].includes(e.status)||e.status===409&&!['COMMAND_BUSY','HTTP_ERROR'].includes(e.code));if(definite){intent.rejected();props.onPending(false);}setUncertain(!definite);setMessage(definite?e.message:'结果待确认：取消等待不会取消服务端操作；使用原键确认，不重复建消息。');}finally{clearTimeout(timeout);active.current=false;if(alive.current&&turn===sequence.current)setBusy(false);}}
 return <Card title={item?'本地消息人工操作':'登记合成合同消息'}>{item&&<p style={{overflowWrap:'anywhere'}}>消息 {item.id} · v{item.version} · {item.state} · SHA256 {item.payloadHash}</p>}{message&&<Alert role="alert" title={message}/>}<Button disabled={!busy} onClick={()=>abort.current?.abort()}>取消接口等待</Button>{uncertain&&<Button disabled={busy} onClick={()=>{if(original.current)void execute(original.current);}}>原键确认接口操作</Button>}
 <Form form={form} layout="vertical" disabled={busy||uncertain} onValuesChange={props.onDirty} onFinish={(v:{confirmedId:string;externalId:string;code:string;sequence:number;materialId?:string;amountMinor?:number;reason:string})=>{setConfirmation(item?command(view,item,action,v.reason):{requestId:props.requestId,body:{confirmedCaseId:view.caseId,patientId:view.patientId,sourceId:view.sourceId,adapter,schema:'SYN-HOSPITAL-1',externalId:v.externalId,sequence:v.sequence,code:v.code,materialId:adapter==='DEVICE'?v.materialId:null,amountMinor:adapter==='BILLING'?v.amountMinor:null,note:v.reason}});}}>
 {item?<label>接口操作<select aria-label="接口操作" disabled={busy||uncertain} value={action} onChange={e=>{setAction(e.target.value as Action);props.onDirty();}}>{Object.entries(actions).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>:<><label>适配器路径<select aria-label="适配器路径" disabled={busy||uncertain} value={adapter} onChange={e=>{setAdapter(e.target.value as Adapter);form.resetFields(['materialId','amountMinor']);props.onDirty();}}>{['HIS','BILLING','DEVICE'].map(a=><option key={a}>{a}</option>)}</select></label>{[['externalId','合成来源关联ID'],['code','合成操作编码']].map(([name,label])=><Form.Item key={name} name={name} label={label} rules={[{required:true,pattern:/^SYN-[A-Za-z0-9_-]{1,60}$/}]}><Input maxLength={64}/></Form.Item>)}<Form.Item name="sequence" label="本地来源序号" rules={[{required:true,type:'number',min:1,max:1000}]}><InputNumber min={1} max={1000} precision={0}/></Form.Item>{adapter==='DEVICE'&&<Form.Item name="materialId" label="核对材料UUID" preserve={false} rules={[{required:true,pattern:/^[a-f0-9-]{36}$/}]}><Input maxLength={36}/></Form.Item>}{adapter==='BILLING'&&<Form.Item name="amountMinor" label="模拟金额最小单位（非支付）" preserve={false} rules={[{required:true,type:'number',min:0,max:1000000}]}><InputNumber min={0} max={1000000} precision={0}/></Form.Item>}</>}
 <Form.Item name="confirmedId" label="核对接口病例UUID" rules={[{validator:(_,v:unknown)=>v===view.caseId?Promise.resolve():Promise.reject(Error('病例UUID不匹配'))}]}><Input maxLength={36}/></Form.Item><Form.Item name="reason" label="接口操作原因" rules={[{required:true,whitespace:true},{max:500}]}><Input.TextArea maxLength={500}/></Form.Item><Button htmlType="submit" type="primary" disabled={busy||uncertain}>核对本地接口操作</Button></Form><Modal open={!!confirmation} title="确认合成接口操作" okText="确认仅本地合成操作" cancelText="返回修改接口" onCancel={()=>setConfirmation(undefined)} onOk={()=>{const c=confirmation;setConfirmation(undefined);if(c)void execute(c);}}><p>只操作精确病例及消息版本；本地记录不是医院签收、支付或设备执行。ACK仍须验证接收证据。</p></Modal></Card>;
}
function AdapterHistory({requestId,id}:{requestId:string;id:string}){const [reader]=useState(()=>new ReadController(async(_:null,signal:AbortSignal)=>({status:'ready' as const,data:await history(requestId,id,signal)})));const state=useSyncExternalStore(reader.subscribe,reader.getSnapshot);useEffect(()=>{void reader.run(null);return reader.stop;},[reader]);return <Card title="追加接口历史"><ReadPanel state={state}>{rows=><Table rowKey="version" dataSource={rows} pagination={false} columns={[{title:'版本',dataIndex:'version'},{title:'动作',dataIndex:'action'},{title:'状态',dataIndex:'state'},{title:'原因',dataIndex:'reason'},{title:'人员',dataIndex:'actorId'},{title:'时间',dataIndex:'createdAt'}]}/>}</ReadPanel></Card>;}
