import { fetchCsrf, readJson, request } from '../../api';
export const actions = { CLAIM:'领取本地尝试', RECEIVE:'本地接收记录', ACK:'核验业务回执', RECONCILE:'对账', TIMEOUT:'回收超时尝试', FAIL:'记录本地失败', POISON:'隔离死信', CANCEL:'取消后续处理', REPAIR:'人工复核顺序并重排' };
export type Action=keyof typeof actions;
export type Adapter='HIS'|'BILLING'|'DEVICE';
export interface Item {id:string;requestId:string;caseId:string;sourceId:string;adapter:Adapter;externalId:string;sequence:number;payloadHash:string;version:number;state:string;attempts:number;attemptId:string|null;leaseUntil:string|null;nextAt:string;errorCode:string;locallyRecorded:boolean}
export interface View {requestId:string;caseId:string;patientId:string;sourceId:string;page:number;items:Item[];capabilities:Record<string,string>}
export interface Intent {requestId:string;id?:string;action?:Action;body:Record<string,unknown>}
const obj=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('接口响应格式错误');return v as Record<string,unknown>;};
const text=(v:unknown):string=>{if(typeof v!=='string')throw Error('接口字段格式错误');return v;};
const num=(v:unknown):number=>{if(typeof v!=='number'||!Number.isSafeInteger(v)||v<0)throw Error('接口版本格式错误');return v;};
const uuid=(v:unknown)=>{const s=text(v);if(!/^[a-f0-9-]{36}$/.test(s))throw Error('接口身份格式错误');return s;};
const nullable=(v:unknown)=>v===null?null:text(v);
export function parseView(v:unknown,id:string):View {const d=obj(v);if(d.requestId!==id||!Array.isArray(d.items)||d.items.length>20)throw Error('接口申请不匹配');const capabilities=obj(d.capabilities);if(capabilities.HL7_FHIR!=='NOT_CONFIGURED'||capabilities.VENDOR_HIS_EMR_BILLING_DEVICE!=='NOT_CONFIGURED')throw Error('不支持的接口能力');return {requestId:id,caseId:uuid(d.caseId),patientId:uuid(d.patientId),sourceId:uuid(d.sourceId),page:num(d.page),capabilities:Object.fromEntries(Object.entries(capabilities).map(([k,v])=>[k,text(v)])),items:d.items.map(v=>{const i=obj(v);if(i.requestId!==id||i.caseId!==d.caseId||i.sourceId!==d.sourceId||!['HIS','BILLING','DEVICE'].includes(text(i.adapter))||!['QUEUED','ATTEMPTING','RETRY_WAIT','REJECTED','DEAD','CANCELLED','ACKED','RECONCILED'].includes(text(i.state))||num(i.attempts)>3||num(i.version)>99||typeof i.locallyRecorded!=='boolean'||!/^[a-f0-9]{64}$/.test(text(i.payloadHash))||(i.state==='ATTEMPTING')!==(i.leaseUntil!==null))throw Error('接口队列身份或状态不正确');return {id:uuid(i.id),requestId:id,caseId:uuid(i.caseId),sourceId:uuid(i.sourceId),adapter:i.adapter as Adapter,externalId:text(i.externalId),sequence:num(i.sequence),payloadHash:text(i.payloadHash),version:num(i.version),state:text(i.state),attempts:num(i.attempts),attemptId:nullable(i.attemptId),leaseUntil:nullable(i.leaseUntil),nextAt:text(i.nextAt),errorCode:text(i.errorCode),locallyRecorded:i.locallyRecorded};})};}
const base=(id:string)=>'/api/requests/'+encodeURIComponent(id)+'/adapters';
export async function load(id:string,page:number,signal:AbortSignal){return parseView(await readJson(await request(base(id)+'?page='+page,{signal})),id);}
export function command(view:View,item:Item,action:Action,reason:string):Intent {if(item.requestId!==view.requestId||item.caseId!==view.caseId||item.sourceId!==view.sourceId)throw Error('接口病例不匹配');return {requestId:view.requestId,id:item.id,action,body:{confirmedCaseId:view.caseId,sourceId:view.sourceId,payloadHash:item.payloadHash,expectedVersion:item.version,attemptId:action==='CLAIM'?null:item.attemptId,reason,confirmed:true}};}
export async function send(c:Intent,key:string,signal:AbortSignal){const csrf=await fetchCsrf(signal),d=obj(await readJson(await request(base(c.requestId)+(c.id?'/'+c.id+'/'+c.action:''),{method:'POST',signal,headers:{'Content-Type':'application/json',[csrf.headerName]:csrf.token,'Idempotency-Key':key},body:JSON.stringify(c.body)}))),r=obj(d.receipt);if(r.status!==200||r.resourceType!=='SYNTHETIC_ADAPTER_MESSAGE'||c.id&&r.resourceId!==c.id||c.id&&num(r.version)!==Number(c.body.expectedVersion)+1||typeof d.replayed!=='boolean')throw Error('接口回执不匹配');uuid(r.resourceId);return true;}
export interface Event {version:number;action:string;state:string;errorCode:string;actorId:string;reason:string;createdAt:string}
export async function history(requestId:string,id:string,signal:AbortSignal):Promise<Event[]>{const rows=await readJson(await request(base(requestId)+'/'+id+'/history',{signal}));if(!Array.isArray(rows)||rows.length>100)throw Error('接口历史超出范围');return rows.map(v=>{const e=obj(v);return {version:num(e.version),action:text(e.action),state:text(e.state),errorCode:text(e.errorCode),actorId:uuid(e.actorId),reason:text(e.reason),createdAt:text(e.createdAt)};});}
