import { fetchCsrf, readJson, request } from '../../api';
export interface Tile { level: number; x: number; y: number; width: number; height: number; sha256: string; size: number }
export interface Manifest { content: { hospitalId: string; requestId: string; scanId: string; slideId: string; objectId: string; objectHash: string; scanVersion: number; provider: string; width: number; height: number; tileSize: number; maxLevel: number; manifestHash: string; tiles: Tile[] }; publicationVersion: number; capability: string; calibration: string }
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) throw Error('阅片响应格式错误'); return v as Record<string, unknown>; }
function text(v: unknown): string { if (typeof v !== 'string' || !v) throw Error('阅片标识缺失'); return v; }
function number(v: unknown, min: number, max: number): number { if (typeof v !== 'number' || !Number.isSafeInteger(v) || v < min || v > max) throw Error('阅片尺寸或版本越界'); return v; }
function hash(v: unknown) { const s = text(v); if (!/^[a-f0-9]{64}$/.test(s)) throw Error('阅片摘要无效'); return s; }
export function parseManifest(value: unknown, rid: string, scan: string, pub: number): Manifest { const v = obj(value), c = obj(v.content); if (c.requestId !== rid || c.scanId !== scan || v.publicationVersion !== pub || v.capability !== 'SYNTHETIC_RGB_ONLY' || v.calibration !== 'UNAVAILABLE_NO_PHYSICAL_SCALE' || c.provider !== 'SYN-RGB-PYRAMID-1' || c.tileSize !== 128 || !Array.isArray(c.tiles) || c.tiles.length > 40) throw Error('阅片身份、能力或清单无效'); const width = number(c.width, 1, 512), height = number(c.height, 1, 512), max = number(c.maxLevel, 0, 9); if (max !== Math.ceil(Math.log2(Math.max(width, height)))) throw Error('金字塔层级无效'); const tiles = c.tiles.map(x => { const t = obj(x); return { level: number(t.level, 0, max), x: number(t.x, 0, 3), y: number(t.y, 0, 3), width: number(t.width, 1, 128), height: number(t.height, 1, 128), sha256: hash(t.sha256), size: number(t.size, 1, 100000) }; }); const expected: string[] = []; for (let l = 0; l <= max; l++) { const w = Math.ceil(width / 2 ** (max - l)), h = Math.ceil(height / 2 ** (max - l)); for (let y = 0; y < Math.ceil(h / 128); y++) for (let x = 0; x < Math.ceil(w / 128); x++) { const t = tiles.find(t => t.level === l && t.x === x && t.y === y); if (!t || t.width !== Math.min(128, w - 128 * x) || t.height !== Math.min(128, h - 128 * y)) throw Error('瓦片缺失或坐标无效'); expected.push(`${l}/${x}/${y}`); } } if (tiles.length !== expected.length) throw Error('瓦片重复或清单不完整'); return { content: { hospitalId: text(c.hospitalId), requestId: rid, scanId: scan, slideId: text(c.slideId), objectId: text(c.objectId), objectHash: hash(c.objectHash), scanVersion: number(c.scanVersion, 0, Number.MAX_SAFE_INTEGER), provider: text(c.provider), width, height, tileSize: 128, maxLevel: max, manifestHash: hash(c.manifestHash), tiles }, publicationVersion: pub, capability: text(v.capability), calibration: text(v.calibration) }; }
export const base = (rid: string, scan: string) => `/api/requests/${encodeURIComponent(rid)}/scans/${encodeURIComponent(scan)}/viewer`;
export async function publication(rid: string, scan: string, signal: AbortSignal): Promise<number> { const v = obj(await readJson(await request(`/api/requests/${encodeURIComponent(rid)}/scans/${encodeURIComponent(scan)}/digital-qc`, { signal }))); if (v.requestId !== rid || v.scanId !== scan || v.effectiveState !== 'PUBLISHED_SYNTHETIC_CONTRACT' || v.currentScan !== true || v.invalidReason !== '') throw Error('当前精确扫描没有有效QC发布资格'); return number(v.version, 0, 99); }
export async function load(rid: string, scan: string, pub: number, signal: AbortSignal) { return parseManifest(await readJson(await request(`${base(rid, scan)}?publicationVersion=${pub}`, { signal, cache: 'no-store' })), rid, scan, pub); }
export async function prepare(rid: string, scan: string, pub: number, key: string, signal: AbortSignal) { const csrf = await fetchCsrf(signal); const v = obj(await readJson(await request(base(rid, scan), { method: 'POST', signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify({ publicationVersion: pub }) }))); const r = obj(v.receipt); if (r.resourceId !== scan || r.resourceType !== 'VIEWER_MANIFEST' || r.version !== 0 || r.status !== 200) throw Error('清单回执不匹配'); }
export async function choices(rid: string, signal: AbortSignal): Promise<{ id: string; label: string }[]> { const v = obj(await readJson(await request(`/api/requests/${encodeURIComponent(rid)}/scans?page=1`, { signal }))); if (v.requestId !== rid || !Array.isArray(v.jobs) || v.jobs.length > 20) throw Error('扫描列表不匹配'); return v.jobs.map(x => { const j = obj(x); if (j.requestId !== rid) throw Error('扫描列表跨病例'); return { id: text(j.id), label: `${text(j.slideId)} / 扫描 ${number(j.ordinal, 0, 999)}` }; }); }
export async function binary(url: string, expected: Tile, signal: AbortSignal): Promise<Blob> { if (!url.startsWith('/api/requests/') || url.includes('://') || url.includes('..')) throw Error('非法瓦片地址'); const r = await request(url, { signal, cache: 'no-store' }); if (r.headers.get('Content-Type')?.split(';')[0] !== 'image/png' || Number(r.headers.get('Content-Length')) !== expected.size) throw Error('瓦片类型或大小不匹配'); const b = await r.arrayBuffer(); const bytes = new Uint8Array(b); if (bytes.length !== expected.size || bytes.length > 100000 || [137, 80, 78, 71, 13, 10, 26, 10].some((v, i) => bytes[i] !== v)) throw Error('瓦片PNG无效'); const digest = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', b)), x => x.toString(16).padStart(2, '0')).join(''); if (digest !== expected.sha256 || r.headers.get('X-Content-SHA256') !== digest) throw Error('瓦片摘要不匹配'); return new Blob([b], { type: 'image/png' }); }
