import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Alert,Button,Input,Select,Slider,Space} from 'antd';
import OpenSeadragon from 'openseadragon';
import type {Manifest} from './api';
import * as api from './result-api';
import {project,mirrorMatrix,type Matrix} from './roi-geometry';
export function ResultOverlay({manifest,viewer,host}:{manifest:Manifest;viewer:OpenSeadragon.Viewer;host:HTMLElement}){
 const [input,setInput]=useState(''),[id,setId]=useState(''),[round,setRound]=useState(0),[opacity,setOpacity]=useState(0.5),[blend,setBlend]=useState<'normal'|'multiply'>('normal'),[shown,setShown]=useState(true),[view,setView]=useState<{data:api.ResultMetadata;url:string;matrix:Matrix;clip:string;opacity:number;blend:string;shown:boolean}>(),[error,setError]=useState(''),[status,setStatus]=useState('未选择结果；未知不等于阴性');const clipId=useId(),stop=useRef<()=>void>(()=>{});
 useEffect(()=>{if(!id||!shown)return;const c=new AbortController();let url='',cached:{epoch:string;hash:string;blob:Blob}|undefined,busy=false,failed=false;const clear=()=>{setView(undefined);if(url){URL.revokeObjectURL(url);url='';}};const cancel=()=>{c.abort();clear();setStatus('叠加已取消并清空');};stop.current=cancel;
 const verify=async()=>{if(c.signal.aborted||busy||failed)return;busy=true;setView(undefined);setStatus('正在核验当前授权与合成产物');try{const signal=AbortSignal.any([c.signal,AbortSignal.timeout(10000)]);const data=await api.metadata(manifest,id,signal);const blob=cached?.epoch===data.epoch&&cached.hash===data.tileHash?cached.blob:await api.png(manifest,data,signal);cached={epoch:data.epoch,hash:data.tileHash,blob};signal.throwIfAborted();if(c.signal.aborted)return;const item=viewer.world.getItemAt(0);if(!item)throw Error('当前图像已关闭');const a=item.imageToViewerElementCoordinates(new OpenSeadragon.Point(0,0)),b=item.imageToViewerElementCoordinates(new OpenSeadragon.Point(1,0)),d=item.imageToViewerElementCoordinates(new OpenSeadragon.Point(0,1));const base:Matrix=[b.x-a.x,b.y-a.y,d.x-a.x,d.y-a.y,a.x,a.y];const matrix=viewer.viewport.getFlip()?mirrorMatrix(base,host.clientWidth):base;const crop=item.getClip(),rect=crop??{x:0,y:0,width:manifest.content.width,height:manifest.content.height};const clip=[{x:rect.x,y:rect.y},{x:rect.x+rect.width,y:rect.y},{x:rect.x+rect.width,y:rect.y+rect.height},{x:rect.x,y:rect.y+rect.height}].map(p=>{const q=project(p,matrix);return `${q.x},${q.y}`;}).join(' ');clear();url=URL.createObjectURL(blob);setView({data,url,matrix,clip,opacity,blend,shown});setError('');setStatus('合成强度叠加已核验 · 非诊断');}catch(e){if(!c.signal.aborted){failed=true;clear();setError(e instanceof Error?e.message:'叠加不可用');setStatus('失效或读取失败；叠加已清空');}}finally{busy=false;}};
 const changed=()=>{setView(undefined);void verify();};const events=['animation-finish','rotate','flip','resize'] as const;const hide=()=>setView(undefined);const item=viewer.world.getItemAt(0);item?.addHandler('clip-change',changed);viewer.addHandler('viewport-change',hide);events.forEach(e=>viewer.addHandler(e,changed));void verify();const timer=setInterval(()=>void verify(),5000);return()=>{c.abort();if(timer)clearInterval(timer);item?.removeHandler('clip-change',changed);viewer.removeHandler('viewport-change',hide);events.forEach(e=>viewer.removeHandler(e,changed));if(url)URL.revokeObjectURL(url);};
 },[manifest,viewer,host,id,round,opacity,blend,shown]);
 return <section aria-label="非诊断合成结果叠加"><Alert type="warning" title="仅已接受技术产物的合成视觉夹具；强度0–255不是疾病风险，不写入报告。"/><Input aria-label="精确合成结果ID" value={input} maxLength={36} onChange={e=>setInput(e.target.value)}/><Space><Button onClick={()=>{stop.current();setError('');setView(undefined);setId(input.trim());setRound(n=>n+1);}}>核验并加载合成叠加</Button><Button onClick={()=>{stop.current();setId('');}}>取消合成叠加</Button><Button onClick={()=>{stop.current();setView(undefined);setStatus(shown?'叠加已隐藏并清空；重新显示需核验':'正在核验当前授权与合成产物');setShown(v=>!v);}}>{shown?'隐藏合成叠加':'显示合成叠加'}</Button><Select virtual={false} aria-label="合成混合方式" value={blend} options={[{value:'normal',label:'正常混合'},{value:'multiply',label:'正片叠底'}]} onChange={setBlend}/></Space><label>合成透明度<Slider ariaLabelForHandle="合成透明度" min={0} max={1} step={0.1} value={opacity} onChange={setOpacity}/></label><p role="status">{status}；最多5秒重新核验已交付像素，变换和设置变化先隐藏再核验。</p>{error&&<Alert role="alert" type="error" title={error}/>} {view&&<details><summary>精确合成来源和版本</summary><pre>{JSON.stringify(view.data,null,2)}</pre></details>}
 {view&&shown&&view.opacity===opacity&&view.blend===blend&&view.shown===shown&&createPortal(<svg aria-label="实际合成强度图层" style={{position:'absolute',inset:0,width:'100%',height:'100%',pointerEvents:'none',mixBlendMode:blend,opacity}}><defs><clipPath id={clipId}><polygon points={view.clip}/></clipPath></defs><g clipPath={`url(#${clipId})`}><image onError={()=>{stop.current();setError('合成PNG解码失败；叠加已清空');}} href={view.url} width={manifest.content.width} height={manifest.content.height} preserveAspectRatio="none" transform={`matrix(${view.matrix.join(' ')})`}/>{view.data.regions.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.width} height={r.height} transform={`matrix(${view.matrix.join(' ')})`} fill="none" stroke="#fff" strokeWidth={2}/>)}</g></svg>,host)}
 </section>;
}
