export interface Point { x: number; y: number }
export type Kind = 'POINT' | 'RECTANGLE' | 'POLYGON';
export type Matrix = readonly [number, number, number, number, number, number];
export function project(p: Point, m: Matrix): Point { return { x: m[0] * p.x + m[2] * p.y + m[4], y: m[1] * p.x + m[3] * p.y + m[5] }; }
export function inverse(m: Matrix): Matrix { const d = m[0] * m[3] - m[1] * m[2]; if (!m.every(Number.isFinite) || Math.abs(d) < 1e-12) throw Error('不可逆视图变换'); return [m[3] / d, -m[1] / d, -m[2] / d, m[0] / d, (m[2] * m[5] - m[3] * m[4]) / d, (m[1] * m[4] - m[0] * m[5]) / d]; }
export function transform(rotation: number, flip: boolean, zoom: number, pan: Point, crop: { x: number; y: number; width: number; height: number }): Matrix { if (![rotation, zoom, pan.x, pan.y, crop.x, crop.y, crop.width, crop.height].every(Number.isFinite) || zoom <= 0 || crop.width <= 0 || crop.height <= 0) throw Error('无效视图变换'); const r = rotation * Math.PI / 180, f = flip ? -1 : 1, a = Math.cos(r) * zoom * f, b = Math.sin(r) * zoom * f, c = -Math.sin(r) * zoom, d = Math.cos(r) * zoom, x = crop.x + crop.width / 2, y = crop.y + crop.height / 2; return [a, b, c, d, pan.x - a * x - c * y, pan.y - b * x - d * y]; }
export function vertices(kind: Kind, p: Point[]): Point[] { if (kind !== 'RECTANGLE' || p.length !== 2) return p; return [p[0], { x: p[1].x, y: p[0].y }, p[1], { x: p[0].x, y: p[1].y }]; }
function cross(a: Point, b: Point, c: Point) { return (b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x); }
function on(a: Point, b: Point, c: Point) { return Math.abs(cross(a, b, c)) < 1e-9 && c.x >= Math.min(a.x, b.x) - 1e-9 && c.x <= Math.max(a.x, b.x) + 1e-9 && c.y >= Math.min(a.y, b.y) - 1e-9 && c.y <= Math.max(a.y, b.y) + 1e-9; }
export function area(p: Point[]) { return Math.abs(p.reduce((a, q, i) => a + q.x * p[(i + 1) % p.length].y - p[(i + 1) % p.length].x * q.y, 0) / 2); }
export function validate(kind: Kind, p: Point[], width: number, height: number) { if (p.length > 32 || (kind === 'POINT' && p.length !== 1) || (kind === 'RECTANGLE' && p.length !== 2) || (kind === 'POLYGON' && p.length < 3) || p.some(q => !Number.isFinite(q.x) || !Number.isFinite(q.y) || q.x < 0 || q.y < 0 || q.x > width || q.y > height) || new Set(p.map(q => `${q.x},${q.y}`)).size !== p.length) throw Error('ROI顶点数量、有限值或边界无效'); const v = vertices(kind, p); if (kind !== 'POINT' && area(v) < 1e-6) throw Error('ROI面积必须非零'); if (kind === 'POLYGON') for (let i = 0; i < p.length; i++) for (let j = i + 1; j < p.length; j++) { if (j === i + 1 || (i === 0 && j === p.length - 1)) continue; const a = p[i], b = p[(i + 1) % p.length], c = p[j], d = p[(j + 1) % p.length]; if ((cross(a, b, c) * cross(a, b, d) < 0 && cross(c, d, a) * cross(c, d, b) < 0) || on(a, b, c) || on(a, b, d) || on(c, d, a) || on(c, d, b)) throw Error('ROI多边形不能自交'); } }
export function measure(kind: Kind, p: Point[], calibration?: { mppX: number; mppY: number; version: number }) { if (calibration && (![calibration.mppX, calibration.mppY].every(x => Number.isFinite(x) && x > 0 && x <= 100) || !Number.isSafeInteger(calibration.version) || calibration.version < 0)) throw Error('无效校准'); const q = vertices(kind, p).map(v => ({ x: v.x * (calibration?.mppX ?? 1), y: v.y * (calibration?.mppY ?? 1) })); return { length: kind === 'POINT' ? 0 : q.reduce((s, a, i) => s + Math.hypot(a.x - q[(i + 1) % q.length].x, a.y - q[(i + 1) % q.length].y), 0), area: kind === 'POINT' ? 0 : area(q), unit: calibration ? '合成µm' : 'px' }; }

// OpenSeadragon pixelFromPoint includes rotation but not the viewport canvas flip.
export function mirrorMatrix(m: Matrix, viewportWidth: number): Matrix {
 if (!m.every(Number.isFinite) || !Number.isFinite(viewportWidth) || viewportWidth <= 0) throw Error('镜像变换无效');
 return [-m[0], m[1], -m[2], m[3], viewportWidth-m[4], m[5]];
}
