import { fetchCsrf, readJson, request } from '../../api';
import type { Manifest } from './api';
import { validate, type Kind, type Point } from './roi-geometry';
export interface Calibration { version: number; mppX: number; mppY: number; basis: string; reason: string; actorId: string }
export interface Revision { roiId: string; revision: number; collectionVersion: number; authorId: string; actorId: string; kind: Kind; points: Point[]; deleted: boolean; reason: string; calibrationVersion: number | null; measurement: { length: number; area: number; unit: string; calibrationVersion: number | null }; createdAt: string }
export interface View { requestId: string; scanId: string; manifestHash: string; version: number; actorId: string; calibration: Calibration | null; items: Revision[]; historyOnly: boolean }
export interface Save { publicationVersion: number; manifestHash: string; expectedVersion: number; roiId: string; expectedRevision: number; kind: Kind; points: Point[]; deleted: boolean; reason: string; calibrationVersion: number | null }
function obj(x: unknown): Record<string, unknown> { if (!x || typeof x !== 'object' || Array.isArray(x)) throw Error('ROI响应错误'); return x as Record<string, unknown>; }
function str(x: unknown): string { if (typeof x !== 'string' || !x) throw Error('ROI标识错误'); return x; }
function n(x: unknown, min = 0): number { if (typeof x !== 'number' || !Number.isFinite(x) || x < min) throw Error('ROI数值错误'); return x; }
function integer(x: unknown, min = 0): number { const v = n(x, min); if (!Number.isSafeInteger(v)) throw Error('ROI版本错误'); return v; }
export function parse(value: unknown, m: Manifest, history = false): View { const v = obj(value), c = m.content; if (v.requestId !== c.requestId || v.scanId !== c.scanId || v.manifestHash !== c.manifestHash || v.historyOnly !== history || !Array.isArray(v.items) || v.items.length > (history ? 100 : 50)) throw Error('ROI身份或版本绑定错误'); let calibration: Calibration | null = null; if (v.calibration !== null) { const k = obj(v.calibration); if (k.basis !== 'SYNTHETIC_TEST' || n(k.mppX) <= 0 || n(k.mppX) > 100 || n(k.mppY) <= 0 || n(k.mppY) > 100) throw Error('ROI校准错误'); calibration = { version: integer(k.version), mppX: n(k.mppX), mppY: n(k.mppY), basis: str(k.basis), reason: str(k.reason), actorId: str(k.actorId) }; } const items = v.items.map(x => { const r = obj(x); if (!['POINT', 'RECTANGLE', 'POLYGON'].includes(str(r.kind)) || !Array.isArray(r.points) || typeof r.deleted !== 'boolean') throw Error('ROI几何错误'); const kind = r.kind as Kind, points = r.points.map(q => { const p = obj(q); return { x: n(p.x), y: n(p.y) }; }); validate(kind, points, c.width, c.height); const measurement = obj(r.measurement), cv = r.calibrationVersion === null ? null : integer(r.calibrationVersion); if (measurement.calibrationVersion !== cv || measurement.unit !== (cv === null ? 'px' : 'SYNTHETIC_um')) throw Error('ROI测量绑定错误'); return { roiId: str(r.roiId), revision: integer(r.revision), collectionVersion: integer(r.collectionVersion), authorId: str(r.authorId), actorId: str(r.actorId), kind, points, deleted: r.deleted, reason: str(r.reason), calibrationVersion: cv, measurement: { length: n(measurement.length), area: n(measurement.area), unit: str(measurement.unit), calibrationVersion: cv }, createdAt: str(r.createdAt) }; }); if (!history && new Set(items.map(x => x.roiId)).size !== items.length) throw Error('重复ROI'); return { requestId: c.requestId, scanId: c.scanId, manifestHash: c.manifestHash, version: integer(v.version, -1), actorId: str(v.actorId), calibration, items, historyOnly: history }; }
const base = (m: Manifest) => `/api/requests/${encodeURIComponent(m.content.requestId)}/scans/${encodeURIComponent(m.content.scanId)}/roi`;
export async function load(m: Manifest, signal: AbortSignal) { return parse(await readJson(await request(`${base(m)}?publicationVersion=${m.publicationVersion}`, { signal, cache: 'no-store' })), m); }
export async function history(m: Manifest, roi: string, signal: AbortSignal) { return parse(await readJson(await request(`${base(m)}/${encodeURIComponent(roi)}/history`, { signal, cache: 'no-store' })), m, true); }
export async function save(m: Manifest, input: Save, key: string, signal: AbortSignal) { const csrf = await fetchCsrf(signal); const v = obj(await readJson(await request(base(m), { method: 'POST', signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify(input) }))); const r = obj(v.receipt); if (r.resourceId !== input.roiId || r.resourceType !== 'ROI' || r.status !== 200 || r.version !== input.expectedRevision + 1) throw Error('ROI保存回执不匹配'); }
export async function calibrate(m: Manifest, version: number, x: number, y: number, reason: string, key: string, signal: AbortSignal) { const csrf = await fetchCsrf(signal); const v = obj(await readJson(await request(`${base(m)}/calibration`, { method: 'POST', signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify({ publicationVersion: m.publicationVersion, manifestHash: m.content.manifestHash, expectedVersion: version, mppX: x, mppY: y, basis: 'SYNTHETIC_TEST', reason }) }))); const r = obj(v.receipt); if (r.resourceId !== m.content.scanId || r.resourceType !== 'ROI_CALIBRATION' || r.version !== version + 1) throw Error('校准回执不匹配'); }
