import { useEffect, useId, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Alert, Button, Input, InputNumber, Modal, Select, Space } from 'antd';
import OpenSeadragon from 'openseadragon';
import { ApiError } from '../../api';
import type { Manifest } from './api';
import * as api from './roi-api';
import { inverse, project, validate, vertices, measure, type Kind, type Matrix, type Point } from './roi-geometry';
type Intent = { key: string; body: api.Save } | { key: string; calibration: { x: number; y: number; reason: string; version: number } };
export function RoiEditor({ manifest, viewer, host, onState, onFatal }: { manifest: Manifest; viewer: OpenSeadragon.Viewer; host: HTMLElement; onState: (dirty: boolean, pending: boolean) => void; onFatal: (e: unknown) => void }) {
 const clipId = useId();
 const [view, setView] = useState<api.View>(); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [kind, setKind] = useState<Kind>('RECTANGLE'); const [points, setPoints] = useState<Point[]>([]); const [mode, setMode] = useState(false); const [selected, setSelected] = useState<api.Revision>(); const [vertex, setVertex] = useState(0); const [reason, setReason] = useState(''); const [dirty, setDirty] = useState(false); const [pending, setPending] = useState(false); const [busy, setBusy] = useState(false); const [matrix, setMatrix] = useState<Matrix>([1, 0, 0, 1, 0, 0]); const [undo, setUndo] = useState<Point[][]>([]); const [confirm, setConfirm] = useState<(() => void)>(); const [history, setHistory] = useState<api.View>(); const [mppX, setMppX] = useState<number | null>(null); const [mppY, setMppY] = useState<number | null>(null); const [crop, setCrop] = useState(false);
 const active = useRef<AbortController | undefined>(undefined), intent = useRef<Intent | undefined>(undefined), locked = useRef(false); const alive = useRef(true); const notify = useRef(onState), fatal = useRef(onFatal); notify.current = onState; fatal.current = onFatal;
 useEffect(() => { notify.current(dirty, pending); }, [dirty, pending]);
 useEffect(() => { alive.current = true; const c = new AbortController(); active.current = c; void api.load(manifest, c.signal).then(v => { if (!c.signal.aborted) setView(v); }).catch(e => { if (!c.signal.aborted) setError(e instanceof Error ? e.message : 'ROI读取失败'); }); return () => { alive.current = false; c.abort(); active.current?.abort(); notify.current(false, false); }; }, [manifest]);
 useEffect(() => { const update = () => { const item = viewer.world.getItemAt(0); if (!item) return; const a = item.imageToViewerElementCoordinates(new OpenSeadragon.Point(0, 0)), b = item.imageToViewerElementCoordinates(new OpenSeadragon.Point(1, 0)), c = item.imageToViewerElementCoordinates(new OpenSeadragon.Point(0, 1)); setMatrix([b.x - a.x, b.y - a.y, c.x - a.x, c.y - a.y, a.x, a.y]); }; update(); const events = ['animation', 'viewport-change', 'resize', 'rotate', 'flip'] as const; events.forEach(e => viewer.addHandler(e, update)); return () => events.forEach(e => viewer.removeHandler(e, update)); }, [viewer, host]);
 function reset() { setPoints([]); setSelected(undefined); setHistory(undefined); setUndo([]); setReason(''); setMode(false); setDirty(false); setMppX(null); setMppY(null); }
 function guard(work: () => void) { if (pending || busy) return; if (dirty) setConfirm(() => work); else work(); }
 function edit(next: Point[]) { if (pending || busy) return; setUndo(u => [...u.slice(-19), points]); setPoints(next); setDirty(true); }
 function click(x: number, y: number) { if (!mode || !view || pending || busy) return; try { const p = project({ x, y }, inverse(matrix)); const c = manifest.content, marginX = crop ? c.width / 4 : 0, marginY = crop ? c.height / 4 : 0; if (!Number.isFinite(p.x) || !Number.isFinite(p.y) || p.x < marginX || p.y < marginY || p.x > c.width - marginX || p.y > c.height - marginY) throw Error('点击位于图像或裁剪范围之外'); const q = { x: Math.round(p.x * 1000) / 1000, y: Math.round(p.y * 1000) / 1000 }; if (selected) edit(points.map((v, i) => i === vertex ? q : v)); else if (points.length < (kind === 'POINT' ? 1 : kind === 'RECTANGLE' ? 2 : 32)) edit([...points, q]); else throw Error('顶点达到上限；请选择撤销或编辑'); } catch (e) { setError(e instanceof Error ? e.message : '坐标无效'); } }
 async function refreshView() { active.current?.abort(); const c = new AbortController(); active.current = c; locked.current = true; setBusy(true); setView(undefined); setHistory(undefined); setError(''); try { const v = await api.load(manifest, c.signal); if (!c.signal.aborted && alive.current) setView(v); } catch (e) { if (!c.signal.aborted && alive.current) setError(e instanceof Error ? e.message : 'ROI重新读取失败'); } finally { if (active.current === c) { locked.current = false; if (alive.current) setBusy(false); } } }
 async function send() { if (locked.current || !intent.current) return; locked.current = true; setBusy(true); setError(''); const c = new AbortController(); active.current = c; const original = intent.current; try { if ('body' in original) await api.save(manifest, original.body, original.key, c.signal); else { const v = original.calibration; await api.calibrate(manifest, v.version, v.x, v.y, v.reason, original.key, c.signal); } if (c.signal.aborted || !alive.current) return; const current = await api.load(manifest, c.signal); if (c.signal.aborted || !alive.current) return; setView(current); intent.current = undefined; setPending(false); reset(); setNotice('已确认当前图像的版本化合成记录'); } catch (e) { if (!c.signal.aborted && alive.current) { setError(e instanceof Error ? e.message : '保存结果未确认，请原键重试'); if (e instanceof ApiError && ([401, 403, 404].includes(e.status) || e.code === 'DIGITAL_QC_NOT_READY')) fatal.current(e); } } finally { locked.current = false; if (alive.current) setBusy(false); } }
 function save(deleted = false) { if (!view || pending || busy) return; try { validate(kind, points, manifest.content.width, manifest.content.height); if (!reason.trim()) throw Error('必须输入人工原因'); if (selected && selected.authorId !== view.actorId) throw Error('只能修改本人标注'); intent.current = { key: crypto.randomUUID(), body: { publicationVersion: manifest.publicationVersion, manifestHash: manifest.content.manifestHash, expectedVersion: view.version, roiId: selected?.roiId ?? crypto.randomUUID(), expectedRevision: selected?.revision ?? -1, kind, points, deleted, reason, calibrationVersion: deleted ? selected?.calibrationVersion ?? null : view.calibration?.version ?? null } }; setPending(true); void send(); } catch (e) { setError(e instanceof Error ? e.message : 'ROI无效'); } }
 function calibrate() { if (!view || pending || busy || mppX === null || mppY === null) return; if (!reason.trim() || ![mppX, mppY].every(n => Number.isFinite(n) && n > 0 && n <= 100)) { setError('校准必须有独立正数X/Y及人工原因'); return; } intent.current = { key: crypto.randomUUID(), calibration: { x: mppX, y: mppY, reason, version: view.version } }; setPending(true); void send(); }
 async function loadHistory(id: string) { const c = new AbortController(); active.current?.abort(); active.current = c; try { const v = await api.history(manifest, id, c.signal); if (!c.signal.aborted && alive.current) setHistory(v); } catch (e) { if (!c.signal.aborted && alive.current) setError(e instanceof Error ? e.message : '历史读取失败'); } }
 const preview = points.length ? measure(kind, points, view?.calibration ?? undefined) : null;
 function shape(k: Kind, p: Point[], key: string, draft: boolean) { const q = vertices(k, p).map(v => project(v, matrix)); return k === 'POINT' ? <circle data-roi-shape={key} key={key} cx={q[0]?.x} cy={q[0]?.y} r="6" fill={draft ? '#ffdf00' : '#00ffab'} /> : <polygon data-roi-shape={key} key={key} points={q.map(v => `${v.x},${v.y}`).join(' ')} fill={draft ? '#ffdf0030' : '#00ffab20'} stroke={draft ? '#ffdf00' : '#00ffab'} strokeWidth="3" />; }
 const cropPoints = [{ x: manifest.content.width / 4, y: manifest.content.height / 4 }, { x: manifest.content.width * 3 / 4, y: manifest.content.height * 3 / 4 }];
 return <section aria-label="ROI标注编辑"><Alert type="info" title="人工合成ROI；规范坐标为图像像素，显式保存，无自动诊断。" />{error && <Alert type="error" title={error} />}{notice && <p role="status">{notice}</p>}<p>集合版本 {view?.version ?? '未加载'} / 标注 {view?.items.length ?? '未知'}/50 / {view?.calibration ? `合成校准v${view.calibration.version} X=${view.calibration.mppX} Y=${view.calibration.mppY} µm/px（非临床）` : '校准未知：仅px，不提供µm'} / {dirty ? '未保存ROI' : '无本地修改'}</p>
 <Space wrap><Button disabled={pending || busy} onClick={() => guard(() => { reset(); void refreshView(); })}>重新读取ROI及授权</Button><Select virtual={false} aria-label="ROI形状" value={kind} disabled={pending || busy} options={['POINT', 'RECTANGLE', 'POLYGON'].map(value => ({ value, label: value }))} onChange={v => guard(() => { reset(); setKind(v); })} /><Button disabled={!view || pending || busy} onClick={() => guard(() => { reset(); setMode(true); })}>新建ROI并点击画布</Button><Button disabled={pending || !points.length} onClick={() => setMode(v => !v)}>{mode ? '结束点击并恢复导航' : '编辑ROI顶点'}</Button>{selected && <InputNumber aria-label="编辑顶点序号" min={0} max={points.length - 1} value={vertex} onChange={v => setVertex(v ?? 0)} />}<Button disabled={pending || !undo.length} onClick={() => { const p = undo.at(-1); if (p) { setPoints(p); setUndo(u => u.slice(0, -1)); setDirty(true); } }}>撤销本地顶点操作</Button><Button disabled={pending} onClick={() => guard(reset)}>取消本地ROI编辑</Button></Space>
 <Input aria-label="ROI人工原因" maxLength={200} disabled={pending || busy} value={reason} onChange={e => { setReason(e.target.value); setDirty(true); }} />
 <Space wrap><Button disabled={!view || pending || busy || !points.length} onClick={() => save()}>保存ROI修订</Button><Button disabled={!selected || selected.deleted || pending || busy || JSON.stringify(points) !== JSON.stringify(selected.points) || selected.authorId !== view?.actorId} onClick={() => { setConfirm(() => () => save(true)); }}>软删除选中ROI</Button><Button disabled={!pending || busy} onClick={() => void send()}>原键重试ROI操作</Button><Button disabled={!busy} onClick={() => { active.current?.abort(); setNotice('已停止等待，结果未确认；保留原键重试'); }}>停止等待ROI保存</Button><Button disabled={!pending || busy} onClick={() => setConfirm(() => () => { intent.current = undefined; setPending(false); reset(); void refreshView(); })}>放弃本地跟踪并重新读取</Button></Space>
 {preview && <p>本地预览周长 {preview.length.toFixed(3)} {preview.unit} / 面积 {preview.area.toFixed(3)} {preview.unit}²；绑定当前明确校准</p>}
 <Space wrap><Button onClick={() => viewer.viewport.setRotation((viewer.viewport.getRotation() + 90) % 360, true)}>旋转90度</Button><Button onClick={() => viewer.viewport.setFlip(!viewer.viewport.getFlip())}>水平翻转</Button><Button onClick={() => { const next = !crop; viewer.world.getItemAt(0)?.setClip(next ? new OpenSeadragon.Rect(manifest.content.width / 4, manifest.content.height / 4, manifest.content.width / 2, manifest.content.height / 2) : null); setCrop(next); }}>{crop ? '取消中心裁剪' : '仅显示中心裁剪'}</Button><label>合成MPP X(µm/px)<InputNumber aria-label="合成MPP X" value={mppX} min={0.000001} max={100} disabled={pending || busy} onChange={v => { setMppX(v); setDirty(true); }} /></label><label>合成MPP Y(µm/px)<InputNumber aria-label="合成MPP Y" value={mppY} min={0.000001} max={100} disabled={pending || busy} onChange={v => { setMppY(v); setDirty(true); }} /></label><Button disabled={!view || pending || busy || mppX === null || mppY === null} onClick={calibrate}>登记合成校准版本</Button></Space>
 <ul>{view?.items.map(r => <li key={r.roiId}>{r.roiId} / {r.kind} / rev{r.revision} / {r.deleted ? '已软删除' : '有效记录'} / 作者{r.authorId} / 面积{r.measurement.area.toFixed(3)} {r.measurement.unit}² / 校准{r.calibrationVersion ?? '未知'} <Button disabled={pending || busy || r.deleted} onClick={() => guard(() => { reset(); setSelected(r); setKind(r.kind); setPoints(r.points); setReason(r.reason); setVertex(0); })}>选择ROI {r.roiId}</Button><Button disabled={pending || busy} onClick={() => void loadHistory(r.roiId)}>历史 {r.roiId}</Button></li>)}</ul>
 {history && <div aria-label="ROI只读历史"><Button onClick={() => setHistory(undefined)}>关闭ROI历史</Button>{history.items.map(r => <p key={r.revision}>rev{r.revision} / {r.reason} / {r.deleted ? '软删除' : '保存'} / {r.createdAt}</p>)}</div>}
 <Modal open={!!confirm} title="确认放弃本地编辑或执行明确操作" onCancel={() => setConfirm(undefined)} onOk={() => { const work = confirm; setConfirm(undefined); work?.(); }}>操作不会覆盖已有历史；取消可保留当前输入。</Modal>
 {createPortal(<svg aria-label="ROI图像叠加层" tabIndex={mode ? 0 : -1} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: mode ? 'auto' : 'none' }} onClick={e => { const r = e.currentTarget.getBoundingClientRect(); click(e.clientX - r.left, e.clientY - r.top); }} onKeyDown={e => { if (e.key === 'Escape') { setMode(false); e.preventDefault(); } if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !pending) { const p = undo.at(-1); if (p) { setPoints(p); setUndo(u => u.slice(0, -1)); setDirty(true); } e.preventDefault(); } }}><defs><clipPath id={clipId}><polygon points={vertices('RECTANGLE', crop ? cropPoints : [{ x: 0, y: 0 }, { x: manifest.content.width, y: manifest.content.height }]).map(p => project(p, matrix)).map(p => `${p.x},${p.y}`).join(' ')} /></clipPath></defs><g clipPath={`url(#${clipId})`}>{view?.items.filter(r => !r.deleted && r.roiId !== selected?.roiId).map(r => shape(r.kind, r.points, r.roiId, false))}{points.length > 0 && shape(kind, points, 'draft', true)}</g></svg>, host)}
 </section>;
}
