import { useEffect, useRef, useState } from 'react';
import { Alert, Button, Modal, Select, Space } from 'antd';
import OpenSeadragon from 'openseadragon';
import { ApiError } from '../../api';
import * as api from './api';
import { RoiEditor } from './RoiEditor';
import { RoiHistory } from './RoiHistory';

type Ready = { viewer: OpenSeadragon.Viewer; hash: string };
export function TileViewer({ requestId, scanId, onExpired, onDirty, onClean, onPending }: { requestId: string; scanId: string; onExpired: () => void; onDirty: () => void; onClean: () => void; onPending: (v: boolean) => void }) {
 const [choiceError, setChoiceError] = useState(''); const [selected, setSelected] = useState(scanId); const [second, setSecond] = useState(scanId); const [dual, setDual] = useState(false); const [sync, setSync] = useState(false); const [choices, setChoices] = useState<{ id: string; label: string }[]>([]); const [confirm, setConfirm] = useState<(() => void)>(); const [ready, setReady] = useState<Record<string, Ready>>({}); const states = useRef<Record<string, { dirty: boolean; pending: boolean }>>({}); const syncing = useRef(false);
 useEffect(() => { const c = new AbortController(); void api.choices(requestId, c.signal).then(v => { if (!c.signal.aborted) setChoices(v); }).catch(e => { if (!c.signal.aborted) setChoiceError(e instanceof Error ? e.message : '扫描列表查询失败'); }); return () => c.abort(); }, [requestId]);
 function state(side: string, dirty: boolean, pending: boolean) { states.current[side] = { dirty, pending }; if (Object.values(states.current).some(x => x.dirty)) onDirty(); else onClean(); onPending(Object.values(states.current).some(x => x.pending)); }
 function change(work: () => void) { if (Object.values(states.current).some(x => x.pending)) { setChoiceError('保存结果未确认，请原键重试或明确放弃本地跟踪'); return; } if (Object.values(states.current).some(x => x.dirty)) setConfirm(() => work); else work(); }
 function prepared(side: string, value?: Ready) { setReady(v => { const next = { ...v }; if (value) next[side] = value; else delete next[side]; return next; }); if (!value) setSync(false); }
 function synchronize(side: string, source: OpenSeadragon.Viewer) { if (!sync || syncing.current || !ready.left || !ready.right || ready.left.hash !== ready.right.hash) return; const target = ready[side === 'left' ? 'right' : 'left'].viewer; const a = source.viewport, b = target.viewport; if (b.getCenter().distanceTo(a.getCenter()) < 1e-8 && Math.abs(b.getZoom() - a.getZoom()) < 1e-8 && b.getRotation() === a.getRotation() && b.getFlip() === a.getFlip()) return; syncing.current = true; try { b.setRotation(a.getRotation(), true); b.setFlip(a.getFlip()); b.zoomTo(a.getZoom(), undefined, true); b.panTo(a.getCenter(), true); } finally { syncing.current = false; } }
 const options = choices.map(x => ({ value: x.id, label: x.label }));
 return <section aria-label="合成数字阅片"><Alert type="warning" title="合成RGB几何图／非临床；真实WSI与厂商格式未支持；未知校准仅像素，合成校准不证明临床测量准确性。" />{choiceError && <Alert type="error" title={choiceError} />}<label>选择精确扫描<Select virtual={false} aria-label="选择精确扫描" style={{ minWidth: 300 }} value={selected} options={options} onChange={v => change(() => { setSync(false); setSelected(v); })} /></label><Space><Button onClick={() => change(() => { setSync(false); setDual(v => !v); })}>{dual ? '关闭第二视图' : '打开第二视图'}</Button>{dual && <Select aria-label="第二视图扫描" virtual={false} value={second} options={options} onChange={v => change(() => { setSync(false); setSecond(v); })} />}<Button disabled={!dual || !ready.left || !ready.right || ready.left.hash !== ready.right.hash} onClick={() => setSync(v => !v)}>{sync ? '关闭像素恒等同步' : '显式开启像素恒等同步'}</Button></Space><p>不同扫描或清单没有已验证映射，同步不可用；不作自动配准。</p>
 <div style={{ display: 'grid', gridTemplateColumns: dual ? 'minmax(0,1fr) minmax(0,1fr)' : 'minmax(0,1fr)', gap: 12 }}><section aria-label="主视图"><ImageView key={`${requestId}:${selected}`} requestId={requestId} scanId={selected} onExpired={onExpired} onState={(d,p) => state('left',d,p)} onReady={v => prepared('left',v)} onViewport={v => synchronize('left',v)} /></section>{dual && <section aria-label="第二视图"><ImageView key={`${requestId}:${second}`} requestId={requestId} scanId={second} onExpired={onExpired} onState={(d,p) => state('right',d,p)} onReady={v => prepared('right',v)} onViewport={v => synchronize('right',v)} /></section>}</div>
 <Modal open={!!confirm} title="放弃当前未保存ROI并切换视图？" onCancel={() => setConfirm(undefined)} onOk={() => { const work = confirm; setConfirm(undefined); work?.(); }}>只丢弃本地未保存输入，已存历史保留。</Modal></section>;
}
function ImageView({ requestId, scanId, onExpired, onState, onReady, onViewport }: { requestId: string; scanId: string; onExpired: () => void; onState: (dirty: boolean, pending: boolean) => void; onReady: (v?: Ready) => void; onViewport: (v: OpenSeadragon.Viewer) => void }) {
 const [historicalManifest, setHistoricalManifest] = useState<api.Manifest>();
 const [roiLocked, setRoiLocked] = useState(false);
 const [osd, setOsd] = useState<OpenSeadragon.Viewer>(); const [roi, setRoi] = useState(false); const overlay = useRef<HTMLDivElement>(null); const callbacks = useRef({ onReady, onViewport }); callbacks.current = { onReady, onViewport }; const fatal = useRef<(e: unknown) => void>(() => {});
 const stop = useRef<(() => void) | undefined>(undefined);
 const element = useRef<HTMLDivElement>(null); const viewer = useRef<OpenSeadragon.Viewer | undefined>(undefined); const control = useRef<AbortController | undefined>(undefined); const [round, setRound] = useState(0); const [error, setError] = useState(''); const [status, setStatus] = useState('加载清单与授权'); const [manifest, setManifest] = useState<api.Manifest>(); const [pub, setPub] = useState<number>(); const [prepareNeeded, setPrepareNeeded] = useState(false); const [busy, setBusy] = useState(false); const [zoom, setZoom] = useState(''); const [position, setPosition] = useState(''); const key = useRef(crypto.randomUUID()); const write = useRef(false); const expired = useRef(onExpired); expired.current = onExpired;
 useEffect(() => {
  const root = new AbortController(); control.current = root; const jobs = new Map<OpenSeadragon.ImageJob, AbortController>(); let disposed = false; let instance: OpenSeadragon.Viewer | undefined; let timer: ReturnType<typeof setInterval> | undefined; let checking = false; let failed = false; let tileFailure: unknown;
  function destroy() { setOsd(undefined); callbacks.current.onReady(); if (instance) { instance.destroy(); instance = undefined; viewer.current = undefined; } for (const c of jobs.values()) c.abort(); jobs.clear(); element.current?.replaceChildren(); }
  stop.current = () => { root.abort(); if (timer) clearInterval(timer); destroy(); };
  function fail(e: unknown) { if (disposed || root.signal.aborted || failed) return; failed = true; destroy(); setManifest(undefined); setStatus('图像已清空'); setError(e instanceof Error ? e.message : '瓦片加载失败；空白不能解释为阴性'); if (e instanceof ApiError && e.status === 401) expired.current(); }
  fatal.current = fail;
  async function open() {
   try { const p = await api.publication(requestId, scanId, root.signal); if (root.signal.aborted) return; setPub(p); let m: api.Manifest; try { m = await api.load(requestId, scanId, p, root.signal); } catch (e) { if (!root.signal.aborted && e instanceof ApiError && e.code === 'VIEWER_NOT_PREPARED') { setPrepareNeeded(true); setStatus('需要显式生成合成瓦片清单'); return; } throw e; }
    if (root.signal.aborted || !element.current) return; setManifest(m); setHistoricalManifest(m); setPrepareNeeded(false); setError(''); setStatus('正在加载真实合成PNG瓦片');
    const source = new OpenSeadragon.TileSource({ width: m.content.width, height: m.content.height, tileSize: 128, tileOverlap: 0, minLevel: 0, maxLevel: m.content.maxLevel });
    source.getTileUrl = (level, x, y) => `${api.base(requestId, scanId)}/tiles/${level}/${x}/${y}?publicationVersion=${p}`;
    source.downloadTileStart = job => { const c = new AbortController(); jobs.set(job, c); const stop = () => c.abort(); root.signal.addEventListener('abort', stop, { once: true }); let timedOut = false; const timeout = setTimeout(() => { timedOut = true; stop(); }, 10000); const spec = m.content.tiles.find(t => source.getTileUrl(t.level, t.x, t.y) === job.src); if (!spec) { clearTimeout(timeout); root.signal.removeEventListener('abort', stop); jobs.delete(job); tileFailure = Error('瓦片缺失，停止显示'); job.fail('瓦片坐标不在清单', null); fail(tileFailure); return; } void api.binary(job.src, spec, c.signal).then(blob => { if (!disposed && !c.signal.aborted && !failed) job.finish(blob, null, 'rasterBlob'); }).catch(e => { if (!disposed && !root.signal.aborted && (!c.signal.aborted || timedOut)) { tileFailure = e; job.fail('瓦片失败或超时', null); fail(e); } }).finally(() => { clearTimeout(timeout); root.signal.removeEventListener('abort', stop); jobs.delete(job); }); };
    source.downloadTileAbort = job => { jobs.get(job)?.abort(); jobs.delete(job); };
    instance = OpenSeadragon({ element: element.current, tileSources: Object.assign(source, { url: '' }), showNavigationControl: false, showNavigator: true, navigatorPosition: 'BOTTOM_LEFT', navigatorSizeRatio: .2, drawer: 'canvas', maxImageCacheCount: 32, imageLoaderLimit: 4, timeout: 10000, blendTime: 0, animationTime: .2, maxZoomPixelRatio: 8, visibilityRatio: 1, constrainDuringPan: true }); viewer.current = instance;
    instance.addHandler('open', () => { if (instance && !disposed && !failed) { setOsd(instance); callbacks.current.onReady({ viewer: instance, hash: m.content.manifestHash }); } });
    instance.addHandler('tile-loaded', () => { if (!disposed && !failed) setStatus('真实合成PNG已加载；不代表临床就绪'); });
    instance.addHandler('tile-load-failed', () => fail(tileFailure ?? Error('瓦片缺失或网络失败，已停止显示；请显式重试')));
    const verify = async () => { if (checking || failed || root.signal.aborted) return; checking = true; try { const current = await api.load(requestId, scanId, p, root.signal); if (current.content.manifestHash !== m.content.manifestHash) throw Error('清单变化，旧图已失效'); } catch (e) { fail(e); } finally { checking = false; } };
    instance.addHandler('viewport-change', () => { if (instance && !failed) { callbacks.current.onViewport(instance); setZoom(instance.viewport.getZoom().toFixed(2)); const c = instance.viewport.getCenter(); setPosition(`${c.x.toFixed(3)},${c.y.toFixed(3)}`); void verify(); } });
    timer = setInterval(() => void verify(), 2000);
   } catch (e) { fail(e); }
  }
  void open(); return () => { disposed = true; root.abort(); if (timer) clearInterval(timer); destroy(); };
 }, [requestId, scanId, round]);
 async function prepare() { if (pub === undefined || write.current) return; write.current = true; setBusy(true); setError(''); const c = control.current; if (!c) { write.current = false; setBusy(false); return; } try { await api.prepare(requestId, scanId, pub, key.current, c.signal); if (!c.signal.aborted) { setPrepareNeeded(false); setRound(v => v + 1); } } catch (e) { if (!c.signal.aborted) setError(e instanceof Error ? e.message : '生成结果未确认，请原键重试'); } finally { write.current = false; setBusy(false); } }
 function move(action: string) { const v = viewer.current; if (!v) return; if (action === 'home') v.viewport.goHome(); else if (action === '+' || action === '-') v.viewport.zoomBy(action === '+' ? 1.5 : 1 / 1.5); else { const delta = .1 / v.viewport.getZoom(); v.viewport.panBy(new OpenSeadragon.Point(action === 'ArrowLeft' ? -delta : action === 'ArrowRight' ? delta : 0, action === 'ArrowUp' ? -delta : action === 'ArrowDown' ? delta : 0)); } v.viewport.applyConstraints(); }
 return <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}><p>扫描 {scanId} / 发布版本 {pub ?? '待核验'} / 原件 {manifest?.content.objectId ?? '待核验'}</p><p role="status">{status}</p>{error && <Alert role="alert" type="error" title={error} />}
  <Space wrap>{prepareNeeded && <Button disabled={busy} onClick={() => void prepare()}>生成或原键确认合成瓦片</Button>}<Button disabled={roiLocked} onClick={() => { stop.current?.(); setManifest(undefined); setStatus('已停止加载并清空图像'); }}>停止加载图像</Button><Button disabled={busy || roiLocked} onClick={() => { setError(''); setManifest(undefined); setStatus('重新核验授权'); setRound(v => v + 1); }}>重新授权并加载</Button><Button disabled={!manifest} onClick={() => move('+')}>放大图像</Button><Button disabled={!manifest} onClick={() => move('-')}>缩小图像</Button><Button disabled={!manifest} onClick={() => move('home')}>适配窗口</Button></Space>
  <p>图像相对缩放 {zoom || '—'} / 导航坐标 {position || '—'}；键盘方向键平移，+/-缩放，Home适配。已交付像素的授权刷新间隔2秒。</p>
  {historicalManifest && <RoiHistory key={historicalManifest.content.manifestHash} manifest={historicalManifest} />}
  {manifest && osd && overlay.current && roi && <RoiEditor manifest={manifest} viewer={osd} host={overlay.current} onState={(d,p) => { setRoiLocked(d || p); onState(d,p); }} onFatal={e => fatal.current(e)} />}
  <Button disabled={!manifest || !osd} onClick={() => setRoi(true)}>打开ROI编辑</Button>
  <div style={{ position: 'relative', marginTop: 'auto', flexShrink: 0 }}><div ref={element} aria-label="合成瓦片画布" tabIndex={0} onKeyDown={e => { if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', '+', '-', 'Home'].includes(e.key)) { e.preventDefault(); move(e.key === 'Home' ? 'home' : e.key); } }} style={{ height: 520, width: '100%', background: '#152638', position: 'relative' }} /><div ref={overlay} style={{ position: 'absolute', inset: 0, pointerEvents: 'none' }} /></div>
 </div>;
}
