package com.pis.report;
import com.pis.diagnosis.DiagnosisService;
import com.pis.accession.WorkflowAccess;
import com.pis.api.ApiException;
import com.pis.audit.*;
import com.pis.idempotency.*;
import jakarta.validation.Validator;
import java.util.*;
import java.time.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import static com.pis.report.ConsultationContracts.*;
@Service
public class ConsultationService {
 private final JdbcTemplate jdbc;private final DiagnosisService diagnosis;private final ReportService reports;private final WorkflowAccess access;private final IdempotentCommands commands;private final AuditRecorder audit;private final Validator validator;private final ConsultationRejectionAudit rejections;
 public ConsultationService(JdbcTemplate jdbc,DiagnosisService diagnosis,ReportService reports,WorkflowAccess access,IdempotentCommands commands,AuditRecorder audit,Validator validator,ConsultationRejectionAudit rejections){this.jdbc=jdbc;this.diagnosis=diagnosis;this.reports=reports;this.access=access;this.commands=commands;this.audit=audit;this.validator=validator;this.rejections=rejections;}
 private Head map(java.sql.ResultSet r,int i)throws java.sql.SQLException{return new Head(r.getObject("id",UUID.class),r.getObject("case_id",UUID.class),r.getObject("revision_id",UUID.class),r.getLong("assignment_version"),r.getString("dependencies"),r.getString("material_basis"),r.getString("kind"),r.getString("purpose"),r.getObject("expires_at",OffsetDateTime.class).toInstant(),r.getObject("created_by",UUID.class),r.getString("state"),r.getLong("version"),r.getObject("summary_id",UUID.class));}
 private Event event(java.sql.ResultSet r,int i)throws java.sql.SQLException{return new Event(r.getObject("id",UUID.class),r.getLong("version"),r.getString("action"),r.getObject("actor_id",UUID.class),r.getObject("target_id",UUID.class),r.getString("disposition"),r.getString("content"),r.getString("reason"),r.getObject("summary_id",UUID.class),r.getObject("adopted_revision_id",UUID.class),r.getObject("recorded_at",OffsetDateTime.class).toInstant());}
 private Head head(UUID caseId,UUID id){var rows=jdbc.query("SELECT * FROM report_consultation WHERE case_id=? AND id=?",this::map,caseId,id);if(rows.isEmpty())throw missing();return rows.getFirst();}
 private boolean owner(DiagnosisService.ReviewContext c){try{diagnosis.reportContext(c.caseId());return true;}catch(ApiException e){if(e.status()!=HttpStatus.NOT_FOUND)throw e;return false;}}
 private void permit(DiagnosisService.ReviewContext c,Head h,boolean owner){if(owner)return;if(h==null||!h.expiresAt().isAfter(Instant.now())||!h.state().equals("OPEN")||jdbc.queryForObject("SELECT count(*) FROM consultation_member WHERE consultation_id=? AND user_id=? AND state IN ('INVITED','ACCEPTED')",Long.class,h.id(),access.actor().id())!=1)throw missing();}
 private List<Member> members(UUID id){return jdbc.query("SELECT * FROM consultation_member WHERE consultation_id=? ORDER BY user_id",(r,i)->new Member(r.getObject("user_id",UUID.class),r.getString("state"),r.getObject("opinion_id",UUID.class),r.getObject("confirmed_summary_id",UUID.class)),id);}
 private String basis(UUID id){return jdbc.queryForObject("SELECT jsonb_agg(jsonb_build_array(user_id,state,opinion_id) ORDER BY user_id)::text FROM consultation_member WHERE consultation_id=?",String.class,id);}
 private boolean frozen(UUID caseId){return jdbc.queryForObject("SELECT count(*) FROM report_review_head h JOIN report_review_event e ON e.id=h.event_id JOIN report_draft d ON d.case_id=h.case_id AND d.revision_id=e.revision_id WHERE h.case_id=? AND e.action='SIMULATE_SIGN'",Long.class,caseId)>0;}
 private String invalid(DiagnosisService.ReviewContext c,Head h){if(!h.state().equals("OPEN"))return h.state();if(!h.expiresAt().isAfter(Instant.now()))return "EXPIRED";var r=reports.current(c.caseId());if(r==null||!r.id().equals(h.revisionId()))return "REPORT_CHANGED";if(c.assignmentVersion()!=h.assignmentVersion())return "ASSIGNMENT_CHANGED";if(frozen(c.caseId()))return "REPORT_FROZEN";if(!c.ready()||!c.dependencies().equals(h.dependencies()))return "QC_OR_QUALIFICATION_CHANGED";
  var ms=members(h.id());var current=diagnosis.qualificationSnapshots(c.scopeId(),ms.stream().map(Member::userId).toList());var original=new HashMap<UUID,String>();jdbc.query("SELECT user_id,qualification_snapshot FROM consultation_member WHERE consultation_id=?",r->{original.put(r.getObject("user_id",UUID.class),r.getString("qualification_snapshot"));},h.id());
  for(var m:ms){if(m.state().equals("REVOKED")||m.state().equals("REJECTED"))return "PARTICIPANT_UNAVAILABLE";if(!Objects.equals(current.get(m.userId()),original.get(m.userId())))return "PARTICIPANT_QUALIFICATION_CHANGED";}return null;}
 private boolean summaryCurrent(Head h){return h.summaryId()!=null&&jdbc.queryForObject("SELECT count(*) FROM consultation_event WHERE id=? AND action='SUMMARY' AND disposition='RESOLVED' AND basis=?",Long.class,h.summaryId(),basis(h.id()))==1;}
 private boolean ready(Head h){var ms=members(h.id());return summaryCurrent(h)&&!ms.isEmpty()&&ms.stream().allMatch(m->m.state().equals("ACCEPTED")&&m.opinionId()!=null&&h.summaryId().equals(m.confirmedSummaryId()));}
 @Transactional(timeout=10) public View detail(UUID caseId,UUID selected,int page){var c=diagnosis.reviewContext(caseId);jdbc.queryForList("SELECT id FROM pathology_request WHERE id=? FOR SHARE",c.requestId());c=diagnosis.reviewContext(caseId);boolean own=owner(c);var h=selected==null?null:head(caseId,selected);if(h!=null)permit(c,h,own);if(page<1||page>10000)throw conflict("CONSULT_PAGE");jdbc.execute("SET LOCAL statement_timeout='5s'");
  var list=jdbc.query("SELECT c.* FROM report_consultation c WHERE c.case_id=? AND (? OR (c.state='OPEN' AND c.expires_at>statement_timestamp() AND EXISTS(SELECT 1 FROM consultation_member m WHERE m.consultation_id=c.id AND m.user_id=? AND m.state IN ('INVITED','ACCEPTED')))) ORDER BY c.created_at DESC,c.id LIMIT 100",this::map,caseId,own,access.actor().id());
  // An uninvited user may discover no consultation content, even if their existing workflow scope permits the case.
  if(!own&&h==null&&list.isEmpty())throw missing();
  var events=h==null?List.<Event>of():jdbc.query("SELECT * FROM consultation_event WHERE consultation_id=? ORDER BY version DESC LIMIT 20 OFFSET ?",this::event,h.id(),(page-1)*20);
  String invalid=h==null?null:invalid(c,h);if(invalid==null&&h!=null&&h.summaryId()!=null&&!summaryCurrent(h))invalid="SUMMARY_UNRESOLVED_OR_CHANGED";audit.append(c.hospitalId(),"CONSULT_READ_V1","PATHOLOGY_CASE",caseId,null,h==null?0:h.version());
  return new View(caseId,c.patientId(),c.number(),access.actor().id(),own,list,h,h==null?(own?reports.current(caseId):null):reports.revision(caseId,h.revisionId()),h==null?List.of():members(h.id()),events,h==null?List.of():jdbc.query("SELECT e.* FROM consultation_member m JOIN consultation_event e ON e.id=m.opinion_id WHERE m.consultation_id=? ORDER BY m.user_id",this::event,h.id()),h==null||h.summaryId()==null?null:jdbc.query("SELECT * FROM consultation_event WHERE id=?",this::event,h.summaryId()).getFirst(),own?diagnosis.detail(caseId).candidates():List.of(),invalid,h!=null&&invalid==null&&ready(h),page);
 }
 public IdempotentCommands.Result command(UUID caseId,UUID id,Action action,Command in,String key){var errors=validator.validate(in);if(!errors.isEmpty())throw new jakarta.validation.ConstraintViolationException(errors);var initial=diagnosis.reviewContext(caseId);
  try{return commands.execute(initial.hospitalId(),"CONSULT_"+action+"_V1",key,Map.of("case",caseId,"consultation",id==null?"":id.toString(),"command",in),new IdempotentCommands.Work(){
   public void authorize(CurrentActor.Actor actor){var c=diagnosis.reviewContext(caseId);boolean own=owner(c);var h=id==null?null:head(caseId,id);permit(c,h,own);if(Set.of(Action.CREATE,Action.WITHDRAW,Action.REVOKE,Action.SUMMARY,Action.ADOPT).contains(action)&&!own)throw missing();}
   public void authorizeReplay(CurrentActor.Actor actor,CommandReceipt receipt){authorize(actor);}
   public IdempotentCommands.Mutation mutate(CurrentActor.Actor actor){jdbc.queryForList("SELECT id FROM pathology_request WHERE id=? FOR UPDATE",initial.requestId());authorize(actor);var c=diagnosis.reviewContext(caseId);if(!caseId.equals(in.confirmedCaseId()))throw missing();var h=id==null?null:head(caseId,id);long old=h==null?-1:h.version();if(old!=in.expectedVersion())throw conflict("VERSION_CONFLICT");UUID cid=h==null?UUID.randomUUID():id,event=UUID.randomUUID(),summary=h==null?null:h.summaryId(),adopted=null;String state=h==null?"OPEN":h.state(),snapshot=null;
    if(action==Action.CREATE){if(h!=null)throw conflict("CONSULT_STATE");if(!c.ready())throw conflict("DIAGNOSIS_NOT_READY");if(frozen(caseId))throw conflict("REPORT_SIMULATED_FROZEN");var r=reports.current(caseId);if(r==null||!r.id().equals(in.revisionId())||!Objects.equals(in.assignmentVersion(),c.assignmentVersion()))throw conflict("CONSULT_INPUT_CHANGED");required(in.purpose());if(!Set.of("CONSULT","REREAD").contains(in.kind()==null?"":in.kind()))throw conflict("CONSULT_KIND");try{ConsultationPolicy.expiry(in.expiresAt(),Instant.now());}catch(IllegalArgumentException e){throw conflict(e.getMessage());}
     var targets=new TreeSet<>(in.invitees());if(targets.isEmpty()||targets.size()!=in.invitees().size()||targets.contains(actor.id()))throw conflict("CONSULT_PARTICIPANTS");if(jdbc.queryForObject("SELECT count(*) FROM report_consultation WHERE case_id=?",Long.class,caseId)>=100)throw conflict("CONSULT_LIMIT");var qualifications=diagnosis.qualificationSnapshots(c.scopeId(),new ArrayList<>(targets));if(qualifications.size()!=targets.size())throw conflict("CONSULT_PARTICIPANTS");
     jdbc.update("INSERT INTO report_consultation(id,case_id,hospital_id,request_id,scope_id,revision_id,assignment_version,dependencies,material_basis,kind,purpose,expires_at,created_by,state,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'OPEN',0)",cid,caseId,c.hospitalId(),c.requestId(),c.scopeId(),r.id(),c.assignmentVersion(),c.dependencies(),jdbc.queryForObject("SELECT coalesce(jsonb_agg(jsonb_build_object('id',m.id,'version',m.version,'qcVersion',q.version,'state',q.state) ORDER BY m.id),'[]'::jsonb)::text FROM material_entity m JOIN workflow_quality_projection q ON q.id=m.id WHERE m.case_id=?",String.class,caseId),in.kind(),in.purpose(),OffsetDateTime.ofInstant(in.expiresAt(),ZoneOffset.UTC),actor.id());for(var q:qualifications.entrySet())jdbc.update("INSERT INTO consultation_member(consultation_id,user_id,qualification_snapshot,state) VALUES(?,?,?,'INVITED')",cid,q.getKey(),q.getValue());
    }else{if(h==null||!h.state().equals("OPEN"))throw conflict("CONSULT_STATE");if(!Set.of(Action.WITHDRAW,Action.REVOKE,Action.REJECT,Action.RETURN).contains(action)&&invalid(c,h)!=null)throw conflict("CONSULT_INPUT_CHANGED");
     var member=members(cid).stream().filter(m->m.userId().equals(actor.id())).findFirst().orElse(null);
     switch(action){
      case WITHDRAW -> state="WITHDRAWN";
      case REVOKE -> {if(jdbc.update("UPDATE consultation_member SET state='REVOKED',confirmed_summary_id=NULL WHERE consultation_id=? AND user_id=? AND state IN ('INVITED','ACCEPTED')",cid,in.targetId())!=1)throw missing();}
      case ACCEPT,REJECT -> {if(member==null||!member.state().equals("INVITED"))throw conflict("CONSULT_MEMBER_STATE");jdbc.update("UPDATE consultation_member SET state=? WHERE consultation_id=? AND user_id=?",action==Action.ACCEPT?"ACCEPTED":"REJECTED",cid,actor.id());}
      case RETURN -> {if(member==null||!member.state().equals("ACCEPTED"))throw missing();state="RETURNED";}
      case OPINION -> {if(member==null||!member.state().equals("ACCEPTED"))throw missing();required(in.content());if(!ConsultationPolicy.opinion(in.disposition()))throw conflict("CONSULT_DISPOSITION");}
      case SUMMARY -> {required(in.content());if(!ConsultationPolicy.summary(in.disposition()))throw conflict("CONSULT_DISPOSITION");var ms=members(cid);var ids=ms.stream().map(Member::opinionId).filter(Objects::nonNull).toList();if(ms.stream().anyMatch(m->!m.state().equals("ACCEPTED")||m.opinionId()==null)||!new HashSet<>(in.opinionIds()).equals(new HashSet<>(ids))||in.opinionIds().size()!=ids.size())throw conflict("CONSULT_OPINIONS_CHANGED");snapshot=basis(cid);summary=event;}
      case CONFIRM -> {if(member==null||!member.state().equals("ACCEPTED"))throw missing();if(!Objects.equals(summary,in.summaryId())||!summaryCurrent(h))throw conflict("CONSULT_SUMMARY_CHANGED");}
      case ADOPT -> {required(in.content());if(!Objects.equals(summary,in.summaryId())||!ready(h))throw conflict("CONSULT_NOT_READY");var r=reports.current(caseId);var fields=r.fields().deepCopy();((tools.jackson.databind.node.ObjectNode)fields).put("notes",r.fields().get("notes").stringValue()+"\n"+in.content());var mutation=reports.appendDraft(caseId,new ReportContracts.Save(r.version(),c.assignmentVersion(),caseId,r.templateCode(),r.templateVersion(),fields,in.reason()),actor);adopted=reports.current(caseId).id();audit.append(c.hospitalId(),"REPORT_CONSULT_ADOPT_V1","REPORT_DRAFT",caseId,r.version(),mutation.receipt().version());state="ADOPTED";}
      default -> throw conflict("CONSULT_STATE");
     }
    }
    jdbc.update("INSERT INTO consultation_event(id,consultation_id,case_id,version,action,actor_id,target_id,disposition,content,reason,basis,summary_id,adopted_revision_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",event,cid,caseId,old+1,action.name(),actor.id(),action==Action.REVOKE?in.targetId():null,Set.of(Action.OPINION,Action.SUMMARY).contains(action)?in.disposition():null,in.content(),in.reason(),snapshot,Set.of(Action.CONFIRM,Action.ADOPT).contains(action)?summary:null,adopted);
    if(action==Action.OPINION)jdbc.update("UPDATE consultation_member SET opinion_id=?,confirmed_summary_id=NULL WHERE consultation_id=? AND user_id=?",event,cid,actor.id());if(action==Action.CONFIRM)jdbc.update("UPDATE consultation_member SET confirmed_summary_id=? WHERE consultation_id=? AND user_id=?",summary,cid,actor.id());
    if(h!=null&&jdbc.update("UPDATE report_consultation SET version=version+1,state=?,summary_id=? WHERE id=? AND version=?",state,summary,cid,old)!=1)throw conflict("VERSION_CONFLICT");
    return new IdempotentCommands.Mutation(new CommandReceipt(200,"REPORT_CONSULTATION",cid,old+1),old<0?null:old);
   }
  });}catch(ApiException e){rejections.record(initial.hospitalId(),initial.requestId(),action.name(),e.code());throw e;}
 }
 private static void required(String value){if(value==null||value.isBlank())throw conflict("CONSULT_TEXT_REQUIRED");}
 private static ApiException missing(){return new ApiException(HttpStatus.NOT_FOUND,"CONSULT_NOT_FOUND","Consultation access unavailable");}
 private static ApiException conflict(String code){return new ApiException(HttpStatus.CONFLICT,code,"Consultation requires explicit review");}
}
