import { fetchCsrf, readJson, request } from '../../api';
import { parseMaterial, type Material } from './api';
export const actions = { REGISTER: '登记细胞学标本', QC_PASS: '来源合成QC通过', QC_FAIL: '来源合成QC失败', IDENTITY_MISMATCH: '登记身份隔离', PREPARE: '预留材料并新建制备', COMPLETE: '核对消耗并生成材料', FAIL: '记录制备失败与数量去向' };
export const paths = { DIRECT_SMEAR: '直接涂片', LIQUID_BASED: '液基制片', CELL_BLOCK: '可选细胞蜡块' };
export type Action = keyof typeof actions; export type Path = keyof typeof paths;
export interface Specimen { id: string; containerId: string; patientId: string; caseId: string; initialQuantity: number; remaining: number; version: number; qcState: string; qcVersion: number; sampleDescription: string }
export interface Preparation { id: string; path: Path; metadata: string; transferred: number; sourceQcVersion: number; repeatOf: string | null; state: string; version: number }
export interface Event { id: string; version: number; preparationId: string | null; action: Action; transferred: number; consumed: number; discarded: number; returned: number; slides: number; reason: string; actorId: string; recordedAt: string }
export interface Detail { requestId: string; containerId: string; patientId: string; caseId: string; caseNumber: string; specimen: Specimen | null; preparations: Preparation[]; materials: Material[]; page: number; events: Event[] }
export interface Command { requestId: string; containerId: string; action: Action; body: { confirmedContainerId: string; expectedVersion: number; reason: string; metadata: string; path: Path | null; transferred: number; repeatOf: string | null; preparationId: string | null; preparationVersion: number; consumed: number; discarded: number; returned: number; slides: number } }
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('Invalid cytology response'); return v as Record<string, unknown>; }
function str(v: unknown): string { if (typeof v !== 'string' || !v) throw new Error('Invalid cytology text'); return v; }
function nullable(v: unknown): string | null { return v === null ? null : str(v); }
function num(v: unknown, min = 0): number { if (typeof v !== 'number' || !Number.isSafeInteger(v) || v < min) throw new Error('Invalid cytology count'); return v; }
function list(v: unknown, max: number): unknown[] { if (!Array.isArray(v) || v.length > max) throw new Error('Invalid cytology list'); return v; }
export function parseDetail(v: unknown, rid: string, cid: string, page: number): Detail {
 const d = obj(v); if (d.requestId !== rid || d.containerId !== cid || d.page !== page) throw new Error('Mismatched cytology identity');
 const patientId = str(d.patientId), caseId = str(d.caseId); let specimen: Specimen | null = null;
 if (d.specimen !== null) { const s = obj(d.specimen); if (s.containerId !== cid || s.patientId !== patientId || s.caseId !== caseId || !['PENDING', 'PASS', 'FAIL', 'IDENTITY_MISMATCH'].includes(str(s.qcState)) || num(s.remaining) > num(s.initialQuantity, 1) || num(s.initialQuantity) > 99) throw new Error('Invalid cytology source'); specimen = { id: str(s.id), containerId: cid, patientId, caseId, initialQuantity: num(s.initialQuantity, 1), remaining: num(s.remaining), version: num(s.version), qcState: str(s.qcState), qcVersion: num(s.qcVersion, -1), sampleDescription: str(s.sampleDescription) }; }
 const preparations = list(d.preparations, 100).map(v => { const p = obj(v), path = str(p.path), state = str(p.state); if (!Object.hasOwn(paths, path) || !['RESERVED', 'COMPLETED', 'FAILED'].includes(state)) throw new Error('Invalid preparation'); return { id: str(p.id), path: path as Path, metadata: str(p.metadata), transferred: num(p.transferred, 1), sourceQcVersion: num(p.sourceQcVersion), repeatOf: nullable(p.repeatOf), state, version: num(p.version) }; });
 const materials = list(d.materials, 100).map(parseMaterial); if (materials.some(m => m.requestId !== rid || m.patientId !== patientId || m.caseId !== caseId || m.containerId !== cid || !preparations.some(p => p.id === m.cytologyPreparationId))) throw new Error('Mismatched material preparation');
 if ((!specimen && (preparations.length > 0 || materials.length > 0)) || new Set(preparations.map(p => p.id)).size !== preparations.length || new Set(materials.map(m => m.id)).size !== materials.length || preparations.some(p => p.transferred > 99 || p.repeatOf !== null && !preparations.some(old => old.id === p.repeatOf && old.id !== p.id))) throw new Error('Invalid preparation history');
 if (materials.some(m => { const p = preparations.find(p => p.id === m.cytologyPreparationId); return !p || p.state !== 'COMPLETED' || (p.path !== 'CELL_BLOCK' ? m.kind !== 'SLIDE' || m.blockId !== null : m.kind === 'SLIDE' && !materials.some(b => b.id === m.blockId && b.kind === 'BLOCK' && b.cytologyPreparationId === p.id)); })) throw new Error('Mismatched cytology path');
 const events = list(d.events, 20).map(v => { const e = obj(v), action = str(e.action); if (!Object.hasOwn(actions, action)) throw new Error('Unknown cytology event'); return { id: str(e.id), version: num(e.version), preparationId: nullable(e.preparationId), action: action as Action, transferred: num(e.transferred), consumed: num(e.consumed), discarded: num(e.discarded), returned: num(e.returned), slides: num(e.slides), reason: str(e.reason), actorId: str(e.actorId), recordedAt: str(e.recordedAt) }; });
 if (new Set(events.map(e => e.id)).size !== events.length || events.some((e, i) => !specimen || e.version > specimen.version || i > 0 && e.version >= events[i - 1].version)) throw new Error('Invalid cytology history');
 return { requestId: rid, containerId: cid, patientId, caseId, caseNumber: str(d.caseNumber), specimen, preparations, materials, page, events };
}
const base = (rid: string, cid: string) => '/api/materials/requests/' + rid + '/cytology/' + cid;
export async function load(rid: string, cid: string, page: number, signal: AbortSignal) { return parseDetail(await readJson(await request(base(rid, cid) + '?page=' + page, { signal })), rid, cid, page); }
export async function send(c: Command, key: string) {
 const abort = new AbortController(), timer = setTimeout(() => abort.abort(), 15000);
 try { const csrf = await fetchCsrf(abort.signal); const result = obj(await readJson(await request(base(c.requestId, c.containerId) + '/' + c.action, { method: 'POST', signal: abort.signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify(c.body) }))), r = obj(result.receipt); if (r.resourceType !== 'CYTOLOGY_CONTAINER' || r.resourceId !== c.containerId || r.status !== 200 || r.version !== c.body.expectedVersion + 1) throw new Error('Mismatched cytology receipt'); return true; } finally { clearTimeout(timer); }
}
