import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Alert, Button, Card, Form, Input, InputNumber, Modal, Select, Table } from 'antd';
import { ApiError } from '../../api';
import { ReadController } from '../../shared/workflow';
import { ReadPanel } from '../../shared/WorkflowElements';
import { CommandIntent } from '../../shared/command';
import { actions, batchStates, load, send, type Action, type Command, type Detail } from './stainApi';
const invalidReasons: Record<string, string> = { NOT_FROZEN: '成员尚未冻结', CONTROL_MISSING: '缺少通过的对照记录', CONTROL_FAILED: '对照失败，必须使用新来源重跑', CONTROL_REVOKED: '对照已撤销，旧接受记录失效', RESULT_MISSING: '尚未录入人工技术结果', TECHNICAL_FAILED: '人工技术QC失败', SOURCE_CHANGED: '来源依赖已改变或输出玻片已作废' };
type Callbacks = { onDirty: () => void; onClean: () => void; onPending: (v: boolean) => void; onExpired: () => void };
export function Staining({ requestId, ...cb }: Callbacks & { requestId: string }) {
 const [id, setId] = useState<string | null>(null), [page, setPage] = useState(1), [action, setAction] = useState<Action>('CREATE'), [dirty, setDirty] = useState(false), [pending, setPending] = useState(false), [generation, setGeneration] = useState(0), [next, setNext] = useState<(() => void) | null>(null);
 const [reader] = useState(() => new ReadController(async (key: { id: string | null; page: number }, signal: AbortSignal) => { try { return { status: 'ready' as const, data: await load(requestId, key.id, key.page, signal) }; } catch (e) { if (e instanceof ApiError && e.status === 401) cb.onExpired(); throw e; } }));
 const [catalog] = useState(() => new ReadController(async (_: null, signal: AbortSignal) => { try { return { status: 'ready' as const, data: await load(requestId, null, 1, signal) }; } catch (e) { if (e instanceof ApiError && e.status === 401) cb.onExpired(); throw e; } }));
 const catalogState = useSyncExternalStore(catalog.subscribe, catalog.getSnapshot), detailState = useSyncExternalStore(reader.subscribe, reader.getSnapshot); const state = id === null ? catalogState : detailState;
 useEffect(() => { void catalog.run(null); return catalog.stop; }, [catalog]);
 useEffect(() => { if (id !== null) void reader.run({ id, page }); return reader.stop; }, [reader, id, page]);
 function reload() { void catalog.run(null); if (id !== null) void reader.run({ id, page }); }

 function clean() { setDirty(false); cb.onClean(); }
 function change(fn: () => void) { if (pending) return; if (dirty) setNext(() => fn); else { clean(); setGeneration(v => v + 1); fn(); } }
 function saved(bid: string) { void catalog.run(null); clean(); setGeneration(v => v + 1); if (bid !== id) { setId(bid); setPage(1); setAction('FREEZE'); } else void reader.run({ id, page }); }
 function select(bid: string | null) { setId(bid); setPage(1); setAction(bid ? 'FREEZE' : 'CREATE'); }
 return <><Alert type="warning" title="特殊染色 / IHC · 本地合成记录" description="无仪器执行、厂商方案或诊断推荐。单病例批次；每张新染色身份对应一张已登记来源玻片。对照登记不等于有效结果。" /><Button disabled={pending} onClick={() => change(reload)}>重新读取染色批次</Button>
 <ReadPanel state={catalogState}>{d => <Card title="本病例合成批次"><Button disabled={pending} onClick={() => change(() => select(null))}>新建染色批次</Button>{d.batches.map(b => <Button key={b.id} disabled={pending} style={{ maxWidth: '100%', height: 'auto', whiteSpace: 'normal', overflowWrap: 'anywhere' }} onClick={() => { if (b.id !== id) change(() => select(b.id)); }}>查看染色批次 {b.id}</Button>)}</Card>}</ReadPanel>
 <ReadPanel state={state}>{d => <><section className="identity-strip" aria-label="染色病例身份"><strong>{d.caseNumber}</strong><span>患者 {d.patientId}</span><span>申请 {requestId}</span><span>病例 {d.caseId}</span></section>
 {d.selected && <Card title="确切批次与版本"><p style={{ overflowWrap: 'anywhere' }}>{d.selected.id} / v{d.selected.version} · 冻结版本 {d.selected.frozenVersion ?? '无'} · {batchStates[d.selected.state]}</p><p>项目 {d.selected.kind} / {d.selected.projectCode} v{d.selected.projectVersion} · 方案 {d.selected.schemeCode} v{d.selected.schemeVersion}</p><p>人工开发元数据：{d.selected.metadata}</p><p>试剂批号 {d.selected.reagentLot} · 有效期 {d.selected.expiresOn}（UTC业务日，含到期当天）</p><p style={{ overflowWrap: 'anywhere' }}>对照材料 {d.selected.controlReference} / {d.selected.controlId} · 当前对照事件 {d.selected.controlEventId ?? '无'}</p><p>重跑来源 {d.selected.rerunOf ?? '无'}；旧结果与旧身份保留</p></Card>}
 <label htmlFor="stain-action">染色批次操作</label><Select id="stain-action" virtual={false} style={{ width: '100%' }} disabled={pending} value={action} options={Object.entries(actions).filter(([a]) => id ? a !== 'CREATE' : a === 'CREATE').map(([value, label]) => ({ value, label }))} onChange={(v: Action) => change(() => setAction(v))} />
 <Entry key={(id ?? 'new') + ':' + action + ':' + generation} d={d} action={action} {...cb} onDirty={() => { setDirty(true); cb.onDirty(); }} onClean={clean} onPending={v => { setPending(v); cb.onPending(v); }} onSaved={saved} />
 <Card title="申请、冻结成员与独立玻片"><Table rowKey="id" dataSource={d.orders} pagination={false} scroll={{ x: 1000 }} columns={[{ title: '检测申请', dataIndex: 'id' }, { title: '来源玻片 / 版本', render: (_, o) => <span>{o.sourceId} / v{o.sourceVersion}</span> }, { title: '新染色玻片', render: (_, o) => o.outputId ?? '未冻结，不产生材料' }, { title: '当前有效性', render: (_, o) => <span>{o.effectiveState === 'PASS' ? '本批次技术结果有效（仍需材料QC）' : '未就绪／已隔离'}<br />{o.invalidReason ? invalidReasons[o.invalidReason] ?? '依赖未就绪，请核对历史' : ''}</span> }]} /></Card>
 <Card title="不可覆盖的对照与结果历史"><Table rowKey="id" dataSource={d.events} pagination={false} scroll={{ x: 1200 }} columns={[{ title: '动作 / 版本', render: (_, e) => <span>{actions[e.action]} / v{e.version}<br />{e.id}</span> }, { title: '绑定', render: (_, e) => <span>申请 {e.orderId ?? '—'}<br />冻结 {e.frozenVersion ?? '—'}<br />对照 {e.controlEventId ?? '—'}</span> }, { title: '人工结果 / 原因', render: (_, e) => <span style={{ whiteSpace: 'pre-wrap' }}>{e.technicalQc ?? '—'}<br />{e.content}<br />{e.reason}</span> }, { title: '人员 / 时间', render: (_, e) => <span>{e.actorId}<br />{e.recordedAt}</span> }]} /><Button disabled={pending || page === 1} onClick={() => change(() => setPage(p => p - 1))}>上一页染色历史</Button><span>第 {page} 页</span><Button disabled={pending || d.events.length < 20 || page >= 10000} onClick={() => change(() => setPage(p => p + 1))}>下一页染色历史</Button></Card>
 </>}</ReadPanel><Modal open={!!next} title="放弃染色输入并切换批次或操作？" okText="清除并继续" cancelText="继续编辑" onCancel={() => setNext(null)} onOk={() => { const fn = next; setNext(null); clean(); setGeneration(v => v + 1); fn?.(); }}>清除不适用字段；已提交的服务器操作不会撤销。</Modal></>;
}
interface Values { confirmedId: string; sourceIds?: string[]; kind?: 'SPECIAL' | 'IHC'; projectCode?: string; projectVersion?: number; schemeCode?: string; schemeVersion?: number; metadata?: string; reagentLot?: string; expiresOn?: string; controlReference?: string; rerunOf?: string; orderId?: string; technicalQc?: 'TECH_PASS' | 'TECH_FAIL'; content?: string; reason: string }
function Entry({ d, action, onDirty, onClean, onPending, onExpired, onSaved }: Callbacks & { d: Detail; action: Action; onSaved: (id: string) => void }) {
 const [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [message, setMessage] = useState(''); const [intent] = useState(() => new CommandIntent<Command>()); const active = useRef(false), alive = useRef(true), original = useRef<Command | undefined>(undefined);
 useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
 async function execute(c: Command) { if (active.current) return; active.current = true; original.current = c; setBusy(true); onDirty(); onPending(true); setMessage(''); try { const result = await intent.run(c, send); if (result && alive.current) { onPending(false); onClean(); onSaved(result); } } catch (e) { if (!alive.current) return; if (e instanceof ApiError && e.status === 401) { onExpired(); return; } const definite = e instanceof ApiError && ([400, 403, 404].includes(e.status) || e.status === 409 && !['COMMAND_BUSY', 'HTTP_ERROR'].includes(e.code)); if (definite) { intent.rejected(); onPending(false); } setUncertain(!definite); setMessage(definite ? e.message : '结果待确认；保留原病例、批次、版本、输入及幂等键重试。'); } finally { active.current = false; if (alive.current) setBusy(false); } }
 const control = ['CONTROL_PASS', 'CONTROL_FAIL', 'REVOKE', 'RESULT'].includes(action);
 return <Card title={actions[action]}>{message && <Alert role="status" title={message} />}{uncertain && <Button disabled={busy} onClick={() => { if (original.current) void execute(original.current); }}>确认原染色请求</Button>}
 <Form<Values> layout="vertical" disabled={busy || uncertain} onValuesChange={onDirty} onFinish={v => { if (busy || uncertain) return; const sources = (v.sourceIds ?? []).map(id => d.sources.find(s => s.id === id)).filter(s => s !== undefined).map(s => ({ id: s.id, version: s.version })); void execute({ requestId: d.requestId, batchId: d.selected?.id ?? null, action, body: { confirmedRequestId: v.confirmedId, expectedVersion: d.selected?.version ?? -1, reason: v.reason, sources, kind: v.kind ?? null, projectCode: v.projectCode ?? null, projectVersion: v.projectVersion ?? null, schemeCode: v.schemeCode ?? null, schemeVersion: v.schemeVersion ?? null, metadata: v.metadata ?? null, reagentLot: v.reagentLot ?? null, expiresOn: v.expiresOn ?? null, controlReference: v.controlReference ?? null, rerunOf: v.rerunOf ?? null, orderId: v.orderId ?? null, frozenVersion: d.selected?.frozenVersion ?? null, controlEventId: d.selected?.controlEventId ?? null, technicalQc: v.technicalQc ?? null, content: v.content ?? '' } }); }}>
 <Form.Item name="confirmedId" label="核对染色申请 UUID" rules={[{ validator: (_, v: unknown) => v === d.requestId ? Promise.resolve() : Promise.reject(new Error('请核对申请UUID')) }]}><Input maxLength={36} /></Form.Item>
 {['CREATE', 'ADD'].includes(action) && <Form.Item name="sourceIds" label="逐张核对来源玻片（最多20张）" rules={[{ required: true }]}><Select mode="multiple" virtual={false} options={d.sources.map(s => ({ value: s.id, label: s.number + ' / ' + s.id + ' / QC ' + s.qcState, disabled: s.state !== 'ACTIVE' || s.qcState !== 'PASS' || s.route === 'STAINED_SLIDE' }))} /></Form.Item>}
 {action === 'CREATE' && <><Form.Item name="kind" label="合成检测类型" rules={[{ required: true }]}><Select virtual={false} options={[{ value: 'SPECIAL', label: '特殊染色（合成）' }, { value: 'IHC', label: 'IHC（合成）' }]} /></Form.Item>
 {(['projectCode', 'schemeCode'] as const).map(name => <Form.Item key={name} name={name} label={name === 'projectCode' ? '开发项目代码' : '开发方案代码'} rules={[{ required: true }, { pattern: /^SYN-[A-Z0-9-]{1,40}$/, message: '仅SYN-开头的开发标识' }]}><Input maxLength={44} /></Form.Item>)}
 {(['projectVersion', 'schemeVersion'] as const).map(name => <Form.Item key={name} name={name} label={name === 'projectVersion' ? '项目版本' : '方案版本'} rules={[{ required: true }]}><InputNumber min={1} max={9999} precision={0} /></Form.Item>)}
 <Form.Item name="metadata" label="不可变开发元数据（无厂商操作方案）" rules={[{ required: true, whitespace: true }]}><Input.TextArea maxLength={1000} /></Form.Item><Form.Item name="reagentLot" label="人工合成试剂批号" rules={[{ required: true, whitespace: true }]}><Input maxLength={120} /></Form.Item><Form.Item name="expiresOn" label="合成有效期（UTC日期）" rules={[{ required: true }, { pattern: /^\d{4}-\d\d-\d\d$/, message: 'YYYY-MM-DD' }]}><Input maxLength={10} /></Form.Item><Form.Item name="controlReference" label="人工合成对照材料标识及说明" rules={[{ required: true, whitespace: true }]}><Input maxLength={255} /></Form.Item><Form.Item name="rerunOf" label="重跑来源批次（可选）"><Select allowClear virtual={false} options={d.batches.filter(b => b.frozenVersion !== null).map(b => ({ value: b.id, label: b.id + ' / ' + batchStates[b.state] }))} /></Form.Item></>}
 {action === 'FREEZE' && <Alert type="warning" title="冻结后不能追加成员；逐张转移为新身份，旧玻片保留来源历史，不自动返还数量。" />}
 {action === 'RESULT' && <><Form.Item name="orderId" label="核对确切检测申请" rules={[{ required: true }]}><Select virtual={false} options={d.orders.filter(o => o.outputId && !o.resultId).map(o => ({ value: o.id, label: o.id + ' / 新玻片 ' + o.outputId }))} /></Form.Item><Form.Item name="technicalQc" label="人工技术QC结果" rules={[{ required: true }]}><Select virtual={false} options={[{ value: 'TECH_PASS', label: '技术记录通过（非诊断）' }, { value: 'TECH_FAIL', label: '技术记录失败／隔离' }]} /></Form.Item></>}
 {control && <Form.Item name="content" label="人工对照／技术观察及撤销依据" rules={[{ required: true, whitespace: true }]}><Input.TextArea rows={4} maxLength={4000} /></Form.Item>}
 <Form.Item name="reason" label="染色操作／重跑原因" rules={[{ required: true, whitespace: true }]}><Input.TextArea maxLength={2000} /></Form.Item><Button type="primary" htmlType="submit" disabled={busy || uncertain}>{actions[action]}并保存</Button></Form></Card>;
}
