import { fetchCsrf, readJson, request } from '../../api';
export const actions = { CREATE: '登记合成检测批次', ADD: '追加待冻结检测申请', FREEZE: '核对数量并冻结成员', CONTROL_PASS: '记录对照通过', CONTROL_FAIL: '记录对照失败', REVOKE: '撤销对照并隔离', RESULT: '登记人工技术结果' };
export type Action = keyof typeof actions;
export const batchStates: Record<string, string> = { DRAFT: '草稿／成员未冻结', FROZEN: '已冻结／对照未通过', PASS: '对照通过／仍需逐项结果与QC', FAIL: '对照失败／禁止放行', REVOKED: '对照撤销／旧结果失效' };
export interface Batch { id: string; state: string; version: number; frozenVersion: number | null; controlId: string; controlEventId: string | null; controlReference: string; reagentLot: string; expiresOn: string; rerunOf: string | null; kind: 'SPECIAL' | 'IHC'; projectCode: string; projectVersion: number; schemeCode: string; schemeVersion: number; metadata: string }
export interface Source { id: string; number: string; version: number; blockId: string | null; route: string; state: string; qcState: string }
export interface Order { id: string; sourceId: string; sourceVersion: number; outputId: string | null; resultId: string | null; effectiveState: string; invalidReason: string | null }
export interface Event { id: string; version: number; action: Action; orderId: string | null; frozenVersion: number | null; controlEventId: string | null; technicalQc: string | null; content: string; reason: string; actorId: string; recordedAt: string }
export interface Detail { requestId: string; patientId: string; caseId: string; caseNumber: string; batches: Batch[]; selected: Batch | null; sources: Source[]; orders: Order[]; page: number; events: Event[] }
export interface Body { confirmedRequestId: string; expectedVersion: number; reason: string; sources: { id: string; version: number }[]; kind: 'SPECIAL' | 'IHC' | null; projectCode: string | null; projectVersion: number | null; schemeCode: string | null; schemeVersion: number | null; metadata: string | null; reagentLot: string | null; expiresOn: string | null; controlReference: string | null; rerunOf: string | null; orderId: string | null; frozenVersion: number | null; controlEventId: string | null; technicalQc: 'TECH_PASS' | 'TECH_FAIL' | null; content: string }
export interface Command { requestId: string; batchId: string | null; action: Action; body: Body }
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('Invalid staining response'); return v as Record<string, unknown>; }
function str(v: unknown, empty = false): string { if (typeof v !== 'string' || (!empty && !v)) throw new Error('Invalid staining text'); return v; }
function nullable(v: unknown): string | null { return v === null ? null : str(v); }
function num(v: unknown): number { if (typeof v !== 'number' || !Number.isSafeInteger(v) || v < 0) throw new Error('Invalid staining version'); return v; }
function version(v: unknown) { return v === null ? null : num(v); }
function list(v: unknown, limit: number): unknown[] { if (!Array.isArray(v) || v.length > limit) throw new Error('Invalid staining list'); return v; }
function batch(v: unknown): Batch { const b = obj(v); const state = str(b.state), kind = str(b.kind), frozen = version(b.frozenVersion), ver = num(b.version); if (!Object.hasOwn(batchStates, state) || !['SPECIAL', 'IHC'].includes(kind) || (state === 'DRAFT') !== (frozen === null) || (frozen !== null && frozen > ver) || !/^\d{4}-\d\d-\d\d$/.test(str(b.expiresOn))) throw new Error('Invalid batch state'); return { id: str(b.id), state, kind: kind as Batch['kind'], version: ver, frozenVersion: frozen, controlId: str(b.controlId), controlEventId: nullable(b.controlEventId), controlReference: str(b.controlReference), reagentLot: str(b.reagentLot), expiresOn: str(b.expiresOn), rerunOf: nullable(b.rerunOf), projectCode: str(b.projectCode), projectVersion: num(b.projectVersion), schemeCode: str(b.schemeCode), schemeVersion: num(b.schemeVersion), metadata: str(b.metadata) }; }
export function parseDetail(value: unknown, rid: string, bid: string | null, page: number): Detail {
 const d = obj(value); if (d.requestId !== rid || d.page !== page) throw new Error('Mismatched staining request'); const selected = d.selected === null ? null : batch(d.selected); if ((selected?.id ?? null) !== bid) throw new Error('Mismatched staining batch');
 const batches = list(d.batches, 100).map(batch); if (new Set(batches.map(b => b.id)).size !== batches.length || selected && !batches.some(b => b.id === selected.id && b.version === selected.version)) throw new Error('Invalid batch list');
 const sources = list(d.sources, 100).map(v => { const s = obj(v); return { id: str(s.id), number: str(s.number), version: num(s.version), blockId: nullable(s.blockId), route: str(s.route), state: str(s.state), qcState: str(s.qcState) }; });
 const orders = list(d.orders, 20).map(v => { const o = obj(v), state = str(o.effectiveState); if (!['NOT_FROZEN', 'PASS', 'SOURCE_QUARANTINED'].includes(state)) throw new Error('Unknown result state'); return { id: str(o.id), sourceId: str(o.sourceId), sourceVersion: num(o.sourceVersion), outputId: nullable(o.outputId), resultId: nullable(o.resultId), effectiveState: state, invalidReason: nullable(o.invalidReason) }; });
 if (orders.some(o => !selected || !sources.some(s => s.id === o.sourceId) || o.effectiveState === 'PASS' && (!o.resultId || !o.outputId || selected.state !== 'PASS')) || new Set(orders.map(o => o.id)).size !== orders.length) throw new Error('Invalid staining lineage');
 const events = list(d.events, 20).map(v => { const e = obj(v), action = str(e.action), qc = nullable(e.technicalQc); if (!Object.hasOwn(actions, action) || qc !== null && !['TECH_PASS', 'TECH_FAIL'].includes(qc)) throw new Error('Unknown staining event'); return { id: str(e.id), version: num(e.version), action: action as Action, orderId: nullable(e.orderId), frozenVersion: version(e.frozenVersion), controlEventId: nullable(e.controlEventId), technicalQc: qc, content: str(e.content, true), reason: str(e.reason), actorId: str(e.actorId), recordedAt: str(e.recordedAt) }; });
 if (events.some((e, i) => !selected || e.version > selected.version || i > 0 && e.version >= events[i - 1].version) || new Set(events.map(e => e.id)).size !== events.length) throw new Error('Invalid staining history');
 return { requestId: rid, patientId: str(d.patientId), caseId: str(d.caseId), caseNumber: str(d.caseNumber), selected, batches, sources, orders, page, events };
}
const base = (rid: string) => '/api/materials/requests/' + encodeURIComponent(rid) + '/staining';
export async function load(rid: string, bid: string | null, page: number, signal: AbortSignal) { return parseDetail(await readJson(await request(base(rid) + '?page=' + page + (bid ? '&batch=' + encodeURIComponent(bid) : ''), { signal })), rid, bid, page); }
export async function send(c: Command, key: string): Promise<string> { const abort = new AbortController(), timer = setTimeout(() => abort.abort(), 15000); try { const csrf = await fetchCsrf(abort.signal); const r = obj(obj(await readJson(await request(base(c.requestId) + '/' + c.action + (c.batchId ? '?batch=' + encodeURIComponent(c.batchId) : ''), { method: 'POST', signal: abort.signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify(c.body) }))).receipt); if (r.resourceType !== 'STAIN_BATCH' || r.status !== 200 || r.version !== c.body.expectedVersion + 1 || c.batchId !== null && r.resourceId !== c.batchId) throw new Error('Mismatched staining receipt'); return str(r.resourceId); } finally { clearTimeout(timer); } }
