import { signInWorkflow } from './workflow-login';
import { test, expect } from '@playwright/test';

test('manual synthetic identity and request persist without an existing encounter', async ({ page }) => {
  await signInWorkflow(page);
  await page.getByRole('button', { name: '申请登记工作区' }).click();
  await page.getByLabel('授权工作范围').click();
  await page.getByText('合成申请工作范围', { exact: true }).last().click();
  await page.getByRole('button', { name: '手工申请', exact: true }).last().click();
  const number = 'SYN-MANUAL-' + crypto.randomUUID();
  await page.getByLabel('患者显示名', { exact: true }).fill('合成手工患者');
  await page.getByLabel('手工就诊号', { exact: true }).fill(number);
  await page.getByLabel('部位', { exact: true }).fill('合成手工样本');
  const response = page.waitForResponse(r => r.url().endsWith('/api/requests/manual') && r.request().method() === 'POST');
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  const created = await response;
  expect(created.status()).toBe(201);
  const body = await created.json() as { receipt: { resourceId: string } };
  await expect(page.getByTestId('request-row-' + body.receipt.resourceId)).toContainText(number);
  const detail = await page.request.get('/api/requests/' + body.receipt.resourceId);
  expect(detail.status()).toBe(200);
  const record = await detail.json() as { patientId: string; encounterId: string; patientLabel: string; state: string };
  expect(record.patientId).toMatch(/^[0-9a-f-]{36}$/);
  expect(record.encounterId).toMatch(/^[0-9a-f-]{36}$/);
  expect(record.patientLabel).toBe('合成手工患者');
  expect(record.state).toBe('DRAFT');
  await page.reload();
  await page.getByRole('button', { name: '申请登记工作区' }).click();
  await page.getByLabel('授权工作范围').click();
  await page.getByText('合成申请工作范围', { exact: true }).last().click();
  await expect(page.getByTestId('request-row-' + body.receipt.resourceId)).toContainText(number);
});

// Actual login, CSRF/session, application and PostgreSQL. No routes are mocked in this suite.
test('synthetic request registration, editing and submission persist through real API', async ({ page }) => {
  await signInWorkflow(page);
  await page.getByRole('button', { name: '申请登记工作区' }).click();
  await page.getByLabel('授权工作范围').click();
  await page.getByText('合成申请工作范围', { exact: true }).last().click();
  await page.getByRole('button', { name: '病理申请录入', exact: true }).click();
  await page.getByLabel('精确就诊号').fill('SYN-WORKFLOW-001');
  await page.getByRole('button', { name: '查找就诊' }).click();
  await page.getByLabel('选择已核对就诊').click();
  await page.getByText('合成申请患者 / SYN-WORKFLOW-001', { exact: true }).last().click();
  await page.getByLabel('临床诊断与病史', { exact: true }).fill('合成临床资料，仅用于自动化测试');
  await page.getByLabel('手术 / 采样时间（UTC）').fill('2026-01-01T08:00');
  await page.getByLabel('部位', { exact: true }).fill('合成测试部位');
  await page.getByLabel('固定液', { exact: true }).fill('合成测试固定液');
  await page.getByLabel('固定开始时间（UTC）').fill('2026-01-01T08:10');
  const createdResponse = page.waitForResponse(response => response.url().endsWith('/api/requests') && response.request().method() === 'POST');
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  const created = await createdResponse; expect(created.status()).toBe(201);
  const { receipt } = await created.json() as { receipt: { resourceId: string } };
  const detailResponse = await page.request.get('/api/requests/' + receipt.resourceId);
  expect(detailResponse.status()).toBe(200);
  const detail = await detailResponse.json() as { id: string; requestNumber: string; encounterNumber: string };
  expect(detail.id).toBe(receipt.resourceId); expect(detail.encounterNumber).toBe('SYN-WORKFLOW-001');
  const row = page.getByTestId('request-row-' + receipt.resourceId);
  const open = () => row.getByRole('button', { name: '查看 ' + detail.requestNumber, exact: true }).click();
  await expect(page.getByText('服务器已确认操作；列表将重新查询。')).toBeVisible();
  await open();
  await expect(page.getByLabel('临床诊断与病史', { exact: true })).toHaveValue('合成临床资料，仅用于自动化测试');
  await page.getByLabel('临床诊断与病史', { exact: true }).fill('修订后的合成资料');
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  await open();
  await expect(page.getByLabel('临床诊断与病史', { exact: true })).toHaveValue('修订后的合成资料');
  await page.getByRole('button', { name: '核对后提交', exact: true }).click();
  await expect(row.getByRole('cell', { name: '待接收', exact: true })).toBeVisible();
  await open();
  await expect(page.getByRole('button', { name: '保存草稿', exact: true })).toBeDisabled();
  await expect(page.getByLabel('临床诊断与病史', { exact: true })).toBeDisabled();
});
