import {test,expect} from '@playwright/test';
import {signInWorkflow} from './workflow-login';
import type {View,Item} from '../src/features/integration/api';
test('local adapter persists source binding receipt dedup and explicit ACK then reconciliation',async({page})=>{
 await signInWorkflow(page);const scopes=await(await page.request.get('/api/requests/scopes')).json() as {id:string}[];const encounters=await(await page.request.get('/api/requests/encounters',{params:{scopeId:scopes[0].id,number:'SYN-WORKFLOW-001'}})).json() as {id:string;patientId:string}[];const csrf=await(await page.request.get('/api/auth/csrf')).json() as {token:string};const headers=()=>({'X-CSRF-TOKEN':csrf.token,'Idempotency-Key':crypto.randomUUID()});const created=await page.request.post('/api/requests',{headers:headers(),data:{scopeId:scopes[0].id,encounterId:encounters[0].id,draft:{clinicalHistory:'Synthetic interface observation',sampledAt:'2026-01-01T08:00:00Z',containers:[{site:'Synthetic',laterality:'UNKNOWN',materialQuantity:1,fixative:'Synthetic',fixedAt:'2026-01-01T08:10:00Z'}]}}});expect(created.status()).toBe(201);const rid=(await created.json() as {receipt:{resourceId:string}}).receipt.resourceId;expect((await page.request.post('/api/requests/'+rid+'/submit',{headers:headers(),data:{expectedVersion:0}})).status()).toBe(200);const d=await(await page.request.get('/api/requests/'+rid)).json() as {containers:{id:string}[];requestNumber:string};expect((await page.request.post('/api/receptions/'+rid+'/receive',{headers:headers(),data:{expectedVersion:1,patientId:encounters[0].patientId,encounterNumber:'SYN-WORKFLOW-001',containerIds:d.containers.map(c=>c.id)}})).status()).toBe(200);
 const path='/api/requests/'+rid+'/adapters',read=async()=>{const r=await page.request.get(path);expect(r.status()).toBe(200);return await r.json() as View;};const initial=await read();expect(initial.capabilities.HL7_FHIR).toBe('NOT_CONFIGURED');
 await page.getByRole('button',{name:'申请登记工作区',exact:true}).click();await expect(page.getByText('当前工作范围：合成申请工作范围', { exact: true })).toBeVisible();await page.getByRole('button',{name:'查看 '+d.requestNumber,exact:true}).click();await page.getByRole('button',{name:'处理此申请接口',exact:true}).click();await page.getByLabel('合成来源关联ID').fill('SYN-E2E-ONE');await page.getByLabel('合成操作编码').fill('SYN-LINK');await page.getByLabel('本地来源序号').fill('1');await page.getByLabel('核对接口病例UUID').fill(initial.caseId);await page.getByLabel('接口操作原因').fill('Synthetic local observation, no clinical action');await page.getByRole('button',{name:'核对本地接口操作',exact:true}).click();const response=page.waitForResponse(r=>new URL(r.url()).pathname===path&&r.request().method()==='POST');await page.getByRole('button',{name:'确认仅本地合成操作',exact:true}).click();expect((await response).status()).toBe(200);await expect(page.getByRole('cell',{name:'QUEUED',exact:true})).toBeVisible();const id=(await read()).items[0].id;
 const act=async(action:string,item?:Item)=>{const i=item??(await read()).items[0];return page.request.post(path+'/'+id+'/'+action,{headers:headers(),data:{confirmedCaseId:i.caseId,sourceId:i.sourceId,payloadHash:i.payloadHash,expectedVersion:i.version,attemptId:action==='CLAIM'?null:i.attemptId,reason:'Synthetic explicit '+action,confirmed:true}});};expect((await act('CLAIM')).status()).toBe(200);expect((await act('ACK')).status()).toBe(409);expect((await act('RECEIVE')).status()).toBe(200);expect((await read()).items[0]).toMatchObject({state:'ATTEMPTING',locallyRecorded:true});expect((await act('RECEIVE')).status()).toBe(200);expect((await act('ACK')).status()).toBe(200);expect((await act('RECONCILE')).status()).toBe(200);await page.getByRole('button',{name:'刷新接口队列',exact:true}).click();await expect(page.getByRole('cell',{name:'RECONCILED',exact:true})).toBeVisible();await page.getByRole('button',{name:'处理消息 '+id,exact:true}).click();await expect(page.getByText('追加接口历史',{exact:true})).toBeVisible();expect((await read()).items).toHaveLength(1);const original=await page.request.get('/api/requests/'+rid);expect((await original.json() as {state:string}).state).toBe('RECEIVED');
 const ops=await page.request.get('/api/requests/'+rid+'/operations');expect(ops.status()).toBe(200);expect(ops.headers()['cache-control']).toContain('no-store');expect(await ops.json()).toMatchObject({requestId:rid,pending:0,failed:0,recovery:'NOT_VERIFIED',encryption:'NOT_CONFIGURED'});
 await page.getByRole('button',{name:'申请单查询',exact:true}).click();await page.getByRole('button',{name:'查看 '+d.requestNumber,exact:true}).click();await page.getByRole('button',{name:'查看此申请运维',exact:true}).click();await expect(page.getByText('当前实例恢复验证',{exact:true})).toBeVisible();await expect(page.getByText('NOT_VERIFIED',{exact:true})).toBeVisible();

});
