import { signInWorkflow } from './workflow-login';
import { test, expect } from '@playwright/test';

test('grossing keeps description revisions, cassette sources and private photo withdrawal', async ({ page }) => {
  await signInWorkflow(page);
  await page.getByRole('button', { name: '申请登记工作区' }).click();
  const scopes = await (await page.request.get('/api/requests/scopes')).json() as { id: string }[];
  const encounters = await (await page.request.get('/api/requests/encounters', { params: { scopeId: scopes[0].id, number: 'SYN-GROSS-001' } })).json() as { id: string; patientId: string }[];
  const csrf = await (await page.request.get('/api/auth/csrf')).json() as { token: string };
  const headers = () => ({ 'X-CSRF-TOKEN': csrf.token, 'Idempotency-Key': crypto.randomUUID() });
  const created = await page.request.post('/api/requests', { headers: headers(), data: { scopeId: scopes[0].id, encounterId: encounters[0].id,
    draft: { clinicalHistory: 'Synthetic grossing E2E', sampledAt: '2026-01-01T08:00:00Z', containers: [{ site: 'Synthetic site', laterality: 'UNKNOWN', materialQuantity: 1, fixative: 'Synthetic fixative', fixedAt: '2026-01-01T08:10:00Z' }] } } });
  expect(created.status()).toBe(201);
  const { receipt } = await created.json() as { receipt: { resourceId: string } };
  expect((await page.request.post(`/api/requests/${receipt.resourceId}/submit`, { headers: headers(), data: { expectedVersion: 0 } })).status()).toBe(200);
  const detail = await (await page.request.get('/api/requests/' + receipt.resourceId)).json() as { requestNumber: string; containers: { id: string }[] };
  const cid = detail.containers[0].id;
  expect((await page.request.post(`/api/receptions/${receipt.resourceId}/receive`, { headers: headers(), data: { expectedVersion: 1, patientId: encounters[0].patientId, encounterNumber: 'SYN-GROSS-001', containerIds: [cid] } })).status()).toBe(200);
  await page.getByLabel('授权工作范围').click(); await page.getByText('合成申请工作范围', { exact: true }).last().click();
  await page.getByTestId('request-row-' + receipt.resourceId).getByRole('button', { name: '查看 ' + detail.requestNumber, exact: true }).click();
  await page.getByRole('button', { name: '处理此病例取材' }).click();
  await page.getByLabel('大体描述', { exact: true }).fill('Synthetic initial gross description');
  await page.getByRole('button', { name: '建立取材记录', exact: true }).dblclick();
  await expect(page.getByLabel('取材病例身份')).toContainText('DRAFT');
  const operation = async (name: string) => {
    await page.getByLabel('取材操作', { exact: true }).click();
    await page.getByRole('option', { name, exact: true }).click();
  };
  await operation('新增取材盒');
  await page.getByLabel('来源已接收容器').click();
  await page.getByText(cid + ' / Synthetic site', { exact: true }).last().click();
  await page.keyboard.press('Escape');
  await page.getByLabel('取材部位', { exact: true }).fill('Synthetic cassette site');
  await page.getByRole('button', { name: '新增取材盒', exact: true }).click();
  await expect(page.getByText('Synthetic cassette site', { exact: true })).toBeVisible();
  await operation('添加合成图像');
  await page.getByLabel('图像关联容器').click();
  await page.getByText(cid + ' / Synthetic site', { exact: true }).last().click();
  await page.getByLabel('合成图像备注').fill('Synthetic private illustration');
  await page.getByRole('button', { name: '选择随包合成PNG样本', exact: true }).click();
  await expect(page.getByText('已核验随包合成PNG样本，尚未保存附件。')).toBeVisible();
  await page.getByRole('button', { name: '添加合成图像', exact: true }).click();
  await page.getByRole('button', { name: '查看合成图像', exact: true }).click();
  await expect(page.getByRole('img', { name: '合成取材示意图，不是真实照片，无测量校准' })).toBeVisible();
  const before = await (await page.request.get('/api/grossing/requests/' + receipt.resourceId)).json() as { record: { id: string; photos: { id: string }[]; cassettes: { id: string }[] } };
  expect(before.record.photos).toHaveLength(1); expect(before.record.cassettes).toHaveLength(1);
  await operation('撤回图像');
  await page.getByLabel('撤回的图像').click();
  await page.getByText('Synthetic private illustration', { exact: true }).last().click();
  await page.getByLabel('操作原因 / 更正说明').fill('Synthetic withdrawn attachment');
  await page.getByRole('button', { name: '撤回图像', exact: true }).click();
  await expect(page.getByText('已撤回或记录已取消，不能下载')).toBeVisible();
  await expect(page.getByRole('img', { name: '合成取材示意图，不是真实照片，无测量校准' })).toHaveCount(0);
  expect((await page.request.get('/api/grossing/photos/' + before.record.photos[0].id + '/content')).status()).toBe(409);
  await operation('完成取材记录');
  await page.getByLabel('操作原因 / 更正说明').fill('Synthetic completed record only');
  await page.getByRole('button', { name: '完成取材记录', exact: true }).click();
  await expect(page.getByLabel('取材病例身份')).toContainText('COMPLETED');
  await page.getByLabel('大体描述', { exact: true }).fill('Synthetic corrected description');
  await page.getByLabel('操作原因 / 更正说明').fill('Synthetic appended correction');
  const correctionResponse = page.waitForResponse(response => new URL(response.url()).pathname === '/api/grossing/records/' + before.record.id + '/correction' && response.request().method() === 'POST');
  await page.getByRole('button', { name: '更正已完成描述', exact: true }).click();
  const correction = await correctionResponse; expect(correction.status()).toBe(200);
  const saved = await correction.json() as { receipt: { resourceId: string; version: number } };
  expect(saved.receipt.resourceId).toBe(before.record.id);
  await expect(page.getByLabel('取材病例身份')).toContainText('版本 ' + saved.receipt.version);
  const revisions = page.getByRole('region', { name: '取材描述修订', exact: true });
  await expect(revisions).toHaveAttribute('data-record-id', before.record.id);
  await expect(revisions.getByRole('cell', { name: 'Synthetic corrected description', exact: true })).toBeVisible();
  const after = await (await page.request.get('/api/grossing/requests/' + receipt.resourceId)).json() as { record: { id: string; state: string; cassettes: { id: string; state: string; containerIds: string[] }[]; revisions: { description: string }[] } };
  expect(after.record.id).toBe(before.record.id);
  expect(after.record.state).toBe('COMPLETED');
  expect(after.record.revisions.map(r => r.description)).toEqual(['Synthetic corrected description', 'Synthetic initial gross description']);
  expect(after.record.cassettes[0]).toMatchObject({ id: before.record.cassettes[0].id, state: 'PLANNED', containerIds: [cid] });
});
