import { signInWorkflow } from './workflow-login';
import { test, expect } from '@playwright/test';

test('labels preserve identity through preview, simulated failure, retry, cancel and reprint', async ({ page }) => {
  await page.addInitScript(() => { window.print = () => { document.documentElement.dataset.printRequests = String(Number(document.documentElement.dataset.printRequests ?? '0') + 1); }; });
  await signInWorkflow(page);
  await page.getByRole('button', { name: '申请登记工作区' }).click();
  const scopes = await (await page.request.get('/api/requests/scopes')).json() as { id: string }[];
  const encounters = await (await page.request.get('/api/requests/encounters', { params: { scopeId: scopes[0].id, number: 'SYN-LABEL-001' } })).json() as { id: string; patientId: string }[];
  const csrf = await (await page.request.get('/api/auth/csrf')).json() as { token: string };
  const headers = () => ({ 'X-CSRF-TOKEN': csrf.token, 'Idempotency-Key': crypto.randomUUID() });
  const created = await page.request.post('/api/requests', { headers: headers(), data: { scopeId: scopes[0].id, encounterId: encounters[0].id,
    draft: { clinicalHistory: 'Synthetic label E2E', sampledAt: '2026-01-01T08:00:00Z', containers: [{ site: 'Synthetic site', laterality: 'UNKNOWN', materialQuantity: 1, fixative: 'Synthetic fixative', fixedAt: '2026-01-01T08:10:00Z' }] } } });
  expect(created.status()).toBe(201);
  const { receipt } = await created.json() as { receipt: { resourceId: string } };
  expect((await page.request.post(`/api/requests/${receipt.resourceId}/submit`, { headers: headers(), data: { expectedVersion: 0 } })).status()).toBe(200);
  const detail = await (await page.request.get('/api/requests/' + receipt.resourceId)).json() as { requestNumber: string; containers: { id: string }[] };
  const cid = detail.containers[0].id;
  expect((await page.request.post(`/api/receptions/${receipt.resourceId}/receive`, { headers: headers(), data: { expectedVersion: 1, patientId: encounters[0].patientId, encounterNumber: 'SYN-LABEL-001', containerIds: [cid] } })).status()).toBe(200);
  await expect(page.getByText('当前工作范围：合成申请工作范围', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '查看 ' + detail.requestNumber, exact: true }).click();
  await page.getByRole('button', { name: '处理此申请标签' }).click();
  await page.getByLabel('选择容器实体').click(); await page.getByText(cid, { exact: true }).last().click();
  await page.getByRole('button', { name: '创建标签任务', exact: true }).dblclick();
  await expect(page.getByRole('button', { name: '打开标签预览', exact: true })).toBeVisible();
  const jobs = await (await page.request.get('/api/labels/containers/' + cid)).json() as { jobs: { id: string; barcode: string }[] };
  expect(jobs.jobs).toHaveLength(1); const root = jobs.jobs[0];
  await page.getByRole('button', { name: '打开标签预览', exact: true }).click();
  await expect(page.getByLabel('合成容器标签预览')).toContainText(cid);
  await expect(page.getByRole('img', { name: 'Code39 ' + root.barcode })).toBeVisible();
  await page.getByRole('button', { name: '打开浏览器打印对话框', exact: true }).click();
  await expect.poll(() => page.evaluate(() => document.documentElement.dataset.printRequests)).toBe('1');
  await page.getByRole('button', { name: '关闭标签预览', exact: true }).click();
  await expect(page.getByLabel('合成容器标签预览')).toHaveCount(0);
  await page.getByLabel('扫描条码校验此容器').fill(root.barcode);
  await page.getByRole('button', { name: '校验条码身份', exact: true }).click();
  await expect(page.getByText('服务器确认条码与此容器任务一致；不代表实物打印成功。')).toBeVisible();
  expect((await page.request.post(`/api/labels/jobs/${root.id}/verify`, { headers: headers(), data: { containerId: '00000000-0000-4000-8000-000000000001', barcode: root.barcode } })).status()).toBe(409);
  await page.getByLabel('重打 / 重试 / 取消 / 模拟失败原因').fill('Synthetic adapter disconnected');
  await page.getByRole('button', { name: '模拟适配器失败', exact: true }).click();
  await expect(page.getByRole('button', { name: '重试此任务', exact: true })).toBeEnabled();
  await page.getByLabel('重打 / 重试 / 取消 / 模拟失败原因').fill('Synthetic retry');
  await page.getByRole('button', { name: '重试此任务', exact: true }).click();
  await expect(page.getByRole('button', { name: '模拟适配器失败', exact: true })).toBeEnabled();
  await page.getByLabel('重打 / 重试 / 取消 / 模拟失败原因').fill('Synthetic cancelled preview');
  await page.getByRole('button', { name: '取消任务', exact: true }).click();
  await expect(page.getByRole('button', { name: '取消任务', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '同实体重打', exact: true }).click();
  await expect(page.getByText('请填写1–2000字的操作原因')).toBeVisible();
  await page.getByLabel('重打 / 重试 / 取消 / 模拟失败原因').fill('Synthetic damaged label reprint');
  await page.getByRole('button', { name: '同实体重打', exact: true }).click();
  await expect(page.getByText('来源任务：' + root.id)).toBeVisible();
  const after = await (await page.request.get('/api/labels/containers/' + cid)).json() as { jobs: { id: string; barcode: string; containerId: string; parentJobId: string | null; state: string }[] };
  expect(after.jobs).toHaveLength(2);
  expect(after.jobs.every(j => j.barcode === root.barcode && j.containerId === cid)).toBe(true);
  expect(after.jobs.find(j => j.id === root.id)?.state).toBe('CANCELLED');
  expect(after.jobs.some(j => j.parentJobId === root.id && j.state === 'PREVIEW_READY')).toBe(true);
});
