import { test, expect } from '@playwright/test';
import { createHash } from 'node:crypto';
import { signInWorkflow, handoffUsername } from './workflow-login';
import type { Version, View } from '../src/features/storage/api';
import type { Job } from '../src/features/scan/api';
test('synthetic scan binds real stored object and slide, leases, isolates publication and rejects cancelled callbacks', async ({ page, browser }) => {
  await signInWorkflow(page);
  const scopes = await (await page.request.get('/api/requests/scopes')).json() as { id: string }[];
  expect(scopes).toHaveLength(1); const scope = scopes[0].id;
  const encounters = await (await page.request.get('/api/requests/encounters', { params: { scopeId: scope, number: 'SYN-SCAN-001' } })).json() as { id: string; patientId: string }[];
  const csrf = await (await page.request.get('/api/auth/csrf')).json() as { token: string };
  const headers = () => ({ 'X-CSRF-TOKEN': csrf.token, 'Idempotency-Key': crypto.randomUUID() });
  const created = await page.request.post('/api/requests', { headers: headers(), data: { scopeId: scope, encounterId: encounters[0].id, draft: { clinicalHistory: 'Synthetic storage source', sampledAt: '2026-01-01T08:00:00Z', containers: [{ site: 'Synthetic site', laterality: 'UNKNOWN', materialQuantity: 1, fixative: 'Synthetic', fixedAt: '2026-01-01T08:10:00Z' }] } } });
  expect(created.status()).toBe(201); const rid = (await created.json() as { receipt: { resourceId: string } }).receipt.resourceId;
  const submitHeaders = headers(); const submitPath = `/api/requests/${rid}/submit`;
  expect((await page.request.post(submitPath, { headers: submitHeaders, data: { expectedVersion: 0 } })).status()).toBe(200);
  expect((await page.request.post(submitPath, { headers: submitHeaders, data: { expectedVersion: 0 } })).headers()['idempotency-replayed']).toBe('true');
  const detail = await (await page.request.get(`/api/requests/${rid}`)).json() as { requestNumber: string; containers: { id: string }[] };
  expect((await page.request.post(`/api/receptions/${rid}/receive`, { headers: headers(), data: { expectedVersion: 1, patientId: encounters[0].patientId, encounterNumber: 'SYN-SCAN-001', containerIds: detail.containers.map(c => c.id) } })).status()).toBe(200);

  const path = `/api/requests/${rid}/storage`;
  const listing = await page.request.get(path); expect(listing.status()).toBe(200); const view = await listing.json() as View;
  const direct = await page.request.post(`/api/materials/requests/${rid}/direct-slides`, { headers: headers(), data: { requestVersion: 2, confirmedContainerId: detail.containers[0].id, reason: 'Synthetic scan source' } }); expect(direct.status()).toBe(201);
  const slide = (await direct.json() as { receipt: { resourceId: string } }).receipt.resourceId;
  expect((await page.request.post(`/api/quality/materials/${slide}/assess`, { headers: headers(), data: { expectedVersion: -1, materialVersion: 0, taskVersion: null, confirmedMaterialId: slide, standardVersion: 'SYN-MATERIAL-QC-1', outcome: 'PASS', reason: 'Synthetic source QC' } })).status()).toBe(200);
  const material = await (await page.request.get(`/api/materials/${slide}`)).json() as { entity: { barcode: string } };
  const data = Buffer.alloc(256); let offset = data.write('PIS-SYNTHETIC-STORAGE-V1\nPISSCN1\n');
  for (const value of [encounters[0].patientId, view.caseId, slide]) { Buffer.from(value.replaceAll('-', ''), 'hex').copy(data, offset); offset += 16; }
  offset += data.write(material.entity.barcode, offset, 'ascii'); data.writeInt32BE(32, offset); data.writeInt32BE(32, offset + 4);
  const sha256 = createHash('sha256').update(data).digest('hex');
  const reserveHeaders = headers(); const body = { assetId: null, expectedHead: -1, confirmedCaseId: view.caseId, byteSize: data.length, sha256, purpose: 'SYNTHETIC_ORIGINAL', mediaType: 'application/octet-stream' };
  const createdVersion = await page.request.post(path, { headers: reserveHeaders, data: body }); expect(createdVersion.status()).toBe(201);
  const id = (await createdVersion.json() as { receipt: { resourceId: string } }).receipt.resourceId;
  expect((await page.request.post(path, { headers: reserveHeaders, data: body })).headers()['idempotency-replayed']).toBe('true');
  expect((await page.request.get(`${path}/${id}/bytes`, { headers: { 'X-Storage-Purpose': 'DOWNLOAD', Range: 'bytes=0-127' } })).status()).toBe(409);
  const staged = await page.request.put(`${path}/${id}/bytes`, { headers: { 'X-CSRF-TOKEN': csrf.token, 'X-Storage-Version': '0', 'Content-Type': 'application/octet-stream' }, data }); expect(staged.status()).toBe(200);
  const version = await staged.json() as Version; expect(version.state).toBe('STAGED'); const finishHeaders = headers(); const finish = { confirmedCaseId: view.caseId, expectedVersion: version.version };
  const ready = await page.request.post(`${path}/${id}/finish`, { headers: finishHeaders, data: finish }); expect(ready.status()).toBe(200); const readyVersion = await ready.json() as Version; expect(readyVersion.state).toBe('READY');
  expect(await (await page.request.post(`${path}/${id}/finish`, { headers: finishHeaders, data: finish })).json()).toEqual(readyVersion);
  const scanPath = `/api/requests/${rid}/scans`;
  const scanInput = { confirmedCaseId: view.caseId, patientId: encounters[0].patientId, slideId: slide, objectId: id, expectedHead: -1, previousId: null, barcode: material.entity.barcode, sourceCode: 'SYN-LOCAL', scannerCode: 'SYN-DEVICE', reason: 'Synthetic E2E import' };
  const batchKey = headers(); const imported = await page.request.post(scanPath, { headers: batchKey, data: { items: [scanInput] } }); expect(imported.status()).toBe(200);
  const results = await imported.json() as { status: number; scanId: string }[]; expect(results[0].status).toBe(201); const scanId = results[0].scanId;
  expect(await (await page.request.post(scanPath, { headers: batchKey, data: { items: [scanInput] } })).json()).toEqual(results);
  expect((await page.request.post(`${scanPath}/${scanId}/CLAIM`, { headers: headers(), data: { expectedVersion: 0, leaseId: null, reason: 'Synthetic claim' } })).status()).toBe(200);
  const running = await (await page.request.get(`${scanPath}/${scanId}`)).json() as Job; expect(running.attempts).toBe(1);
  const completion = { expectedVersion: running.version, leaseId: running.leaseId, reason: 'Synthetic local header parse' }; const completedKey = headers();
  expect((await page.request.post(`${scanPath}/${scanId}/PROCESS`, { headers: completedKey, data: completion })).status()).toBe(200);
  expect((await (await page.request.post(`${scanPath}/${scanId}/PROCESS`, { headers: completedKey, data: completion })).json() as { replayed: boolean }).replayed).toBe(true);
  const completed = await (await page.request.get(`${scanPath}/${scanId}`)).json() as Job; expect(completed.state).toBe('PENDING_DIGITAL_QC'); expect(completed.objectHash).toBe(sha256); expect(completed.errorCode).toBe('DIGITAL_QC_REQUIRED');
  await page.getByRole('button', { name: '申请登记工作区' }).click(); await expect(page.getByText('当前工作范围：合成申请工作范围', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: `查看 ${detail.requestNumber}`, exact: true }).click(); await page.getByRole('button', { name: '处理此申请扫描导入' }).click();
  await expect(page.getByRole('cell', { name: 'PENDING_DIGITAL_QC', exact: true })).toBeVisible(); await page.getByLabel('人工操作原因', { exact: true }).fill('Synthetic cancellation'); await page.getByRole('button', { name: '取消任务', exact: true }).click(); await expect(page.getByRole('cell', { name: 'CANCELLED', exact: true })).toBeVisible();
  expect((await page.request.post(`${scanPath}/${scanId}/PROCESS`, { headers: headers(), data: completion })).status()).toBe(409);
  const other = await browser.newContext({ baseURL: new URL(page.url()).origin });
  try {
    const receiver = await other.newPage(); await receiver.goto('/'); await receiver.getByLabel('用户名', { exact: true }).fill(handoffUsername()); await receiver.getByLabel('密码', { exact: true }).fill(process.env.PIS_E2E_HANDOFF_PASSWORD ?? 'Synthetic-handoff-only-42!');
    const accepted = receiver.waitForResponse(r => new URL(r.url()).pathname === '/api/auth/login'); await receiver.getByRole('button', { name: '登录', exact: true }).click(); expect((await accepted).status()).toBe(204);
    expect((await receiver.request.get(`${scanPath}/${scanId}`)).status()).toBe(404);
  } finally { await other.close(); }
});
