import { test, expect } from '@playwright/test';
import { createHash } from 'node:crypto';
import { signInWorkflow, handoffUsername } from './workflow-login';
import type { Version, View } from '../src/features/storage/api';
import type { Job } from '../src/features/scan/api';
test('viewer renders actual authorized RGB pyramid and revocation rejects warmed resources', async ({ page, browser }, info) => {
  await signInWorkflow(page);
  const scopes = await (await page.request.get('/api/requests/scopes')).json() as { id: string }[];
  expect(scopes).toHaveLength(1); const scope = scopes[0].id;
  const encounters = await (await page.request.get('/api/requests/encounters', { params: { scopeId: scope, number: 'SYN-SCAN-001' } })).json() as { id: string; patientId: string }[];
  const csrf = await (await page.request.get('/api/auth/csrf')).json() as { token: string };
  const headers = () => ({ 'X-CSRF-TOKEN': csrf.token, 'Idempotency-Key': crypto.randomUUID() });
  const created = await page.request.post('/api/requests', { headers: headers(), data: { scopeId: scope, encounterId: encounters[0].id, draft: { clinicalHistory: 'Synthetic storage source', sampledAt: '2026-01-01T08:00:00Z', containers: [{ site: 'Synthetic site', laterality: 'UNKNOWN', materialQuantity: 1, fixative: 'Synthetic', fixedAt: '2026-01-01T08:10:00Z' }] } } });
  expect(created.status()).toBe(201); const rid = (await created.json() as { receipt: { resourceId: string } }).receipt.resourceId;
  const submitHeaders = headers(); const submitPath = `/api/requests/${rid}/submit`;
  expect((await page.request.post(submitPath, { headers: submitHeaders, data: { expectedVersion: 0 } })).status()).toBe(200);
  expect((await page.request.post(submitPath, { headers: submitHeaders, data: { expectedVersion: 0 } })).headers()['idempotency-replayed']).toBe('true');
  const detail = await (await page.request.get(`/api/requests/${rid}`)).json() as { requestNumber: string; containers: { id: string }[] };
  expect((await page.request.post(`/api/receptions/${rid}/receive`, { headers: headers(), data: { expectedVersion: 1, patientId: encounters[0].patientId, encounterNumber: 'SYN-SCAN-001', containerIds: detail.containers.map(c => c.id) } })).status()).toBe(200);

  const path = `/api/requests/${rid}/storage`;
  const listing = await page.request.get(path); expect(listing.status()).toBe(200); const view = await listing.json() as View;
  const direct = await page.request.post(`/api/materials/requests/${rid}/direct-slides`, { headers: headers(), data: { requestVersion: 2, confirmedContainerId: detail.containers[0].id, reason: 'Synthetic scan source' } }); expect(direct.status()).toBe(201);
  const slide = (await direct.json() as { receipt: { resourceId: string } }).receipt.resourceId;
  expect((await page.request.post(`/api/quality/materials/${slide}/assess`, { headers: headers(), data: { expectedVersion: -1, materialVersion: 0, taskVersion: null, confirmedMaterialId: slide, standardVersion: 'SYN-MATERIAL-QC-1', outcome: 'PASS', reason: 'Synthetic source QC' } })).status()).toBe(200);
  const material = await (await page.request.get(`/api/materials/${slide}`)).json() as { entity: { barcode: string } };
  const headerSize = Buffer.byteLength('PIS-SYNTHETIC-STORAGE-V1\n') + 98; const data = Buffer.alloc(headerSize + 512 * 384 * 3); let offset = data.write('PIS-SYNTHETIC-STORAGE-V1\nPISRGB1\n');
  for (const value of [encounters[0].patientId, view.caseId, slide]) { Buffer.from(value.replaceAll('-', ''), 'hex').copy(data, offset); offset += 16; }
  offset += data.write(material.entity.barcode, offset, 'ascii'); data.writeInt32BE(512, offset); data.writeInt32BE(384, offset + 4);
  for (let y = 0; y < 384; y++) for (let x = 0; x < 512; x++) { const i = headerSize + (y * 512 + x) * 3; const dot = (x % 64 - 32) ** 2 + (y % 64 - 32) ** 2 < 400; data[i] = dot ? 160 : 238; data[i + 1] = dot ? 72 : 210; data[i + 2] = dot ? 157 : 232; }
  const sha256 = createHash('sha256').update(data).digest('hex');
  const reserveHeaders = headers(); const body = { assetId: null, expectedHead: -1, confirmedCaseId: view.caseId, byteSize: data.length, sha256, purpose: 'SYNTHETIC_ORIGINAL', mediaType: 'application/octet-stream' };
  const createdVersion = await page.request.post(path, { headers: reserveHeaders, data: body }); expect(createdVersion.status()).toBe(201);
  const id = (await createdVersion.json() as { receipt: { resourceId: string } }).receipt.resourceId;
  expect((await page.request.post(path, { headers: reserveHeaders, data: body })).headers()['idempotency-replayed']).toBe('true');
  expect((await page.request.get(`${path}/${id}/bytes`, { headers: { 'X-Storage-Purpose': 'DOWNLOAD', Range: 'bytes=0-127' } })).status()).toBe(409);
  const staged = await page.request.put(`${path}/${id}/bytes`, { headers: { 'X-CSRF-TOKEN': csrf.token, 'X-Storage-Version': '0', 'Content-Type': 'application/octet-stream' }, data }); expect(staged.status()).toBe(200);
  const version = await staged.json() as Version; expect(version.state).toBe('STAGED'); const finishHeaders = headers(); const finish = { confirmedCaseId: view.caseId, expectedVersion: version.version };
  const ready = await page.request.post(`${path}/${id}/finish`, { headers: finishHeaders, data: finish }); expect(ready.status()).toBe(200); const readyVersion = await ready.json() as Version; expect(readyVersion.state).toBe('READY');
  expect(await (await page.request.post(`${path}/${id}/finish`, { headers: finishHeaders, data: finish })).json()).toEqual(readyVersion);
  const scanPath = `/api/requests/${rid}/scans`;
  const scanInput = { confirmedCaseId: view.caseId, patientId: encounters[0].patientId, slideId: slide, objectId: id, expectedHead: -1, previousId: null, barcode: material.entity.barcode, sourceCode: 'SYN-LOCAL', scannerCode: 'SYN-DEVICE', reason: 'Synthetic E2E import' };
  const batchKey = headers(); const imported = await page.request.post(scanPath, { headers: batchKey, data: { items: [scanInput] } }); expect(imported.status()).toBe(200);
  const results = await imported.json() as { status: number; scanId: string }[]; expect(results[0].status).toBe(201); const scanId = results[0].scanId;
  expect(await (await page.request.post(scanPath, { headers: batchKey, data: { items: [scanInput] } })).json()).toEqual(results);
  expect((await page.request.post(`${scanPath}/${scanId}/CLAIM`, { headers: headers(), data: { expectedVersion: 0, leaseId: null, reason: 'Synthetic claim' } })).status()).toBe(200);
  const running = await (await page.request.get(`${scanPath}/${scanId}`)).json() as Job; expect(running.attempts).toBe(1);
  const completion = { expectedVersion: running.version, leaseId: running.leaseId, reason: 'Synthetic local header parse' }; const completedKey = headers();
  expect((await page.request.post(`${scanPath}/${scanId}/PROCESS`, { headers: completedKey, data: completion })).status()).toBe(200);
  expect((await (await page.request.post(`${scanPath}/${scanId}/PROCESS`, { headers: completedKey, data: completion })).json() as { replayed: boolean }).replayed).toBe(true);
  const completed = await (await page.request.get(`${scanPath}/${scanId}`)).json() as Job; expect(completed.state).toBe('PENDING_DIGITAL_QC'); expect(completed.objectHash).toBe(sha256); expect(completed.errorCode).toBe('DIGITAL_QC_REQUIRED');
  const qcPath = `${scanPath}/${scanId}/digital-qc`;
  expect((await page.request.get(`${qcPath}/bytes?publicationVersion=0`)).status()).toBe(409);
  const evaluation = { expectedVersion: -1, scanVersion: completed.version, objectId: id, slideId: slide, objectHash: sha256, checklist: 'SYN-DIGITAL-QC-1', coverage: 'PASS', focus: 'UNKNOWN', missing: 'PASS', coveragePercent: 100, missingTiles: 0, regions: [], note: 'Synthetic unknown focus' };
  expect((await page.request.post(qcPath, { headers: headers(), data: evaluation })).status()).toBe(200);
  expect((await page.request.post(`${qcPath}/PUBLISH`, { headers: headers(), data: { expectedVersion: 0, assessmentVersion: 0, reason: 'Synthetic blocked publish' } })).status()).toBe(409);
  const revised = { ...evaluation, expectedVersion: 0, focus: 'PASS', note: 'Synthetic explicit pass' }; const qcKey = headers();
  expect((await page.request.post(qcPath, { headers: qcKey, data: revised })).status()).toBe(200);
  expect((await (await page.request.post(qcPath, { headers: qcKey, data: revised })).json() as { replayed: boolean }).replayed).toBe(true);
  await page.getByRole('button', { name: '申请登记工作区' }).click(); await page.getByLabel('授权工作范围').click(); await page.getByText('合成申请工作范围', { exact: true }).last().click();
  await page.getByRole('button', { name: `查看 ${detail.requestNumber}`, exact: true }).click(); await page.getByRole('button', { name: '处理此申请扫描导入' }).click(); await page.getByRole('button', { name: '数字QC 0', exact: true }).click();
  await expect(page.getByText('EVALUATED_NOT_PUBLISHED / 当前依赖有效', { exact: true })).toBeVisible();
  await page.getByLabel('QC人工备注或原因', { exact: true }).fill('Synthetic explicit publication'); await page.getByRole('button', { name: '发布合成契约版本' }).click();
  await expect(page.getByText('PUBLISHED_SYNTHETIC_CONTRACT / 当前依赖有效', { exact: true })).toBeVisible();
  const download = await page.request.get(`${qcPath}/bytes?publicationVersion=2`, { headers: { Range: 'bytes=0-31' } }); expect(download.status()).toBe(206); expect(download.headers()['x-pis-capability']).toBe('SYNTHETIC_CONTRACT_ONLY_NO_VIEWER'); expect(await download.body()).toEqual(data.subarray(0, 32));
  const viewerPath = `${scanPath}/${scanId}/viewer`;
  await page.getByRole('button', { name: '打开合成瓦片阅片器' }).click();
  await page.getByRole('button', { name: '生成或原键确认合成瓦片' }).click();
  const canvas = page.getByLabel('合成瓦片画布', { exact: true }).locator('canvas').first();
  await expect.poll(async () => canvas.evaluate(node => { const c = node as HTMLCanvasElement; const ctx = c.getContext('2d'); if (!ctx) return 0; const p = ctx.getImageData(0, 0, c.width, c.height).data; let pink = 0; for (let i = 0; i < p.length; i += 16) if (p[i] > 140 && p[i + 2] > 120 && p[i] > p[i + 1] + 15) pink++; return pink; })).toBeGreaterThan(500);
  const original = await page.getByText(/图像相对缩放/).textContent(); await page.getByRole('button', { name: '放大图像' }).click(); await expect(page.getByText(/图像相对缩放/)).not.toHaveText(original ?? '');
  await page.getByRole('button', { name: '适配窗口' }).click(); await page.screenshot({ path: info.outputPath('real-service-synthetic-viewer.png'), fullPage: true });
  await page.getByRole('button', { name: '打开ROI编辑', exact: true }).click();
  await expect(page.getByText(/集合版本 -1/)).toBeVisible();
  await page.getByRole('button', { name: '新建ROI并点击画布' }).click();
  const layer = page.getByLabel('ROI图像叠加层', { exact: true });
  await layer.click({ position: { x: 300, y: 170 } }); await layer.click({ position: { x: 460, y: 280 } });
  await page.getByLabel('ROI人工原因', { exact: true }).fill('Synthetic E2E rectangle');
  await page.getByRole('button', { name: '保存ROI修订', exact: true }).click(); await expect(page.getByText(/集合版本 0/)).toBeVisible();
  const roiPath = `${scanPath}/${scanId}/roi`; const roiView = await (await page.request.get(`${roiPath}?publicationVersion=2`)).json() as { items: { roiId: string; measurement: { unit: string; area: number } }[] };
  expect(roiView.items).toHaveLength(1); expect(roiView.items[0].measurement.unit).toBe('px'); expect(roiView.items[0].measurement.area).toBeGreaterThan(0);
  await page.getByRole('button', { name: '旋转90度' }).click(); await page.getByRole('button', { name: '水平翻转' }).click(); await expect(page.locator('[data-roi-shape]')).toHaveCount(1);
  await page.screenshot({ path: info.outputPath('real-service-synthetic-roi.png'), fullPage: true });
  const tilePath = `${viewerPath}/tiles/9/0/0?publicationVersion=2`; const tile = await page.request.get(tilePath); expect(tile.status()).toBe(200); expect((await tile.body()).subarray(0, 8)).toEqual(Buffer.from([137,80,78,71,13,10,26,10])); expect(createHash('sha256').update(await tile.body()).digest('hex')).toBe(tile.headers()['x-content-sha256']);
  // T33: actual authorized binary decode, fixed RGB channels and bounded concurrent reads.
  const rgb = await page.evaluate(async (bytes: number[]) => {
    const image = await createImageBitmap(new Blob([new Uint8Array(bytes)], { type: 'image/png' }));
    try { const canvas = document.createElement('canvas'); canvas.width = image.width; canvas.height = image.height;
      const ctx = canvas.getContext('2d'); if (!ctx) throw Error('No decoder canvas'); ctx.drawImage(image, 0, 0);
      return { width: image.width, height: image.height, cell: Array.from(ctx.getImageData(32, 32, 1, 1).data), background: Array.from(ctx.getImageData(4, 4, 1, 1).data) };
    } finally { image.close(); }
  }, Array.from(await tile.body()));
  expect(rgb).toEqual({ width: 128, height: 128, cell: [160, 72, 157, 255], background: [238, 210, 232, 255] });
  const concurrent = await Promise.all(Array.from({ length: 4 }, () => page.request.get(tilePath)));
  for (const response of concurrent) { expect(response.status()).toBe(200); expect(await response.body()).toEqual(await tile.body()); expect(response.headers()['cache-control']).toBe('private, no-store'); }
  // T34: registry is metadata only; exact current source qualification never permits execution.
  const aiPath=`${scanPath}/${scanId}/ai`,modelsPath=`/api/requests/ai/scopes/${scope}/models`;
  const aiScanResponse=await page.request.get(`${aiPath}?publicationVersion=2`);expect(aiScanResponse.status()).toBe(200);
  const aiScan=await aiScanResponse.json() as {manifestHash:string;calibrationVersion:number|null};
  const modelMetadata={digest:'a'.repeat(64),preprocessing:'SYN-PRE-1',configSchema:'SYN-AI-CONFIG-1',maxTiles:16,inputContract:'SYN-RGB-PYRAMID-1',pathology:'SYN-PATH',stain:'SYN-STAIN',scannerCode:'SYN-DEVICE',scannerVersion:'SYN-V1',quality:'ALL_DIGITAL_QC_PASS',calibration:'PIXEL_ONLY',approvalScope:'SYNTHETIC_CONTRACT_ONLY',evidence:'DECLARED_SYNTHETIC',evidenceRef:'SYN-REFERENCE',limitations:'Synthetic contract fixture; no diagnostic performance evidence'};
  const modelResponse=await page.request.post(modelsPath,{headers:headers(),data:{modelId:crypto.randomUUID(),expectedHead:-1,code:'SYN-E2E',metadata:modelMetadata,reason:'Synthetic registry'}});expect(modelResponse.status()).toBe(200);
  const modelId=(await modelResponse.json() as {receipt:{resourceId:string}}).receipt.resourceId;
  expect((await page.request.post(`${modelsPath}/${modelId}/state`,{headers:headers(),data:{expectedVersion:0,state:'VALIDATION_ONLY',reason:'Synthetic validation only'}})).status()).toBe(200);
  expect((await page.request.post(`${aiPath}/profile`,{headers:headers(),data:{publicationVersion:2,manifestHash:aiScan.manifestHash,expectedVersion:-1,profile:{pathology:'SYN-PATH',stain:'SYN-STAIN',scannerVersion:'SYN-V1'},reason:'Synthetic source metadata'}})).status()).toBe(200);
  const aiHeaders=headers(),aiInput={modelVersionId:modelId,stateVersion:1,profileVersion:0,publicationVersion:2,manifestHash:aiScan.manifestHash,calibrationVersion:aiScan.calibrationVersion,reason:'Synthetic exact qualification'};
  const aiResult=await page.request.post(`${aiPath}/assess`,{headers:aiHeaders,data:aiInput});expect(aiResult.status(),await aiResult.text()).toBe(200);
  const firstReceipt=await aiResult.json() as {receipt:{resourceId:string;resourceType:string;version:number;status:number};replayed:boolean};
  expect(firstReceipt.replayed).toBe(false);expect(firstReceipt.receipt).toMatchObject({resourceType:'AI_ASSESSMENT',version:0,status:200});const aiId=firstReceipt.receipt.resourceId;
  const decision=await page.request.get(`${aiPath}/assess/${aiId}`);expect(decision.status()).toBe(200);const firstDecision=await decision.json() as Record<string,unknown>;
  expect(firstDecision).toMatchObject({outcome:'VALIDATION_ONLY_APPLICABLE',executionAllowed:false,modelVersionId:modelId,manifestHash:aiScan.manifestHash});
  // T07's required replay signal is in Result; the HTTP header is optional.
  const replay=await page.request.post(`${aiPath}/assess`,{headers:aiHeaders,data:aiInput});expect(replay.status(),await replay.text()).toBe(200);
  expect(await replay.json()).toEqual({...firstReceipt,replayed:true});
  const reread=await page.request.get(`${aiPath}/assess/${aiId}`);expect(reread.status()).toBe(200);const repeatedDecision=await reread.json() as Record<string,unknown>;
  expect(repeatedDecision).toEqual(firstDecision);expect(createHash('sha256').update(JSON.stringify(repeatedDecision)).digest('hex')).toBe(createHash('sha256').update(JSON.stringify(firstDecision)).digest('hex'));
  const changed=await page.request.post(`${aiPath}/assess`,{headers:aiHeaders,data:{...aiInput,reason:'Synthetic different intent'}});
  expect(changed.status(),await changed.text()).toBe(409);expect(await changed.json()).toMatchObject({code:'IDEMPOTENCY_KEY_REUSED'});
  await page.getByRole('button',{name:'核对此扫描AI适用契约',exact:true}).click();await page.getByRole('button',{name:`选择模型 ${modelId}`,exact:true}).click();await page.getByRole('button',{name:'核对当前扫描适用资料',exact:true}).click();await page.getByLabel('AI操作原因',{exact:true}).fill('Synthetic browser assessment');await page.getByRole('button',{name:'判定合成适用性（不执行）',exact:true}).click();await expect(page.getByRole('region',{name:'AI模型契约管理'}).getByRole('status')).toContainText('VALIDATION_ONLY_APPLICABLE');
  await page.screenshot({path:info.outputPath('real-service-synthetic-ai-contract.png'),fullPage:true});
  // T35: real PostgreSQL task/outbox, bounded local fixture and immutable non-diagnostic artifact.
  await page.getByRole('button',{name:'进入合成契约任务（非临床）',exact:true}).click();
  await page.getByLabel('合成任务操作原因',{exact:true}).fill('Synthetic technical task');
  await page.getByRole('button',{name:'创建合成契约任务',exact:true}).click();
  await expect(page.getByRole('region',{name:'合成契约任务'}).getByRole('status')).toContainText('QUEUED');
  await expect(page.getByRole('button',{name:'原键确认任务操作',exact:true})).toBeDisabled();
  await page.getByLabel('合成任务操作原因',{exact:true}).fill('Synthetic claim');await page.getByRole('button',{name:'领取合成任务',exact:true}).click();
  await expect(page.getByRole('region',{name:'合成契约任务'}).getByRole('status')).toContainText('RUNNING');await expect(page.getByRole('button',{name:'原键确认任务操作',exact:true})).toBeDisabled();
  await page.getByLabel('合成任务操作原因',{exact:true}).fill('Synthetic local fixture');await page.getByRole('button',{name:'运行有界非诊断夹具',exact:true}).click();
  await expect(page.getByRole('region',{name:'合成契约任务'}).getByRole('status')).toContainText('SYNTHETIC_SUCCEEDED');await expect(page.getByRole('button',{name:'原键确认任务操作',exact:true})).toBeDisabled();
  const taskState=JSON.parse(await page.getByLabel('任务精确版本',{exact:true}).innerText()) as {job:{id:string;artifactId:string};clinicalExecutionAllowed:boolean};expect(taskState.clinicalExecutionAllowed).toBe(false);
  const taskPath=`/api/requests/${rid}/synthetic-tasks/${taskState.job.id}`;
  const artifact=await page.request.post(`${taskPath}/artifact`,{headers:headers()});expect(artifact.status(),await artifact.text()).toBe(200);expect(await artifact.text()).toContain('NON_DIAGNOSTIC_SYNTHETIC_CONTRACT_ONLY');
  const again=await page.request.post(`${taskPath}/artifact`,{headers:headers()});expect(again.status()).toBe(200);expect(await again.body()).toEqual(await artifact.body());
  await page.screenshot({path:info.outputPath('real-service-synthetic-worker.png'),fullPage:true});
  expect((await page.request.post(`${modelsPath}/${modelId}/state`,{headers:headers(),data:{expectedVersion:1,state:'DISABLED',reason:'Synthetic recall'}})).status()).toBe(200);
  expect((await page.request.get(`${aiPath}/assess/${aiId}`)).status()).toBe(409);expect((await page.request.post(`${aiPath}/assess`,{headers:aiHeaders,data:aiInput})).status()).toBe(409);
  expect((await page.request.post(`${taskPath}/artifact`,{headers:headers()})).status()).toBe(409);
  await page.getByRole('button',{name:'返回当前扫描AI契约',exact:true}).click();
  await page.getByRole('button',{name:'返回当前扫描阅片',exact:true}).click();await expect(page.getByLabel('合成瓦片画布',{exact:true}).locator('canvas').first()).toBeVisible();
  expect((await page.request.post(`${qcPath}/REVOKE`, { headers: headers(), data: { expectedVersion: 2, assessmentVersion: 1, reason: 'Synthetic viewer revoke' } })).status()).toBe(200);
  expect((await page.request.get(`${aiPath}?publicationVersion=2`)).status()).toBe(409);
  for (const resource of [tilePath, `${viewerPath}?publicationVersion=2`, `${viewerPath}/thumbnail?publicationVersion=2`]) expect((await page.request.get(resource)).status()).toBe(409);
  await expect(page.getByLabel('合成瓦片画布', { exact: true }).locator('canvas')).toHaveCount(0, { timeout: 6000 });
  expect((await page.request.get(`${roiPath}?publicationVersion=2`)).status()).toBe(409);
  expect((await page.request.get(`${roiPath}/${roiView.items[0].roiId}/history`)).status()).toBe(200);
  await expect(page.getByLabel('ROI图像叠加层', { exact: true })).toHaveCount(0);
  const other = await browser.newContext({ baseURL: 'http://127.0.0.1:5173' });
  try { const receiver = await other.newPage(); await receiver.goto('/'); await receiver.getByLabel('用户名', { exact: true }).fill(handoffUsername()); await receiver.getByLabel('密码', { exact: true }).fill(process.env.PIS_E2E_HANDOFF_PASSWORD ?? 'Synthetic-handoff-only-42!'); const accepted = receiver.waitForResponse(r => new URL(r.url()).pathname === '/api/auth/login'); await receiver.getByRole('button', { name: '登录', exact: true }).click(); expect((await accepted).status()).toBe(204); expect((await receiver.request.get(qcPath)).status()).toBe(404); expect((await receiver.request.get(modelsPath)).status()).toBe(404); expect((await receiver.request.get(`${roiPath}/${roiView.items[0].roiId}/history`)).status()).toBe(404); expect((await receiver.request.get(tilePath)).status()).toBe(404); expect((await receiver.request.get(`${qcPath}/bytes?publicationVersion=2`)).status()).toBe(404); } finally { await other.close(); }
});
