package com.pis.statistics;
import com.pis.accession.WorkflowAccess;
import com.pis.api.ApiException;
import com.pis.audit.*;
import com.pis.idempotency.*;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import jakarta.validation.Validator;
import tools.jackson.databind.json.JsonMapper;
import static com.pis.statistics.StatisticsContracts.*;
@Service
public class StatisticsService {
 private final JdbcTemplate jdbc;private final WorkflowAccess access;private final IdempotentCommands commands;private final AuditRecorder audit;private final Validator validator;private final JsonMapper json;private final Clock clock;
 public StatisticsService(JdbcTemplate jdbc,WorkflowAccess access,IdempotentCommands commands,AuditRecorder audit,Validator validator,JsonMapper json,@org.springframework.beans.factory.annotation.Qualifier("worklistClock") Clock clock){this.jdbc=jdbc;this.access=access;this.commands=commands;this.audit=audit;this.validator=validator;this.json=json;this.clock=clock;}
 private record Rights(UUID hospital,UUID actor,boolean drill,String mask) { }
 private Rights rights(UUID scope){try{var s=access.require(scope,WorkflowAccess.Permission.READ);var u=access.actor();if(org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive()){jdbc.queryForList("SELECT user_id FROM statistics_grant WHERE user_id=? AND scope_id=? FOR SHARE",u.id(),scope);jdbc.queryForList("SELECT user_id FROM statistics_resource_grant WHERE user_id=? AND scope_id=? ORDER BY request_id FOR SHARE",u.id(),scope);}var r=jdbc.query("SELECT a.can_drill,concat(CASE WHEN g.can_receive THEN 'RECEPTION,' ELSE '' END,CASE WHEN g.can_process THEN 'TECHNICAL,' ELSE '' END,CASE WHEN a.can_report THEN 'REPORT,' ELSE '' END,CASE WHEN g.can_qc THEN 'QC,' ELSE '' END) mask FROM statistics_grant a JOIN workflow_grant g USING(user_id,scope_id) WHERE a.user_id=? AND a.scope_id=? AND a.revoked_at IS NULL AND a.valid_until>statement_timestamp()",(v,i)->new Rights(s.hospitalId(),u.id(),v.getBoolean(1),v.getString(2)),u.id(),scope);if(r.isEmpty())throw missing();return r.getFirst();}catch(org.springframework.security.access.AccessDeniedException e){throw missing();}}
 // This public versioned SQL projection is the cross-domain boundary. Authorization precedes all grouping.
 public static final String FACTS="""
 WITH authorized AS MATERIALIZED (
  SELECT w.request_id FROM request_workflow w JOIN statistics_grant g ON g.scope_id=w.scope_id AND g.user_id=?
  WHERE w.scope_id=? AND g.revoked_at IS NULL AND g.valid_until>statement_timestamp()
   AND (g.all_requests OR EXISTS(SELECT 1 FROM statistics_resource_grant rg WHERE rg.user_id=g.user_id AND rg.scope_id=g.scope_id AND rg.request_id=w.request_id AND rg.revoked_at IS NULL AND rg.valid_until>statement_timestamp()))
 ), events AS MATERIALIZED (
  SELECT e.* FROM statistics_source_event_v1 e JOIN authorized a USING(request_id)
  WHERE e.event_at<=? AND position(e.metric||',' IN ?)>0
 ), firsts AS (
  SELECT DISTINCT ON(metric,entity_id,phase) * FROM events WHERE phase IN ('START','END') ORDER BY metric,entity_id,phase,event_at,event_id
 ), entities AS (SELECT DISTINCT metric,entity_id,request_id FROM events), cohort AS (
  SELECT n.metric,n.entity_id,n.request_id,s.event_id start_event,s.event_at start_at,e.event_id end_event,e.event_at end_at
  FROM entities n LEFT JOIN firsts s ON s.metric=n.metric AND s.entity_id=n.entity_id AND s.phase='START'
  LEFT JOIN firsts e ON e.metric=n.metric AND e.entity_id=n.entity_id AND e.phase='END'
  WHERE (s.event_at>=? AND s.event_at<?) OR (s.event_at IS NULL AND e.event_at>=? AND e.event_at<?)
 ), latest AS (SELECT DISTINCT ON(metric,entity_id) * FROM events WHERE phase IN ('ASSESS','CHANGE','EXCLUDE') ORDER BY metric,entity_id,event_at DESC,version DESC,event_id DESC)
 SELECT c.*,l.event_id latest_event,l.event_at latest_at,l.phase,l.outcome,
 CASE WHEN c.metric='QC' THEN jsonb_build_object('materialVersion',m.version,'qualityVersion',q.version,'effectiveState',q.state)::text ELSE '{}' END source_basis,
 CASE WHEN c.metric='QC' THEN CASE WHEN m.state='VOID' THEN 'EXCLUDED' WHEN l.phase='ASSESS' AND l.outcome='PASS' AND q.state='PASS' THEN 'PASS' WHEN l.phase='ASSESS' AND l.outcome='FAIL' AND q.state IN ('FAIL','IDENTITY_MISMATCH') THEN 'FAIL' ELSE 'UNKNOWN' END ELSE NULL END qc_status
 FROM cohort c LEFT JOIN latest l ON l.metric=c.metric AND l.entity_id=c.entity_id
 LEFT JOIN material_entity m ON c.metric='QC' AND m.id=c.entity_id LEFT JOIN workflow_quality_projection q ON q.id=m.id
 ORDER BY c.metric,c.entity_id LIMIT 5001
 """;
 private List<Fact> collect(UUID scope,Rights r,StatisticsPolicy.Window window,Instant cutoff){var stamp=OffsetDateTime.ofInstant(cutoff,ZoneOffset.UTC);return jdbc.query(FACTS,(v,i)->{Metric metric=Metric.valueOf(v.getString("metric"));Instant start=instant(v,"start_at"),end=instant(v,"end_at");UUID endEvent=v.getObject("end_event",UUID.class);String status;Long seconds=null;if(metric==Metric.QC){status=v.getString("qc_status");end=instant(v,"latest_at");endEvent=v.getObject("latest_event",UUID.class);}else{boolean excluded="EXCLUDE".equals(v.getString("phase"));if(excluded){end=instant(v,"latest_at");endEvent=v.getObject("latest_event",UUID.class);}var t=StatisticsPolicy.timing(start,end,cutoff,excluded);status=t.status();seconds=t.seconds();}return new Fact(metric,v.getObject("entity_id",UUID.class),v.getObject("request_id",UUID.class),v.getObject("start_event",UUID.class),endEvent,start,end,status,seconds,v.getString("source_basis"));},r.actor(),scope,stamp,r.mask(),OffsetDateTime.ofInstant(window.start(),ZoneOffset.UTC),OffsetDateTime.ofInstant(window.end(),ZoneOffset.UTC),OffsetDateTime.ofInstant(window.start(),ZoneOffset.UTC),OffsetDateTime.ofInstant(window.end(),ZoneOffset.UTC));}
 private static Instant instant(java.sql.ResultSet r,String key)throws java.sql.SQLException{var t=r.getObject(key,OffsetDateTime.class);return t==null?null:t.toInstant();}
 private static OffsetDateTime timestamp(Instant v){return v==null?null:OffsetDateTime.ofInstant(v,ZoneOffset.UTC);}
 private static String hash(String text){try{return HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(text.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 public IdempotentCommands.Result create(UUID scope,Query input,String key){var errors=validator.validate(input);if(!errors.isEmpty())throw new jakarta.validation.ConstraintViolationException(errors);StatisticsPolicy.Window window;try{window=StatisticsPolicy.window(input.from(),input.to(),input.zone());}catch(IllegalArgumentException|DateTimeException e){throw invalid();}var initial=rights(scope);
  return commands.execute(initial.hospital(),"STATISTICS_SNAPSHOT_V1",key,Map.of("scope",scope,"query",input),new IdempotentCommands.Work(){public void authorize(CurrentActor.Actor a){rights(scope);}public void authorizeReplay(CurrentActor.Actor a,CommandReceipt receipt){check(scope,receipt.resourceId(),false);}
   public IdempotentCommands.Mutation mutate(CurrentActor.Actor actor){var r=rights(scope);jdbc.execute("SET LOCAL statement_timeout='5s'");jdbc.queryForList("SELECT pg_advisory_xact_lock(hashtextextended(?,0))","STATISTICS_SNAPSHOT_V1:"+actor.id());if(jdbc.queryForObject("SELECT count(*) FROM statistics_snapshot WHERE actor_id=?",Long.class,actor.id())>=500)throw new ApiException(HttpStatus.CONFLICT,"STATISTICS_LIMIT","Synthetic snapshot limit reached");var cutoff=clock.instant().truncatedTo(java.time.temporal.ChronoUnit.MICROS);if(!window.start().isBefore(cutoff))throw invalid();var facts=collect(scope,r,window,cutoff);if(facts.size()>5000)throw new ApiException(HttpStatus.BAD_REQUEST,"STATISTICS_RANGE_TOO_LARGE","Narrow the authorized date range");UUID id=UUID.randomUUID();String digest=hash(json.writeValueAsString(facts));jdbc.update("INSERT INTO statistics_snapshot(id,actor_id,scope_id,definition,from_date,to_date,zone,starts_at,ends_at,cutoff,permission_mask,facts_hash,fact_count) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",id,actor.id(),scope,StatisticsPolicy.DEFINITION,input.from(),input.to(),input.zone(),timestamp(window.start()),timestamp(window.end()),timestamp(cutoff),r.mask(),digest,facts.size());
    jdbc.batchUpdate("INSERT INTO statistics_fact(snapshot_id,metric,entity_id,request_id,start_event,end_event,start_at,end_at,status,duration_seconds,source_basis) VALUES(?,?,?,?,?,?,?,?,?,?,?)",facts,100,(p,f)->{p.setObject(1,id);p.setString(2,f.metric().name());p.setObject(3,f.entityId());p.setObject(4,f.requestId());p.setObject(5,f.startEvent());p.setObject(6,f.endEvent());p.setObject(7,timestamp(f.startAt()));p.setObject(8,timestamp(f.endAt()));p.setString(9,f.status());p.setObject(10,f.durationSeconds());p.setString(11,f.sourceBasis());});check(scope,id,false);return new IdempotentCommands.Mutation(new CommandReceipt(200,"STATISTICS_SNAPSHOT",id,0),null);}
  });
 }
 private record Snapshot(UUID id,UUID scope,LocalDate from,LocalDate to,String zone,Instant cutoff,String mask,String hash) { }
 private Snapshot check(UUID scope,UUID id,boolean drill){var r=rights(scope);if(drill&&!r.drill())throw missing();var list=jdbc.query("SELECT * FROM statistics_snapshot WHERE id=? AND scope_id=? AND actor_id=?",(v,i)->new Snapshot(id,scope,v.getObject("from_date",LocalDate.class),v.getObject("to_date",LocalDate.class),v.getString("zone"),instant(v,"cutoff"),v.getString("permission_mask"),v.getString("facts_hash")),id,scope,r.actor());if(list.isEmpty()||!list.getFirst().mask().equals(r.mask()))throw missing();Long denied=jdbc.queryForObject("SELECT count(*) FROM statistics_fact f JOIN request_workflow w ON w.request_id=f.request_id JOIN statistics_grant g ON g.scope_id=w.scope_id AND g.user_id=? WHERE f.snapshot_id=? AND (w.scope_id<>? OR NOT (g.all_requests OR EXISTS(SELECT 1 FROM statistics_resource_grant rg WHERE rg.user_id=g.user_id AND rg.scope_id=g.scope_id AND rg.request_id=f.request_id AND rg.revoked_at IS NULL AND rg.valid_until>statement_timestamp())))",Long.class,r.actor(),id,scope);if(denied!=0)throw missing();return list.getFirst();}
 private List<Fact> saved(UUID id){return jdbc.query("SELECT * FROM statistics_fact WHERE snapshot_id=? ORDER BY metric,entity_id LIMIT 5001",(v,i)->new Fact(Metric.valueOf(v.getString("metric")),v.getObject("entity_id",UUID.class),v.getObject("request_id",UUID.class),v.getObject("start_event",UUID.class),v.getObject("end_event",UUID.class),instant(v,"start_at"),instant(v,"end_at"),v.getString("status"),v.getObject("duration_seconds",Long.class),v.getString("source_basis")),id);}
 @Transactional(timeout=10) public View view(UUID scope,UUID id,Metric metric,Sort sort,int page){if(page<1||page>250)throw invalid();var s=check(scope,id,metric!=null);var r=rights(scope);if(metric!=null&&!r.mask().contains(metric.name()+","))throw missing();jdbc.execute("SET LOCAL statement_timeout='5s'");var facts=saved(id);if(!hash(json.writeValueAsString(facts)).equals(s.hash()))throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"STATISTICS_INTEGRITY","Snapshot integrity check failed");var summaries=new ArrayList<Summary>();for(var m:Metric.values()){var rows=facts.stream().filter(f->f.metric()==m).toList();long completed=count(rows,"COMPLETED"),open=count(rows,"OPEN"),unknown=count(rows,"UNKNOWN"),excluded=count(rows,"EXCLUDED"),num=m==Metric.QC?count(rows,"FAIL"):completed,den=m==Metric.QC?count(rows,"PASS")+num:rows.size();summaries.add(new Summary(m,!s.mask().contains(m.name()+",")?"NOT_AUTHORIZED":rows.isEmpty()?"NO_DATA":"DATA",rows.size(),completed,open,unknown,excluded,num,den,den==0?null:(double)num/den,StatisticsPolicy.median(rows.stream().filter(f->f.status().equals("COMPLETED")).map(Fact::durationSeconds).toList())));}
  var selected=facts.stream().filter(f->f.metric()==metric).sorted(sort==Sort.ENTITY?Comparator.comparing(Fact::entityId):Comparator.comparing(Fact::startAt,sort==Sort.START_ASC?Comparator.nullsLast(Comparator.naturalOrder()):Comparator.nullsLast(Comparator.reverseOrder())).thenComparing(Fact::entityId)).toList();check(scope,id,metric!=null);audit.append(r.hospital(),metric==null?"STATISTICS_READ_V1":"STATISTICS_DRILL_V1","STATISTICS_SNAPSHOT",id,null,0);
  return new View(id,scope,StatisticsPolicy.DEFINITION,s.from(),s.to(),s.zone(),s.cutoff(),s.hash(),r.drill(),List.copyOf(summaries),metric,sort,page,selected.size(),selected.stream().skip((page-1)*20L).limit(20).toList());
 }
 private static long count(List<Fact> rows,String state){return rows.stream().filter(f->f.status().equals(state)).count();}
 private static ApiException missing(){return new ApiException(HttpStatus.NOT_FOUND,"STATISTICS_NOT_FOUND","Statistics snapshot or permission unavailable");}
 private static ApiException invalid(){return new ApiException(HttpStatus.BAD_REQUEST,"STATISTICS_FILTER_INVALID","Bounded dates, timezone and page required");}
}
