import { request, readJson, fetchCsrf } from '../../api';
export interface Job { id: string; requestId: string; caseId: string; patientId: string; claimedCaseId: string; claimedPatientId: string; slideId: string; objectId: string; objectHash: string; objectSize: number; ordinal: number; previousId: string | null; sourceBasis: string; barcode: string; sourceCode: string; scannerCode: string; reason: string; state: string; errorCode: string; version: number; attempts: number; leaseId: string | null; leaseActor: string | null; leaseUntil: string | null; retryAt: string | null; width: number | null; height: number | null; invalidReason: string }
export interface View { requestId: string; caseId: string; patientId: string; page: number; jobs: Job[]; slides: { id: string; barcode: string; version: number; status: string }[]; capabilities: Record<string, string>; publication: string }
export interface Create { confirmedCaseId: string; patientId: string; slideId: string; objectId: string; expectedHead: number; previousId: string | null; barcode: string; sourceCode: string; scannerCode: string; reason: string }
export interface Command { expectedVersion: number; leaseId: string | null; reason: string }
export interface Item { objectId: string; status: number; scanId: string | null; code: string }
const states = ['QUEUED', 'RUNNING', 'RETRY_WAIT', 'FAILED', 'CANCELLED', 'QUARANTINED', 'PENDING_DIGITAL_QC'];
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) throw Error('导入响应格式错误'); return v as Record<string, unknown>; }
function str(v: unknown): string { if (typeof v !== 'string') throw Error('导入文本无效'); return v; }
function num(v: unknown): number { if (typeof v !== 'number' || !Number.isSafeInteger(v) || v < 0) throw Error('导入数值无效'); return v; }
function nullable(v: unknown) { return v === null ? null : str(v); }
export function parseView(value: unknown, rid: string, page: number): View { const v = obj(value); if (v.requestId !== rid || v.page !== page || v.publication !== 'NOT_PUBLISHED_BY_IMPORT' || !Array.isArray(v.jobs) || v.jobs.length > 20 || !Array.isArray(v.slides) || v.slides.length > 100) throw Error('导入病例或分页不匹配');
 const jobs = v.jobs.map(x => { const j = obj(x); if (j.requestId !== rid || j.caseId !== v.caseId || j.patientId !== v.patientId || !states.includes(str(j.state)) || !/^[a-f0-9]{64}$/.test(str(j.objectHash)) || !/^[a-f0-9]{64}$/.test(str(j.sourceBasis)) || num(j.attempts) > 3) throw Error('导入任务身份或状态无效'); return { id: str(j.id), requestId: rid, caseId: str(j.caseId), patientId: str(j.patientId), claimedCaseId: str(j.claimedCaseId), claimedPatientId: str(j.claimedPatientId), slideId: str(j.slideId), objectId: str(j.objectId), objectHash: str(j.objectHash), objectSize: num(j.objectSize), ordinal: num(j.ordinal), previousId: nullable(j.previousId), sourceBasis: str(j.sourceBasis), barcode: str(j.barcode), sourceCode: str(j.sourceCode), scannerCode: str(j.scannerCode), reason: str(j.reason), state: str(j.state), errorCode: str(j.errorCode), version: num(j.version), attempts: num(j.attempts), leaseId: nullable(j.leaseId), leaseActor: nullable(j.leaseActor), leaseUntil: nullable(j.leaseUntil), retryAt: nullable(j.retryAt), width: j.width === null ? null : num(j.width), height: j.height === null ? null : num(j.height), invalidReason: str(j.invalidReason) }; });
 const capabilities = obj(v.capabilities); if (capabilities.SYNTHETIC_HEADER_V1 !== 'CONTRACT_ONLY' || ['TIFF_CONTAINER', 'SVS', 'NDPI', 'MRXS'].some(k => capabilities[k] !== 'NOT_CONFIGURED') || capabilities.ARCHIVE !== 'UNSUPPORTED') throw Error('不能声称未经验证的厂商能力');
 return { requestId: rid, caseId: str(v.caseId), patientId: str(v.patientId), page, jobs, slides: v.slides.map(x => { const s = obj(x); return { id: str(s.id), barcode: str(s.barcode), version: num(s.version), status: str(s.status) }; }), capabilities: Object.fromEntries(Object.entries(capabilities).map(([k, value]) => [k, str(value)])), publication: str(v.publication) };
}
const path = (rid: string) => `/api/requests/${encodeURIComponent(rid)}/scans`;
export async function load(rid: string, page: number, signal: AbortSignal) { return parseView(await readJson(await request(`${path(rid)}?page=${page}`, { signal })), rid, page); }
export async function post(rid: string, target: string, body: unknown, key: string, signal: AbortSignal): Promise<unknown> { const csrf = await fetchCsrf(signal); return readJson(await request(`${path(rid)}${target}`, { method: 'POST', signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify(body) })); }
export function parseItems(value: unknown, input: Create[]): Item[] { if (!Array.isArray(value) || value.length !== input.length) throw Error('逐项回执不完整'); return value.map((x, i) => { const v = obj(x); if (v.objectId !== input[i].objectId || ![201, 400, 403, 404, 409, 429, 503].includes(num(v.status)) || (v.status === 201 ? typeof v.scanId !== 'string' : v.scanId !== null)) throw Error('逐项回执与对象不匹配'); return { objectId: str(v.objectId), status: num(v.status), scanId: nullable(v.scanId), code: str(v.code) }; }); }

export interface Event { scanId: string; version: number; action: string; state: string; errorCode: string; leaseId: string | null; attempts: number; reason: string; occurredAt: string }
export async function history(rid: string, id: string, signal: AbortSignal): Promise<Event[]> { const data = await readJson(await request(`${path(rid)}/${id}/events`, { signal })); if (!Array.isArray(data) || data.length > 50) throw Error('导入历史越界'); return data.map(x => { const v = obj(x); if (v.scanId !== id || !states.includes(str(v.state))) throw Error('历史任务不匹配'); return { scanId: id, version: num(v.version), action: str(v.action), state: str(v.state), errorCode: str(v.errorCode), leaseId: nullable(v.leaseId), attempts: num(v.attempts), reason: str(v.reason), occurredAt: str(v.occurredAt) }; }); }

export function commandReceipt(value: unknown, id: string, expectedVersion: number) { const r = obj(obj(value).receipt); if (r.resourceType !== 'SCAN_IMPORT' || r.resourceId !== id || r.status !== 200 || r.version !== expectedVersion + 1) throw Error('导入操作回执不匹配'); }
