import { describe, it, expect } from 'vitest';
import { parseView, parseItems, commandReceipt, type Create } from './api';
const job = { id: 'scan', requestId: 'request', caseId: 'case', patientId: 'patient', claimedCaseId: 'case', claimedPatientId: 'patient', slideId: 'slide', objectId: 'object', objectHash: 'a'.repeat(64), objectSize: 256, ordinal: 0, previousId: null, sourceBasis: 'b'.repeat(64), barcode: 'SYN', sourceCode: 'SYN-LOCAL', scannerCode: 'SYN-DEV', reason: 'Synthetic', state: 'PENDING_DIGITAL_QC', errorCode: 'DIGITAL_QC_REQUIRED', version: 2, attempts: 1, leaseId: 'lease', leaseActor: 'actor', leaseUntil: '2026-10-03T00:00:00Z', retryAt: null, width: 32, height: 32, invalidReason: '' };
const view = { requestId: 'request', caseId: 'case', patientId: 'patient', page: 1, jobs: [job], slides: [], capabilities: { SYNTHETIC_HEADER_V1: 'CONTRACT_ONLY', TIFF_CONTAINER: 'NOT_CONFIGURED', SVS: 'NOT_CONFIGURED', NDPI: 'NOT_CONFIGURED', MRXS: 'NOT_CONFIGURED', ARCHIVE: 'UNSUPPORTED' }, publication: 'NOT_PUBLISHED_BY_IMPORT' };
describe('scan import contract', () => {
 it('retains pending QC and exact immutable original identity', () => { expect(parseView(view, 'request', 1).jobs[0]).toEqual(job); });
 it('rejects cross-case, foreign patient and fabricated publication', () => { for (const patch of [{ caseId: 'other' }, { patientId: 'other' }, { state: 'READY' }, { objectHash: '' }, { attempts: 4 }]) expect(() => parseView({ ...view, jobs: [{ ...job, ...patch }] }, 'request', 1)).toThrow(); expect(() => parseView({ ...view, publication: 'PUBLISHED' }, 'request', 1)).toThrow(); });
 it('does not infer vendor compatibility or accept unbounded history', () => { expect(() => parseView({ ...view, capabilities: { ...view.capabilities, SVS: 'SUPPORTED' } }, 'request', 1)).toThrow(); expect(() => parseView({ ...view, jobs: Array(21).fill(job) }, 'request', 1)).toThrow(); expect(() => parseView(view, 'request', 2)).toThrow(); });
 it('keeps partial failures separate from accepted task IDs', () => { const input: Create = { confirmedCaseId: 'case', patientId: 'patient', slideId: 'slide', objectId: 'one', expectedHead: -1, previousId: null, barcode: 'synthetic', sourceCode: 'SYN-LOCAL', scannerCode: 'SYN-DEV', reason: 'Synthetic' };const items = [input, { ...input, objectId: 'two' }]; expect(parseItems([{ objectId: 'one', status: 201, scanId: 'scan', code: 'RECORDED_NOT_PUBLISHED' }, { objectId: 'two', status: 409, scanId: null, code: 'SCAN_DUPLICATE' }], items).map(x => x.status)).toEqual([201, 409]); expect(() => parseItems([{ objectId: 'one', status: 409, scanId: 'fake-success', code: 'SCAN_DUPLICATE' }], [input])).toThrow(); expect(() => parseItems([], items)).toThrow(); });
 it('requires the original task and CAS progression in a command receipt', () => { const receipt = { resourceType: 'SCAN_IMPORT', resourceId: 'scan', status: 200, version: 2 }; expect(() => commandReceipt({ receipt }, 'scan', 1)).not.toThrow(); expect(() => commandReceipt({ receipt }, 'foreign', 1)).toThrow(); expect(() => commandReceipt({ receipt }, 'scan', 2)).toThrow(); });

});
