import { useEffect, useRef, useState } from 'react';
import { Alert, Button, Input, Modal, Select, Space, Table, Typography } from 'antd';
import { ApiError } from '../../api';
import * as api from './api';
type Intent = { key: string; target: string; body: api.Command | { items: api.Create[] } };
export function Scan({ requestId, onDirty, onClean, onPending, onExpired, onQc }: { onQc: (id: string) => void; requestId: string; onDirty: () => void; onClean: () => void; onPending: (v: boolean) => void; onExpired: () => void }) {
 const [history, setHistory] = useState<api.Event[]>([]);
 const [queued, setQueued] = useState<api.Create[]>([]);
 const [view, setView] = useState<api.View>(); const [page, setPage] = useState(1); const [slide, setSlide] = useState(''); const [barcode, setBarcode] = useState(''); const [caseId, setCaseId] = useState(''); const [patient, setPatient] = useState(''); const [objects, setObjects] = useState(''); const [source, setSource] = useState(''); const [scanner, setScanner] = useState(''); const [reason, setReason] = useState(''); const [previous, setPrevious] = useState<api.Job>();
 const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [results, setResults] = useState<api.Item[]>([]); const [busy, setBusy] = useState(false); const [pending, setPending] = useState(false); const [switchTo, setSwitchTo] = useState<string>(); const dirty = useRef(false); const [abandon, setAbandon] = useState(false);
 const active = useRef<AbortController | undefined>(undefined); const locked = useRef(false); const intent = useRef<Intent | undefined>(undefined); const expired = useRef(onExpired); expired.current = onExpired;
 useEffect(() => { const c = new AbortController(); active.current = c; locked.current = true; setBusy(true); void api.load(requestId, page, c.signal).then(v => { if (!c.signal.aborted) setView(v); }).catch(e => { if (!c.signal.aborted) { setError(e instanceof Error ? e.message : '读取失败'); if (e instanceof ApiError && e.status === 401) expired.current(); } }).finally(() => { if (!c.signal.aborted) { locked.current = false; setBusy(false); } }); return () => { c.abort(); active.current?.abort(); }; }, [requestId, page]);
 function changed() { dirty.current = true; onDirty(); }
 async function run(work: (s: AbortSignal) => Promise<void>) { if (locked.current) return; locked.current = true; setBusy(true); setError(''); const c = new AbortController(); active.current = c; try { await work(c.signal); } catch (e) { if (!c.signal.aborted) { setError(e instanceof Error ? e.message : '操作失败'); if (e instanceof ApiError && [401, 403, 404].includes(e.status)) { setView(undefined); setHistory([]); setResults([]); } if (e instanceof ApiError && e.status === 401) onExpired(); } } finally { if (active.current === c) { locked.current = false; setBusy(false); } } }
 async function refresh(s: AbortSignal) { setView(undefined); setHistory([]); const v = await api.load(requestId, page, s); if (!s.aborted) setView(v); }
 async function send(s: AbortSignal) { const i = intent.current; if (!i) return; const result = await api.post(requestId, i.target, i.body, i.key, s); if (s.aborted) return; let unsaved = false; if ('items' in i.body) { const items = i.body.items; const outcomes = api.parseItems(result, items); setResults(outcomes); const failures = items.filter((_, index) => outcomes[index].status !== 201); setQueued(failures); unsaved = failures.length > 0; } else api.commandReceipt(result, i.target.split('/')[1], i.body.expectedVersion); intent.current = undefined; setPending(false); onPending(false); dirty.current = unsaved; if (unsaved) onDirty(); else onClean(); setNotice('服务器已记录；请按当前状态核对。导入完成不代表发布；请进入精确版本数字QC核验。'); await refresh(s); }
 function build(): api.Create | undefined { if (!view) return; const id = objects.trim(); if (!slide || !caseId || !patient || !barcode || !reason.trim() || !/^SYN-[A-Za-z0-9_-]{1,60}$/.test(source) || !/^SYN-[A-Za-z0-9_-]{1,60}$/.test(scanner) || !id || /\s/.test(id)) { setError('请核对必填身份、SYN-来源/设备、原因和单个原件版本UUID。'); return; } return { confirmedCaseId: caseId, patientId: patient, slideId: slide, objectId: id, expectedHead: previous?.ordinal ?? -1, previousId: previous?.id ?? null, barcode, sourceCode: source, scannerCode: scanner, reason }; }
 function add() { if (locked.current || pending) return; const item = build(); if (!item) return; if (queued.length >= 10 || queued.some(x => x.slideId === item.slideId || x.objectId === item.objectId)) { setError('单批最多10项，每玻片和每原件限一项；重扫需独立确认。'); return; } setQueued([...queued, item]); setSlide(''); setBarcode(''); setCaseId(''); setPatient(''); setObjects(''); setSource(''); setScanner(''); setReason(''); setPrevious(undefined); changed(); }
 function create() { if (locked.current || !view || pending) return; let items = queued; if (items.length === 0) { const item = build(); if (!item) return; items = [item]; } else if (slide || objects || barcode || caseId || patient || source || scanner) { setError('当前表单尚未加入批次，请先加入或取消本地表单。'); return; }
  intent.current = { key: crypto.randomUUID(), target: '', body: { items } }; setPending(true); onPending(true); changed(); void run(send);
 }
 function command(j: api.Job, action: string) { if (locked.current || pending) return; if (!reason.trim()) { setError('必须填写本次人工操作原因。'); return; } intent.current = { key: crypto.randomUUID(), target: `/${j.id}/${action}`, body: { expectedVersion: j.version, leaseId: j.leaseId, reason } }; setPending(true); onPending(true); changed(); void run(send); }
 function reset(next: string) { setSlide(next); setBarcode(''); setCaseId(''); setPatient(''); setObjects(''); setSource(''); setScanner(''); setReason(''); setPrevious(undefined); setResults([]); dirty.current = queued.length > 0; if (dirty.current) onDirty(); else onClean(); }
 return <section aria-label="合成扫描导入"><Typography.Title level={2}>扫描任务与导入</Typography.Title><Alert type="warning" title="仅合成头契约；厂商适配未配置，导入不代表发布；数字QC另行核验，T31阅片器未实现。" />
  {error && <Alert role="alert" type="error" title={error} />}{notice && <Alert role="status" type="info" title={notice} />}
  <p>申请 {requestId}；病例 {view?.caseId ?? '未知'}；患者ID {view?.patientId ?? '未知'}。请人工核对，不从文件自动修正身份。</p>
  <Space wrap><Button disabled={busy} onClick={() => void run(refresh)}>刷新导入与授权</Button><Button disabled={!busy} onClick={() => { active.current?.abort(); locked.current = false; setBusy(false); setNotice('仅停止等待，操作可能已完成；使用原键确认。'); }}>停止等待导入</Button><Button disabled={busy || !pending} onClick={() => void run(send)}>原键确认导入操作</Button><Button disabled={busy || !pending} onClick={() => setAbandon(true)}>停止本地跟踪</Button></Space>
  <fieldset disabled={busy || pending}><legend>人工核对与有界批量</legend>
   <Select virtual={false} disabled={busy || pending} aria-label="物理玻片" style={{ minWidth: 260 }} value={slide || undefined} options={view?.slides.map(s => ({ value: s.id, label: `${s.id} / ${s.barcode} / ${s.status}` }))} onChange={v => { if (dirty.current && (slide || barcode || caseId || patient || objects || source || scanner || reason)) setSwitchTo(v); else reset(v); }} />
   <label>核对病例UUID<Input aria-label="核对病例UUID" value={caseId} onChange={e => { setCaseId(e.target.value); changed(); }} /></label><label>核对患者UUID<Input aria-label="核对患者UUID" value={patient} onChange={e => { setPatient(e.target.value); changed(); }} /></label><label>人工扫描条码<Input aria-label="人工扫描条码" maxLength={64} value={barcode} onChange={e => { setBarcode(e.target.value); changed(); }} /></label>
   <label>原件版本UUID（每映射一项）<Input.TextArea aria-label="原件版本UUID" value={objects} maxLength={500} onChange={e => { setObjects(e.target.value); changed(); }} /></label>
   <label>合成来源编号<Input aria-label="合成来源编号" maxLength={64} value={source} onChange={e => { setSource(e.target.value); changed(); }} /></label><label>合成扫描仪编号<Input aria-label="合成扫描仪编号" maxLength={64} value={scanner} onChange={e => { setScanner(e.target.value); changed(); }} /></label>
   <label>人工操作原因<Input aria-label="人工操作原因" maxLength={500} value={reason} onChange={e => { setReason(e.target.value); changed(); }} /></label><p>{previous ? `重扫来源 ${previous.id} / 序列 ${previous.ordinal}；必须使用新原件版本` : '新扫描身份；同一玻片后续扫描须选择重扫来源'}</p>
   <Button disabled={!view || busy || pending} onClick={add}>加入已核对批次</Button><Button disabled={!view || busy || pending} onClick={create}>登记逐项导入</Button><Button disabled={busy || pending} onClick={() => reset('')}>取消本地表单</Button>
  </fieldset>
  {queued.length > 0 && <Table<api.Create> aria-label="待登记映射" rowKey="objectId" dataSource={queued} pagination={false} columns={[{ title: '待登记玻片', dataIndex: 'slideId' }, { title: '确切原件', dataIndex: 'objectId' }, { title: '人工条码', dataIndex: 'barcode' }, { title: '移除本地项', render: (_, item) => <Button disabled={busy || pending} onClick={() => { const next = queued.filter(x => x.objectId !== item.objectId); setQueued(next); if (next.length === 0 && !slide && !objects) { dirty.current = false; onClean(); } }}>移除 {item.objectId}</Button> }]} />}
  {results.length > 0 && <Table<api.Item> aria-label="逐项登记结果" rowKey="objectId" dataSource={results} pagination={false} columns={[{ title: '原件版本', dataIndex: 'objectId' }, { title: 'HTTP结果', dataIndex: 'status' }, { title: '结果码', dataIndex: 'code' }, { title: '任务ID', dataIndex: 'scanId' }]} />}
  <Table<api.Job> rowKey="id" dataSource={view?.jobs ?? []} pagination={false} scroll={{ x: true }} columns={[{ title: '任务 / 原件', render: (_, j) => <>{j.id}<br />{j.objectId}<br />{j.objectHash}</> }, { title: '版本/尝试', render: (_, j) => `${j.ordinal} / CAS ${j.version} / 尝试 ${j.attempts}` }, { title: '人工映射依据', render: (_, j) => <>{j.claimedCaseId}<br />{j.claimedPatientId}<br />{j.barcode}</> }, { title: '当前状态', dataIndex: 'state' }, { title: '原因 / 失效', render: (_, j) => `${j.errorCode} ${j.invalidReason}` }, { title: '租约截止', dataIndex: 'leaseUntil' }, { title: '操作', render: (_, j) => <Space wrap><Button disabled={busy || pending} onClick={() => onQc(j.id)}>数字QC {j.ordinal}</Button><Button disabled={busy} onClick={() => void run(async s => { setHistory([]); const events = await api.history(requestId, j.id, s); if (!s.aborted) setHistory(events); })}>追加历史</Button>{['CLAIM', 'PROCESS', 'RECOVER', 'RETRY', 'CANCEL'].map(a => <Button key={a} disabled={busy || pending || (a === 'CLAIM' && j.state !== 'QUEUED') || (['PROCESS', 'RECOVER'].includes(a) && j.state !== 'RUNNING') || (a === 'RETRY' && j.state !== 'RETRY_WAIT') || (a === 'CANCEL' && j.state === 'CANCELLED')} onClick={() => command(j, a)}>{({ CLAIM: '领取尝试', PROCESS: '本地解析合成头', RECOVER: '恢复过期尝试', RETRY: '受控重试', CANCEL: '取消任务' })[a]}</Button>)}<Button disabled={busy || pending || dirty.current} onClick={() => { reset(j.slideId); setPrevious(j); changed(); }}>选择重扫来源</Button></Space> }]} />
  {history.length > 0 && <Table<api.Event> aria-label="导入追加历史" rowKey={e => `${e.scanId}:${e.version}`} dataSource={history} pagination={false} columns={[{ title: '任务ID', dataIndex: 'scanId' }, { title: '历史版本', dataIndex: 'version' }, { title: '动作', dataIndex: 'action' }, { title: '当时状态', dataIndex: 'state' }, { title: '原因', dataIndex: 'reason' }, { title: '记录时间', dataIndex: 'occurredAt' }]} />}
  <Space><Button disabled={busy || pending || dirty.current || page === 1} onClick={() => { setView(undefined); setPage(page - 1); }}>上一页</Button><span>第 {page} 页</span><Button disabled={busy || pending || dirty.current || page === 50 || view?.jobs.length !== 20} onClick={() => { setView(undefined); setPage(page + 1); }}>下一页</Button></Space>
  <Modal title="切换玻片并清除本地输入？" open={switchTo !== undefined} okText="清除并切换" cancelText="继续核对" onCancel={() => setSwitchTo(undefined)} onOk={() => { reset(switchTo ?? ''); setSwitchTo(undefined); }}><p>原件、条码及来源字段不会沿用到另一玻片。</p></Modal>
  <Modal title="停止跟踪原请求？" open={abandon} okText="保留服务器任务并停止跟踪" cancelText="继续确认" onCancel={() => setAbandon(false)} onOk={() => { intent.current = undefined; setPending(false); onPending(false); setAbandon(false); setNotice('没有撤销服务器任务；请刷新逐项状态。'); }}><p>停止跟踪不代表取消任务或删除原件。</p></Modal>
 </section>;
}
