import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Alert, Button, Card, Form, Input, Modal, Select, Table } from 'antd';
import { ApiError } from '../../api';
import { ReadController } from '../../shared/workflow';
import { ReadPanel } from '../../shared/WorkflowElements';
import { CommandIntent } from '../../shared/command';
import { actions, load, send, type Action, type Command, type View } from './consultationApi';
type Props = { id: string; onDirty: () => void; onClean: () => void; onPending: (v: boolean) => void; onExpired: () => void; onSaved: () => void };
const reasons: Record<string, string> = { REPORT_FROZEN: '报告已模拟冻结，不能继续视为可采纳草稿', EXPIRED: '邀请已到期', REPORT_CHANGED: '报告修订已改变', ASSIGNMENT_CHANGED: '病例分配已改变', QC_OR_QUALIFICATION_CHANGED: '材料、QC或医生资格已改变', PARTICIPANT_UNAVAILABLE: '有参与者拒绝或被撤销', PARTICIPANT_QUALIFICATION_CHANGED: '参与者资格已改变', SUMMARY_UNRESOLVED_OR_CHANGED: '汇总尚未解决分歧或个人意见已更新', RETURNED: '会诊已退回', WITHDRAWN: '会诊已撤回', ADOPTED: '已追加为新草稿修订（未签署）' };
export function ConsultationEditor({ id: caseId, ...cb }: Props) {
 const [id, setId] = useState<string | null>(null), [page, setPage] = useState(1), [action, setAction] = useState<Action>('CREATE'), [dirty, setDirty] = useState(false), [pending, setPending] = useState(false), [generation, setGeneration] = useState(0), [next, setNext] = useState<(() => void) | null>(null);
 const [catalog] = useState(() => new ReadController(async (_: null, signal: AbortSignal) => { try { return { status: 'ready' as const, data: await load(caseId, null, 1, signal) }; } catch (e) { if (e instanceof ApiError && e.status === 401) cb.onExpired(); throw e; } }));
 const [reader] = useState(() => new ReadController(async (key: { id: string; page: number }, signal: AbortSignal) => { try { return { status: 'ready' as const, data: await load(caseId, key.id, key.page, signal) }; } catch (e) { if (e instanceof ApiError && e.status === 401) cb.onExpired(); throw e; } }));
 const cat = useSyncExternalStore(catalog.subscribe, catalog.getSnapshot), detail = useSyncExternalStore(reader.subscribe, reader.getSnapshot); useEffect(() => { void catalog.run(null); return catalog.stop; }, [catalog]); useEffect(() => { if (id) void reader.run({ id, page }); return reader.stop; }, [id, page, reader]);
 function clean() { setDirty(false); cb.onClean(); } function change(fn: () => void) { if (pending) return; if (dirty) setNext(() => fn); else { clean(); setGeneration(g => g + 1); fn(); } }
 function select(id: string | null) { setId(id); setPage(1); setAction(id ? 'ACCEPT' : 'CREATE'); }
 function refresh() { void catalog.run(null); if (id) void reader.run({ id, page }); }
 function saved(newId: string) { clean(); setGeneration(g => g + 1); void catalog.run(null); if (newId !== id) select(newId); else if (id) void reader.run({ id, page }); }
 return <><Alert type="warning" title="院内合成会诊 / 复阅 · 不发邀请、不对外共享、不签署报告" description="个人意见不自动变成诊断；人工汇总仍须每位参与者确认确切版本。采纳仅追加人工说明到新草稿。" /><Button disabled={pending} onClick={() => change(refresh)}>刷新会诊与授权</Button>
 <ReadPanel state={cat}>{d => <Card title="当前病例可访问会诊">{d.owner && <Button disabled={pending} onClick={() => change(() => select(null))}>新建会诊或复阅</Button>}{d.consultations.map(h => <Button key={h.id} disabled={pending} style={{ maxWidth: '100%', height: 'auto', whiteSpace: 'normal', overflowWrap: 'anywhere' }} onClick={() => change(() => select(h.id))}>查看会诊 {h.id}</Button>)}</Card>}</ReadPanel>
 <ReadPanel state={id ? detail : cat}>{d => <><section className="identity-strip" aria-label="会诊病例身份"><strong>{d.number}</strong><span>病例 {d.caseId}</span><span>患者 {d.patientId}</span><span>当前用户 {d.actorId} / {d.owner ? '当前领取医生' : '本次受邀医生'}</span></section>
 {d.selected && <Card title="确切会诊依据"><p style={{ overflowWrap: 'anywhere' }}>{d.selected.id} / v{d.selected.version} · {d.selected.kind} · {d.selected.state}</p><p>目的：{d.selected.purpose}</p><p>有效期至 {d.selected.expiresAt} · 分配版本 {d.selected.assignmentVersion}</p><p style={{ overflowWrap: 'anywhere' }}>报告修订 {d.selected.revisionId} · 模板 {d.basis?.templateCode} / v{d.basis?.templateVersion}</p><Alert title={d.invalidReason ? reasons[d.invalidReason] ?? '依据失效，须重新核对' : d.ready ? '确切汇总已获全体明确确认；采纳仍须服务器复核' : '意见或确认尚不完整，不代表已达成一致'} type={d.ready ? 'info' : 'warning'} /><Table rowKey="id" dataSource={d.selected.materialBasis} pagination={false} scroll={{ x: 600 }} columns={[{ title: '绑定材料', dataIndex: 'id' }, { title: '材料版本', dataIndex: 'version' }, { title: 'QC版本', dataIndex: 'qcVersion' }, { title: '原QC状态', dataIndex: 'state' }]} /></Card>}
 <Card title="绑定报告原内容（只读）">{d.basis ? Object.entries(d.basis.fields).map(([k, v]) => <p key={k} style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{{ gross: '大体记录', microscopy: '镜下记录', diagnosis: '人工诊断草稿', notes: '附注', sampleCount: '合成数量', manualChecked: '人工核对标记' }[k] ?? k}：{String(v)}</p>) : '尚无可用草稿'}</Card>
 <label htmlFor="consult-action">院内会诊操作</label><Select id="consult-action" style={{ width: '100%' }} virtual={false} value={action} disabled={pending} options={Object.entries(actions).filter(([a]) => id ? a !== 'CREATE' : a === 'CREATE').map(([value, label]) => ({ value, label }))} onChange={(v: Action) => change(() => setAction(v))} />
 <Entry key={(id ?? 'new') + action + generation} d={d} action={action} {...cb} onDirty={() => { setDirty(true); cb.onDirty(); }} onClean={clean} onPending={v => { setPending(v); cb.onPending(v); }} saved={saved} />
 <Card title="当前个人意见与人工汇总">{d.opinions.map(e => <p key={e.id} style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{e.actorId} / {e.id} / {e.disposition}<br />{e.content}</p>)}{d.summary ? <p style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>当前汇总 {d.summary.id} / {d.summary.disposition}<br />{d.summary.content}<br />处理原因：{d.summary.reason}</p> : '尚无人工汇总，不代表一致'}</Card>
 <Card title="个人意见及确切汇总确认"><Table rowKey="userId" dataSource={d.members} pagination={false} scroll={{ x: 900 }} columns={[{ title: '受邀人员', dataIndex: 'userId' }, { title: '参与状态', dataIndex: 'state' }, { title: '个人最新意见ID', dataIndex: 'opinionId' }, { title: '明确确认汇总ID', dataIndex: 'confirmedSummaryId' }]} /></Card>
 <Card title="追加意见、分歧与采纳历史"><Table rowKey="id" dataSource={d.events} pagination={false} scroll={{ x: 1100 }} columns={[{ title: '动作 / 版本', render: (_, e) => <span>{actions[e.action]} / v{e.version}<br />{e.id}</span> }, { title: '个人意见 / 汇总', render: (_, e) => <span style={{ whiteSpace: 'pre-wrap' }}>{e.disposition ?? '—'}<br />{e.content}<br />原因：{e.reason}</span> }, { title: '绑定及采纳修订', render: (_, e) => <span>{e.summaryId ?? '—'}<br />{e.adoptedRevisionId ?? '未采纳'}</span> }, { title: '人员 / 时间', render: (_, e) => <span>{e.actorId}<br />{e.recordedAt}</span> }]} /><Button disabled={pending || page === 1} onClick={() => change(() => setPage(p => p - 1))}>上一页会诊历史</Button><Button disabled={pending || d.events.length < 20 || page >= 10000} onClick={() => change(() => setPage(p => p + 1))}>下一页会诊历史</Button></Card>
 </>}</ReadPanel><Modal open={!!next} title="放弃会诊输入并切换？" okText="清除并继续" cancelText="继续编辑" onCancel={() => setNext(null)} onOk={() => { const fn = next; setNext(null); clean(); setGeneration(g => g + 1); fn?.(); }}>切换会清除不适用字段，不能撤销已提交服务器操作。</Modal></>;
}
interface Values { confirmedId: string; reason: string; kind?: string; purpose?: string; expiresAt?: string; invitees?: string[]; targetId?: string; disposition?: string; content?: string }
function Entry({ d, action, saved, onDirty, onClean, onPending, onExpired }: Omit<Props, 'id' | 'onSaved'> & { d: View; action: Action; saved: (id: string) => void }) {
 const [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [message, setMessage] = useState(''); const [intent] = useState(() => new CommandIntent<Command>()); const active = useRef(false), alive = useRef(true), original = useRef<Command | undefined>(undefined);
 useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
 async function execute(c: Command) { if (active.current) return; active.current = true; original.current = c; setBusy(true); onDirty(); onPending(true); setMessage(''); try { const id = await intent.run(c, send); if (id && alive.current) { onPending(false); onClean(); saved(id); } } catch (e) { if (!alive.current) return; if (e instanceof ApiError && e.status === 401) { onExpired(); return; } const definite = e instanceof ApiError && ([400, 403, 404].includes(e.status) || e.status === 409 && !['COMMAND_BUSY', 'HTTP_ERROR'].includes(e.code)); if (definite) { intent.rejected(); onPending(false); } setUncertain(!definite); setMessage(definite ? e.message : '会诊结果待确认，请保留原病例、依据版本和幂等键重试。'); } finally { active.current = false; if (alive.current) setBusy(false); } }
 const ownerAction = ['CREATE', 'WITHDRAW', 'REVOKE', 'SUMMARY', 'ADOPT'].includes(action), member = d.members.find(m => m.userId === d.actorId); const allowed = ownerAction ? d.owner && (action === 'CREATE' ? !!d.basis : d.selected?.state === 'OPEN') && (action !== 'ADOPT' || d.ready) : d.selected?.state === 'OPEN' && !!member && (['ACCEPT', 'REJECT'].includes(action) ? member.state === 'INVITED' : member.state === 'ACCEPTED') && (action !== 'CONFIRM' || !!d.summary && !d.invalidReason);
 return <Card title={actions[action]}>{message && <Alert role="status" title={message} />}{uncertain && <Button disabled={busy} onClick={() => { if (original.current) void execute(original.current); }}>确认原会诊请求</Button>}
 <Form<Values> layout="vertical" disabled={busy || uncertain || !allowed} onValuesChange={onDirty} onFinish={v => { if (!allowed || busy || uncertain) return; void execute({ caseId: d.caseId, id: d.selected?.id ?? null, action, body: { confirmedCaseId: v.confirmedId, expectedVersion: d.selected?.version ?? -1, reason: v.reason, revisionId: d.basis?.id ?? null, assignmentVersion: d.selected?.assignmentVersion ?? d.basis?.assignmentVersion ?? null, kind: v.kind ?? null, purpose: v.purpose ?? null, expiresAt: v.expiresAt ?? null, invitees: v.invitees ?? [], targetId: v.targetId ?? null, disposition: v.disposition ?? null, content: v.content ?? '', opinionIds: action === 'SUMMARY' ? d.members.flatMap(m => m.opinionId ? [m.opinionId] : []) : [], summaryId: ['CONFIRM', 'ADOPT'].includes(action) ? d.selected?.summaryId ?? null : null } }); }}>
 <Form.Item name="confirmedId" label="核对会诊病例 UUID" rules={[{ validator: (_, v: unknown) => v === d.caseId ? Promise.resolve() : Promise.reject(new Error('请核对病例UUID')) }]}><Input maxLength={36} /></Form.Item>
 {action === 'CREATE' && <><Form.Item name="kind" label="会诊目的类型" rules={[{ required: true }]}><Select virtual={false} options={[{ value: 'CONSULT', label: '院内会诊（合成）' }, { value: 'REREAD', label: '院内复阅（合成）' }]} /></Form.Item><Form.Item name="purpose" label="具体会诊目的" rules={[{ required: true, whitespace: true }]}><Input.TextArea maxLength={2000} /></Form.Item><Form.Item name="invitees" label="明确邀请合格人员" rules={[{ required: true }]}><Select mode="multiple" virtual={false} options={d.candidates.filter(c => c.id !== d.actorId).map(c => ({ value: c.id, label: c.name + ' / ' + c.id }))} /></Form.Item><Form.Item name="expiresAt" label="授权到期时间（含时区，最多30天）" rules={[{ required: true }, { validator: (_, v: unknown) => typeof v === 'string' && /(?:Z|[+-]\d\d:\d\d)$/.test(v) && Number.isFinite(Date.parse(v)) ? Promise.resolve() : Promise.reject(new Error('例如2026-10-04T12:00:00Z')) }]}><Input maxLength={40} /></Form.Item></>}
 {action === 'REVOKE' && <Form.Item name="targetId" label="撤销具体参与者" rules={[{ required: true }]}><Select virtual={false} options={d.members.filter(m => ['INVITED', 'ACCEPTED'].includes(m.state)).map(m => ({ value: m.userId, label: m.userId }))} /></Form.Item>}
 {['OPINION', 'SUMMARY'].includes(action) && <Form.Item name="disposition" label="明确意见或分歧状态" rules={[{ required: true }]}><Select virtual={false} options={(action === 'OPINION' ? [{ value: 'AGREE', label: '个人同意意见' }, { value: 'DISAGREE', label: '个人存在分歧' }, { value: 'UNKNOWN', label: '个人尚不确定' }] : [{ value: 'UNRESOLVED', label: '分歧尚未解决' }, { value: 'RESOLVED', label: '人工汇总待各参与者确认' }])} /></Form.Item>}
 {['OPINION', 'SUMMARY', 'ADOPT'].includes(action) && <Form.Item name="content" label={action === 'ADOPT' ? '人工采纳追加说明（保留原草稿正文）' : '人工意见或汇总内容'} rules={[{ required: true, whitespace: true }]}><Input.TextArea rows={4} maxLength={4000} /></Form.Item>}
 {['CONFIRM', 'ADOPT'].includes(action) && <p style={{ overflowWrap: 'anywhere' }}>绑定汇总 {d.selected?.summaryId ?? '无'}；此操作不签署报告。</p>}
 <Form.Item name="reason" label="会诊操作原因" rules={[{ required: true, whitespace: true }]}><Input.TextArea maxLength={2000} /></Form.Item><Button type="primary" htmlType="submit" disabled={!allowed || busy || uncertain}>{actions[action]}并保存</Button></Form></Card>;
}
