import { fetchCsrf, readJson, request } from '../../api';
import { parseRevision, type Revision } from './api';
export const actions = { CREATE: '发起合成会诊或复阅', ACCEPT: '接受本地邀请', REJECT: '拒绝本地邀请', WITHDRAW: '撤回会诊', REVOKE: '撤销参与权限', RETURN: '退回会诊', OPINION: '追加个人意见', SUMMARY: '记录人工汇总', CONFIRM: '确认确切汇总', ADOPT: '追加采纳说明到草稿' };
export type Action = keyof typeof actions;
export interface Head { id: string; caseId: string; revisionId: string; assignmentVersion: number; materialBasis: { id: string; version: number; qcVersion: number; state: string }[]; kind: string; purpose: string; expiresAt: string; createdBy: string; state: string; version: number; summaryId: string | null }
export interface Member { userId: string; state: string; opinionId: string | null; confirmedSummaryId: string | null }
export interface Event { id: string; version: number; action: Action; actorId: string; targetId: string | null; disposition: string | null; content: string; reason: string; summaryId: string | null; adoptedRevisionId: string | null; recordedAt: string }
export interface View { caseId: string; patientId: string; number: string; actorId: string; owner: boolean; consultations: Head[]; selected: Head | null; basis: Revision | null; members: Member[]; events: Event[]; opinions: Event[]; summary: Event | null; candidates: { id: string; name: string }[]; invalidReason: string | null; ready: boolean; page: number }
export interface Command { caseId: string; id: string | null; action: Action; body: { confirmedCaseId: string; expectedVersion: number; reason: string; revisionId: string | null; assignmentVersion: number | null; kind: string | null; purpose: string | null; expiresAt: string | null; invitees: string[]; targetId: string | null; disposition: string | null; content: string; opinionIds: string[]; summaryId: string | null } }
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('Invalid consultation'); return v as Record<string, unknown>; }
function str(v: unknown, empty = false): string { if (typeof v !== 'string' || !empty && !v) throw new Error('Invalid consultation text'); return v; }
function nullable(v: unknown) { return v === null ? null : str(v); }
function num(v: unknown, min = 0): number { if (typeof v !== 'number' || !Number.isSafeInteger(v) || v < min) throw new Error('Invalid consultation version'); return v; }
function arr(v: unknown, max: number): unknown[] { if (!Array.isArray(v) || v.length > max) throw new Error('Invalid consultation list'); return v; }
function bool(v: unknown): boolean { if (typeof v !== 'boolean') throw new Error('Invalid consultation flag'); return v; }
function head(v: unknown, caseId: string): Head { const h = obj(v); if (h.caseId !== caseId || !['OPEN', 'RETURNED', 'WITHDRAWN', 'ADOPTED'].includes(str(h.state)) || !['CONSULT', 'REREAD'].includes(str(h.kind)) || !Number.isFinite(Date.parse(str(h.expiresAt)))) throw new Error('Invalid consultation identity'); return { id: str(h.id), caseId, revisionId: str(h.revisionId), assignmentVersion: num(h.assignmentVersion), kind: str(h.kind), purpose: str(h.purpose), expiresAt: str(h.expiresAt), createdBy: str(h.createdBy), state: str(h.state), version: num(h.version), summaryId: nullable(h.summaryId), materialBasis: arr(JSON.parse(str(h.materialBasis)), 100).map(v => { const m = obj(v); return { id: str(m.id), version: num(m.version), qcVersion: num(m.qcVersion, -1), state: str(m.state) }; }) }; }
const parseEvent = (v: unknown): Event => { const e = obj(v); const action = str(e.action), disposition = nullable(e.disposition); if (!Object.hasOwn(actions, action) || disposition !== null && !['AGREE', 'DISAGREE', 'UNKNOWN', 'RESOLVED', 'UNRESOLVED'].includes(disposition)) throw new Error('Invalid opinion'); return { id: str(e.id), version: num(e.version), action: action as Action, actorId: str(e.actorId), targetId: nullable(e.targetId), disposition, content: str(e.content, true), reason: str(e.reason), summaryId: nullable(e.summaryId), adoptedRevisionId: nullable(e.adoptedRevisionId), recordedAt: str(e.recordedAt) }; };
export function parseView(v: unknown, caseId: string, id: string | null, page: number): View { const d = obj(v); if (d.caseId !== caseId || d.page !== page) throw new Error('Mismatched consultation case/page'); const selected = d.selected === null ? null : head(d.selected, caseId); if ((selected?.id ?? null) !== id) throw new Error('Mismatched consultation'); const consultations = arr(d.consultations, 100).map(h => head(h, caseId)); if (new Set(consultations.map(h => h.id)).size !== consultations.length || selected && !consultations.some(h => h.id === selected.id && h.version === selected.version)) throw new Error('Invalid consultation catalog'); const basis = d.basis === null ? null : parseRevision(d.basis, caseId); if (selected && basis?.id !== selected.revisionId) throw new Error('Mismatched bound report');
 const members = arr(d.members, 10).map(v => { const m = obj(v); if (!['INVITED', 'ACCEPTED', 'REJECTED', 'REVOKED'].includes(str(m.state))) throw new Error('Invalid participant'); return { userId: str(m.userId), state: str(m.state), opinionId: nullable(m.opinionId), confirmedSummaryId: nullable(m.confirmedSummaryId) }; }); if (new Set(members.map(m => m.userId)).size !== members.length) throw new Error('Duplicate participant');
 const opinions = arr(d.opinions, 10).map(parseEvent), summary = d.summary === null ? null : parseEvent(d.summary);
 if (opinions.length !== members.filter(m => m.opinionId).length || opinions.some(e => e.action !== 'OPINION' || !members.some(m => m.userId === e.actorId && m.opinionId === e.id)) || new Set(opinions.map(e => e.id)).size !== opinions.length || (summary?.id ?? null) !== (selected?.summaryId ?? null) || summary && summary.action !== 'SUMMARY') throw new Error('Mismatched personal or summary version');
 const events = arr(d.events, 20).map(parseEvent); if (events.some((e, i) => !selected || e.version > selected.version || i > 0 && e.version >= events[i - 1].version)) throw new Error('Invalid consultation history'); const ready = bool(d.ready), invalidReason = nullable(d.invalidReason); if (ready && (summary?.disposition !== 'RESOLVED' || !selected || selected.state !== 'OPEN' || invalidReason || !selected.summaryId || members.length === 0 || members.some(m => m.state !== 'ACCEPTED' || !m.opinionId || m.confirmedSummaryId !== selected.summaryId))) throw new Error('Invented consensus');
 return { caseId, patientId: str(d.patientId), number: str(d.number), actorId: str(d.actorId), owner: bool(d.owner), consultations, selected, basis, members, events, opinions, summary, candidates: arr(d.candidates, 100).map(v => { const c = obj(v); return { id: str(c.id), name: str(c.name) }; }), invalidReason, ready, page };
}
const base = (id: string) => '/api/requests/consultations/cases/' + encodeURIComponent(id);
export async function load(caseId: string, id: string | null, page: number, signal: AbortSignal) { return parseView(await readJson(await request(base(caseId) + '?page=' + page + (id ? '&consultation=' + encodeURIComponent(id) : ''), { signal })), caseId, id, page); }
export async function send(c: Command, key: string) { const abort = new AbortController(), timer = setTimeout(() => abort.abort(), 15000); try { const csrf = await fetchCsrf(abort.signal); const r = obj(obj(await readJson(await request(base(c.caseId) + '/' + c.action + (c.id ? '?consultation=' + encodeURIComponent(c.id) : ''), { method: 'POST', signal: abort.signal, headers: { 'Content-Type': 'application/json', [csrf.headerName]: csrf.token, 'Idempotency-Key': key }, body: JSON.stringify(c.body) }))).receipt); if (r.status !== 200 || r.resourceType !== 'REPORT_CONSULTATION' || r.version !== c.body.expectedVersion + 1 || c.id && r.resourceId !== c.id) throw new Error('Mismatched consultation receipt'); return str(r.resourceId); } finally { clearTimeout(timer); } }
