import {fetchCsrf,readJson,request} from '../../api';
import {parseRevision,type Revision,base} from './api';
export type Action='ACCEPT_REFERENCE'|'REJECT'|'DEFER';
export interface Event {id:string;caseId:string;resultId:string;version:number;targetRevisionId:string;targetVersion:number;action:Action;reason:string;actorId:string;recordedAt:string;adoptedRevisionId:string|null;artifactHash:string;binding:Record<string,unknown>}
export interface View {caseId:string;resultId:string;version:number;target:Revision|null;assignmentVersion:number;ready:boolean;invalidReason:string|null;source:{id:string;artifactHash:string;binding:Record<string,unknown>};history:Event[];page:number;executionAllowed:false}
export interface Command {caseId:string;body:{confirmedCaseId:string;resultId:string;targetRevisionId:string;reportVersion:number;assignmentVersion:number;expectedVersion:number;action:Action;reason:string;confirmed:true}}
const obj=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('人工处理响应结构无效');return v as Record<string,unknown>;};
const num=(v:unknown,min=0)=>Number.isSafeInteger(v)&&Number(v)>=min;
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
export function parseView(raw:unknown,id:string,result:string,page:number):View{const v=obj(raw),s=obj(v.source),b=obj(s.binding),input=obj(b.input),decision=obj(input.decision);
 if(v.caseId!==id||v.resultId!==result||v.page!==page||v.executionAllowed!==false||typeof v.ready!=='boolean'||!num(v.version,-1)||!num(v.assignmentVersion)||s.id!==result||b.resultId!==result||input.caseId!==id||decision.executionAllowed!==false||!hash(s.artifactHash)||!hash(decision.modelDigest)||!hash(input.configDigest)||typeof input.preprocessing!=='string'||!Array.isArray(v.history)||v.history.length>20||!(v.invalidReason===null||typeof v.invalidReason==='string')||v.ready&&v.invalidReason!==null)throw Error('人工处理病例、结果或版本不匹配');
 const target=v.target===null?null:parseRevision(v.target,id);if(v.ready&&!target)throw Error('缺少目标修订');
 for(const item of v.history){const e=obj(item);if(e.caseId!==id||e.resultId!==result||!num(e.version)||!num(e.targetVersion)||!['ACCEPT_REFERENCE','REJECT','DEFER'].includes(String(e.action))||typeof e.id!=='string'||typeof e.reason!=='string'||typeof e.actorId!=='string'||typeof e.recordedAt!=='string'||typeof e.targetRevisionId!=='string'||!(e.adoptedRevisionId===null||typeof e.adoptedRevisionId==='string')||!hash(e.artifactHash))throw Error('人工记录来源不匹配');obj(e.binding);}
 return {...v,target} as unknown as View;}
export async function loadDecision(id:string,result:string,page:number,signal:AbortSignal){if(!/^[a-f0-9-]{36}$/.test(result))throw Error('请输入精确结果UUID');return parseView(await readJson(await request(`${base}${id}/synthetic-decisions?resultId=${result}&page=${page}`,{signal,cache:'no-store'})),id,result,page);}
export async function sendDecision(c:Command,key:string,signal:AbortSignal){const csrf=await fetchCsrf(signal);const v=obj(await readJson(await request(`${base}${c.caseId}/synthetic-decisions`,{method:'POST',signal,headers:{'Content-Type':'application/json',[csrf.headerName]:csrf.token,'Idempotency-Key':key},body:JSON.stringify(c.body)}))),r=obj(v.receipt);if(r.status!==200||r.resourceType!=='SYNTHETIC_REPORT_DECISION'||typeof r.resourceId!=='string'||r.version!==c.body.expectedVersion+1||typeof v.replayed!=='boolean')throw Error('人工处理回执不匹配');return r.resourceId;}
