import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Alert, Button, Card, Form, Input, Modal, Select, Table } from 'antd';
import { ApiError } from '../../api';
import { ReadController } from '../../shared/workflow';
import { ReadPanel } from '../../shared/WorkflowElements';
import { CommandIntent } from '../../shared/command';
import { actions, load, send, history, type Action, type Item, type Command } from './deliveryApi';
type Props = { id: string; onDirty: () => void; onClean: () => void; onPending: (v: boolean) => void; onExpired: () => void; onSaved: () => void };
export function DeliveryEditor({ id, ...callbacks }: Props) {
 const [page, setPage] = useState(1), [selected, setSelected] = useState<Item | undefined>(), [dirty, setDirty] = useState(false), [pending, setPending] = useState(false), [confirm, setConfirm] = useState(false), [generation, setGeneration] = useState(0); const next = useRef<(() => void) | undefined>(undefined);
 const [reader] = useState(() => new ReadController(async (p: number, signal: AbortSignal) => { try { return { status: 'ready' as const, data: await load(id, p, signal) }; } catch (e) { if (e instanceof ApiError && e.status === 401) callbacks.onExpired(); throw e; } }));
 const state = useSyncExternalStore(reader.subscribe, reader.getSnapshot); useEffect(() => { void reader.run(page); return reader.stop; }, [reader, page]);
 function change(action: () => void) { if (pending) return; if (dirty) { next.current = action; setConfirm(true); } else action(); }
 return <><Alert type="warning" title="仅本地合成投递 · 无临床或法律签署效力" description="不连接外部系统；HTTP成功不代表业务ACK。人工推进持久化队列，最多3次尝试；超时不代表接收端未收到。" />
 <ReadPanel state={state}>{d => <><p>病例 {id} · CA {d.caStatus}</p><Table rowKey="id" dataSource={d.items} pagination={false} scroll={{ x: 1200 }} columns={[{ title: '投递ID', dataIndex: 'id' }, { title: '状态', dataIndex: 'state' }, { title: '尝试数', dataIndex: 'attempts' }, { title: '下次允许尝试', dataIndex: 'nextAt' }, { title: '冻结修订', dataIndex: 'revisionId' }, { title: '本地目的端', dataIndex: 'destination' }, { title: '操作', key: 'select', render: (_, i) => <Button onClick={() => change(() => { setSelected(i); setGeneration(v => v + 1); })}>处理投递 {i.id}</Button> }]} /><Button disabled={page === 1 || pending} onClick={() => change(() => { setSelected(undefined); setPage(p => p - 1); })}>上一页投递</Button><Button disabled={d.items.length < 20 || pending} onClick={() => change(() => { setSelected(undefined); setPage(p => p + 1); })}>下一页投递</Button></>}</ReadPanel>
 <Button onClick={() => change(() => { setSelected(undefined); setGeneration(v => v + 1); })}>新建本地投递</Button>
 <DeliveryForm key={generation + ':' + (selected?.id ?? 'new')} id={id} item={selected} {...callbacks} onDirty={() => { setDirty(true); callbacks.onDirty(); }} onPending={v => { setPending(v); callbacks.onPending(v); }} />
 {selected && <DeliveryHistory key={selected.id} id={id} delivery={selected.id} onExpired={callbacks.onExpired} />}
 <Modal open={confirm} title="放弃未保存的投递输入？" okText="放弃并切换投递" cancelText="继续当前投递" onCancel={() => { next.current = undefined; setConfirm(false); }} onOk={() => { const action = next.current; next.current = undefined; setConfirm(false); setDirty(false); callbacks.onClean(); setGeneration(v => v + 1); action?.(); }}><p>不会撤销已经持久化的队列或接收记录。</p></Modal></>;
}
function DeliveryForm({ id, item, onDirty, onClean, onPending, onExpired, onSaved }: Props & { item?: Item }) {
 const [action, setAction] = useState<Action>('CLAIM'), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [message, setMessage] = useState(''); const active = useRef(false), alive = useRef(true), original = useRef<Command | undefined>(undefined); const [intent] = useState(() => new CommandIntent<Command>());
 useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
 async function execute(c: Command) { if (active.current) return; active.current = true; original.current = c; setBusy(true); onDirty(); onPending(true); setMessage(''); try { if (await intent.run(c, send) && alive.current) { onPending(false); onClean(); onSaved(); } } catch (e) { if (!alive.current) return; if (e instanceof ApiError && e.status === 401) { onExpired(); return; } const definite = e instanceof ApiError && ([400, 403, 404].includes(e.status) || e.status === 409 && !['COMMAND_BUSY', 'HTTP_ERROR'].includes(e.code)); if (definite) { intent.rejected(); onPending(false); } setUncertain(!definite); setMessage(definite ? e.message : '投递结果待确认；请保留原输入及请求键确认，不更换目的端或报告。'); } finally { active.current = false; if (alive.current) setBusy(false); } }
 return <Card title={item ? '处理持久化本地投递' : '登记固定产物到本地模拟端'}>{item && <p style={{ overflowWrap: 'anywhere' }}>产物 {item.artifactId} · 修订 {item.revisionId} · SHA256 {item.sha256} · 当前 {item.state} / v{item.version} · 尝试 {item.attemptId ?? '尚无'}</p>}{message && <Alert role="status" title={message} />}{uncertain && <Button disabled={busy} onClick={() => { if (original.current) void execute(original.current); }}>确认原投递请求</Button>}
 {item && <><label htmlFor="delivery-action">本地投递动作</label><Select id="delivery-action" virtual={false} value={action} disabled={busy || uncertain} style={{ width: '100%' }} options={Object.entries(actions).map(([value, label]) => ({ value, label }))} onChange={(v: Action) => { setAction(v); onDirty(); }} /></>}
 <Form<{ confirmedId: string; artifact: string; signature: string; revision: string; hash: string; reason: string }> layout="vertical" disabled={busy || uncertain} onValuesChange={onDirty} onFinish={v => { void execute({ caseId: id, delivery: item?.id, action: item ? action : undefined, body: { confirmedCaseId: v.confirmedId, artifactId: item?.artifactId ?? v.artifact, signatureId: item?.signatureId ?? v.signature, revisionId: item?.revisionId ?? v.revision, sha256: item?.sha256 ?? v.hash, destination: 'LOCAL_SIM', expectedVersion: item?.version ?? 0, attemptId: item && action !== 'CLAIM' ? item.attemptId : null, reason: v.reason } }); }}>
 {!item && <><p>从固定PDF或版本链页面核对确切产物；只接受当前依赖有效的冻结报告。目的端固定 LOCAL_SIM。</p>{[['artifact', '固定产物UUID'], ['signature', '模拟签署UUID'], ['revision', '冻结修订UUID'], ['hash', '产物SHA256']].map(([name, label]) => <Form.Item key={name} name={name} label={label} rules={[{ required: true }, { pattern: name === 'hash' ? /^[a-f0-9]{64}$/ : /^[a-f0-9-]{36}$/ }]}><Input maxLength={name === 'hash' ? 64 : 36} /></Form.Item>)}</>}
 <Form.Item name="confirmedId" label="核对投递病例UUID" rules={[{ validator: (_, v: unknown) => v === id ? Promise.resolve() : Promise.reject(new Error('请核对病例UUID')) }]}><Input maxLength={36} /></Form.Item><Form.Item name="reason" label="本地投递操作原因" rules={[{ required: true, whitespace: true }, { max: 2000 }]}><Input.TextArea rows={3} maxLength={2000} /></Form.Item><Button type="primary" htmlType="submit" disabled={busy || uncertain}>提交本地投递操作</Button></Form></Card>;
}

function DeliveryHistory({ id, delivery, onExpired }: { id: string; delivery: string; onExpired: () => void }) {
 const [page, setPage] = useState(1); const [reader] = useState(() => new ReadController(async (p: number, signal: AbortSignal) => { try { return { status: 'ready' as const, data: await history(id, delivery, p, signal) }; } catch (e) { if (e instanceof ApiError && e.status === 401) onExpired(); throw e; } })); const state = useSyncExternalStore(reader.subscribe, reader.getSnapshot); useEffect(() => { void reader.run(page); return reader.stop; }, [reader, page]);
 return <Card title="追加投递与对账历史"><ReadPanel state={state}>{rows => <><Table rowKey="version" dataSource={rows} pagination={false} scroll={{ x: 900 }} columns={[{ title: '版本', dataIndex: 'version' }, { title: '动作', dataIndex: 'action' }, { title: '状态', dataIndex: 'state' }, { title: '尝试ID', dataIndex: 'attemptId' }, { title: '原因', dataIndex: 'reason' }, { title: '时间', dataIndex: 'occurredAt' }]} /><Button disabled={page === 1} onClick={() => setPage(p => p - 1)}>上一页投递历史</Button><Button disabled={rows.length < 20 || page >= 10000} onClick={() => setPage(p => p + 1)}>下一页投递历史</Button></>}</ReadPanel></Card>;
}
