import {useCallback,useEffect,useRef,useState} from 'react';
import {Alert,Button,Input,Modal,Select,Space} from 'antd';
import {ApiError} from '../../api';
import {CommandIntent} from '../../shared/command';
import {loadImpact,sendImpact,type Impact,type ImpactCommand} from './impact-api';
export function ImpactReview({id,decision,onBack,onDirty,onClean,onPending,onExpired}:{id:string;decision:string;onBack:()=>void;onDirty:()=>void;onClean:()=>void;onPending:(v:boolean)=>void;onExpired:()=>void}){
 const [view,setView]=useState<Impact>(),[reason,setReason]=useState(''),[action,setAction]=useState<'ACKNOWLEDGE'|'DEFER'>('DEFER'),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[leave,setLeave]=useState<'back'|'refresh'|null>(null);
 const gen=useRef(0),abort=useRef<AbortController|null>(null),active=useRef(false),intent=useRef(new CommandIntent<ImpactCommand>()),saved=useRef<ImpactCommand|null>(null),callbacks=useRef({onClean,onExpired});callbacks.current={onClean,onExpired};
 const read=useCallback(async()=>{const g=++gen.current;abort.current?.abort();const c=new AbortController();abort.current=c;setBusy(true);setView(undefined);setError('');try{const v=await loadImpact(id,decision,AbortSignal.any([c.signal,AbortSignal.timeout(10000)]));if(g!==gen.current)return;setView(v);setReason('');setAction('DEFER');callbacks.current.onClean();}catch(e){if(g===gen.current&&!c.signal.aborted){setError(e instanceof Error?e.message:'影响读取失败');if(e instanceof ApiError&&e.status===401)callbacks.current.onExpired();}}finally{if(g===gen.current)setBusy(false);}},[id,decision]);
 useEffect(()=>{const generation=gen,controller=abort;void read();return()=>{generation.current++;controller.current?.abort();};},[read]);
 async function execute(c:ImpactCommand){if(active.current)return;active.current=true;saved.current=c;const g=++gen.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setBusy(true);setError('');setConfirm(false);onPending(true);onDirty();try{await intent.current.run(c,(body,key)=>sendImpact(body,key,AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])));if(g!==gen.current)return;setUncertain(false);onPending(false);onClean();await read();}catch(e){if(g!==gen.current)return;const definite=e instanceof ApiError&&([400,401,403,404].includes(e.status)||e.status===409&&!['COMMAND_BUSY','HTTP_ERROR'].includes(e.code));setUncertain(!definite);if(definite){intent.current.rejected();onPending(false);}setError(definite&&e instanceof Error?e.message:'复核结果待确认；请保留原键确认，取消等待不等于服务端撤销。');if(e instanceof ApiError&&e.status===401)onExpired();}finally{active.current=false;if(g===gen.current)setBusy(false);}}
 const dirty=reason.length>0||action!=='DEFER';
 function navigate(kind:'back'|'refresh'){if(dirty){setLeave(kind);return;}if(kind==='back'){onClean();onBack();}else void read();}
 return <section aria-label="合成引用失效复核"><Alert type="warning" title="历史仅供追溯；知悉不恢复失效结果，不修改或签署报告。"/><Space><Button disabled={busy||uncertain} onClick={()=>navigate('back')}>返回人工决定</Button><Button disabled={busy||uncertain} onClick={()=>navigate('refresh')}>重新核验失效影响</Button><Button disabled={!busy} onClick={()=>{abort.current?.abort();if(!active.current){gen.current++;setBusy(false);setView(undefined);}}}>取消等待影响</Button>{uncertain&&<Button disabled={busy} onClick={()=>{if(saved.current)void execute(saved.current);}}>原键确认影响复核</Button>}</Space>{error&&<Alert role="alert" type="error" title={error}/>}{busy&&<p role="status">正在核验或提交精确影响版本</p>}
 {view&&<><p>决定 {decision} · 复核版本 {view.version} · 结果 {view.decision.resultId}</p><Alert type={view.consumable?'info':'warning'} title={view.consumable?'查询时引用有效；消费仍须服务端重查':'仅授权历史；不可作为当前有效引用消费'}/><p>{view.pendingReview?'待人工复核':view.sourceValid?'来源当前有效':'此影响快照已人工知悉；结果仍失效'}</p><p>失效原因：{view.snapshot.validity.reasons.join('、')||'无'} · 已模拟签署：{view.snapshot.reportFrozen?'是；内容保持原样':'否'}</p><details><summary>精确失效依赖与原目标版本</summary><pre>{JSON.stringify(view.snapshot,null,2)}</pre></details><Select aria-label="影响复核动作" virtual={false} value={action} disabled={busy||uncertain} onChange={v=>{setAction(v);onDirty();}} options={[{value:'DEFER',label:'暂缓处理'},{value:'ACKNOWLEDGE',label:'已知悉失效并保留历史'}]}/><Input.TextArea aria-label="影响复核理由" value={reason} maxLength={500} disabled={busy||uncertain} onChange={e=>{setReason(e.target.value);onDirty();}}/><Button disabled={busy||uncertain||view.sourceValid||!reason.trim()} onClick={()=>setConfirm(true)}>确认影响快照</Button><h3>追加式复核历史</h3>{view.history.map(r=><p key={r.id}>{r.action} · {r.reason} · {r.actorId} · {r.recordedAt} · {r.snapshotHash===view.snapshot.epoch?'当前影响快照':'旧影响快照，不代表当前已复核'}</p>)}</>}
 <Modal open={confirm} title="明确记录失效复核？" okText="提交此快照复核" cancelText="保留并返回" onCancel={()=>setConfirm(false)} onOk={()=>{if(view)void execute({caseId:id,decisionId:decision,body:{confirmedCaseId:id,decisionId:decision,expectedVersion:view.version,snapshotHash:view.snapshot.epoch,action,reason:reason.trim(),confirmed:true}});}}><p>仅记录 {decision} / {view?.snapshot.epoch} 的 {action}，理由：{reason}。不会恢复消费资格或改写报告。</p></Modal>
 <Modal open={leave!==null} title="清除未提交复核理由？" okText="清除并继续" cancelText="保留复核表单" onCancel={()=>setLeave(null)} onOk={()=>{const target=leave;setLeave(null);onClean();if(target==='back')onBack();else void read();}}><p>已保存记录保持不变。</p></Modal>
 </section>;
}
