import {fetchCsrf,readJson,request} from '../../api';
export interface ImpactReview {id:string;version:number;snapshotHash:string;action:'ACKNOWLEDGE'|'DEFER';reason:string;actorId:string;recordedAt:string}
export interface Impact {caseId:string;decision:{id:string;resultId:string;adoptedRevisionId:string|null};snapshot:{decisionId:string;resultId:string;epoch:string;currentRevisionId:string|null;assignmentVersion:number;reportFrozen:boolean;reportReady:boolean;validity:{epoch:string;reasons:string[];dependencies:Record<string,unknown>}};version:number;sourceValid:boolean;consumable:boolean;pendingReview:boolean;history:ImpactReview[];executionAllowed:false}
export interface ImpactCommand {caseId:string;decisionId:string;body:{confirmedCaseId:string;decisionId:string;expectedVersion:number;snapshotHash:string;action:'ACKNOWLEDGE'|'DEFER';reason:string;confirmed:true}}
const obj=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('失效影响响应无效');return v as Record<string,unknown>;};
const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
export function parseImpact(raw:unknown,id:string,decisionId:string):Impact {const v=obj(raw),d=obj(v.decision),s=obj(v.snapshot),validity=obj(s.validity);
 if(v.caseId!==id||d.id!==decisionId||s.decisionId!==decisionId||typeof d.resultId!=='string'||s.resultId!==d.resultId||!hash(s.epoch)||!hash(validity.epoch)||!Array.isArray(validity.reasons)||!validity.reasons.every(x=>typeof x==='string')||!Number.isSafeInteger(v.version)||Number(v.version)<-1||Number(v.version)>99||!Number.isSafeInteger(s.assignmentVersion)||!(s.currentRevisionId===null||typeof s.currentRevisionId==='string')||typeof s.reportFrozen!=='boolean'||typeof s.reportReady!=='boolean'||typeof v.sourceValid!=='boolean'||typeof v.consumable!=='boolean'||typeof v.pendingReview!=='boolean'||v.executionAllowed!==false||v.consumable&&!v.sourceValid||!Array.isArray(v.history)||v.history.length>100)throw Error('失效影响病例、决定或版本不匹配');obj(validity.dependencies);
 for(const row of v.history){const r=obj(row);if(typeof r.id!=='string'||!Number.isSafeInteger(r.version)||!hash(r.snapshotHash)||!['ACKNOWLEDGE','DEFER'].includes(String(r.action))||typeof r.reason!=='string'||typeof r.actorId!=='string'||typeof r.recordedAt!=='string')throw Error('复核历史无效');}
 return v as unknown as Impact;
}
const path=(id:string,decision:string)=>`/api/requests/reports/cases/${id}/synthetic-decisions/${decision}`;
export async function loadImpact(id:string,decision:string,signal:AbortSignal){return parseImpact(await readJson(await request(path(id,decision)+'/impact',{signal,cache:'no-store'})),id,decision);}
export async function sendImpact(c:ImpactCommand,key:string,signal:AbortSignal){const csrf=await fetchCsrf(signal);const v=obj(await readJson(await request(path(c.caseId,c.decisionId)+'/impact-reviews',{method:'POST',signal,headers:{'Content-Type':'application/json',[csrf.headerName]:csrf.token,'Idempotency-Key':key},body:JSON.stringify(c.body)}))),r=obj(v.receipt);if(r.status!==200||r.resourceType!=='SYNTHETIC_IMPACT_REVIEW'||typeof r.resourceId!=='string'||r.version!==c.body.expectedVersion+1||typeof v.replayed!=='boolean')throw Error('复核回执不匹配');return r.resourceId;}
