import {useEffect,useRef,useState} from 'react';
import {Alert,Button,Input,Modal,Select,Space} from 'antd';
import {ImpactReview} from './ImpactReview';
import {ApiError} from '../../api';
import {CommandIntent} from '../../shared/command';
import {loadDecision,sendDecision,type Action,type Command,type View} from './decision-api';
export function SyntheticDecision({id,onDirty,onClean,onPending,onExpired}:{id:string;onDirty:()=>void;onClean:()=>void;onPending:(v:boolean)=>void;onExpired:()=>void}){
 const [input,setInput]=useState(''),[view,setView]=useState<View>(),[reason,setReason]=useState(''),[action,setAction]=useState<Action>('DEFER'),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('请选择精确合成结果'),[confirm,setConfirm]=useState(false),[switching,setSwitching]=useState(false);
 const [impact,setImpact]=useState(''),[nextImpact,setNextImpact]=useState('');
 const generation=useRef(0),abort=useRef<AbortController|null>(null),active=useRef(false),intent=useRef(new CommandIntent<Command>()),saved=useRef<Command|null>(null);
 useEffect(()=>()=>{generation.current++;abort.current?.abort();},[id]);
 async function read(result:string,page=1){const g=++generation.current;abort.current?.abort();const c=new AbortController();abort.current=c;setView(undefined);setBusy(true);setError('');try{const v=await loadDecision(id,result,page,AbortSignal.any([c.signal,AbortSignal.timeout(10000)]));if(g!==generation.current)return;setView(v);setReason('');setAction('DEFER');setStatus('已核验人工处理依据');onClean();}catch(e){if(g===generation.current&&!c.signal.aborted){setError(e instanceof Error?e.message:'读取失败');if(e instanceof ApiError&&e.status===401)onExpired();}}finally{if(g===generation.current)setBusy(false);}}
 async function execute(command:Command){if(active.current)return;active.current=true;saved.current=command;const g=++generation.current;abort.current?.abort();const c=new AbortController();abort.current=c;setBusy(true);setConfirm(false);setError('');onDirty();onPending(true);
 try{const receipt=await intent.current.run(command,(body,key)=>sendDecision(body,key,AbortSignal.any([c.signal,AbortSignal.timeout(15000)])));if(g!==generation.current)return;if(receipt){setUncertain(false);onPending(false);onClean();setReason('');setStatus('人工处理已确认；未签署、未生成诊断');await read(command.body.resultId);}}
 catch(e){if(g!==generation.current)return;const definite=e instanceof ApiError&&([400,401,403,404].includes(e.status)||e.status===409&&!['COMMAND_BUSY','HTTP_ERROR'].includes(e.code));setUncertain(!definite);if(definite){intent.current.rejected();onPending(false);}setError(definite&&e instanceof Error?e.message:'操作结果待确认，请用原键确认；取消等待不等于撤销服务端操作。');if(e instanceof ApiError&&e.status===401)onExpired();}
 finally{active.current=false;if(g===generation.current)setBusy(false);}}
 const dirty=reason.length>0||action!=='DEFER';
 if(impact)return <ImpactReview key={id+impact} id={id} decision={impact} onBack={()=>{setImpact('');void read(input.trim());}} onDirty={onDirty} onClean={onClean} onPending={onPending} onExpired={onExpired}/>;
 return <section aria-label="医生人工处理合成结果"><Alert type="warning" title="非诊断合成引用；仅医生明确处理，不自动诊断或签署，临床执行禁止。"/><label>人工处理结果ID<Input aria-label="人工处理结果ID" maxLength={36} disabled={busy||uncertain} value={input} onChange={e=>{setInput(e.target.value);setView(undefined);onDirty();}}/></label><Space><Button disabled={busy||uncertain} onClick={()=>{if(dirty)setSwitching(true);else void read(input.trim());}}>核验人工处理依据</Button><Button disabled={!busy} onClick={()=>{if(active.current){abort.current?.abort();}else{generation.current++;abort.current?.abort();setBusy(false);setView(undefined);setStatus('已取消读取');}}}>取消等待人工处理</Button>{uncertain&&<Button disabled={busy} onClick={()=>{if(saved.current)void execute(saved.current);}}>原键确认人工处理</Button>}</Space>
 <p role="status">{status}</p>{error&&<Alert role="alert" type="error" title={error}/>}
 {view&&<><p>病例 {id} · 结果 {view.resultId} · 决定版本 {view.version} · 目标草稿 {view.target?.version??'无'} / {view.target?.id}</p>{!view.ready&&<Alert type="error" title={`禁止新处理：${view.invalidReason??'未知'}`}/>}<details><summary>精确输入、模型及配置快照</summary><pre>{JSON.stringify(view.source,null,2)}</pre></details><Select aria-label="人工处理动作" virtual={false} disabled={busy||uncertain} value={action} onChange={v=>{setAction(v);onDirty();}} options={[{value:'ACCEPT_REFERENCE',label:'采纳非诊断引用'},{value:'REJECT',label:'拒绝'},{value:'DEFER',label:'暂缓'}]}/><Input.TextArea aria-label="人工处理原因" maxLength={500} disabled={busy||uncertain} value={reason} onChange={e=>{setReason(e.target.value);onDirty();}}/><p>采纳仅新增内容不变的草稿修订及引用；拒绝/暂缓不修改草稿。理由：{reason}</p><Button disabled={busy||uncertain||!view.ready||!reason.trim()} onClick={()=>setConfirm(true)}>确认人工处理版本</Button><h3>不可变人工记录（当前依据可能已失效）</h3>{view.history.map(e=><article key={e.id}><Button disabled={busy||uncertain} onClick={()=>{if(dirty)setNextImpact(e.id);else{onClean();setImpact(e.id);}}}>查看失效影响 {e.id}</Button><p>{e.action} · 决定版本 {e.version} · {e.reason}</p><p>作者 {e.actorId} · {e.recordedAt} · 目标 {e.targetRevisionId} · 采纳修订 {e.adoptedRevisionId??'无'} · {e.adoptedRevisionId===view.target?.id?'当前草稿引用':'历史记录'}</p></article>)}<Space><Button disabled={busy||uncertain||dirty||view.page===1} onClick={()=>void read(view.resultId,view.page-1)}>上一页人工记录</Button><Button disabled={busy||uncertain||dirty||view.history.length<20} onClick={()=>void read(view.resultId,view.page+1)}>下一页人工记录</Button></Space></>}
 <Modal open={confirm} title="确认精确结果与报告修订？" okText="明确提交人工处理" cancelText="保留并返回" onCancel={()=>setConfirm(false)} onOk={()=>{if(view?.target)void execute({caseId:id,body:{confirmedCaseId:id,resultId:view.resultId,targetRevisionId:view.target.id,reportVersion:view.target.version,assignmentVersion:view.assignmentVersion,expectedVersion:view.version,action,reason:reason.trim(),confirmed:true}});}}><p>病例 {id} · 结果 {view?.resultId} · 目标 {view?.target?.id} · {action} · {reason}。此操作不是诊断或签署。</p></Modal>
 <Modal open={!!nextImpact} title="清除表单并查看失效影响？" okText="清除并查看影响" cancelText="保留表单" onCancel={()=>setNextImpact('')} onOk={()=>{setReason('');setAction('DEFER');onClean();setImpact(nextImpact);setNextImpact('');}}><p>不修改已保存的决定。</p></Modal>
 <Modal open={switching} title="清除人工处理表单并重新核验？" okText="清除并核验" onCancel={()=>setSwitching(false)} onOk={()=>{setSwitching(false);void read(input.trim());}}><p>尚未提交的理由将被清除，既有记录不变。</p></Modal>
 </section>;
}
